---
draft: true
---

[[YkxyDKHKOIwHLcdjIZCcUkSxnwqzgejc]]
== References Are Powerful

[.lead]
//
References are a widely-used idea in computer science.

By controlling the process of dereferencing or _translating_ a reference we can:

[.s]
//
* *move* objects from place to place: just like your phone can move around with
the same number
//
* *block* translation in certain cases: just like you can reject email from
certain senders

[[VjdvpgqzTAgeaTuQOvPNlsUiBIhYcxFE]]
[.oneword]
== And Memory Management
(Or why you never need to `delete` anything in Java...)

[[LMkQlNJtjcgVmFapXzOxalWcbrMgJCdj]]
== Java Memory Management

[source,java]
----
String save;
for (long i = 0; ; i++) {
  String s = new String(i);
  if (i == 0) {
    save = s;
  }
}
----

Java utilizes references to automatically clean up unused objects to reclaim
memory&mdash;a process known as _garbage collection_.

[.s]
//
* If a reference to an object exists, it must still be useful, *so keep it*
//
* If no reference to an object exists, _it cannot be used_, *so remove it*

[[ExXBunKhuHMRMgeissCMJFagFMaATymr]]
[.ss]
== Reference Counting Example

[source,java]
----
String save;
for (long i = 0; ; i++) {
  String s = new String(i);
  if (i == 0) {
    save = s;
  }
  // i == 0
}
----

<<<

++++
<div class="digraph small">
  String [ label = "String|0" ]
  save -> String
  s -> String
</div>
++++

[[DhaLhZFXsqpNrJSlnhNezfCAhyJMtdkH]]
[.ss]
== Reference Counting Example

[source,java]
----
String save;
for (long i = 0; ; i++) {
  String s = new String(i);
  if (i == 0) {
    save = s;
  }
  // i == 1
}
----

<<<

++++
<div class="digraph small">
  String [ label = "String|0" ]
  String1 [ label = "String|1" ]
  save -> String
  s -> String1
</div>
++++

[[ySGaaRXUtptkhVrcBQumHCwMiBCjyqCp]]
[.ss]
== Reference Counting Example

[source,java]
----
String save;
for (long i = 0; ; i++) {
  String s = new String(i);
  if (i == 0) {
    save = s;
  }
  // i == 2
}
----

<<<

++++
<div class="digraph small">
  String [ label = "String|0" ]
  String1 [ label = "String|1" ]
  String2 [ label = "String|2" ]
  save -> String
  s -> String2
  {rank=same; String String1 String2}
</div>
++++

[[zEHDaKoSAyMYFCMSoqKCpNYvHppfhklu]]
[.ss]
== Reference Counting Example

[source,java]
----
String save;
for (long i = 0; ; i++) {
  String s = new String(i);
  if (i == 0) {
    save = s;
  }
  // i == 3
}
----

<<<

++++
<div class="digraph small">
  String [ label = "String|0" ]
  String1 [ label = "String|1" ]
  String2 [ label = "String|2" ]
  String3 [ label = "String|3" ]
  save -> String
  s -> String3
  {rank=same; String String1 String2 String3}
</div>
++++

[[GrSlJoshnMHiqwfLmUJHgieSBvLWhWFV]]
[.ss]
== Reference Counting Example

[source,java]
----
String save;
for (long i = 0; ; i++) {
  String s = new String(i);
  if (i == 0) {
    save = s;
  }
  // i == 3
}
----

<<<

++++
<div class="digraph small">
  String [ label = "String|0" ]
  String1 [ label = "String|1", fillcolor="red", style="filled" ]
  String2 [ label = "String|2", fillcolor="red", style="filled" ]
  String3 [ label = "String|3" ]
  save -> String
  s -> String3
  {rank=same; String String1 String2 String3}
</div>
++++

[[kYPIHYzgsQZYzQsiBRpOBnQwzxswiPLl]]
[.ss]
== Reference Counting Example

[source,java]
----
String save;
for (long i = 0; ; i++) {
  String s = new String(i);
  if (i == 0) {
    save = s;
  }
  // i == 3
}
----

<<<

++++
<div class="digraph small">
  String [ label = "String|0" ]
  String3 [ label = "String|3" ]
  save -> String
  s -> String3
</div>
++++

[[qexqAkkifuIXasHnUyVKnZUKPHXMJDhs]]
[.oneword]
//
== Questions So Far?

Because it's about to get more interesting...

[[AjzHJAjSLdiqNLruXOGHOnHrnxuAuDeW]]
== ! Max Example

[.janini.jdk.compiler.smaller]
....
public class Max {
  private Integer[] values;
  Max(Integer[] setValues) {
    values = setValues;
  }
  public Integer max() {
    if (values == null || values.length == 0) {
      return null;
    }
    Integer currentMax = values[0];
    for (int i = 1; i < values.length; i++) {
      if (values[i] > currentMax) {
        currentMax = values[i];
      }
    }
    return currentMax;
  }
}
public class Example {
  public static void main(String[] unused) {
    Max max = new Max(new Integer[] { 1, 2, 5 });
    System.out.println(max.max());
  }
}
....

[[CNStHcEuMtLuLZNrRDHnHTfWoQKLaFOc]]
== Bounded Type Parameters

[.lead]
//
The compiler knows all about the relationship between different types, and so it
can help us ensure that our generic classes receive appropriate type parameters.

[.s]
//
* `<T extends S>`: type `T` extends class `S` _or_ implements interface `S`
//
* `<T extends S & U & V>`: type `T` extends _or_ implements `S`, `U`, and `V`

[[NBwNwCLFtuvIOmBTFniwQfGjqxGIilgM]]
== ! Sum Example

[.janini.jdk.compiler.smaller]
....
public class Max<T> {
  private T[] values;
  Max(T[] setValues) {
    values = setValues;
  }
  public T max() {
    if (values == null || values.length == 0) {
      return null;
    }
    T currentMax = values[0];
    for (int i = 1; i < values.length; i++) {
      if (values[i].compareTo(currentMax) > 0) {
        currentMax = values[i];
      }
    }
    return currentMax;
  }
}
public class Example {
  public static void main(String[] unused) {
    Max<Integer> max = new Max<>(new Integer[] { 1, 2, 5 });
    System.out.println(max.max());
  }
}
....

[[acJMdhJiXZbEnbTuUrdAXwOliHuicqON]]
== Generic Interfaces

[.lead]
//
Just like classes, interface definitions can use type parameters:

[source,java]
----
public interface SimpleList<E> {
  public E get(int index);
  public void set(int index, E element);
  public void add(int index, E element);
  public E remove(int index);
  public int size();
}
----

[[euuZHusAeuacnfuZfcSNltmMoMlPTQzB]]
== ! SimpleLinkedList Extends Generic Interface

[.janini.jdk.smallest.compiler]
....
public interface SimpleList<E> {
  public E get(int index);
  public void set(int index, E element);
  public void add(int index, E element);
  public E remove(int index);
  public int size();
}
public class SimpleLinkedList<E> implements SimpleList<E> {
  class Item {
    E value;
    Item next;
    Item(E setValue, Item setNext) {
      value = setValue;
      next = setNext;
    }
  }
  private Item start;
  private int currentSize;

  public SimpleLinkedList() { }

  public SimpleLinkedList(E[] array) {
    for (int i = array.length - 1; i >= 0; i--) {
      this.add(0, array[i]);
    }
  }

  public void add(int index, E toAdd) {
    if (index == 0) {
      start = new Item(toAdd, start);
      currentSize++;
      return;
    }
    Item previousItem = getItem(index - 1);
    if (previousItem == null) {
      return;
    }
    Item newItem = new Item(toAdd, previousItem.next);
    previousItem.next = newItem;
    currentSize++;
  }

  public E remove(int index) {
    E toReturn;
    if (index == 0) {
      toReturn = start.value;
      start = start.next;
      return toReturn;
    }
    Item previousItem = getItem(index - 1);
    toReturn = previousItem.next.value;
    previousItem.next = previousItem.next.next;
    return toReturn;
  }

  public E get(int index) {
    Item item = getItem(index);
    if (item == null) {
      return null;
    } else {
      return item.value;
    }
  }

  public void set(int index, E toSet) {
    Item item = getItem(index);
    if (item != null) {
      item.value = toSet;
    }
  }

  public int size() {
    return currentSize;
  }

  protected Item getItem(int index) {
    if (index < 0 || index >= currentSize) {
      return null;
    }
    int currentIndex = 0;
    for (Item current = start; current != null; current = current.next) {
      if (currentIndex == index) {
        return current;
      }
      currentIndex++;
    }
    return null;
  }
}
public class Example {
  public static void main(String[] unused) {
    SimpleLinkedList simpleList = new SimpleLinkedList();
    for (int i = 0; i < 10; i++) {
      simpleList.add(0, i);
    }
    System.out.println(simpleList.size());
    for (int i = 0; i < 5; i++) {
      simpleList.remove(i);
    }
    System.out.println(simpleList.get(0));
  }
}
....

[[gBphzendXgwuWEZtZhRkrXYNYuseXjKN]]
== ! Max Example

[.janini.jdk.compiler.smaller]
....
public class Max<T extends Comparable> {
  private T[] values;
  Max(T[] setValues) {
    values = setValues;
  }
  public T max() {
    if (values == null || values.length == 0) {
      return null;
    }
    T currentMax = values[0];
    for (int i = 1; i < values.length; i++) {
      if (values[i].compareTo(currentMax) > 0) {
        currentMax = values[i];
      }
    }
    return currentMax;
  }
}
public class Example {
  public static void main(String[] unused) {
    Max max = new Max(new Integer[] { 1, 2, 5 });
    System.out.println(max.max());
  }
}
....

[[eGnIkyHdLiXKxjLLaJTeZnUzetkwHOfn]]
== Generic Gotchas

[.lead]
//
I've elided many of the details of working with generics.
//
Review
//
https://docs.oracle.com/javase/tutorial/java/generics/index.html[the official
documentation]
//
to learn more.

But here's one of the more obvious things that doesn't work the way you'd want:

[source,java]
----
public class LastTen<T> {
  private T[] values;
  private List<T> listOfValues;
  LastTen() {
    value = new T[10]; // You can't create an array of a generic type
    // As a solution you can use a collection type like a list
    listOfValues = new ArrayList<T>(); // This works
  }
}
----

[[UPAPOWEeeKidMowTCCjoibyydGiiZGUf]]
== ! Generic `LastTen`

[.janini.jdk.compiler.smaller]
....
import java.util.List;
import java.util.ArrayList;

public class LastTen<T> {
  private List<T> values = new ArrayList<>(10);
  private int currentIndex = 0;
  LastTen() {
    for (int i = 0; i < 10; i++) {
      values.add(i, null);
    }
  }
  public void add(T newValue) {
    values.set(currentIndex, newValue);
    currentIndex = (currentIndex + 1) % 10;
  }
  public List<T> get() {
    return values;
  }
}
public class Example {
  public static void main(String[] unused) {
    LastTen<String> lastTen = new LastTen<>();
    for (int i = 0; i < 30; i++) {
      lastTen.add("foo" + i);
    }
    System.out.println(lastTen.get());
  }
}
....

[[uMnbIPzTufFEHnvuXezGuoQWziZdYXxm]]
[.oneword]
//
== Questions About Generics?

[[QMnpLBhmSfuaDcVcmhNuOtYHGFWVdsfT]]
== ! Generifying HashMap

[.janini.compiler.jdk.smallest]
....
public class HashMap {
  private static final int TABLE_SIZE = 16;
  class Item {
    public Object key;
    public Object value;
    public Item next;
    Item(Object setKey, Object setValue, Item setNext) {
      key = setKey;
      value = setValue;
      next = setNext;
    }
  }
  private Item[] items = new Item[TABLE_SIZE];
  public int itemCount = 0;
  private int hash(Object key) {
    int hashValue = key.hashCode() % TABLE_SIZE;
    if (hashValue < 0) {
      hashValue += TABLE_SIZE;
    }
    return hashValue;
  }
  public void put(Object key, Object value) {
    int bucket = hash(key);
    Item current = items[bucket];
    for (; current != null; current = current.next) {
      if (current.key.equals(key)) {
        current.value = value;
        return;
      }
    }
    Item newItem = new Item(key, value, items[bucket]);
    items[bucket] = newItem;
    itemCount++;
    return;
  }
  public Object get(Object key, Object value) {
    int bucket = hash(key);
    Item current = items[bucket];
    for (; current != null; current = current.next) {
      if (current.key.equals(key)) {
        return current.value;
      }
    }
    return null;
  }
}
public class Example {
  public static void main(String[] unused) {
    HashMap ourHashMap = new HashMap();
    ourHashMap.put("test", "me");
    System.out.println(ourHashMap.itemCount);
    ourHashMap.put("test", "another");
    System.out.println(ourHashMap.itemCount);
  }
}
....
