---
title: Provide Feedback
description: >
  Provide anonymous feedback on any and every element of CS 125.
priority: 0.8
doTOC: false
---
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu[forum,role='noexternal']]

[.lead]
//
Use the form below to provide anonymous feedback on any and all aspects of CS
125.

Do you like something? Let us know! Could something be better? Let us know. Want
a certain topic or concept to be covered in class? Let us know!

Responses are completely anonymous.
//
Constructive feedback may receive a response on the
//
https://cs125-forum.cs.illinois.edu/c/spring-2018-announcements/feedback[forum].
//
If you don't want us to excerpt part of your response in order to reply to it,
please say so.
//
If you want an individualized response, feel free to request this and include
your email address in your reply.
//
However, if you're a current student it's best to simply send a private message
on the {forum}, or post in the
//
https://cs125-forum.cs.illinois.edu/c/spring-2018-announcements/feedback[forum
feedback category]
//
anonymously as well.

[[form]]
== Feedback Form

*As a reminder, responses are completely anonymous.*
//
We look forward to hearing from you!

++++
<form action="https://docs.google.com/forms/u/1/d/e/1FAIpQLSd-nYWVJbXxrbhSYSHfFbdO0zRNODQYWViMBPor7xVDmJCDWw/formResponse" target="_self" method="POST" id="mG61Hd">
  <div class="form-group">
    <textarea class="form-control" id="cs125Feedback" rows="8" name="entry.1443323906"></textarea>
  </div>
  <button type="submit" class="btn btn-secondary">Submit</button>
</form>
++++

// vim: ts=2:sw=2:et:ft=asciidoc
