---
title: Join Our Course Staff
description: >
  Join the CS 125 course staff! We have both paid and unpaid positions
  available, and you'll be able to work on any number of exciting projects or
  just directly help other students.
priority: 0.9
---
:linkattrs:

[.lead]
//
Ready to help staff the most innovative course on campus?
//
footnote:[According to us, obviously]

CS 125 relies on both volunteers and paid staff to help teach computer science
and programming to hundreds of students.
//
If you've taken the course or have equivalent knowledge, you're ready to
<<ca, volunteer>> to help other students.
//
And if you'd prefer to work behind the scenes and build novel tools that help
power CS 125, we have <<cd, paid development positions>> as well.
//
We're also looking for <<data, data scientists>> to derive insights
from the massive data sets that CS 125 produces each semester.

[[ca]]
== Volunteer Course Assistant

CS 125 relies on volunteers to fill most student-facing roles each semester.
//
As a volunteer course assistant (CA), you'll interact directly with students
during office hours and in labs.
//
You'll be the wise counselor, the one providing encouragement, and provide a
sympathetic ear to students when they are just plain frustrated footnote:[That
happens!].

Being a volunteer CS 125 CA is a 3&ndash;5 hour per week time commitment.
//
To read more about the CA position and apply
//
https://goo.gl/forms/7PRF4UM600PJCiuu2[click here].
//
However, we want to emphasize a few things:

. *You do not need to have aced the class to be a CA or to become a good CA.*
Helping others with their code requires training and practice, and we'll provide
both.
//
If you've struggled a bit you'll be in a better position to empathize with
struggling students.
//
. *Teaching other students will help _you_ learn the material better.*
//
So this is a great thing to do before you move on to CS 225&mdash;particularly
if you aren't taking CS 126.

[[cd]]
== Course Developers

CS 125 also has a smaller set of paid undergraduate staff positions.
//
With the CAs available to staff office hours and hold labs, our paid positions
involve little to no student contact footnote:[Unless your specific project
requires it.].
//
Instead, we turn you loose on exciting and challenging development projects
designed to make the course better in the long run.
//
Past CS 125 course developers have worked on our grade return system, course
data analysis, plagiarism detection, MP development, and helped plan our first
//
link:/info/fair/[final project fair].
//
Course developer positions are 10 hour / week positions with pay starting at $11
/ hour but negotiable for experienced developers.

We always have a variety of exciting projects involving lots of different
technologies and environments.
//
Peruse the
//
https://goo.gl/GMS1Le[full list here].
//
But it's safe to say that if you like building things that hundreds of people
will use, we probably have a project that will interest and challenge you.
//
For next fall we're working on things like

. https://goo.gl/d7zvst[making enormous lectures fun and interactive],
//
. https://goo.gl/VybB4H[new tools allowing us to embed questions anywhere],
//
. https://goo.gl/oV57ei[frameworks enabling crowdsourced code review at scale],
//
. https://goo.gl/FBPjix[bringing data structures to life through intelligent
interactive visualizations],
//
. monitoring how students and course staff interact with the class through
//
https://goo.gl/eq8No9[new apps]
//
and
//
https://goo.gl/hXP26c[IntelliJ plugins],
//
. https://goo.gl/UHQ61Y[continuing to improve our existing MPs, including more use
of Android],
//
. and a
//
https://goo.gl/uzBvaj[variety of other interesting and cool projects].

For more details about these projects, or if you have ideas or comments, feel
free to
//
https://goo.gl/GMS1Le[contribute to our brainstorming document].

We're very flexible about what course developers work on and happy to work with
you to strengthen your skill set.
//
We are excited about these projects and want them to make forward
progress&mdash;but overall this is primarily a learning experience for the
course developers.
//
If this sounds up your alley, please
//
https://goo.gl/forms/HLjj9gr6I6kQlqtf1[click here]
//
to find out more and apply.

[[data]]
== Course Data Analysts

For the 2018&ndash;2019 academic year we are also looking to hire several data
analysts.
//
CS 125 generates _a lot_ of data, and will generate even more as the course gets
larger and we instrument more parts of the class.
//
https://goo.gl/eHwk8J[Several development projects]
//
involve improving our existing instrumentation, to measure things like how much
time students spend working on each MP and in office hours.
//
We should be able to harness this data to understand and improve the course.
//
Data analyst positions are 10 hour / week positions with pay starting at $11 /
hour but negotiable for experienced developers.

If that sounds like a fun challenge, please also
//
https://goo.gl/forms/HLjj9gr6I6kQlqtf1[click here]
//
to find out more and apply.
//
Note that the application is the same as that for <<cd, course developers>>, so
please indicate your interest in the data analyst position when you apply.

// vim: ts=2:sw=2:et:ft=asciidoc
