---
title: Join Our Course Staff
description: >
  Join the CS 125 course staff! We have both paid and unpaid positions
  available, and you'll be able to work on any number of exciting projects or
  just directly help other students.
priority: 0.9
---
:linkattrs:

[.lead]
//
Ready to help staff the most innovative course on campus?
//
footnote:[According to us, obviously]

CS 125 needs your help to teach computer science and programming to thousands of
students each year.
//
If you've taken the course or have equivalent knowledge, you're ready to
<<ca, directly help>> other students and get paid or earn course credit.
//
////
And if you'd prefer to work behind the scenes and build novel tools that help
power CS 125, we have <<cd, paid development positions>> as well.
//
We're also looking for <<data, data scientists>> to derive insights
from the massive data sets that CS 125 produces each semester.
////
And we also have more challenging roles available for more experienced students
willing to assume course leadership roles.

[[head]]
== Head Course Assistant

[.lead]
//
CS 125 Head Course Assistants assume significant leadership over the day-to-day
operations and future direction of the course.

As a Head CA, you'll be directly involved in the day-to-day operation of CS 125.
//
Head CAs are expected to be leaders, technologically sharp, and willing to
assume responsibility for delivering or maintaining significant course
components.

CS 125 has a large and varied technological footprint.
//
As Head CA you might be responsible for designing and delivering an entire set
of assessments: a machine project or semester-long set of homework problems.
//
Or you could be put in charge of maintaining the CS 125 Kubernetes cloud and the
many microservices running on it, which range from simple data pumps to complex
services supported by multiple containers.
//
Or you might be asked to own one of our multiple incubating projects: the
footnote:[long awaited] CS 125 App, an ongoing effort to generate small problem
test suites from solutions, a crowdsourced system for performing distributed
code review, or something new and exciting we haven't thought up yet.
//
A particular need over the next few semesters is students that are excited about
either Kotlin, React, or both.

[[captain]]
== Office Hour Captain

[.lead]
//
CS 125 Office Hour Captains are paid course staff responsible for making sure
that office hours and the forum run smoothly.

Your responsibilities will include captaining a certain number of office hours a
week, attending weekly captains' meetings, and helping train the rest of the
course assistants.
//
During office hours Captains both provide Tier 2 support and help manage the
rest of the staff to ensure that student questions are answered.

[[ca]]
== Course Assistant

[.lead]
//
As a course assistant (CA), you'll interact directly with students during office
hours and in labs&mdash;you'll be the wise counselor, the one providing
encouragement, and provide a sympathetic ear to students when they are just
plain frustrated footnote:[That happens!].

**Being a CS 125 CA is a paid 10 hour per week time commitment.**
//
Most of your time will be spent in office hours or helping with labs.
//
But there will also be a weekly meeting to attend, and you may be asked to help
with training sessions or material development.
//
To read more about the CA position and apply
//
https://forms.gle/7Mq9uAa6tUUjWwQF9[click here].
//
However, we want to emphasize a few things:

. *You do not need to have aced the class to be a CA or to become a good CA.*
//
Helping others with their code requires training and practice. We'll provide
both.
//
And if you've struggled a bit you'll be in a better position to empathize with
struggling students.
//
. *Teaching other students will help _you_ learn the material better.*
//
So this is a great thing to do before you move on to CS 225&mdash;particularly
if you aren't taking CS 126.

[[cv]]
== Course Volunteer

[.lead]
//
Course Volunteers are Course Assistants in training.

You'll be expected to do fewer hours, earn course credit, and be ready
to apply for a position as a Course Assistant in the following semester.


[[cd]]
== Course Developers

CS 125 also has a smaller set of paid undergraduate staff positions.
//
With the CAs available to staff office hours and hold labs, our paid positions
involve little to no student contact footnote:[Unless your specific project
requires it.].
//
Instead, we turn you loose on exciting and challenging development projects
designed to make the course better in the long run.
//
Past CS 125 course developers have worked on our grade return system, course
data analysis, plagiarism detection, MP development, and helped plan our first
//
link:/info/fair/[final project fair].
//
Course developer positions are 10 hour / week positions with pay starting at $11
/ hour but negotiable for experienced developers.

We always have a variety of exciting projects involving lots of different
technologies and environments.
//
Peruse the link:/tech/ideas[full list here].
//
But we're very flexible about what course developers work on and happy to work with
you to strengthen your skill set.
//
We are excited about these projects and want them to make forward
progress&mdash;but overall this is primarily a learning experience for the
course developers.

If this sounds up your alley, please
//
https://forms.gle/pMgL7HcZx8bRYCL19[click here]
//
to find out more and apply.

// vim: ts=2:sw=2:et:ft=asciidoc
