---
title: Joining CS 125 Late
description: >
  You can join CS 125 late, but you need to catch up quickly. This page contains
  information for people that register for CS 125 during the first few weeks of
  the course.
priority: 0.8
---

:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu[forum,role='noexternal']]

[.lead]
//
You _can_ join CS 125 late&mdash;during the first few weeks of the semester.
//
But you'll need to catch up right away.
//
This page contains instructions on how to do that.

Please follow the steps below carefully.

== Enable Google Apps Integration

Follow
//
link:/info/resources#google[these instructions]
//
to activate Google login for your `@illinois.edu` email address.

== Sign Up for Temporary Course Access

It can take up to a day for your registration to appear in our systems.
//
While you are waiting, we suggest you
//
https://forms.gle/iXjKprV7v3ANFui86[use this form]
//
to sign up to receive _temporary_ access to the Spring 2020 course forum and be
put on our mailing lists.
//
Once you complete the form, wait one hour and you should be able to log in to
the course forum.

Note that temporary access will end on 2/20/2020, so you must officially register
before that point.

== Follow the Lab 0 Instructions

At this point you should go through the steps in
//
link:/lab/0/[Lab 0].

== Review Forum Announcements

At this point you should have access to the {forum}.
//
This is a great place to ask further questions!

**You should also review all posts in the
//
https://cs125-forum.cs.illinois.edu/c/spring-2020-announcements[announcements
category].**
//
This is how we distribute information about CS 125.

== Review the Lecture Slides and Videos

As you complete the homework you'll want to go through our
//
link:/learn/[online lecture slides]
//
and view any videos that are available.
//
If videos for this semester have not yet been posted you can review videos from
a previous semester.
//
The content covered in the first few weeks doesn't change much from semester to
semester.

== Complete the Homework

Once you have completed the link:/lab/0/[Lab 0] instructions you should make
sure that you have finished all available
//
https://prairielearn.engr.illinois.edu/pl/course_instance/52292/assessments[homework
problems].
//
**Note that the first set of homework problems is available until the end of
the third week of class (2/10/2020).**
//
So you have time to catch up and finish them.

== If You Missed Our First (or Second) Quiz...

If you missed our first CBTF Quiz you can take it after completing our _second_
CBTF quiz during the second week of class.
//
Quiz 0 is extremely easy and will only take you 5 minutes.
//
So you can take it during the time slot you reserve to take Quiz 1.

If you missed our second CBTF quiz you should schedule a separate time in the
CBTF to take that quiz.
//
Contact the CBTF to make arrangements.

== Keep In Mind

* We don't start counting lecture participation until the third week of class
//
* We don't start counting lab participation until the third week of class
//
* All of the first three week's homework will be due at the end of the
third week of class

Good luck catching up!
//
Please contact us on the {forum} if you have any trouble or questions.

// vim: ts=2:sw=2:et:ft=asciidoc
