---
title: "Course Resources"
description: >
  Helpful resources for succeeding at CS 125.
priority: 0.8
changefreq: monthly
layout: single.hbt
sidebar: info
spelling_exceptions:
  - Codecademy
  - Coursera
  - Eck
  - EdX
  - HackerRank
  - Udacity
---
:sectnums:
:linkattrs:

[.lead]
//
You will probably find the following resources helpful to your success in CS
125.

[[forum]]
== Forum

We have set up a
//
link:/forum/[Discourse forum]
//
for CS 125.
//
The forum is the right place to ask questions, get help, and interact with other
students and the course staff outside of lectures, labs, and office hours.
//
*Please use it for all course-related questions that are not of a sensitive
nature*, since answering them there helps other students with the same
question.

Please also get in the habit of _searching the forum_ before asking a question.
//
Chances are fairly good that your question has already been asked and answered,
which means that you can find out what you wanted to know immediately!
//
On public forums this is also considered good forum etiquette.

=== Accessing the Forum

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/jza08L67oes" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

To participate in CS 125, you need to be able to log on to the
link:/forum/[course forum] using your @illinois.edu email account.
//
That may require activating Google Apps on your Illinois account.
//
Here's what to do:

. Visit https://answers.uillinois.edu/illinois/47880[this site].
//
Click on the appropriate link&mdash;undergraduates, or faculty staff and
graduate students&mdash;and make sure that you have enabled Google Apps
integration.
//
The process requires accepting a license agreement.
//
. Now go to https://www.google.com[Google].
//
If you are not logged in, click "Login" in the upper right hand corner.
//
Otherwise, click your avatar and choose "Add Account".
//
This should redirect you to the familiar Illinois Active Directory log in page.
//
. Once you have completed these steps, you should have a choice of login
options when you return to the forum.
//
Choose your @illinois.edu address and you will be able to access and participate
in the forum.

=== Why Not Piazza?

We are using the excellent
//
https://github.com/discourse/discourse[open-source]
//
https://www.discourse.org/[Discourse] forum software
//
to power our course forum.
//
Why aren't we using https://piazza.com/[Piazza], which is fairly popular in the
educational space?
//
There are four main reasons that we consider Discourse a better choice for CS
125:

. *Discourse enables discussion.*
//
Piazza is designed for students to converge to one answer.
//
But in computer science, there are frequently multiple ways to approach a
problem, and solutions frequently emerge through a conversation.
//
. *Discourse has a future.*
//
Unlike Piazza, Discourse is increasingly used outside academia by companies to
host product and technology discussion forums, and by other online communities.
//
Familiarity with it will benefit you as you continue your explorations in
computer science.
//
. *Discourse is better tech.*
//
Discourse is a modern, responsive, and interactive web application.
//
Piazza... is not.
//
As budding computer scientists, we want to expose you to the best tech out there
so that you are inspired by the kind of things that you will soon be able to
create.
//
. *Discourse is
//
https://en.wikipedia.org/wiki/Free_and_open-source_software[free and open
source].*
//
We believe in the power of the open source community, and in encouraging you to
share _your_ creations freely and openly.
//
Discourse is a great example of what talented volunteers can build when they
work together.

[[textbook]]
== Online Textbook

We assign readings from the comprehensive and free online textbook
//
http://math.hws.edu/javanotes/[Introduction to Programming Using Java, Seventh
Edition],
//
by
//
http://math.hws.edu/eck/[David J. Eck]
//
of
//
http://www2.hws.edu/[Hobart and William Smith Colleges].
//
This textbook is available in several formats, including as a
//
http://math.hws.edu/eck/cs124/downloads/javanotes7-linked.pdf[PDF].
//
There are also examples programs included&mdash;see the
//
http://math.hws.edu/javanotes/[website]
//
for more details.

[[online]]
== Other Online Resources

The internet is full of information, and _particularly_ full of information
about computer science.
//
We will not curate a list of online resources here, since Google is by far the
best way to find out more.
//
But here are a few examples of high-quality materials that may help you learn
Java:

* *https://www.codecademy.com/[Codecademy]* has great interactive online
tutorials about many programming languages, including
https://www.codecademy.com/learn/learn-java[Java].
//
* http://www.learnjavaonline.org/[Learn Java Online] provides an interactive
web-based learning experience specifically tailored to Java.
//
* *https://www.coursera.org/[Coursera]* also has many
https://www.coursera.org/courses?languages=en&query=java[Java-based courses]
from a variety of excellent universities.
//
https://www.edx.org/[EdX] and https://www.udacity.com[Udacity] do as well.
//
* The online programming practice site https://www.hackerrank.com/[HackerRank]
has a https://www.hackerrank.com/domains/java/java-introduction[series of
introductory Java questions]

This list is just the tip of the iceberg, but it should make it clear that _if
you want to learn Java, you can_.
//
We're hear to provide help and inspiration along the way.
