---
title: "Welcome to CS 125"
---

[.lead]
//
Good software is designed to help a user accomplish a task.
//
Similarly, this course is designed to help you accomplish a task: _learning
computer science_.
//
The pre-lecture readings are designed to help you, so below we discuss how to
approach them effectively.

== About The Readings

CS 125 is designed based on research about how students best learn the ideas and
skills required to get started in computer science.
//
An important part of our approach is having you complete pre-lecture readings
and activities _before coming to class_.
//
After completing the readings, you arrive at lecture with a preliminary
understanding of the concepts covered that day.
//
You are ready to engage in the in-class activities, engage with the material,
and ask questions.
//
Lectures will discuss ideas introduced in the readings, expand on new concepts
and, most importantly, work problems designed to cement your understanding of
the material.
//
Lectures are designed to _reinforce_&mdash;not introduce&mdash;the material that
you have already begun to learn through the pre-lecture materials.
//
As a result, you will get the most out of the readings, the lectures, and the
course, if you complete the pre-lecture activities _before_ coming to lecture.

== Preparing for Class

You should budget enough time in your schedule to complete each day's assigned
readings and activities.
//
But we understand that occasionally you may not be able to complete all of
them&mdash;when you get sick, or have an important exam in another class.
//
Our advice is these cases is to review as much of the material as possible
before attending lecture.
//
Then, complete a more detailed examination with a day or two.
//
**CS 125 moves quickly, and you cannot afford to fall behind.**
//
Participation in lab sections and success on the quizzes and machine problems
depends on your conceptual understanding of the material.

== Active Reading

The information presented here is intended to promote _active reading_.
//
When reading passively&mdash;such as consuming a novel during your summer
vacation&mdash;the goal is to be entertained.
//
The goal of active reading&mdash;understanding&mdash;is different, and so it
requires a different approach.
//
When reading actively, the reader will be reorganizing or restructuring
information with the goal of achieving deep understanding.
//
The active reader is constantly making ties to things she already knows so that
it becomes a part of her greater understanding.
//
We will facilitate active reading by providing activities and exercises designed
to promote rapid understanding and assimilation of the course content.

A primary difference between active and passive reading is _pace_.
//
Technical reading demands a slower pace than pleasure reading.
//
You may need to repeat complex passages to ensure that you understand them.

Optimally, rereading and revisiting content at a variety of time intervals has
been shown to be most effective.
//
Multiple encounters with the same material trigger the brain to recognize that
it is important and reinforce its placement in long-term memory.
//
Later readings may provide valuable context that will make the original reading
more understandable in the second or third encounter.
//
You can't learn anything by reading or doing it once.
//
Understanding requires multiple encounters spread out over a long period of
time.

=== Guidelines for Active Reading

Active reading is a skill, and you'll get better at it with practice.
//
Here are some suggestions to get you started:

* *Identify and highlight important sections.* Pay particular attention to
the example problems&mdash;they are often the most important parts.
//
* *Write your own notes.* Reword the material is a powerful form of
reinforcement.
//
* *Vary your pace.* Read fast, read slowly, depending on the content.
//
Is this technical material that I need to think about?
//
Then read slowly.
//
Is this more explanatory, or material I already understand?
//
Then skim quickly.
//
* *Quiz yourself.*
//
Do example problems&mdash;or better yet, modified versions of the given
problems&mdash;until you can easily do them yourself.
//
* *Make the material relevant.*
//
Is there a technology that I use that work this way?
//
Is there something I'd like to build that could incorporate this ideas?
//
* *Change your environment.*
//
Find different locations: read inside, outside, in quiet places and places with
a din.
//
Read in groups with different people, including friends and strangers.
//
Take the opportunity to teach the ideas to each other.

=== Concentrating

The time spent on course reading should be efficient, directed and focused.
//
Besides saving time for other endeavors, you will increase your happiness.
//
If your current environment is not conducive to focus, go someplace else.
//
Use the notification settings on your device to eliminate interruptions from
email and text messages while you are actively reading.
//
Even with these provisions, distractions will occasionally occur.
//
Tend to these interruptions, then return to your reading.
//
While computers are tremendously powerful and programming is extremely exciting
and fulfilling, there _are_ more important things in life than computer science.

=== Learn to Read Selectively

You won’t always need to read or reread entire blocks of content.
//
Sometimes getting a feel for the content of a section is enough to remind you of
all the content contained therein.
//
And sometimes its all you need to know.

When reviewing, reading the introduction and the conclusions is often enough to
allow you to quiz yourself on the content.
//
If you are able to sufficiently recall and use the information in the chapter,
that refresher should be enough time spent reviewing.
//
Experts almost always read the abstracts and conclusions of research papers
footnote:[...and possibly glance at the figures...] to get a sense of what the
paper is about before deciding to read the entire thing.
//
Your personal notes on a section should play a similar role to an abstract in
your reviewing of material.

To aid your active reading, you may want to try an approach developed by the
educational philosopher
//
https://en.wikipedia.org/wiki/Francis_P._Robinson[Francis Robinson].
//
It is called
//
https://en.wikipedia.org/wiki/SQ3R[**SQ3R**]:

* **Survey:** Develop an overview that can guide you on what you can skim and
what will require more attention.
//
* **Question:** Ask yourself what this chapter is about.
//
What do I know about this already?
//
What don’t I understand?
//
What is this page about?
//
What is the key idea?
//
What facts or examples support it?
//
How is it organized?
//
* **Read** the content with the goal to _summarize_ the content.
//
Reduce it to a much smaller number of notes.
//
* **Retrieve** footnote:[or Recite] the content from memory.
//
Use this step to test your understanding.
//
Try teaching the material to someone else.
//
* **Review** your notes.
//
Do this a day or two later, to let your brain encounter the material again.

Remember&mdash;the goal is to ensure that your brain continually returns to key
concepts over a long period of time.
//
This builds the mental pathways that lead to long-term understanding.
