---
title: "MP0: Triple Crown"
description:
  MP0 has you complete three small programming tasks to whet your appetite for
  what comes next.
priority: 0.5
changefreq: monthly
layout: single.hbt
sidebar: MP
---
:sectnums:
:linkattrs:

[.lead]
//
Let's start hacking!
//
MP0 challenges you to complete three small programming tasks.
//
It also introduces you to the development workflow we'll use throughout the rest
of the semester.

*MP0 is due Friday 1/26/2017 @ 5PM.
//
To receive full credit, you must submit by this deadline.*
//
Late submissions will be subject to the
//
link:/info/syllabus/#regrading[MP late submission policy].

[[objectives]]
== Learning Objectives

The purpose of MP0 is to get you started programming in Java.
//
Specifically, it begins to train you to:

. initialize and use variables of appropriate types
//
. perform simple calculations using integer arithmetic
//
. use simple loops and conditional statements
//
. translate program descriptions into working code
//
. work with test suites as part of your development process

[[structure]]
== Assignment Structure

MP0 consists of three short programs:

. `LCM.java`: computes the
//
https://en.wikipedia.org/wiki/Least_common_multiple[least common multiple]
//
of two integers
//
. `MaximumOfLastN.java`: returns the maximum of last N values of an array of floats
//
. `Quizzer.java`: computes a score for a short quiz

[[getting]]
=== Obtaining MP0

Use
//
https://classroom.github.com/a/qa9fBqpA[this GitHub Classroom invitation link]
//
to fork your copy of MP0.
//
Once your repository has been created, import it into IntelliJ following
//
link:/MP/setup/git/#workflow[our assignment Git workflow guide].

[[requirements]]
=== Your Goal

All three programs need to be completed.
//
The structure of each is similar:

. Each contains a `main` method that solicits input from the user.
//
*You do not need to modify the `main` methods*, but you may want to read them
and try to figure out how they work.
//
. User inputs are passed to a separate helper function that you are assigned to
write.
//
These functions do the heavy lifting for each program: computing the least
common multiple (`lcm`), returning the maximum (`maximumOfLastN`), and computing
the quiz score (`computeScore`).
//
. Each program includes a test suite: `LCMTest.java`, `MaximumOfLastNTest.java`,
and `QuizzerTest.java`.
//
The test suite does not test the main method.
//
Instead, it directly tests the method that you are assigned to write.

Your goal is to correctly implement the missing methods so that all of the tests
pass.
//
Doing so will earn you almost full credit on the assignment&mdash;but see the
section on <<style, style below>>.

[[approach]]
== How to Approach MP0

Although MP0 may seem daunting at first, do not get discouraged!
//
Focus on identifying what you need to do and understanding the requirements of
each function.
//
There is really not a huge amount of code for you to write&mdash;our solution
adds only several dozen lines, although yours may be slightly longer.

=== Understanding What You Need to Do

A core task when approaching any programming assignment or task is to _identify
what you need to do_.
//
For MP0 there are three&mdash;and only three&mdash;functions that you need to
change.
//
Begin by identifying those functions and understanding their requirements.
//
This will go *a long way* to helping you complete the MP.

=== Test-driven Development

We have provided you with testing suites that you can use to perform iterative
test-driven development.
//
Here's how that works:

. Start with one function that you need to write for MP0&mdash;say `lcm`
in `LCM.java`.
//
. Open `LCM.java`.
//
Run the assignment test suite, which is installed as run configuration "Test
MP0".
//
Without changes to `LCM.java`, it should fail.
//
. Begin modifying the `lcm` function.
//
When you think that you have a solution, save you work and re-run the test
suite.
//
. If the test suite succeeds, you're done&mdash;congratulations!
//
. If the test suite fails, you may want to run `LCM.java` as a Java
application and interact with it to determine what is wrong.
//
Perhaps you are calculating the least common multiple correctly when the first
value is greater than the second, but not if the second is greater than the
first.
//
Interactive testing can help diagnose these kinds of problems.

In general *the fewer lines of code you write before running a test, the
better.*
//
When you are starting out, it is easy to introduce bugs into your code.
//
Bugs are easiest to catch one-by-one, and so the fewer lines of untested code
the more likely you are to identify errors in your logic or implementation.

=== Getting Help

The course staff is ready and willing to help you every step of the way!
//
Please come to link:/info/syllabus/#calendar[office hours], or post on the
https://cs125-forum.cs.illinois.edu/c/mps/mp0[forum] when you need help.
//
You should also feel free to help each other, as long as you do not violate the
<<cheating, academic integrity requirements>>.

[[grading]]
== Grading

MP0 is worth 100 points total, broken down as follows:

. *30 points*: `LCM.java`
  ** *10 points* for submitting code that compiles
  ** *10 points* each for non-trivial test case
. *30 points*: `MaximumOfLastN.java`
  ** *10 points* for submitting code that compiles
  ** *20 points* for passing the test
. *30 points*: `Quizzer.java`
  ** *10 points* for submitting code that compiles
  ** *20 points* for passing the test
. *10 points* for no `checkstyle` violations

[[testing]]
=== Test Cases

You should carefully review the test cases in `LCMTest.java`,
`MaximumOfLastNTest.java`, and `QuizzerTest.java`.
//
The MP0 testing suite follows a common pattern where functions are tested
against pre-computed inputs and outputs.
//
So, for example, when testing `MaximumOfLastNTest.java`, we compute the correct
answer for a small subset of test cases and use this to determine whether your
solution works in all cases.

Automated testing is a hugely important part of modern software development.
//
Just like computers are good at running programs, they are also good at running
programs to debug other programs.
//
Independently developing a method and the function that tests it allows the two
to support each other.
//
The test may find errors in the method, and, the method may also identify errors
in the test.

[[autograding]]
=== Autograding

We have provided you with an autograding script that you can use to _estimate_
your current grade as often as you want.
//
The IntelliJ project a run configuration called "Grade MP0" that will run the
autograder for MP0.

Unless you have modified the test cases or autograder configuration files, the
autograding output should approximate the score that you will earn when you
submit.
//
If you modify our test cases or the autograding configuration, all bets are off.
//
You may also lose points if your solution runs too slowly and exceeds the
testing timeouts.

[[style]]
=== Style Points

90 points on MP0 are for correctly implementing the required functions.
//
The other 10 points are for _style_.
//
Writing readable code according to a style guideline is extremely important, and
we are going to help you get into this habit right from the start.
//
Every software development company and most active open-source projects maintain
style guidelines.
//
Adhering to them will help others understand and integrate your contributions.

We have configured the `checkstyle` plugin to enforce a variant of the
//
http://checkstyle.sourceforge.net/sun_style.html[Sun Java coding style].
//
IntelliJ should naturally generate code that meets this standard.
//
So you should not have to fight with IntelliJ too much to avoid `checkstyle`
violations.

However, the `checkstyle` plugin does require you to add
//
https://en.wikipedia.org/wiki/Javadoc[Javadoc]
//
comments, and also avoid the use of so-called
https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad[_magic
numbers_].
//
You may find these requirements a bit annoying at first, but we trust that you
will get used to them.

[[submitting]]
== Submitting Your Work

[[cheating]]
=== Academic Integrity

Learning to program requires practice.
//
If you submit code that is not your own work, you are not getting the practice
that you need to improve.

*All work submitted for MP0 must be your own.*
//
Cheating in CS 125 may result in your removal from the CS program, or from the
University of Illinois.
//
We have many bright, honest students that want to learn computer science.
//
We don't need to waste time and energy on cheaters that don't want to learn.

Specifically, the following activities constitute cheating and will be dealt
with according to relevant
//
https://cs.illinois.edu/academics/honor-code[departmental]
//
and http://studentcode.illinois.edu/[university policies].
//
*You may not*:

. *Turn in work that was completed by anyone other than yourself.*
//
. *Copy or paste code that you did not write* from any source.
//
. *Examine another classmates solution*, reproduce it, and submit it as your own
work.

We reserve the right to run cheating detection software on all submitted student
work.
//
These programs are extremely accurate, and any evidence of cheating that they
uncover will initiate academic integrity violation proceedings.

==== A simple rule of thumb about collaboration

A general rule of thumb is that exchanging or soliciting _ideas_ about how to
solve the MP is not cheating, but exchanging code is cheating.
//
Feel free to discuss your solutions with other students as long as you do not
provide them or allow them to view your source code.
//
If you are talking in English footnote:[or another spoken human language...],
that's fine.
//
If you are talking or exchanging _computer code_, that's cheating.
