---
title: "MP3: Libraries, APIs, and JSON"
description:
  MP3 introduces you to the JSON data serialization format and working with
  external libraries and web APIs.
spelling_exceptions:
  - rickrolled
  - Rick Astley
  - iOS
  - GSON
secret: qOXJ2uy8
---
:sectnums:
:linkattrs:
:imagesdir: /MP/2018/spring/images/MP6

:forum: pass:normal[https://cs125-forum.cs.illinois.edu/c/mps/mp3[forum,role='noexternal']]
:csapi: pass:normal[https://azure.microsoft.com/en-us/services/cognitive-services/[Microsoft Cognitive Services API]]

[.lead]
//
To build great things today it helps to stand on the shoulders of giants.
//
MP3 introduces you to two different ways of using code provided by others: both
through working with external libraries and remote application programmer interfaces.
//
You also get practice working with data formatted in
//
https://www.json.org/[JavaScript Object Notation (JSON)],
//
a simple and widely-supported data exchange format.

*MP3 is due Friday 3/15/2019 @ 5PM.
//
To receive full credit, you must submit by this deadline.*
//
In addition, 10% of your grade on MP3 is for submitting code that earns at least
_50 points_ by *Monday 3/11/2019 @ 5PM.*
//
As usual, late submissions will be subject to the
//
link:/info/2018/spring/syllabus/#regrading[MP late submission policy].

[[objectives]]
== Learning Objectives

MP3 introduces you to using integrating external libraries and APIs into your
Android projects.
//
We'll show you how to use the {csapi} to analyze image data, and you'll
learn how to process the results using the
//
https://github.com/google/gson[Google GSON] library.
//
We'll also continue to reinforce the learning objectives from previous MPs
(link:/MP/0/[0], link:/MP/1/[1], and link:/MP/2/[2]).

[[structure]]
== Assignment Structure

Like previous Android MPs, MP3 is split into two pieces:

* `/lib/`: a small library that extracts certain pieces of information from the
JSON image data returned by the {csapi} using the
//
https://github.com/google/gson[Google GSON library].
//
* `/app/`: an Android app for you to use for your own interactive testing.
//
The Android app is _almost_ complete, but needs a few modifications from you.
//
And, for the app to work correctly, you need to finish the library in `lib`.

Note that you need to create `RecognizePhoto.java` in the propery directory and
add it to the `edu.illinois.cs.cs125.spring2019.mp3.lib` package.

[[lib]]
=== MP3 Image Recognition Library (`lib`)

The <<app, MP3 app>> handles uploading photos to the {csapi}.
//
However, once the results are returned it relies on your library to extract a
few pieces of information:

* *The image width, height, and format*: using `getWidth`, `getHeight`, and
`getFormat`.
//
* *The autogenerated image caption*: using `getCaption`
//
* *Whether the image contains a dog or a cat* footnote:[Or both!]: using
`isADog` and `isACat`
//
* *Whether you've been
//
https://en.wikipedia.org/wiki/Rickrolling[rickrolled]*:
//
that is, whether the photo contains
//
https://en.wikipedia.org/wiki/Rick_Astley[Rick Astley],
//
using `isRick`.

As always, you may find our
//
https://cs125-illinois.github.io/MP3-Solution/[official MP3 online documentation]
//
useful as you understand what you need to do.
//
If you believe that the documentation is unclear, please post on the {forum} and
we'll offer clarification as needed.
//
To complete this part of the assignment you'll want to review the
//
<<json, section on JSON below>>.

[[app]]
=== MP3 App

The MP6 app handles obtaining images&mdash;either ones saved previously on the
device, captured by the camera, or downloaded from the internet.
//
It also uploads those images to the {csapi} and updates the UI
appropriately&mdash;or at least parts of it.

To complete MP3 most of the lines of code that you write will be completing the
<<lib, image recognition library>>.
//
However, there are a few changes that you'll need to make to earn full points
and ensure that the user interface functions properly.
//
To complete the UI you'll need to do the following things:

* *Update the UI properly* using the results provided by your library in
`finishProcessImage`.
//
You should set the description and caption properly, and show or hide the
cat and dog icons as appropriate.
//
* *Reset the UI properly* when no image is shown in `updateCurrentBitmap`.
//
* *Do something when you find Rick.*
//
You do want to celebrate, right?
//
Maybe try something
//
https://stackoverflow.com/questions/574195/android-youtube-app-play-video-intent[like
this].

[[getting]]
=== Obtaining MP3
Use
//
https://classroom.github.com/a/Pdpwi1qv[this GitHub Classroom invitation link]
//
to fork your copy of MP3.
//
Once your repository has been created, import it into Android Studio following
//
link:/MP/setup/git/#workflow[our assignment Git workflow guide].

[[requirements]]
=== Your Goal

At this point you should be familiar with the requirements from previous MPs.
//
See the <<grading, grading description below>>.
//
However, note that for MP3 *we have not provided a complete test suite*.
//
You will have to figure out how to test your Rick Astley detection yourself.

[[apis]]
== APIs

[.lead]
//
https://en.wikipedia.org/wiki/Application_programming_interface[API stands for
_application programming interface_].
//
The better you become at understanding and using existing APIs, the faster and
more easily you will be able to build powerful apps and programs.

=== What is an API?

In the most general terms, an API is
//
https://en.wikipedia.org/wiki/Application_programming_interface["a set of clearly defined methods of communication between various software components"].
//
For MP3 and your final project we are particularly interested in the subset of
_remote web-based APIs_.
//
These APIs are:

* _remote_: they are accessed over the internet, and
//
* _web-based_: they are accessed using standard web protocols.

One way of thinking about APIs is that somewhere, in some data center full of
computers, is a computer that will run certain functions for you if ask it
nicely.
//
To use that functionality you don't have to know where that computer is, or how
the function works.
//
You just have to learn how to get the data to the API in the format that it
expects, and understand how to interpret the results.

An API like a collection of functions, with each function providing different
functionality.
//
Using an API is very much like calling a function&mdash;except that to use a
_remote_ API we need to figure out how to get the data to the API and get the
results back.

=== Microsoft Cognitive Services

MP3 requires you to use a portion of the
//
https://azure.microsoft.com/en-us/services/cognitive-services/[Microsoft
Cognitive Services API].
//
It provides a variety of features focused on enabling interaction with users in
intuitive ways&mdash;processing vision and speech data, and providing
intelligent search, recommendation, and natural language services.

Why should you use this API?
//
Well, imagine that you want to extract information from photos taken by users of
your new app.
//
You have two options:

* Spend several years mastering the sophisticated machine learning and computer
vision algorithms required to implement your own solution...
//
* ...or, use the Microsoft Cognitive Services Computer Vision API.

By using APIs you are truly able to stand on the shoulders of giants.
//
Don't waste your time solving problems that you aren't interested in solving!
//
Chances are that somebody else is waiting for you to solve the problem that
_you_ want to solve.
//
Get on to that and focus on changing the world, not re-solving problems that
others have already solved.

=== Using the Cognitive Services Computer Vision API

To get a sense of what the Cognitive Services Computer Vision API can do,
experiment with some of the examples
//
https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/[on
this page].
//
For each feature, upload your own images to get a sense of what kind of
capabilities this API has.

MP3 focuses on the image analysis feature: the first one listed on
//
https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/[this
page].
//
Go through the sample images and see if you can understand the results returned
by the API:

. Are the results accurate?
//
. In cases where they are inaccurate, can you figure out why?
//
. What kind of information is reported by the API?
//
. What parts of it are you most surprised by and why?

=== Gaining API Access

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/u0eVbgBddsI" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

Like many remote APIs, gaining _programmatic_ access to the Microsoft Cognitive
Services API in your app requires a _key_.
//
Keys allow API provides to control who uses their services, and allows providers
to begin to charge API users if their usage exceeds various thresholds.

Happily, many remote APIs provide free access for usage that is more than
sufficient to develop and test your own programs.
//
And, as a student, you also have access to many free programs offered by
companies to introduce you to their APIs and services.
//
So you can try out a lot of things without paying a dime.
//
Of course, once your app built using the Microsoft Cognitive API takes off and
is being used by one million people, you'll need to start shelling out some
money to Microsoft.
//
But let's get there first.

So the first step to gaining access to the Cognitive Services API is to get an
API key.
//
You can
//
https://azure.microsoft.com/en-us/try/cognitive-services/[follow these instructions]
//
or watch the screencast above.

Microsoft API keys are only valid for specific regions, so note that when you
generate your key.
//
You'll need both the key _and_ the region in just a minute.

=== Integrating the {csapi} into MP3

The screencast above shows you how we use the {csapi} in MP3 and how to add
_your_ {csapi} key to your project so that you can make your own requests.

Of course, like any artificial intelligence system, the {csapi} is not perfect.
//
We've seen it produce some very amusing results.
//
If you find a good one, post it on the {forum} for us to giggle at.

[[json]]
== JSON

[.lead]
//
Object-oriented languages make it easy to model data internally by designing
classes.
//
But at times we need to exchange data between two different programs or systems,
possibly implemented in different languages.
//
That requires representing the data in a format that _both_ systems can
understand.
//
JSON (JavaScript Object Notation) is one popular _data exchange_ format in wide
use on the internet, and frequently used to communicate with web APIs.

JSON is both simple and incredibly powerful.
//
It is based on only two different principles, but can represent a wide variety
of different data.
//
Using the {csapi} requires understanding JSON, and completing MP3 requires that
you implement several simple JSON parsing tasks.

=== What is JSON?

Imagine we have an instance of the following Java class:

[source,java]
----
public Person {
    public String name;
    public int age;

    Person(String setName, String setAge) {
        name = setName;
        age = setAge;
    }
}
Person geoffrey = new Person("Geoffrey", 38);
----

Now image we want to send this information to another computer program: for
example, from an Android app written in Java to a web application programmer
interface (API) that could be written in Java, Python, or any other language.
//
How do we represent this information in a way that is correct and complete, yet
also portable.

JSON (JavaScript Object Notation) has become a popular answer to that question.
//
While it is named after
//
https://www.javascript.com/[JavaScript],
//
the language that introduced JSON, JSON is now supported by pretty much every
common programming language.
//
This allows an app written in Java to communicate with a web API written in
Python, or a web application written in JavaScript to communicate with a web
backend written in Rust.

Enough talk.
//
Here's how the object above could be represented in JSON:

[source,json]
----
{
  "name": "Geoffrey",
  "age": 38
}
----

JSON has only _two_ ways to structure data: objects and arrays.
//
Above you seen an example object.
//
Like Java, it has named variable (`name`, `age`) each of which takes on a
particular value ("Geoffrey", 38).
//
Here's another example.
//
The following instance of this Java object:

[source,java,role='small']
----
public Course {
    public String name;
    public int enrollment;
    public double averageGrade;

    Course(String setName, String setEnrollment, double setAverageGrade) {
        name = setName;
        enrollment = setEnrollment;
        averageGrade = setAverageGrade;
    }
}
Course cs125 = new Course("CS 125", 500, 3.9);
----

would be represented as this JSON string:

[source,json]
----
{
  "name": "CS 125",
  "enrollment": 500,
  "averageGrade": 3.9
}
----

JSON can also represent arrays.
//
This Java array:

[source,java]
----
int[] array = new int[] { 1, 2, 10, 8 };
----

would be represented using this JSON string:

[source,json]
----
[1, 2, 10, 8]
----

We can also represent nested objects and objects with array instance variables:

[source,java]
----
public Person {
    public String name;
    public int age;

    Person(String setName, String setAge) {
        name = setName;
        age = setAge;
    }
}
public Course {
    public String name;
    public int enrollment;
    public double averageGrade;
    public Person instructor;
    public int[] grades;

    Course(String setName, String setEnrollment,
        double setAverageGrade, Person setInstructor,
        int[] setGrades) {
        name = setName;
        enrollment = setEnrollment;
        averageGrade = setAverageGrade;
        instructor = setInstructor;
        grades = setGrades;
    }
}
Course cs125 = new Course("CS 125", 500, 3.9,
  new Person("Geoffrey", 38), new int[] { 4, 4, 3 });
----

[source,json]
----
{
  "name": "CS 125",
  "enrollment": 500,
  "averageGrade": 3.9,
  "instructor": {
    "name": "Geoffrey",
    "age": 38
  },
  "grades": [
    4,
    4,
    3
  ]
}
----

=== Parsing JSON

Because JSON is supported by many different programming languages, many web APIs
return data in JSON format.
//
The {csapi} is one of them.
//
To utilize this data, you must first _parse_ it or _deserialize_ it.
//
The process of converting a Java object&mdash;or object in any language&mdash;to
JSON is called serialization.
//
The reverse process is called deserialization.

Happily, good libraries exist to parse JSON in every programming language.
//
Java is no exception.
//
We have included the
//
https://github.com/google/gson[Google GSON]
//
JSON parsing library in your project for you to use.
//
*Note that you must use the GSON library to parse JSON for MP3.*
//
Attempts to add other JSON parsing libraries to your project will fail during
remote grading.

One way to use GSON is to create a class that matches your JSON string.
//
So if you were provided with this JSON from a web API:

[source,json]
----
{
  "number": 0,
  "caption": "I'm a zero"
}
----

you would design this Java class to represent it:

[source,java]
----
public class Result {
    public int number;
    public String caption;
}
----

Note how our classes mirrors both the names (`number`, `caption`) and types (`int`,
`String`) from the JSON result.

However, when you are working with unfamiliar JSON data, as you are in MP3, we
suggest that you _not_ create new classes and instead
//
https://stackoverflow.com/questions/16595493/gson-parsing-without-a-lot-of-classes[use
the built-in Java classes].
//
Here's an example of how to do this given the JSON string shown above:

[source,java]
----
JsonParser parser = new JsonParser();
JsonObject result = parser.parse(jsonString).getAsJsonObject();
int number = result.get("number").getAsInt();
String caption = result.get("caption").getAsString();
----

**Note that for MP3 we will not grade any additional class files you add to your
`lib` directory.**
//
So we suggest you follow our example above footnote:[Or define your
deserialization classes as inner classes to the `RecognizePhoto` class you are
working on... if you really know what you are doing.].

[[csapi-json]]
=== Example JSON

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/Dj_LgQsmBxs" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++


link:/MP/3/example.json[Here is some example JSON,role='external'] produced by
the {csapi}.
//
You may want to consult this as you begin work on your image recognition
functions.

== Putting It All Together

Finally, the screencast above provides a brief overview of how your app _should_
work once you are done.
//
Good luck!

[[grading]]
== Grading

MP3 is worth 100 points total, broken down as follows:

. *55 points*: `RecognizePhoto.java`
  ** *5 points* for `getWidth`
  ** *5 points* for `getHeight`
  ** *5 points* for `getFormat`
  ** *10 points* for `getCaption`
  ** *10 points* for `isADog`
  ** *10 points* for `isACat`
  ** *10 points* for `isRick`
. *25 points*: `MainActivity.java` and `Tasks.java`
  ** *5 points* for making an API request properly when the button is clicked
  ** *5 points* for setting the metadata properly
  ** *5 points* for setting the caption properly
  ** *10 points* for adjusting the animal icons properly
. *10 points* for no `checkstyle` violations
. *10 points* for committing code that earns at least 50 points before
*Monday 3/11/2019 @ 5PM.*

[[testing]]
=== Test Cases

As in previous MPs, we have provided test cases for MP3.
//
Please review the link:/MP/0/#testing[MP0 testing instructions].

However, _unlike_ previous MPs we have not provided _complete_ test cases for
MP3.
//
Specifically, we have not provided a test for `isRick`.
//
This is intentional, and designed to force you to do your own local testing.
//
It is also designed to not give away exactly what features of the JSON returned
by the {csapi} you will need to look at to complete `isRick`.

[[autograding]]
=== Autograding

Like previous MPs we have provided you with an
autograding script that you can use to estimate your current grade as often as
you want.
//
Please review the link:/MP/0/#autograding[MP0 autograding instructions].
//
However, as <<testing, described above>> note that the local test suite will not
test `isRick`, while the remote test suite will.

[[submitting]]
== Submitting Your Work

Follow the instructions from the
//
link:/MP/setup/git#submitting[submitting portion]
//
of the
//
link:/MP/setup/git#workflow[CS 125 workflow]
//
instructions.

And remember, you must submit something that earns 50 points before *Monday
3/11/2019 @ 5PM* to earn 10 points on the assignment.

[[cheating]]
== Academic Integrity

Please review the link:/MP/0/#cheating[MP0 academic integrity guidelines].

If you cheat, we will make your watch this over and over again:

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/dQw4w9WgXcQ" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++
