---
title: "MP4: 2D"
description:
  In MP4 you have a chance to work with two-dimensional arrays and complete a
  simple photo editing application.
priority: 0.5
changefreq: monthly
layout: single.hbt
sidebar: MP
spelling_exceptions:
---
:sectnums:
:linkattrs:

[.lead]
//
As we have learned previously, computers are frequently used to transform and
analyze data.
//
And an increasing amount of that data is _multi-dimensional_: including both
photo and video data.
//
People are taking a huge amount of photos and video, and processing that data is
almost entirely done on or by computers.

For MP4 you'll be working with two-dimensional photo pixel data as you complete
the server part of a simple photo editing application.
//
*It is due Friday, October 13th, 2017 @ 5PM. To receive full credit, you must
submit by this deadline.*
//
In addition, 10% of your grade on MP3 is for committing code that earns at least
_20 points_ by *Tuesday, October 10th, 2017 @ 5PM.*

[[objectives]]
== Learning Objectives

The purpose of MP4 is to continue introducing you to data transformation.
//
You'll begin to learn how to:

. implement various image transformations by performing transformations on 2D
arrays
//
. avoid writing repetitive code by identifying similarities between various
transformations
//
. working with bits and bytes to get and set pixel color channel information

We'll also continue to reinforce the learning objectives from previous MPs
(link:/MP/1/[1], link:/MP/2/[2], and link:/MP/3/[3]).

[[structure]]
== Assignment Structure

MP3 consists of a single client-server system.
//
The HTML, CSS, and JavaScript for the client are provided for you.
//
But it relies on your backend to work properly.

Your job is to complete the required transformations in `Transform.java`.
//
These functions are called by the web server that is set up using `Server.java`.

As always, you may find our official
//
https://cs125-illinois.github.io/MP4/[MP3 online documentation]
//
helpful in understanding what each function is supposed to do.

[[getting]]
=== Obtaining MP4

Please follow the instructions from link:/MP/1/#getting[MP4].
//
You'll find MP4 in an `MP4` folder in your Subversion home directory.
//
Unless you want to learn a lot more about Subversion, *do not delete your MP4
folder once you have it.*

[[requirements]]
=== Your Goal

At this point you should be familiar with the requirements from previous MPs.
//
MP4 is similar, and retains the starting the assignment on time grading
component from link:/MP/3/[MP3].
//
See the <<grading, grading description below>>.

[[approach]]
== Completing the Transformations

=== Don't Repeat Yourself (DRY)

=== Getting Help

The course staff is ready and willing to help you every step of the way!
//
Please come to link:/info/syllabus/#calendar[office hours], or post (in the
right place) on the
//
link:/forum/[course forum] when you need help.
//
You should also feel free to help each other, as long as you do not violate the
<<cheating, academic integrity requirements>>.

[[grading]]
== Grading

MP4 is worth 100 points total, broken down as follows:

. *80 points*: `Transform.java`
  ** *10 points* for submitting code that compiles
  ** *10 points* for completing the position shift transformations
  ** *20 points* for completing the rotation and flip transformations
  ** *20 points* for completing the color shift transformations
  ** *10 points* for completing the shrink and expand transformations
  ** *5 points* for completing the green screen transformation
  ** *5 points* for completing a mystery transformation
. *10 points* for no `checkstyle` violations
. *10 points* for committing code that earns at least 20 points before *Tuesday,
October 10th, 2017 @ 5PM.*

[[testing]]
=== Test Cases

As in previous MPs, we have provided exhaustive test cases
for each part of MP4.
//
Please review the link:/MP/1/#testing[MP1 testing instructions].

[[autograding]]
=== Autograding

Like previous assignments, we provide you with an autograding script that you
can use to estimate your current grade as often as you want.
//
Note that, like link:/MP/3/[MP3], the local autograder can only calculate 90 out
of your 100 total points.

Unless you have modified the test cases or autograder configuration files, the
autograding output should equal the score that you will earn when you submit.
//
*If you modify our test cases or the autograding configuration, all bets are
off.*

[[submitting]]
== Submitting Your Work

Overall you should refer to link:/MP/subversion[our instructions for using
Subversion].
//
Commit early and often!
//
You only earn credit for the version of your code that is committed to your
repository, so ensure that we have your best submission before the deadline.

And remember, you must commit something that earns 20 points before *Tuesday,
October 10th, 2017 @ 5PM* to earn 10 points on the assignment.

[[cheating]]
=== Academic Integrity

Please review the link:/MP/1/[MP1 academic integrity guidelines].
