---
title: "MP5: ConnectN"
description:
  MP5 provides you with practice in Java class design and working with objects.
  And you get to implement a fun game along the way.
priority: 0.5
changefreq: monthly
layout: single.hbt
sidebar: MP
spelling_exceptions:
  - ConnectN
---
:sectnums:
:linkattrs:

[.lead]
//
Maybe you play them, maybe you don't, maybe you carry your gaming desktop with
you at all times&mdash;but regardless of how you feel about it, a fair number of
people use computers to play games.
//
Some of those games can be instructive, some can be fun.
//
But an MP where you get to build a fun game is both fun _and_ instructive!

For MP5 you'll be learning Java class design and object-oriented programming as
you complete a simple Connect-4-like game.
//
*It is due Friday, November 3rd, 2017 @ 5PM. To receive full credit, you must
submit by this deadline.*
//
In addition, 10% of your grade on MP5 is for committing code that earns at least
_50 points_ by *Friday, October 27th, 2017 @ 5PM.*

[[objectives]]
== Learning Objectives

The purpose of MP5 is begin introducing you to object-oriented programming.
//
MP5 does not explore more advanced topics like inheritance, interfaces, or
polymorphism.
//
It sticks to the basics: instance and class variables, getters and setters,
constructors, and instance and class methods.
//
You'll begin to learn how to:

. design a class that meets a given specification
//
. implement that class including both properly-protected variables and
appropriate methods

We'll also continue to reinforce the learning objectives from previous MPs
(link:/MP/1/[1], link:/MP/2/[2], link:/MP/3/[3], and link:/MP/4/[4]).
//
There is a _small_ amount of 2D array manipulation in MP5, but hopefully not
enough to give you too terrible flashbacks to link:/MP/4/[MP4].

[[structure]]
== Assignment Structure

Like link:/MP/4/[MP4], MP5 consists of a simple client-server system.
//
The HTML, CSS, and JavaScript for the client are provided for you.
//
But it relies on your backend to work properly.

Your job is to create and complete `ConnectN.java`.
//
These functions are called by the web server that is set up using `WebServer.java`.

MP5 provides a bit less scaffolding than previous MPs.
//
This is intentional.
//
Eventually you'll need to write code from scratch, and frequently you'll need to
follow a specification written by other developers or a project manager.

For MP5, the official specification is our
//
https://cs125-illinois.github.io/MP5/[MP5 online documentation].
//
It should precisely define what each public method in `ConnectN.java` should do.
//
If you believe that the documentation is unclear, please post on
link:/forum/[the forum] and we'll offer a clarification is needed.

[[getting]]
=== Obtaining MP4

Please follow the instructions from link:/MP/1/#getting[MP1].
//
You'll find MP5 in an `MP5` folder in your Subversion home directory.
//
Unless you want to learn a lot more about Subversion, *do not delete your MP5
folder once you have it.*
//
This is something that you cannot fix on your own using the Eclipse Subversive
Subversion plugin, and will need to get course staff help with.

[[requirements]]
=== Your Goal

At this point you should be familiar with the requirements from previous MPs.
//
MP5 is similar, and retains (but strengthens) the starting the assignment on
time grading component from link:/MP/3/[MP3] and link:/MP/4/[MP4].
//
See the <<grading, grading description below>>.

[[running]]
=== Running MP5

To experiment with the web interface, do the following:

. Run `WebServer.java` as a Java application.
//
You'll need to at least create `ConnectN.java` and get a few things working
before the web server will run at all.
//
. Open your web browser and navigate to http://localhost:8126[`http://localhost:8126`].

At first, nothing will work because you have not implemented any of the required
game transformation functions yet.
//
But you may want to experiment with your browser using
//
https://cs125.cs.illinois.edu/MP/5/solution/[our solution]
//
to see how things are supposed to work.

As far as browser support, we have confirmed that
//
https://www.google.com/chrome/browser/desktop/index.html[Chrome]
//
works.
//
Other browsers probably should as well.

[[conflicts]]
==== Fixing port conflict problems

Follow the instructions from link:/MP/4/#conflicts[MP4].

[[approach]]
== Approaching MP5

Unlike link:/MP/4/[MP4], MP5 is not a lot of code to write.
//
But here are the bits that are likely to trip you up.

=== Visibility

Make sure that your class has private and public variables as specified.
//
Checkstyle will normally complain about public instance variables.
//
To get it to shut up and get your 10 points, you can add
`@SuppressWarnings("checkstyle:visibilitymodifier")` above the variable that is
causing you problems.

=== Getters and Setters

MP5 requires you to implement some simple getters and setters (just return or
change the variable), and some ones with more complicated behavior.
//
Be sure to read the documentation carefully.

=== Game Logic

You will need to do a bit of work to implement the game board.
//
ConnectN is a Connect-4-like game.
//
Tiles fall in the top (large Y values) and sit at the bottom.
//
Just to confuse you a bit, we've reversed the coordinates from last week.
//
So we're now in the proper first quadrant of 2D space, with X values going left
to right and Y values going down to up:

[.table-bordered]
|===

| `(0, 2)` | `(1, 2)` | `(2, 2)`

| `(0, 1)` | `(1, 1)` | `(1, 2)`

| `(0, 0)` | `(1, 0)` | `(2, 0)`

A ConnectN game ends when either player plays N consecutive tiles in either a
single row or column footnote:[There: I said row and column.].
//
Tiles always have to be played at the lowest possible location in each
column&mdash;in a real Connect-4 board they fall downward and rest on the tiles
below them.
//
Consult the https://en.wikipedia.org/wiki/Connect_Four[Wikipedia] page for more
details.

=== Class Variables and Methods

Classes can define methods and variables that are not attached to instances.
//
See `Player.java` for an example of a class variable used to provide each
instance with a unique ID.
//
You'll need to implement some of these for `ConnectN.java`.

=== Equality

Be careful about varying definitions of equality.
//
You'll need to implement `ConnectN.equals`, but it's definition of equality is
quite strict.
//
On the other hand, the class comparison methods use a different definition of
equality.
//
Passing all of the tests requires distinguishing between the two and
implementing each correctly.

=== Getting Help

The course staff is ready and willing to help you every step of the way!
//
Please come to link:/info/syllabus/#calendar[office hours], or post (in the
right place) on the
//
link:/forum/[course forum] when you need help.
//
You should also feel free to help each other, as long as you do not violate the
<<cheating, academic integrity requirements>>.

[[grading]]
== Grading

MP5 is worth 100 points total, broken down as follows:

. *80 points*: `ConnectN.java`
  ** *5 points* for completing the title modifications
  ** *15 points total* for completing the width, height, and N value getters and
  setters
  ** *10 points* for completing the constructors
  ** *15 points* for completing the get and set board functions
  ** *10 points* for determining the game winner properly
  ** *10 points* for calculating equality correctly
  ** *10 points* for class static methods, including equality checks and factory
  creation methods
  ** *5 points* for maintaining the game count and ID properly
. *10 points* for no `checkstyle` violations
. *10 points* for committing code that earns at least 50 points before *Friday,
October 27th, 2017 @ 5PM.*

[[testing]]
=== Test Cases

As in previous MPs, we have provided exhaustive test cases
for each part of MP5.
//
Please review the link:/MP/1/#testing[MP1 testing instructions].

[[autograding]]
=== Autograding

Like previous assignments, we provide you with an autograding script that you
can use to estimate your current grade as often as you want.
//
Note that, like link:/MP/3/[MP3] and link:/MP/4/[MP4], the local autograder can
only calculate 90 out of your 100 total points.

Unless you have modified the test cases or autograder configuration files, the
autograding output should equal the score that you will earn when you submit.
//
*If you modify our test cases or the autograding configuration, all bets are
off.*

[[submitting]]
== Submitting Your Work

Overall you should refer to link:/MP/subversion[our instructions for using
Subversion].
//
Commit early and often!
//
You only earn credit for the version of your code that is committed to your
repository, so ensure that we have your best submission before the deadline.

And remember, you must commit something that earns 50 points before *Friday,
October 27th, 2017 @ 5PM* to earn 10 points on the assignment.
//
This is a bit of a higher bar than in previous assignments, since fixing
checkstyle errors will only get you 10 points and there are no points for just
compiling.
//
So you'll need to complete a few bits of class logic past this bar.

[[cheating]]
=== Academic Integrity

Please review the link:/MP/1/[MP1 academic integrity guidelines].
