---
title: "MP6: JSON and Android"
description:
  MP6 introduces you to the JSON data serialization format and provides a
  warm-up on Android programming and development.
spelling_exceptions:
  - rickrolled
  - Rick Astley
  - iOS
  - GSON
  - Activitys
secret: JGkqGlWT8m
---
:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu/c/mps/mp6[forum,role='noexternal']]
:csapi: pass:normal[https://azure.microsoft.com/en-us/services/cognitive-services/[Microsoft Cognitive Services API]]

[.lead]
//
Welcome to Android!
//
For MP6 you'll get introduced to Android by modifying a simple app.
//
But the core topic of the MP are actually using application programmer
interfaces (APIs) and serialization.
//
You'll get practice using the
//
{csapi}
//
and on parsing data formatted in
//
https://www.json.org/[JavaScript Object Notation (JSON)],
//
a simple and widely-supported data exchange format.

*MP6 is due Friday 4/13/2018 @ 5PM.
//
To receive full credit, you must submit by this deadline.*
//
In addition, 10% of your grade on MP6 is for submitting code that earns at least
_40 points_ by *Wednesday 4/11/2018 @ 5PM.*
//
As usual, late submissions will be subject to the
//
link:/info/syllabus/#regrading[MP late submission policy].

[[objectives]]
== Learning Objectives

MP6 introduces you to using integrating external APIs into your projects and to
Android development.
//
We'll show you how to use the powerful {csapi} to analyze image data, and you'll
learn how to process the results.
//
We'll also introduce you to the structure of a simple Android app, and you'll
get practice modifying the UI to reflect the information provided by the
Cognitive Services API.
//
We'll also continue to reinforce the learning objectives from previous MPs
(link:/MP/0/[0], link:/MP/1/[1], link:/MP/2/[2], link:/MP/3/[3],
link:/MP/4/[4], and link:/MP/5/[5]).

[[structure]]
== Assignment Structure

Unlike previous MPs, MP6 is split into two pieces:

* `/lib/`: a small library that extracts certain pieces of information from the
image data returned by the {csapi}.
//
*This library is the only part of the MP tested by the test suite.*
//
* `/app/`: an Android app for you to use for your own interactive testing.
//
The Android app is _almost_ complete, but needs a few modifications from you.
//
And, to work correctly, you need to finish the library in `lib`.

[[lib]]
=== MP6 Image Recognition Library (`lib`)

The <<app, MP6 app>> handles uploading photos to the {csapi}.
//
However, once the results are returned it relies on your library to extract a
few pieces of "important" information:

* *The image width, height, and format*: using `getWidth`, `getHeight`, and
`getFormat`.
//
* *The autogenerated image caption*: using `getCaption`
//
* *Whether the image contains a dog or a cat* footnote:[Or both!]: using
`isADog` and `isACat`
//
* *Whether you've been
//
https://en.wikipedia.org/wiki/Rickrolling[rickrolled]*:
//
that is, whether the photo contains
//
https://en.wikipedia.org/wiki/Rick_Astley[Rick Astley],
//
using `isRick`.

As always, you may find our
//
https://cs125-illinois.github.io/MP6-Starter/[official MP6 online documentation]
//
useful as you understand what you need to do.
//
If you believe that the documentation is unclear, please post on the {forum} and
we'll offer clarification as needed.
//
To complete this part of the assignment you'll want to review the
//
<<json, section on JSON below>>.

[[app]]
=== MP6 App

The MP6 app handles obtaining images&mdash;either ones save previously on the
device, captured by the camera, or downloaded from the internet.
//
It also uploads those images to the {csapi} and updates the UI
appropriately&mdash;or at least parts of it.

To complete MP6 most of the lines of code that you write will be completing the
<<lib, image recognition library>>.
//
However, there are a few small changes that we encourage you to make so that the
user interface functions properly.
//
We've done a few things to get you started.
//
Examine `finishProcessImage` to see how we use the results from `getWidth`,
`getHeight`, and `getFormat` to update a part of the UI.
//
To complete the UI you'll need to do the following things:

* *Update the caption* using the result from `getCaption`.
//
You should be able to use our example of updating the description as a starting
point.
//
* *Show or hide the cat and dog icons as appropriate.*
//
You may want to look at `updateCurrentBitmap` for examples of how these icons
are _hidden_ when the current image is cleared.
//
* *Do something when you find Rick.*
//
You do want to celebrate, right?
//
Maybe try something
//
https://stackoverflow.com/questions/574195/android-youtube-app-play-video-intent[like
this].

[[getting]]
=== Obtaining MP6

*Note that we are using Android Studio for MP6.*
//
Use
//
https://classroom.github.com/a/qJ5dPKlE[this GitHub Classroom invitation link]
//
to fork your copy of MP6.
//
Once your repository has been created, import it into *Android Studio* following
//
link:/MP/setup/git/#workflow[our assignment Git workflow guide].

[[help]]
=== Getting Help

The course staff is ready and willing to help you every step of the way
footnote:[Armed with a helpful cheat sheet..]!
//
Please come to link:/info/syllabus/#calendar[office hours], or post on the
{forum} when you need help.
//
You should also feel free to help each other, as long as you do not violate the
<<cheating, academic integrity requirements>>.

[[requirements]]
=== Your Goal

At this point you should be familiar with the requirements from previous MPs.
//
See the <<grading, grading description below>>.
//
However, note that for MP6 *we have not provided a complete test suite*.
//
You will have to figure out how to test your Rick Astley detection yourself.

[[json]]
== JSON

[.lead]
//
Object-oriented languages make it easy to model data internally by designing
classes.
//
But at times we need to exchange data between two different programs or systems,
possibly implemented in different languages.
//
That requires representing the data in a format that _both_ systems can
understand.
//
JSON (JavaScript Object Notation) is one popular _data exchange_ format in wide
use on the internet, and frequently used to communicate with web APIs.

JSON is both simple and incredibly powerful.
//
It is based on only two different principles, but can represent a wide variety
of different data.
//
Using the {csapi} requires understanding JSON, and completing MP6 requires that
you implement several simple JSON parsing tasks.

=== What is JSON?

Imagine we have an instance of the following Java class:

[source,java]
----
public Person {
    public String name;
    public int age;

    Person(String setName, String setAge) {
        name = setName;
        age = setAge;
    }
}
Person geoffrey = new Person("Geoffrey", 38);
----

Now image we want to send this information to another computer program: for
example, from an Android app written in Java to a web application programmer
interface (API) that could be written in Java, Python, or any other language.
//
How do we represent this information in a way that is correct and complete, yet
also portable.

JSON (JavaScript Object Notation) has become a popular answer to that question.
//
While it is named after
//
https://www.javascript.com/[JavaScript],
//
the language that introduced JSON, JSON is now supported by pretty much every
common programming language.
//
This allows an app written in Java to communicate with a web API written in
Python, or a web application written in JavaScript to communicate with a web
backend written in Rust.

Enough talk.
//
Here's how the object above could be represented in JSON:

[source,json]
----
{
  "name": "Geoffrey",
  "age": 38
}
----

JSON has only _two_ ways to structure data: objects and arrays.
//
Above you seen an example object.
//
Like Java, it has named variable (`name`, `age`) each of which takes on a
particular value ("Geoffrey", 38).
//
Here's another example.
//
The following instance of this Java object:

[source,java,role='small']
----
public Course {
    public String name;
    public int enrollment;
    public double averageGrade;

    Course(String setName, String setEnrollment, double setAverageGrade) {
        name = setName;
        enrollment = setEnrollment;
        averageGrade = setAverageGrade;
    }
}
Course cs125 = new Course("CS 125", 500, 3.9);
----

would be represented as this JSON string:

[source,json]
----
{
  "name": "CS 125",
  "enrollment": 500,
  "averageGrade": 3.9
}
----

JSON can also represent arrays.
//
This Java array:

[source,java]
----
int[] array = new int[] { 1, 2, 10, 8 };
----

would be represented using this JSON string:

[source,json]
----
[1, 2, 10, 8]
----

We can also represent nested objects and objects with array instance variables:

[source,java]
----
public Person {
    public String name;
    public int age;

    Person(String setName, String setAge) {
        name = setName;
        age = setAge;
    }
}
public Course {
    public String name;
    public int enrollment;
    public double averageGrade;
    public Person instructor;
    public int[] grades;

    Course(String setName, String setEnrollment,
        double setAverageGrade, Person setInstructor,
        int[] setGrades) {
        name = setName;
        enrollment = setEnrollment;
        averageGrade = setAverageGrade;
        instructor = setInstructor;
        grades = setGrades;
    }
}
Course cs125 = new Course("CS 125", 500, 3.9,
  new Person("Geoffrey", 38), new int[] { 4, 4, 3 });
----

[source,json]
----
{
  "name": "CS 125",
  "enrollment": 500,
  "averageGrade": 3.9,
  "instructor": {
    "name": "Geoffrey",
    "age": 38
  },
  "grades": [
    4,
    4,
    3
  ]
}
----

=== Parsing JSON

Because JSON is supported by many different programming languages, many web APIs
return data in JSON format.
//
The {csapi} is one of them.
//
To utilize this data, you must first _parse_ it or _deserialize_ it.
//
The process of converting a Java object&mdash;or object in any language&mdash;to
JSON is called serialization.
//
The reverse process is called deserialization.

Happily, good libraries exist to parse JSON in every programming language.
//
Java is no exception.
//
We have included the Google
//
https://github.com/google/gson[GSON]
//
JSON parsing library in your project for you to use.

One way to use GSON is to create a class that matches your JSON string.
//
So if you were provided with this JSON from a web API:

[source,json]
----
{
  "number": 0,
  "caption": "I'm a zero"
}
----

you would design this Java class to represent it:

[source,java]
----
public class Result {
    public int number;
    public String caption;
}
----

Note how our classes mirrors both the names (`number`, `caption`) and types (`int`,
`String`) from the JSON result.

However, when you are working with unfamiliar JSON data, as you are in MP6, we
suggest that you _not_ create new classes and instead
//
https://stackoverflow.com/questions/16595493/gson-parsing-without-a-lot-of-classes[use
the built-in Java classes].
//
Here's an example of how to do this given the JSON string shown above:

[source,java]
----
JsonParser parser = new JsonParser();
JsonObject result = parser.parse(jsonString).getAsJsonObject();
int number = result.get("number").getAsInt();
String caption = result.get("caption").getAsString();
----

**Note that for MP6 we will not grade any addition class files you add to your
`lib` directory.**
//
So we suggest you follow our example above footnote:[Or define your
deserialization classes as inner classes to the `RecognizePhoto` class you are
working on... if you really know what you are doing.].

[[csapi-json]]
=== Example JSON

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/Dj_LgQsmBxs" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++


link:/MP/6/example.json[Here is some example JSON,role='external'] produced by
the {csapi}.
//
You may want to consult this as you begin work on your image recognition
functions.

[[android]]
== Android

Android is a Java-based framework for building smartphone apps that run on the
Android platform.
//
By learning how to build Android apps, your programs can have enormous impact.
//
As of a year ago, Google estimated that there were
//
https://www.macrumors.com/2017/05/17/2-billion-active-android-devices/[_2
billion_]
//
active Android devices.
//
That's over 25% of people on Earth&mdash;and
//
http://fortune.com/2017/03/06/apple-iphone-use-worldwide/[several times more
than iOS].

However, Android is also a huge and complex system.
//
It's easy to feel lost when you are getting started.
//
Our best advice is to just slow down, take a deep breath, and try to understand
a bit of what is going on at a time.
//
We'll try to walk you through a few of the salient bits for MP6 below.

=== https://developer.android.com/reference/android/util/Log.html[Logging]

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/YTKKvmcmUOY" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

Like any other computer program, an important part of developing on Android is
generating debugging output.
//
On Android, our familiar `System.out.println`
//
https://stackoverflow.com/questions/2220547/why-doesnt-system-out-println-work-in-android[doesn't quite work the same way we're used to].

However, Android has a simple yet powerful _logging_ system.
//
Unlike `System.out.println`, logging systems allow you to specify multiple log
_levels_ indicating the kind of output that you are generating.
//
This allows you to distinguish between, for example, debugging output that might
only be useful during development and a warning message that might indicate a
more serious problem or failure.
//
The Android logger also allows you to attach a `String` _tag_ to each message to
help separate them when you are debugging or developing.
//
So the final syntax of the call to generate a debugging message, for example, is
`Log.d(TAG, message)`.

For more information, watch the screencast above or review
//
https://developer.android.com/reference/android/util/Log.html[Android's official
logging documentation].

[.alert.alert-primary]
--
//
*Do you need to know this to complete MP6?*
//
Probably, since you need to determine what you app is doing or how things are
going wrong.
//
--

=== https://developer.android.com/reference/android/app/Activity.html[``Activity``s]

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/gwqz1Tm4jTA" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

The Android
//
https://developer.android.com/reference/android/app/Activity.html[`Activity` class]
//
corresponds to a single screen that the user can interact with.
//
Our simple app contains only one activity, but most apps consist of several:
maybe an activity corresponding to the app's main screen, another for a
settings dialog, and still others for other parts of the app.

As you might expect, there are two important moments for an activity: when it
appears on the screen, and when it leaves the screen.
//
Android provides functions that you can override to handle both of these events:
`onCreate` and `onPause`.
//
It is typical for on `onCreate` method to perform tasks required to make the
activity ready for a user to use, such as configuring buttons and other UI
elements.

For more information watch the screencast above or review
//
https://developer.android.com/reference/android/app/Activity.html[Android's
official `Activity` information].

[.alert.alert-primary]
--
//
*Do you need to know this to complete MP6?*
//
No. But you may be confused by the overall app structure if you don't review it.
//
--

=== UI Events

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/_Upqc-IO5_s" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

Why does code in your app run?
//
In many cases it's because a user _interacted_ with an activity&mdash;clicked a
button, entered text into a dialog box, or adjusted an on-screen control.
//
Android provides a way for each app to register _handlers_ than run when various
user interface (UI) events take place.

Our app uses these to:
//
* start the open file dialog
//
* start the process of capturing an image from the camera
//
* open the download file input box
//
* rotate the image
//
* and upload it to the {csapi} for processing.
//
In the screencast above we show how elements of the user interface are linked
programmatically to each specific action.

[.alert.alert-primary]
--
//
*Do you need to know this to complete MP6?*
//
No.
//
But it will be hard to understand how your app works without reviewing it.
//
--

=== UI Modifications

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/Z5GtXAO1Cvc" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

The flip side of user-initiated actions are responses by the app.
//
The normal way for a smartphone app to communicate with the user is by modifying
the UI.
//
Pay closer attention to the apps that you use and you'll start noticing a lot of
this: text boxes and photos that change or display information, progress bars
that indicate either waiting or a long-running action like playing music, etc.

In the screencast above we'll review how to modify your app's UI in response to
user actions&mdash;or, in the case of MP6, in response to the results from the
{csapi}.

[.alert.alert-primary]
--
//
*Do you need to know this to complete MP6?*
//
Yes!
//
There are some missing pieces in `finishProcessImage` waiting for you to
complete.
//
--

=== https://developer.android.com/reference/android/content/Intent.html[Intents]

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/JJHNG7Qn9zg" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

One of the powerful features of Android is the ability for multiple apps to
communicate with each other.
//
If your app wants to take a photo, for example, it can ask the camera app to
take the photo, rather than implementing a camera itself.
//
If you app wants to open a file, as another example, it can ask the file browser
to open the file, rather than implementing a file chooser itself.
//
This both greatly simplifies app development _and_ provides users with a
familiar interface for the same actions.

Our MP6 app uses intents to launch the camera and a file browser.
//
You do not need to understand this feature, but feel free to watch the
screencast above to learn more.
//
And you find it a fun way to respond to the unexpected appearance of Risk
Astley.

[.alert.alert-primary]
--
//
*Do you need to know this to complete MP6?*
//
No, unless you want to really get `isRick` right.
//
--

=== https://developer.android.com/reference/android/os/AsyncTask.html[Asynchronous Tasks]

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/jE2Nevi0_ZI" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

One of the core goals of every application, including smartphone apps, is to
maintain a responsive user interface.
//
If your app freezes for long periods of time, or even short ones, users will
quickly stop using it.

Android accomplishes this by delegating certain slow operations to so-called
_background tasks_.
//
They then run independently of the user interface.
//
So your app can be simultaneously responding to new user input _and_, for
example, downloading a large file.

This is an advanced topic and not one that we expect you to master on this MP or
even on future ones.
//
But if you want to learn a bit more, watch the screencast above.
//
Our MP6 app uses two background tasks: one to download files and save them to
local storage, the second to make requests to the {csapi}.

[.alert.alert-primary]
--
//
*Do you need to know this to complete MP6?*
//
No, but it's interesting!
//
--

=== {csapi}

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/mhRX_EL7vrg" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

What is an API (application programmer interface)?
//
Put it this way&mdash;there are computer systems out there that can do _really_
cool things for you.
//
APIs provide a way to request their help, and easily integrate powerful features
into your applications.
//
You just have to learn how to use them.

In MP6 we're using the really cool {csapi} to process images.
//
The screencast above will show you how to do that.
//
It also walks through the steps you need to add _your_ {csapi} key to your
project so that you can make your own requests.

[.alert.alert-primary]
--
//
*Do you need to know this to complete MP6?*
//
You don't need to understand how the API call is made, but you _may_ need to make
a few small changes to `Tasks.java` and understand the <<csapi-json, JSON
returned>> by the {csapi}.
//
And you do need to add your API key so that your API calls work properly.
//
--

=== Putting It All Together

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/SrCfqmXRu9M" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++


Finally, the screencast above provides a brief overview of how your app _should_
work once you are done.
//
Good luck!

[[grading]]
== Grading

MP6 is worth 100 points total, broken down as follows:

. *10 points*: for submitting code that compiles
. *10 points*: for `getWidth`
. *10 points*: for `getHeight`
. *10 points*: for `getFormat`
. *10 points*: for `getCaption`
. *10 points*: for `isADog`
. *10 points*: for `isACat`
. *10 points*: for `isRick`
. *10 points* for no `checkstyle` violations
. *10 points* for committing code that earns at least 40 points before
*Wednesday 4/11/2018 @ 5PM.*

[[testing]]
=== Test Cases

As in previous MPs, we have provided test cases for MP6.
//
Please review the link:/MP/0/#testing[MP0 testing instructions].

However, _unlike_ previous MPs we have not provided _complete_ test cases for
MP6.
//
Specifically, we have not provided a test for `isRick`.
//
This is intentional, and designed to force you to do your own local testing.
//
It is also designed to not give away exactly what features of the JSON returned
by the {csapi} you will need to look at to complete `isRick`.

[[autograding]]
=== Autograding

Like previous MPs we have provided you with an
autograding script that you can use to estimate your current grade as often as
you want.
//
Please review the link:/MP/0#autograding[MP0 autograding instructions].
//
However, as <<testing, described above>> note that the local test suite will not
test `isRick`, while the remote test suite will.

[[submitting]]
== Submitting Your Work

Follow the instructions from the
//
link:/MP/setup/git#submitting[submitting portion]
//
of the
//
link:/MP/setup/git#workflow[CS 125 workflow]
//
instructions.

And remember, you must submit something that earns 40 points before *Wednesday
4/11/2018 @ 5PM* to earn 10 points on the assignment.

[[cheating]]
=== Academic Integrity

Please review the link:/MP/0#cheating[MP0 academic integrity guidelines].

If you cheat, we will make your watch this over and over again:

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/dQw4w9WgXcQ" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++
