---
title: "MP6: JSON and Android"
description:
  MP6 introduces you to the JSON data serialization format and provides a
  warm-up on Android programming and development.
spelling_exceptions:
  - rickrolled
  - Rick Astley
  - iOS
---
:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu/c/mps/mp6[forum,role='noexternal']]
:csapi: pass:normal[https://azure.microsoft.com/en-us/services/cognitive-services/[Microsoft Cognitive Services API]]

[.lead]
//
Welcome to Android!
//
For MP6 you'll get introduced to Android by modifying a simple app.
//
But the core topic of the MP are actually using application programmer
interfaces (APIs) and serialization.
//
You'll get practice using the
//
{csapi}
//
and on parsing data formatted in
//
https://www.json.org/[JavaScript Object Notation (JSON)],
//
a simple and widely-supported data exchange format.

*MP6 is due Wednesday 4/11/2018 @ 5PM.
//
To receive full credit, you must submit by this deadline.*
//
In addition, 10% of your grade on MP6 is for submitting code that earns at least
_40 points_ by *Monday 4/9/2018 @ 5PM.*
//
As usual, late submissions will be subject to the
//
link:/info/syllabus/#regrading[MP late submission policy].

[[objectives]]
== Learning Objectives

MP6 introduces you to using integrating external APIs into your projects and to
Android development.
//
We'll show you how to use the powerful {csapi} to analyze image data, and you'll
learn how to process the results.
//
We'll also introduce you to the structure of a simple Android app, and you'll
get practice modifying the UI to reflect the information provided by the
Cognitive Services API.
//
We'll also continue to reinforce the learning objectives from previous MPs
(link:/MP/0/[0], link:/MP/1/[1], link:/MP/2/[2], link:/MP/3/[3],
link:/MP/4/[4], and link:/MP/5/[5]).

[[structure]]
== Assignment Structure

Unlike previous MPs, MP6 is split into two pieces:

* `/lib/`: a small library that extracts certain pieces of information from the
image data returned by the {csapi}.
//
*This library is the only part of the MP tested by the test suite.*
//
* `/app/`: an Android app for you to use for your own interactive testing.
//
The Android app is _almost_ complete, but needs a few modifications from you.
//
And, to work correctly, you need to finish the library in `lib`.

[[lib]]
=== MP6 Image Recognition Library (`lib`)

The <<app, MP6 app>> handles uploading photos to the {csapi}.
//
However, once the results are returned it relies on your library to extract a
few pieces of "important" information:

* *The image width, height, and format*: using `getWidth`, `getHeight`, and
`getFormat`.
//
* *The autogenerated image caption*: using `getCaption`
//
* *Whether the image contains a dog or a cat* footnote:[Or both!]: using
`isADog` and `isACat`
//
* *Whether you've been
//
https://en.wikipedia.org/wiki/Rickrolling[rickrolled]*:
//
that is, whether the photo contains
//
https://en.wikipedia.org/wiki/Rick_Astley[Rick Astley],
//
using `isRick`.

As always, you may find our
//
https://cs125-illinois.github.io/MP6-Starter/[official MP6 online documentation]
//
useful as you understand what you need to do.
//
If you believe that the documentation is unclear, please post on the {forum} and
we'll offer clarification as needed.
//
To complete this part of the assignment you'll want to review the
//
<<json, section on JSON below>>.

[[app]]
=== MP6 App

The MP6 app handles obtaining images&mdash;either ones save previously on the
device, captured by the camera, or downloaded from the internet.
//
It also uploads those images to the {csapi} and updates the UI
appropriately&mdash;or at least parts of it.

To complete MP6 most of the lines of code that you write will be completing the
<<lib, image recognition library>>.
//
However, there are a few small changes that we encourage you to make so that the
user interface functions properly.
//
We've done a few things to get you started.
//
Examine `finishProcessImage` to see how we use the results from `getWidth`,
`getHeight`, and `getFormat` to update a part of the UI.
//
To complete the UI you'll need to do the following things:

* *Update the caption* using the result from `getCaption`.
//
You should be able to use our example of updating the description as a starting
point.
//
* *Show or hide the cat and dog icons as appropriate.*
//
You may want to look at `updateCurrentBitmap` for examples of how these icons
are _hidden_ when the current image is cleared.
//
* *Do something when you find Rick.*
//
You do want to celebrate, right?
//
Maybe try something
//
https://stackoverflow.com/questions/574195/android-youtube-app-play-video-intent[like
this].

[[getting]]
=== Obtaining MP6

*Note that we are using Android Studio for MP6.*
//
Use
//
https://classroom.github.com/a/qJ5dPKlE[this GitHub Classroom invitation link]
//
to fork your copy of MP6.
//
Once your repository has been created, import it into *Android Studio* following
//
link:/MP/setup/git/#workflow[our assignment Git workflow guide].

[[requirements]]
=== Your Goal

At this point you should be familiar with the requirements from previous MPs.
//
See the <<grading, grading description below>>.
//
However, note that for MP6 *we have not provided a complete test suite*.
//
You will have to figure out how to test your Rick Astley detection yourself.

[[approach]]
== Approaching MP6

[.lead]
//
As you approach MP6, focus on two core tasks: <<json, working with JSON>>, and
starting to find your way around <<android, Android>>.

[[json]]
=== JSON

[[android]]
=== Android

Android is a Java-based framework for building smartphone apps that run on the
Android platform.
//
By learning how to build Android apps, your programs can have enormous impact.
//
As of a year ago, Google estimated that there were
//
https://www.macrumors.com/2017/05/17/2-billion-active-android-devices/[_2
billion_]
//
active Android devices.
//
That's over 25% of people on Earth&mdash;and
//
http://fortune.com/2017/03/06/apple-iphone-use-worldwide/[several times more
than iOS].

However, Android is also a huge and complex system.
//
It's easy to feel lost when you are getting started.
//
Our best advice is to just slow down, take a deep breath, and try to understand
a bit of what is going on at a time.
//
We'll try to walk you through a few of the salient bits for MP6 below.

==== https://developer.android.com/reference/android/app/Activity.html[Activities]

==== UI Events

==== UI Modifications

==== Tasks

==== {csapi}

[[help]]
=== Getting Help

The course staff is ready and willing to help you every step of the way!
//
Please come to link:/info/syllabus/#calendar[office hours], or post on the
{forum} when you need help.
//
You should also feel free to help each other, as long as you do not violate the
<<cheating, academic integrity requirements>>.

[[grading]]
== Grading

MP6 is worth 100 points total, broken down as follows:

. *10 points*: for submitting code that compiles
. *10 points*: for `getWidth`
. *10 points*: for `getHeight`
. *10 points*: for `getFormat`
. *10 points*: for `getCaption`
. *10 points*: for `isADog`
. *10 points*: for `isACat`
. *10 points*: for `isRick`
. *10 points* for no `checkstyle` violations
. *10 points* for committing code that earns at least 40 points before *Monday
4/9/2018 @ 5PM.*

[[testing]]
=== Test Cases

As in previous MPs, we have provided test cases for MP6.
//
Please review the link:/MP/0/#testing[MP0 testing instructions].

However, _unlike_ previous MPs we have not provided _complete_ test cases for
MP6.
//
Specifically, we have not provided a test for `isRick`.
//
This is intentional, and designed to force you to do your own local testing.
//
It is also designed to not give away exactly what features of the JSON returned
by the {csapi} you will need to look at to complete `isRick`.

[[autograding]]
=== Autograding

Like previous MPs we have provided you with an
autograding script that you can use to estimate your current grade as often as
you want.
//
Please review the link:/MP/0#autograding[MP0 autograding instructions].
//
However, as <<testing, described above>> note that the local test suite will not
test `isRick`, while the remote test suite will.

[[submitting]]
== Submitting Your Work

Follow the instructions from the
//
link:/MP/setup/git#submitting[submitting portion]
//
of the
//
link:/MP/setup/git#workflow[CS 125 workflow]
//
instructions.

And remember, you must submit something that earns 40 points before *Monday
4/9/2018 @ 5PM* to earn 10 points on the assignment.

[[cheating]]
=== Academic Integrity

Please review the link:/MP/0#cheating[MP0 academic integrity guidelines].

If you cheat, we will make your watch this over and over again:

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/dQw4w9WgXcQ" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++
