---
title: "CS 125 Environment Setup"
description:
  Prepare your computer to complete the Java-based machine problems (MPs).
priority: 0.5
changefreq: monthly
layout: single.hbt
spelling_exceptions:
  - Ninite
  - x64
  - /Chromebooks?/
---
:sectnums:

[.lead]
//
To complete the CS 125 machine problems (MPs) you'll write
//
https://www.java.com/en/[Java]
//
code using the
//
http://www.eclipse.org/home/index.php[Eclipse]
//
Integrated Development Environment (IDE) and submit your assignments using the
//
http://www.eclipse.org/home/index.php[Subversion]
//
Version Control System (VCS).
//
This guide will help you install, configure, and understand these tools.

[[eclipse]]
== Eclipse

[.lead]
//
http://www.eclipse.org/home/index.php[Eclipse]
//
is a powerful and popular open-source integrated development environment
(IDE).
//
Many programmers utilize IDEs to simplify the process of writing, building,
testing, and debugging both large and small applications.

If you have a laptop or desktop that you plan to use for CS 125, you should
install Eclipse on it.
//
Follow the instructions below that are appropriate for your machine.
//
Unfortunately Eclipse is not always the easiest piece of software to install,
so don't be discouraged if you get stuck.
//
We're here to help.

**Note that you should always download the
https://www.eclipse.org/downloads/[latest version of Eclipse].**
//
As of late August 2017 that is Eclipse Oxygen.

=== Windows

The easiest solution for Windows machines is to use the very nice
https://ninite.com/[Ninite] bundled installed
footnote:[https://ninite.com/[Ninite] is actually the creation of a student I
know from college&dash;which is how I found out about it.].
//
It will allow you to install both the Java Software Development Kit (SDK) and
the Eclipse Integrated Development Environment (IDE) at the same time.

Here are the steps to follow:

. Go to https://ninite.com/[`ninite.com`].
//
. At minimum you need to check the "Eclipse" and the "JDK x64 8" boxes
footnote:[Of course, if you want other software this is a good time to get
it!].
//
. Download and run the installer.

At this point you should be able to find Eclipse in your installed
applications, or as a shortcut on your desktop.

=== Mac

On Mac there are two steps to installing Eclipse.
//
First, you must install the Java Software Development Kit (SDK):

. Go to
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[this
website].
//
Accept the license agreement and download the Java SE Development Kit for Mac
OS X.
//
. Run the installer to complete the installation.

Next, install the latest version of Eclipse:

. Go to https://eclipse.org/[`eclipse.org`] and click on the download link.
Continue by clicking on the download link on the next page.
//
. Download and run the installer to complete the installation.

By default Eclipse installs itself into an `eclipse` folder in your home
directory.
//
If you want it in your applications, move the installed binary into your
Applications folder.

=== Ubuntu and Chromebooks

Sit tight&mdash;instructions coming shortly.

[[plugins]]
== Eclipse Plugins

[.lead]
//
Once you have <<eclipse, Eclipse installed>>, continue by installing several
plugins.
//
Plugins extend Eclipse by providing new features or capabilities.

[[subversive]]
=== Subversive Subversion Plugin

https://subversion.apache.org/[Subversion] is a software version control
system (VCS).
//
It allows both individual developers and teams to work together more
effectively.
//
You will use Subversion to retrieve your machine problem (MP) assignments, and
to submit your solutions.

To install the Subversive Subversion Eclipse plugin, follow the following
instructions:

. Open the Eclipse Software Marketplace: "Help &rarr; Eclipse Marketplace".
//
. Search for "subversive".
//
. Install the latest version of the "Subversive - SVN Team Provider" plugin.
//
. Restart Eclipse.

Now we need to install some additional software to allow Subversion to connect
to our course repository.
//
Continue by following these instructions to set up so-called Subversive
connectors:

. Open the Eclipse software sources dialog: "Help &rarr; Install New
Software".
//
. Work with
`http://community.polarion.com/projects/subversive/download/eclipse/6.0/update-site/`
and click "Add".
//
. Name the repository anything you want&mdash; "Subversive Connectors" is
fine.
//
. Select both the "Subversive SVN Connectors" and "Subversive SVN Connectors
Sources" checkboxes.
//
. Complete the rest of the installation dialog. When it prompts you about
installing untrusted sources, click install anyway.
//
. Eclipse should restart again, at which point you are all done.

=== checkstyle

When you write code, style matters.
//
This is particularly important as you start to work with others.
//
Inconsistent style produces code that is hard for others to read and understand.

As a result, almost all large footnote:[and even most small] software projects
produce _style guidelines_.
//
These are rules about how code should be formatted to ensure consistency across
multiple developers.
//
Some languages, like https://golang.org/[Go], have even gone as far to make
certain stylistic choices part of the code language specification.

To prepare you for the big wide communal world of programming, we're going to
have you install and use an Eclipse style checking plugin.
//
http://checkstyle.sourceforge.net/[checkstyle] is a Java style checking tool
that is used and supported by large companies that write Java&mdash;including
Google footnote:[Most Android app development is done in Java.].
//
Our style guidelines are based on the
http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html[Sun
Code Conventions].

Installing the checkstyle plugin for Eclipse is fairly easy by using the
software marketplace:

. Open the Eclipse Software Marketplace: "Help &rarr; Eclipse Marketplace".
//
. Search for "checkstyle".
//
. Install the latest version of the "CheckStyle" plugin.
//
. Restart Eclipse.

== Subversion

[.lead]
//
https://subversion.apache.org/[Subversion] is a source code version control
system (VCS), also known as _version control_.
//
Version control systems are at the heart of how programmers manage and share
source code.

=== Why Use Source Version Control?

A source code repository is a bit like the shared folders that are provided by
services like https://www.dropbox.com[Dropbox], https://www.box.com[Box], and
https://drive.google.com[Google Drive].
//
You can save files and folders and share them with other users in various
ways.
//
Some of these tools even track allow you to undo and redo changes and see how
files have changed over time.
//
These are useful tools, and a great way to collaborate with others in a
variety of different scenarios.
//
So it's normal to wonder: what's different about source version control?

Compared to tools like Dropbox, source version control provides programmers
with several important advantages.

==== Versioning entire projects

First, version control systems track the version of _all the files in each repository_,
rather than individual files separately.
//
Programming frequently involves making a set of changes to a group of files
that together accomplish something&mdash;like fixing a bug or adding a new
feature.
//
So when you commit your work using Subversion, it remembers the state of all
the files in your repository at that time.
//
This allows you to compare what your project looked like at different times,
and undo an entire set of changes that might have caused a problem.

Note that this also means that Subversion **does not** track all the changes
you save to a file.
//
Unless you commit your changes, they are not saved to your repository.
//
This may seem like an annoyance&mdash;after all, systems like Dropbox will
sync your files every time you save them.

But when programming this turns out to be a _huge_ advantage.
//
Let's say you save a version of `Foo.java` to test&mdash;but it contains
errors.
//
Now if you are using Dropbox, everyone has that broken version of the file.
//
But if you are using Subversion, you can test your code, notice the errors,
and fix them before committing.

A Subversion footnote:[or Git] commit is really their equivalent of the save
operation.
//
Regardless of whether you save your files in Eclipse or any other way, you
have to commit them to your repository before it will save and remember them.

==== Merging changes

Second, version control systems help you merge changes made by different
developers&mdash;even to the same file.
//
Say that `Foo.java` has 1000 lines.
//
Alice makes a change at the top of the file.
//
Concurrently, Bob makes a change to the bottom of the file.
//
Systems like Dropbox will typically force you to address this conflict by
choosing either Alice's version of the file or Bob's.
//
But version control systems can frequently _automatically_ merge
non-overlapping changes to source code files&mdash;allowing you to choose to
combine the changes from Alice with the changes from Bob.
//
When you are working in large teams on large software projects, this
capability is extremely handy.

=== Introduction to Subversion

Now that you agree that using version control is useful, let's go through
the basics of how to use Subversion.

Subversion organizes your files into a _repository_.
//
A repository can contain any number of files organized any way you like.
//
But a single repository usually contains all of the code used by a single
project.
//
For CS 125, you will use a single repository that holds all of the Java source
code files that you will use this semester&mdash;both in labs and during the
machine problems footnote:[Normally you'd split up each assignment into
separate repositories, but this configuration is easier for us to maintain.].

For CS 125 your subversion repository is stored on a remote server:
`https://subversion.ews.illinois.edu/`.
//
So the steps required to use Subversion effectively&mdash;your version control
_workflow_&mdash;consist of adding Eclipse projects to your repository,
committing changes to your files, and adding new files to your repository.

//==== Adding projects to your repository
//
//When you start a new project in Eclipse, the files are initially stored
//locally and not synchronized with your remote repository.
////
//To add a project to your repository and begin tracking changes using
//Subversion, follow the following steps:
//
//. Make sure that you are in the Java perspective: "Window &rarr; Perspective
//&rarr; Open Perspective &rarr; Java).
////
//. Click on "Team &rarr; Share Project". Select the SVN option and click next.
////
//. Your CS 125 repository that you have added previously should be listed under "Use
//existing repository location". Select it.
////
//. Choose a name for the new folder that will be created in your repository.
