---
title: "CS 125 Environment Setup"
description:
  Prepare your computer to complete the Java-based machine problems (MPs).
priority: 0.5
changefreq: monthly
layout: single.hbt
---
:sectnums:

[.lead]
//
To complete the CS 125 machine problems (MPs) you'll write
//
https://www.java.com/en/[Java]
//
code using the
//
http://www.eclipse.org/home/index.php[Eclipse]
//
Integrated Development Environment (IDE) and submit your assignments using the
//
http://www.eclipse.org/home/index.php[Subversion]
//
Version Control System (VCS).
//
This guide will help you install these tools.

== Eclipse

[.lead]
//
http://www.eclipse.org/home/index.php[Eclipse]
//
is a powerful and popular open-source integrated development environment
(IDE).
//
Many programmers utilize IDEs to simplify the process of writing, building,
testing, and debugging both large and small applications.

If you have a laptop or desktop that you plan to use for CS 125, you should
install Eclipse on it.
//
Follow the instructions below that are appropriate for your machine.
//
Unfortunately Eclipse is not always the easiest piece of software to install,
so don't be discouraged if you get stuck.
//
We're here to help.

**Note that you should always download the
https://www.eclipse.org/downloads/[latest version of Eclipse].**
//
As of late August 2017 that is Eclipse Oxygen.

=== Windows

=== Mac

=== Linux
