---
title: "Introduction to Subversion"
description:
  Understand how to use the Subversion version control system.
priority: 0.5
changefreq: monthly
layout: single.hbt
spelling_exceptions:
  - Chuchu
  - Xyz
---
:sectnums:

[.lead]
//
https://subversion.apache.org/[Subversion] is a source code version control
system (VCS), also known as _version control_.
//
Version control systems are at the heart of how programmers manage and share
source code.

== Why Use Source Version Control?

A source code repository is a bit like the shared folders that are provided by
services like https://www.dropbox.com[Dropbox], https://www.box.com[Box], and
https://drive.google.com[Google Drive].
//
You can save files and folders and share them with other users in various
ways.
//
Some of these tools even track allow you to undo and redo changes and see how
files have changed over time.
//
These are useful tools, and a great way to collaborate with others in a
variety of different scenarios.
//
So it's normal to wonder: what's different about source version control?

Compared to tools like Dropbox, source version control provides programmers
with several important advantages.

=== Versioning Entire Projects

First, version control systems track the version of _all the files in each repository_,
rather than individual files separately.
//
Programming frequently involves making a set of changes to a group of files
that together accomplish something&mdash;like fixing a bug or adding a new
feature.
//
So when you commit your work using Subversion, it remembers the state of all
the files in your repository at that time.
//
This allows you to compare what your project looked like at different times,
and undo an entire set of changes that might have caused a problem.

Note that this also means that Subversion **does not** track all the changes
you save to a file.
//
Unless you commit your changes, they are not saved to your repository.
//
This may seem like an annoyance&mdash;after all, systems like Dropbox will
sync your files every time you save them.

But when programming this turns out to be a _huge_ advantage.
//
Let's say you save a version of `Foo.java` to test&mdash;but it contains
errors.
//
Now if you are using Dropbox, everyone has that broken version of the file.
//
But if you are using Subversion, you can test your code, notice the errors,
and fix them before committing.

A Subversion footnote:[or Git] commit is really their equivalent of the save
operation.
//
Regardless of whether you save your files in Eclipse or any other way, you
have to commit them to your repository before it will save and remember them.

=== Merging Changes

Second, version control systems help you merge changes made by different
developers&mdash;even to the same file.
//
Say that `Foo.java` has 1000 lines.
//
Alice makes a change at the top of the file.
//
Concurrently, Bob makes a change to the bottom of the file.
//
Systems like Dropbox will typically force you to address this conflict by
choosing either Alice's version of the file or Bob's.
//
But version control systems can frequently _automatically_ merge
non-overlapping changes to source code files&mdash;allowing you to choose to
combine the changes from Alice with the changes from Bob.
//
When you are working in large teams on large software projects, this
capability is extremely handy.

== Introduction to Subversion

Now that you agree that using version control is useful, let's go through
the basics of how to use Subversion.

Subversion organizes your files into a _repository_.
//
A repository can contain any number of files organized any way you like.
//
But a single repository usually contains all of the code used by a single
project.
//
For CS 125, you will use a single repository that holds all of the Java source
code files that you will use this semester&mdash;both in labs and during the
machine problems footnote:[Normally you'd split up each assignment into
separate repositories, but this setup is easier for our purposes.].

For CS 125 your subversion repository is stored on a remote server:
//
pass:[<a class="noexternal link_exception spelling_exception" href="https://subversion.ews.illinois.edu/" onclick="return false">https://subversion.ews.illinois.edu/</a>].
//
So the steps required to use Subversion effectively&mdash;your version control
_workflow_&mdash;consist of adding Eclipse projects to your repository,
committing changes to your files, and adding new files to your repository.
//
But first we have to configure Eclipse to use your CS 125 subversion
repository.

=== Connecting to Your Repository

All repositories for this semester are stored as subfolders under
//
pass:[<a class="noexternal link_exception spelling_exception" href="https://subversion.ews.illinois.edu/svn/fa17-cs125/" onclick="return false">https://subversion.ews.illinois.edu/svn/fa17-cs125/</a>].
//
To get the URL for your repository, simply add your Illinois NetID.
//
Here are a few examples:

* I'm NetID `challen`, so my repository is
//
pass:[<a class="noexternal link_exception spelling_exception" href="https://subversion.ews.illinois.edu/svn/fa17-cs125/challen" onclick="return false">https://subversion.ews.illinois.edu/svn/fa17-cs125/challen</a>].
//
* If my dog Chuchu went to school here
//
footnote:[We tried that once, but it
//
https://www.change.org/p/davis-hall-administrators-let-chuchu-come-back[didn't
work out perfectly].], his NetID would be `chuchu` and his repository would be
//
pass:[<a class="noexternal link_exception spelling_exception" href="https://subversion.ews.illinois.edu/svn/fa17-cs125/chuchu" onclick="return false">https://subversion.ews.illinois.edu/svn/fa17-cs125/chuchu</a>].
//
I'm not sure what he'd store in there though&mdash;maybe bones?
//
* If my dog Xyz went to school here, her NetID would be `purrprincess`, and
her repository would be
//
pass:[<a class="noexternal link_exception spelling_exception" href="https://subversion.ews.illinois.edu/svn/fa17-cs125/meowmeow" onclick="return false">https://subversion.ews.illinois.edu/svn/fa17-cs125/meowmeow</a>].
//
(Hopefully her NetID is not taken!)

Hopefully by now you get the pattern.
//
Now that you have the link to your Subversion repository ready, let's set up
Eclipse to use it:

. Start by opening the Eclipse SVN Repository Perspective: "Window &rarr;
Perspective &rarr; Open Perspective &rarr; Other... &rarr; SVN Repository
Explorer".
//
. Now select "New &rarr; Repository Location".
//
. Insert the link to your Subversion repository that you computed above.
//
. Eclipse will prompt you for your Illinois AD username (NetID) and password.
Enter them. You may want to choose to save your credentials so that you are
not repeatedly prompted for your username and password.

At this point you can view your repository.
//
To see what it currently contains, right click on it and click "Refresh".

=== Adding Projects to Your Repository

When you start a new project in Eclipse, the files are initially stored
locally and not synchronized with your remote repository.
//
To add a project to your repository and begin tracking changes using
Subversion, follow the following steps:

. Make sure that you are in the Java perspective: "Window &rarr; Perspective
&rarr; Open Perspective &rarr; Java).
//
. Click on "Team &rarr; Share Project". Select the SVN option and click next.
//
. Your CS 125 repository that you have added previously should be listed under "Use
existing repository location". Select it.
//
. Choose a name for the new folder that will be created in your repository.
//
. At this point you should be able to browse to your repository using the "SVN
Repository Perspective" and see that the new project has been added. Cool!
Welcome to version control.

=== `svn checkout`: Retrieving Projects from Your Repository

Now you've figured out how to add things to your repository.
//
But how do you retrieve stuff that is already there?

Subversion refers to this process as a _checkout_.
//
To checkout a project in Eclipse, follow the following instructions:

. Start by opening the Eclipse SVN Repository Perspective.
//
(Refer to the instructions above if you've forgotten how to do that.)
//
. Next we need to find the project that we want to open using the repository
browser. Once you've located it, right click on it and select "Checkout".
//
. Select "Check out as a project in the workspace". Subversion uses `HEAD` to
refer to the latest version of a project, so you should check out that version
unless you want an earlier one for some reason.
//
. Click "Finish". The project should now appear in your workspace.
