---
title: Objects II
description:
  Objects are an important programming concept in Java as well as other
  programming languages. Today, we continue a multi-week introduction to objects
  by discussing visibility modifiers, constructors, and overloading.
spelling_exceptions:
  - Pokémon
draft: true
---
:sectnums:
:linkattrs:

[.lead]
//
Today we continue introducing you to _objects_.
//
Objects are an important concept in many programming languages, and particularly
in Java.
//
Today's focus is on several components of object-oriented programming:
visibility modifiers, encapsulation, constructors, and overloading.

[[exercises]]
== Written Exercises [.text-muted]#(45 Minutes)#

[.lead]
//
As usual, we begin with a written lab component.
//
Please complete these exercises carefully.
//
Your course staff will review and discuss your answers along with the rest of
your section.

Complete this part of the lab in pairs using Google Docs.
//
Create a copy of https://goo.gl/Y62k8s[our document template], and then edit it
to record you and your partner's answers.
//
**Note that you must open this document using your @illinois.edu Google Apps
account.**
//
We will not grant access to non-Illinois users.

Have a course staff member check your answers as you go.
//
When you are done, move on to the next section.

'''

[[coding]]
== Object Practice [.text-muted]#(60 Minutes)#

[.lead]
//
In the second half of the lab we'll provide you with some practice with the
concepts discussed in the first half.

To try and make it interesting, we continue the bank account example used in the
previous week's written exercises.
//
Everyone likes money, right?

=== Forking the Lab8 Eclipse Project

Just as in previous labs we've set up an Eclipse project for Lab 8.
//
It's on
//
https://github.com/cs125-illinois/Lab8[GitHub].
//
https://help.github.com/articles/fork-a-repo/[Fork]
//
and clone a copy of our repository as you have
//
link:/lab/3/#forking[previously].

[[objects]]
=== Your Goal

[.lead]
//
Your job is to complete the provided classes so that they work properly and
employ object-oriented principles correctly.
//
You'll need to use your newly-acquired knowledge about objects and object
syntax.
//
The course staff will circulate to help out and provide useful advice.

[[mp5]]
== Help with MP5 [.text-muted]#(20 Minutes)#

Use any remaining time in your lab section to get help with link:/MP/4/[MP5].

// vim: ts=2:sw=2:et
