branches:
  only:
    - master
language: node_js
node_js:
  - "12.13.0"
dist: trusty
sudo: false
notifications:
  webhooks:
    urls:
      - "https://cs125-reporting.cs.illinois.edu/tinylistener"
    on_start: never
    on_success: always
    on_failure: never
cache:
  directories:
    - node_modules

# vim: ts=2:sw=2:et:tw=0
