---
title: "Ready to Start"
description:
  Meet your TA, course assistants, and fellow students, and get your environment
  set up to start programming.
outdated:
  name: lab
  current: /lab/
---

:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu[forum,role='noexternal']]

[.lead]
//
Let's get started!
//
The goal of our first lab is to ensure that you have all the tools you need set
up to succeed in CS 125.
//
We'll make sure you can access the forum and participate in lecture, look at how
to do the online homework, and begin preparing you to work on our first MP
which will be released later this week.
//
You'll also prepare your development environment by installing
link:/MP/2018/fall/setup/java/[Java] and link:/MP/2018/fall/setup/intellij[IntelliJ].

== Introductions [.text-muted]#(15 Minutes)#

[.lead]
//
But first let's spend a few minutes getting to know each other.

Make sure that you introduce yourself to your
//
link:/info/2018/fall/people/#tas[teaching assistant],
//
and to the link:/info/2018/fall/people/#cas[course assistant or assistants]
//
that are helping with your section.
//
This is also a great opportunity to meet other students!
//
At some point during this lab section, try to find:

* a person from your dorm
//
* a person from the same major
//
* a person with programming experience...
//
* ...and one without programming experience
//
* somebody very different from you

Make it a goal today to learn _and remember_ the names of five other students.
//
The course staff will be working hard this semester to learn your
names&mdash;but please be patient with us.

Finally, share what you're aiming to get out of CS 125 this semester with your
fellow students and with your TA and CA.
//
This matters a lot to us, since we want you to succeed and have a fulfilling
experience in CS 125.

=== Working Together

You'll frequently be working together in groups in our lab sections... and for
the rest of your life as a technologist.
//
So it's something worth getting good at.

When working with a new group of people, it's best to try to get out of your
comfort zone a bit&mdash;especially at first.
//
If you're used to doing a lot of talking, try to listen and make room for
other voices.
//
And if you're a bit on the quiet side, try to speak up and actively
participate.
//
Things get easier once everyone gets comfortable with each other.

'''

== Environment Preparation [.text-muted]#(45 Minutes)#

[.lead]
//
Next we're going to get you set up with the tools that you need to write
computer code for this course.

**Please read and follow all steps carefully, one by one.**
//
99% of the time when installing or trying to use a computer tool fails, it's
because you didn't follow instructions
//
footnote:[Not to claim to be any better at this than you. But I have learned
with age that at least when something goes wrong to check to make sure I've
follow the instructions!].

=== Enable Google Integration

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/iJV5iB6pdFE" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

In order to log on to the {forum}, and use our
//
link:/m/grades/MPs[online grade interface],
//
you need to enable Google integration for your @illinois.edu account.
//
Follow
//
https://answers.uillinois.edu/illinois/47880[this link]
//
and walk through the instructions for undergraduate (probably) or graduate
(unlikely) students.
//
The screencast above demonstrates the process.
//
Note that the online grades page looks quite different now than when it did when
this screencast was taken, and is currently down for maintenance.
//
But once you enable Google Apps integration it should work everywhere: on the
{forum}, on our link:/learn/[online slides], and on the link:/m/grades/[online
grades page].

=== Setup Tutorials

There are two setup tutorials to complete:

. link:/MP/2018/fall/setup/java/[Install Java]
//
. link:/MP/2018/fall/setup/intellij/[Install IntelliJ]

Once you complete the two tutorials above, continue with the rest of the lab as
described below.
//
**Don't go on until you've installed everything properly.**

[[binary]]
== Binary and Representation [.text-muted]#(50 Minutes)#

[.lead]
//
Let's learn about binary and how computers represent numbers and other kinds of
data.

Complete this part of the lab in pairs using Google Docs.
//
Create a copy of https://goo.gl/hrdEvn[our document template], and then edit it
to record you and your partner's answers.
//
**Note that you must open this document using your @illinois.edu Google Apps
account.**
//
We will not grant access to non-Illinois users.
//
Have a course staff member check your answers as you go.
//
When you are done, move on to the next section.

'''

[[done]]
== Before You Leave

**Don't leave lab until**:

. You have enabled Google Apps integration and logged on successfully to the
{forum}
//
. You have installed link:/MP/2018/fall/setup/java[Java] and
link:/MP/2018/fall/setup/intellij[IntelliJ]
//
. You have completed the https://goo.gl/pof9Y2[binary exercises]
//
. You have completed the first two or three
//
https://goo.gl/r9QTxn[homework problems]
//
. And so has everyone else in your lab section!
//
. Also, have you taken our
//
https://goo.gl/forms/ZLOmoC8x2nkfmG753[initial student survey]
//
and tried our
//
new link:/tech/app/[CS 125 App]?
//
Both will earn you 1% extra credit.

If you need more help, please come to link:/info/2018/fall/syllabus/#calendar[office
hours (which will start Thursday)], or post on the {forum}.
