---
title: Practice with Recursion
date: 2018-03-14
description:
  Continuation of recursive practice on binary trees.
echo: https://goo.gl/BRKaRB
---

[[voXqzPFbehmlKvzPJindiCNjYHooPgth]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Practice with Recursion</div>
++++
....
import java.util.Random;

public class Tree {
  Random random = new Random();
  public int value;
  public Tree right;
  public Tree left;

  Tree(int setValue) {
    value = setValue;
  }
  Tree(int[] array) {
    value = array[0];
    for (int i = 1; i < array.length; i++) {
      add(array[i]);
    }
  }

  public void add(int value) {
    if (left == null) {
      left = new Tree(value);
    } else if (right == null) {
      right = new Tree(value);
    } else if (random.nextBoolean()) {
      right.add(value);
    } else {
      left.add(value);
    }
  }

  public String toString() {
    String returnString = "" + value;
    if (left != null) {
      returnString += " " + left.toString();
    }
    if (right != null) {
      returnString += " " + right.toString();
    }
    return returnString;
  }
}

public class Example {
  public static void main(String[] unused) {
    Tree tree = new Tree(new int[] { 1, 2, 3, 4 });
    System.out.println(tree);
  }
}
....
--

[[KCoLSXBvtoVCOGrfTDNpmjrTaOiwMRuU]]
== Terminology Clarification

[.lead]
//
I may have inadvertently used the term _O(n)_ analysis.
//
A better term is *big O* analysis, since that doesn't confuse it with _O(n)_
or linear algorithm runtime.

I'll try to be as clear as possible about this going forward.

[[AofiGEMMEYWJIVeLQevsIWTSyfEtkNJS]]
== Q7 Review: Runtime

[source,java,role='smaller']
----
int b(int[] array, int m) {
  if (m > array.length) {
    m = array.length;
  }
  int c = 0;
  for (int i = 0; i < m; i++) {
    boolean g = true;
    for (int j = 0; j < m; j++) {
      if (array[j] > array[i]) {
        g = false;
      }
    }
    if (g) {
      return c;
    }
  }
  return c;
}
----

What is the _best case_ runtime of the algorithm implemented above?

[[HgPzpElYRGWNjrYSmhfDndJgrKPSenSz]]
== Q7 Review: List Runtime

[source,java,role='small']
----
MysteryList list = new MysteryList();
for (int i = 0; i < 1024; i++) {
  list.addToFront(i);
}
----

After you put timing measurements into the loop show above, you notice that each
call to `addToFront` takes around the same amount of time.
//
This leads you to believe that this `MysteryList` is probably implemented
using...

[[KUtYLiUZnZOPhwVDnfWqYeHCbnKoexSF]]
== Q7 Review: List Runtime

[source,java,role='small']
----
MysteryList list = new MysteryList();
for (int i = 0; i < 1024; i++) {
  list.add(i);
}
// Insert 0 at position 32
list.insert(0, 32); // Takes 1.2 microseconds
list.insert(1, 128); // Takes 4.2 microseconds
list.insert(4, 1024); // Takes 37.4 microseconds
----

Given the timings shown in the comments above, this `MysteryList` is probably
implemented using...

[[ibsYbuVKxMGiXIpnkatfUqzLWkPDSWIa]]
== Q7 Review: List Runtime

[source,java,role='small']
----
MysteryList list = new MysteryList();
for (int i = 0; i < 1024; i++) {
  list.addToEnd(i);
}
----

After you put timing measurements into the loop show above, you notice that each
call to `addToEnd` takes more and more time as `i` increases.
//
This leads you to believe that this `MysteryList` is probably implemented
using...

[[StphwyYzbZBlYzyBFwMipPwIoNbeFwHF]]
== Q7 Review: Objects

[source,java,role='small']
----
public class Counter {
  public int count = 2;
  public Counter() {
    count++;
  }
}
public class Example {
  public static void main(String[] unused) {
    Counter counter = null;
    for (int i = 0; i < 10; i++) {
      counter = new Counter();
      counter.count++;
    }
    System.out.println(counter.count);
  }
}
----

When the `main` method runs, what will be printed?

[[FsOinhzhYqINRhxrticcWcWRsnCqLdoq]]
== ! Q7 Review: Objects

[.janini.compiler.smaller]
....
public class Counter {
  public int count = 2;
  public Counter() {
    count++;
  }
}
public class Example {
  public static void main(String[] unused) {
    Counter counter = null;
    for (int i = 0; i < 10; i++) {
      counter = new Counter();
      counter.count++;
    }
    System.out.println(counter.count);
  }
}
....

[[vpoHjCEyroQgpqhOwrlcZsKVUMAUhXxb]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
0 [style=invis]
5 -> 3 [style=invis]
5 -> 10 [style=invis]
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5
3 [style=invis]
10 [style=invis]
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

[[PwLcRQFuTmPzYZIQnoEPAAJBGqNLlDLF]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
5 -> 3 [style=invis]
5 -> 10 [style=invis]
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5 [fillcolor="lightblue" style="filled"]
3 [style=invis]
10 [style=invis]
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

* 5 doesn't have a left child

[[yTWkklJcXXfgRXKuSKAEAepHqdbUpRuJ]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
0 [style=invis]
5 -> 3
5 -> 10 [style=invis]
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5 [fillcolor="lightblue" style="filled"]
3
10 [style=invis]
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

* 5 doesn't have a left child
//
* Add 3 as 5's left child

[[GyzgNvdaVBpDuYkRxMeAgJSaTYgVNSUJ]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
5 -> 3
5 -> 10 [style=invis]
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5 [fillcolor="lightblue" style="filled"]
3
10 [style=invis]
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

* 5 doesn't have a right child

[[vKydIATmSNQXKDDGBvHArqtHIAHeznOR]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
5 -> 3
5 -> 10
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5 [fillcolor="lightblue" style="filled"]
3
10
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

* 5 doesn't have a right child
//
* Add 10 as 5's right child

[[UtsBLLEZLvWPrlLzoMTHBxptgGOLmTEI]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
1 [style=invis]
5 -> 3
5 -> 10
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5 [fillcolor="lightblue" style="filled"]
3
10
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

* 5 has both a right and left child

[[ViXGWrhunnFrYSUSpyfUiQOaCWulkhbR]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
5 -> 3
5 -> 10
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5 [fillcolor="lightblue" style="filled"]
3
10 [fillcolor="lightsalmon" style="filled"]
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

* 5 has both a right and left child
//
* Randomly choose a subtree

[[TAJCugGueGfIbLKwmxxwaqzNCsKjnVIN]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
5 -> 3
5 -> 10
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5
3
10 [fillcolor="lightblue" style="filled"]
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

* 5 has both a right and left child
//
* Randomly choose a subtree
//
* And call `add` on that subtree

[[EVXpdhPCbdgLFYtZmiLdHVJqmQDTUKbP]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
5 -> 3
5 -> 10
3 -> 7 [style=invis]
10 -> 9 [style=invis]
10 -> 1 [style=invis]
5
3
10 [fillcolor="lightblue" style="filled"]
7 [style=invis]
9 [style=invis]
1 [style=invis]
</div>
++++

<<<

* 10 doesn't have a left child

[[YfSxcnBsFREfddoDXEkVuAscgGIDJUWg]]
[.ss]
== Recursive Add Review

++++
<div class="digraph small tree TB center">
splines="curved"
5 -> 3
5 -> 10
3 -> 7 [style=invis]
10 -> 9
10 -> 1 [style=invis]
5
3
10 [fillcolor="lightblue" style="filled"]
7 [style=invis]
9
1 [style=invis]
</div>
++++

<<<

* 10 doesn't have a left child
//
* Add 9 as its left child

[[cqVgjZbBhDimdNKBlxRPJOBMHZzAYZob]]
== Recursive Implementation

[source,java]
----
int factorial(int n) {
  if (n == 1) {
    return 1;
  } else {
    return n * factorial(n - 1); // I called myself!
  }
}
----

[.lead]
//
We refer to a function that calls itself as a _recursive function_.

[[qmiqxdoDeDVoxFQfOKZLTweMXGWKnfZQ]]
== ! Recursive Factorial

[.janini.smaller]
....
static int factorial(int n) {
  if (n == 1) {
    return 1;
  } else {
    return n * factorial(n - 1);
  }
}
System.out.println(factorial(4));
....

[[eELiFqaIevIBNkhtbiwbkNcnYnLyfKkS]]
== Recursive Strategies

[.lead]
//
Recursion can be _hard_ to wrap your mind around at first.
//
But these three strategies will help.

[.s]
//
. *Know when to stop.* When you identify the smallest subproblem, you must
return. Otherwise your program will not terminate. This is also called the _base
case_.
//
. *Make the problem smaller in each step.* If the problem doesn't get smaller,
you will never reach the base case. This is also called the _recursive step_.
//
. *Combine results from your recursive calls properly.*

[[gRDqpIvNYsoaRJfrfHSXsebpZMSkrUuJ]]
== Recursive Tree Right Greater Than Left

[.lead]
//
Let's find the number of nodes in our tree where the value of the right child is
greater than or equal to value of the left child.

[[SYKjilNSxLlsdxRsuxYvvTgpGnSqBtXT]]
[.oneword]
//
== What's Our (Recursive) Algorithm?

[[zSswMAKnLOEUAmowsjltDxsmgyLuCSii]]
== Recursive Tree Right Greater Than Left

[.s]
//
* *Base case*: [.s]#We've reached a tree with one node. It does not have a right
child or left child, so we can return 0.#
//
* *Recursive step*: [.s]#Consider our right tree and left tree separately.#
//
* *Combine results*: [.s]#Determine whether our right child is greater than our
left child. If so, add 1 to the sum of results from our left and right child.#

[[LWTPSosRFqExmcZpSPYAxSifaSoFXjZU]]
== !Recursive Right Greater Than Left Example

[.janini.compiler.smallest]
....
import java.util.Random;

public class Tree {
  Random random = new Random();
  public int value;
  public Tree right;
  public Tree left;

  Tree(int setValue) {
    value = setValue;
  }
  Tree(int[] array) {
    value = array[0];
    for (int i = 1; i < array.length; i++) {
      add(array[i]);
    }
  }

  public void add(int value) {
    if (right == null) {
      right = new Tree(value);
    } else if (left == null) {
      left = new Tree(value);
    } else if (random.nextBoolean()) {
      right.add(value);
    } else {
      left.add(value);
    }
  }

  public int rightGreaterThanLeft() {
  }
}

public class Example {
  public static void main(String[] unused) {
    Tree tree = new Tree(new int[] { 1, 2, 3, 4 });
    System.out.println(tree.rightGreaterThanLeft());
  }
}
....

[[ghyIBrFmhpZwjiTuqEhBzmwmKceGzUCO]]
== Announcements

* *No class Friday.* Enjoy Spring Break! footnote:[I definitely will...]
//
* link:/MP/2018/spring/5/[MP5] is due after break.
//
* The early deadline is right after Spring Break.
//
* We've added an
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.
I'll need to leave at 11:30AM.

// vim: ts=2:sw=2:et
