---
title: CS 125 Tech Stack
description: >
  This page describes the various technical tools and components that CS 125
  uses to teach computer science to hundreds of students.
priority: 0.8
spelling_exceptions:
  - AppStore
  - Estimote
  - Redux
---
:linkattrs:

[.lead]
//
CS 125 uses a variety of standard and innovative technologies to teach computer
science to hundreds of students.
//
Here we provide an overview of the CS 125 tech stack, while linked pages provide
more details about certain components.

[[app]]
== CS 125 App (New Fall 2018)

Our CS 125 App tracks the proximity of course staff and students to known course
locations like office hours and Geoff's office (Siebel 2227).
//
The cross-platform app is built using
//
https://facebook.github.io/react-native/[React Native],
//
with a
//
https://redux.js.org/[Redux store]
//
for local state management and
//
http://meteor.com/[Meteor]
//
for remote state management.

link:/tech/app/[To read more about the CS 125 App, click here.]

[[intellijplugin]]
== IntelliJ Plugin (New Fall 2018)

The CS 125 IntelliJ Plugin records the progress of CS 125 students as they
complete the course assignments (link:/MP/[MPs]).
//
The data it generates allows us to ensure that the MPs are at the appropriate
difficulty level while also providing insights into beginning programming
development processes.
//
It also simplifies the process of launching our Gradle autograding plugin.

link:/tech/intellijplugin/[To read more about the CS 125 IntelliJ Plugin, click here.]

// vim: ts=2:sw=2:et:ft=asciidoc
