---
title: CS 125 IntelliJ Plugin
description: >
  The CS 125 IntelliJ Plugin records student work in the IntelliJ IDE and
  simplifies local autograding.
priority: 0.7
spelling_exceptions:
  - nother
---
:linkattrs:

[.lead]
//
The CS 125 IntelliJ Plugin is a(nother) new feature for the course for Fall
2018.
//
It records student activity in the
//
https://www.jetbrains.com/idea/[IntelliJ IDEA Java IDE]
//
as they complete the course programming assignments&mdash;link:/MP/[machine
problems (MPs)] as we call them at Illinois.

[[pluginrepository]]
== Where to Get It

The CS 125 IntelliJ Plugin is published on the
//
https://plugins.jetbrains.com/[JetBrains Plugin Repository].
//
The download link is
//
https://goo.gl/GQ6jSJ[here],
//
but you can also install it directly from the IntelliJ IDEA IDE.
//
However, you will not find it useful unless you are working on a CS 125 MP.
//
In fact, it is disabled otherwise.

[[bugs]]
== Bug Reports

The CS 125 IntelliJ is beta software being built by a small team.
//
So it may not work perfectly for you!
//
CS 125 course staff and students should report bugs
//
https://cs125-forum.cs.illinois.edu/c/bug-reports[on the course forum].
//
(Non-CS 125 course staff and students should not be using this plugin.)

Note that, although we anticipate that most students will find the plugin
helpful, *no part of your grade in CS 125 is influenced by whether or not you
use it.*

[[how]]
=== How It Works

Once you have the CS 125 IntelliJ Plugin installed, opening an IntelliJ project
that contains a CS 125 MP will cause the plugin to begin recording IDE activity
at periodic intervals.
//
We do this by leveraging various IntelliJ event listener mechanisms.

The events that we record include:

* Project opens and closes
//
* Document modifications
//
* Selection and visible area changes
//
* Mouse movement and clicks
//
* Window scrolls
//
* Key presses
//
* Compilation passes and results
//
* Test runs and results
//
* Autograding runs

[[why]]
== Why Are We Doing This?

[.lead]
//
The CS 125 IntelliJ Plugin allows us to accurately answer one of the most
important questions when teaching introductory courses: _How long are students
spending on the assignments?_
//
If the assignments take too long, students will get overwhelmed and give up.
//
If they don't take long enough, we're missing opportunities to provide students
with the practice they need to improve.

Despite the centrality of this question when teaching programming, accurate data
in this area is difficult to obtain.
//
Survey results are unreliable, while other measure of student activity&mdash;for
example, Git commits&mdash;make it hard to reconstruct periods of business and
inactivity.
//
We anticipate that our approach will provide accurate and high-resolution student
activity data.

Beyond measuring how long it took each student to complete each assignment, we
also plan to investigate questions such as:

* *How effective are office hours?*
//
By combining this data set with the proximity information collected by the
//
link:/tech/app[CS 125 App], we can compare the productivity of students when
they work at office hours versus other places and times.
//
* *What development behaviors lead to success for beginning programmers?*
//
For example, do successful beginners work in short stretches or long sittings?
//
Do they frequently or infrequently run tests?
//
And what, if any role, does typing speed play?

[[privacy]]
== Privacy Policy

The CS 125 IntelliJ Plugin is for the exclusive use of CS 125 staff and students.
//
However, downloading and installing the plugin and then opening a IntelliJ
project containing a CS 125 MP will initiate data collection.

All data collected by the CS 125 App is for exclusive use by the CS 125 Course
Staff and researchers at the University of Illinois.
//
It will not be shared with or in any other way provided to third parties.
//
Before using the data generated by the CS 125 App in any research publication,
even in aggregated form, we will obtain consent from plugin users.

All data collected by the CS 125 App is stored in secured servers located on
campus at the University of Illinois.
//
All data transfer back and forth between the app is done over encrypted
connections.
//
The plugin caches a small amount of state locally in case of network
disconnections.

// vim: ts=2:sw=2:et:ft=asciidoc
