---
title: Ready to Start
description:
  Meet your TA, course assistants, and fellow students, and get your environment
  set up to start succeeding in CS 125.
spelling_exceptions:
  - Gravatar
---

:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu[forum,role='noexternal']]

[.lead]
//
Let's get started!
//
The goal of our first lab is to ensure that you have _most_ of the tools you need set
up to succeed in CS 125
//
footnote:[We'll tackle installing Android Studio next week.].

[[introductions]]
== Introductions [.text-muted]#(15 Minutes)#

[.lead]
//
But first let's spend a few minutes getting to know each other.

Make sure that you introduce yourself to your
//
link:/info/people#tas[teaching assistant],
//
and to the link:/info/people#cas[course assistant or assistants]
//
that are helping with your section.
//
This is also a great opportunity to meet other students!
//
At some point during this lab section, try to find:

* a person from your dorm
//
* a person from the same major
//
* a person with programming experience...
//
* ...and one without programming experience
//
* somebody very different from you

Make it a goal today to learn _and remember_ the names of five other students.
//
The course staff will be working hard this semester to learn your
names&mdash;but please be patient with us.

Finally, share what you're aiming to get out of CS 125 this semester with your
fellow students and with your TA and CA.
//
This matters a lot to us, since we want you to succeed and have a fulfilling
experience in CS 125.

=== Working Together

You'll frequently be working together in groups in our lab sections... and for
the rest of your life in tech.
//
So it's something worth getting good at.

When working with a new group of people, it's best to try to get out of your
comfort zone a bit&mdash;especially at first.
//
If you're used to doing a lot of talking, try to listen and make room for
other voices.
//
And if you're a bit on the quiet side, try to speak up and actively
participate.
//
Things get easier once everyone gets comfortable with each other.

'''

== Course Preparation [.text-muted]#(Remaining Time)#

[.lead]
//
Next we're going to get you set up with the tools and systems that you need to
succeed in CS 125.

**Please read and follow all steps carefully, one by one.**
//
99% of the time when installing or trying to use a computer tool fails, it's
because you didn't follow instructions
//
footnote:[Not to claim to be any better at this than you. But I have learned
with age that at least when something goes wrong to check to make sure I've
follow the instructions!].

You should complete the steps below on your laptop if you have one.
//
If you do not have a laptop, there should be several EWS workstations in your
lab room that you can use.
//
**Please work together and help each other complete the following steps!**

[[google]]
=== Enable Google Integration

To access the {forum} and our
//
link:/m/grades/[online grade interface],
//
you need to enable Google integration for your `@illinois.edu` account.

Follow
//
https://techservices.illinois.edu/services/google-apps-illinois[this link]
//
and walk through the instructions for undergraduate (probably) or graduate
(unlikely) students.
//
Once you enable Google Apps integration it should work everywhere: on the
{forum}, on our link:/learn/[online slides], and on the link:/m/grades/[online
grades page].
//
You definitely probably want to test the link:/learn/[online slides] to make
sure that you receive participation credit.

[[gravatar]]
=== Setup a Gravatar

Next you'll set up a Gravatar associated with your `@illinois.edu` email
address.
//
https://www.gravatar.com[Gravatar] is a web service allowing you to establish a
globally recognized avatar.
//
What does that mean?
//
It means that many other websites will use your Gravatar as a photo when you
sign up.

CS 125 we will use your Gravatar photo for both our lab participation tool and
on our {forum}.
//
**So if you want to receive participation credit for lab, you need to set up a
Gravatar associated with your `@illinois.edu` email address.**
//
Your Gravatar should also be an easily-recognizable picture of you, probably a
closely-cropped head shot, so the course staff can identify you.

[[pl]]
=== Enroll on PrairieLearn

We will use
//
https://prairielearn.engr.illinois.edu/[PrairieLearn]
//
for both daily online homework and our weekly quizzes given in the CBTF.

To enroll in our PrairieLearn course follow the following steps:

. Navigate to
//
https://prairielearn.engr.illinois.edu/[the PrairieLearn homepage] and log in.
//
. Click "Add or Remove Courses"
//
. Search for "CS 125" and add the **CS 125: Introduction to Computer Science,
Fall 2019** course. (You will see other CS 125 courses which you do not need
to enroll in.)
//
. At that point visiting
//
https://prairielearn.engr.illinois.edu/pl/course_instance/20716/assessments[this
page]
//
should show you two or three available homework problems to work on&mdash;but
don't work on them until you finish the rest of the setup tasks!

[[cbtf]]
=== Schedule Quiz 0

Make sure that you have signed up to take our first week quiz in the CBTF, if
you haven't signed up or taken it already.
//
Use
//
https://cbtf.engr.illinois.edu/[their online scheduler] to accomplish this.

[[forum]]
=== Explore the Course Forum

Before going on, make sure that you can log in to our course {forum}.

CS 125 uses
//
link:/info/resources/#forum[a Discourse forum]
//
to distribute information about the class.
//
This is _the_ place to ask 99.9% of your course-related questions.
//
It's also where we post
//
https://cs125-forum.cs.illinois.edu/c/fall-2019-announcements[announcements]
//
frequently, and where you'll find help with the course content and the MPs.

Discourse is a powerful and highly-configurable forum.
//
Take a few minutes to explore some of its many settings.
//
In particular, you should try to:

. Change your forum avatar to the <<gravatar, Gravatar you set up previously>>
//
. Enable notifications for the
//
https://cs125-forum.cs.illinois.edu/c/fall-2019-announcements[Fall 2019
Announcements]
//
category so that you _never_ miss an important announcement&mdash;since we will
not always send email reminders
//
. Review
//
https://discourse.stonehearth.net/t/discourse-guide-code-formatting/30587[how to
post formatted code on the forum]
//
like this:

[source]
//
----
```java
// Your java code goes here
System.out.println("Hello, CS 125!");
```
----

[[grades]]
=== Check Your Grades

CS 125 maintains our own
//
link:/m/grades/overview/[gradebook]
//
which you can access at any time.
//
Now would be a good time to make sure that you've received credit for the first
few homework problems.

You may also want to review your
//
link:/m/grades/lectures/[lecture participation scores]
//
and ensure that you understand how to follow along in class.
//
If you are having trouble logging in to the slides ask one of you lab mates for
help&mdash;or post on the {forum}.
//
*Also keep in mind that we don't start counting lecture participation for credit
until Monday 9/2/2019.*
//
So you have a few lectures to figure out our system.

[[survey]]
=== Complete Our Survey

We distribute an initial student survey during the first week weeks to gather
important data about CS 125 students.

Completing the survey is quick and easy _and_ will earn you 1% extra credit!
//
You can access it https://forms.gle/AfQKi6QihhM3Fe1f6[here].

[[book]]
=== Obtain a Copy of "Coders" by Clive Thompson

We'll be reading portions of "Coders" by Clive Thompson this semester, so please
make sure you
//
https://www.amazon.com/Coders-Making-Tribe-Remaking-World/dp/0735220565[acquire
a copy].
//
My suggestion would be the Kindle edition, which you can read on your phone
using the free app footnote:[Or, obviously, on a Kindle if you happen to have
one.]
//
**You should finish Chapter 1 of "Coders" by next week's quiz.**

[[homework]]
=== Work on Homework

If you have some time left, either help others get set up, or work on our
//
https://prairielearn.engr.illinois.edu/pl/course_instance/33373/assessments[first set of homework problems].

**Note that on all of our homework and exam programming problems you can submit
as many times as you want for full credit.**
//
We _want_ you to practice, and so we're definitely not going to penalize you for
doing so!

[[done]]
== Before You Leave

**Don't leave lab until**:

. You know the names of your TA and any course assistants assigned to your lab
section
//
. You've <<google, enabled Google integration>> and can log on to the {forum}
//
. You've set up your <<gravatar, Gravatar>>
//
. You've enrolled in our course on <<pl, PrairieLearn>> and signed up to take
<<cbtf, Quiz 0 in the CBTF>>
//
. You've completed our <<survey, initial student survey>> footnote:[And received
1% extra credit]...
//
. _and_ you've completed <<homework, any available homework problems>>...
//
. **and** so has everyone else in your lab section.
//
. And finally, make sure that your TA or CA marks that you have participated it
today's lab before you leave.

If you need more help completing the tasks above please come to
//
link:/info/syllabus/#calendar[office hours (which start Thursday)]
//
or post on the {forum}.
