---
title: "Ready to Start"
description:
  Start exploring computer science concepts&mdash;including parallelism,
  debugging and testing. And get your environment set up to start programming.
priority: 0.5
changefreq: monthly
layout: single.hbt
sidebar: lab
---

:sectnums:
:linkattrs:

[.lead]
//
Let's get started!
//
The goal of our first lab is to prepare you to begin work on link:/MP/0/[MP0].
//
You'll prepare your development environment by installing
link:/MP/setup/java/[Java] and link:/MP/setup/intellij[IntelliJ], and walk
through the process of committing and submitting your work using
link:/MP/setup/git[Git].

== Introductions [.text-muted]#(15 Minutes)#

[.lead]
//
But first let's spend a few minutes getting to know each other.

Make sure that you introduce yourself to your teaching assistant, and to the
volunteer course assistants that are staffing your lab section.
//
This is also a great opportunity to meet other students!
//
At some point during this lab section, try to find:

* a person from your dorm
//
* a person from the same major footnote:[This is probably not that hard!]
//
* a person with programming experience...
//
* ...and one without programming experience
//
* somebody very different from you

Make it a goal today to learn _and remember_ the names of five other students.
//
The course staff will be working hard this semester to learn your
names&mdash;but please be patient with us.

=== Working Together

You'll frequently be working together in groups in our lab sections... and for
the rest of your life as a technologist.
//
So it's something worth getting good at.

When working with a new group of people, it's best to try to get out of your
comfort zone a bit&mdash;especially at first.
//
If you're used to doing a lot of talking, try to listen and make room for
other voices.
//
And if you're a bit on the quiet side, try to speak up and actively
participate.
//
Things get easier once everyone gets comfortable with each other.

'''

== Environment Preparation [.text-muted]#(45 Minutes)#

[.lead]
//
Next we're going to get you set up with the tools that you need to write
computer code for this course.

There are three setup tutorials to complete;

. link:/MP/setup/java/[Install Java]
//
. link:/MP/setup/intellij/[Install IntelliJ]
//
. link:/MP/setup/git/[Get Started with Git]

Once you complete the tutorials above, continue with the rest of the lab
as described below.
//
**Don't go on until you've installed everything properly and gone through the
introduction to Git.**

== Practice With MP0 [.text-muted]#(50 Minutes)#

[.lead]
//
Now let's walk through the process of obtaining, developing, and submitting
link:/MP/0[MP0].
//
It's due in less than two weeks, so we want you to get comfortable with this
process right away.

To complete this part of lab, read through and follow the instructions on the
link:/MP/0/[MP0 writeup].
//
**Don't leave your lab section until you have successfully submitted
MP0&mdash;even if your submission doesn't earn any points yet.**
//
If you finish early, find someone who hasn't finished and help them out.
//
Future labs will have points for collective achievement, so this is a
good chance to practice working together with your entire section.
