---
title: Sorting and Searching
description:
  "Sorting and searching are fundamental computer science algorithms. They get to
  the heart of two things that computers are very good at: organizing and
  retrieving data. They are also building blocks on which other algorithms are
  built. Today you'll think about how basic searching and sorting algorithms
  work, and have a chance to implement a few yourself."
priority: 0.5
changefreq: monthly
layout: single.hbt
spelling_exceptions:
sidebar: lab
draft: true
---
:sectnums:
:linkattrs:

[.lead]
//
Sorting and searching are fundamental computer science tasks.
//
They get to the heart of two things that computers are very good at: organizing
and retrieving data.
//
They are also building blocks on which other algorithms are built.

Today's lab introduces you to basic searching and sorting algorithms.
//
The written portion starts to develop your intuition about how sorting and
searching algorithms work, and how their performance might vary.
//
The programming component provides an opportunity to implement a few sorting
algorithms, and get a visceral sense of algorithm runtime.

[[exercises]]
== Written Exercises [.text-muted]#(45 Minutes)#

[.lead]
//
As usual, we begin with a written lab component.
//
Please complete these exercises carefully.
//
Your course staff will review and discuss your answers along with the rest of
your section.

Complete this part of the lab in pairs using Google Docs.
//
Create a copy of https://goo.gl/97BiuU[our document template], and then edit it
to record you and your partner's answers.
//
**Note that you must open this document using your @illinois.edu Google Apps
account.**
//
We will not grant access to non-Illinois users.

Have a course staff member check your answers as you go.
//
When you are done, move on to the programming component.

'''

[[coding]]
== Sorting Implementations [.text-muted]#(45 Minutes)#

[.lead]
//
Computers have gotten extremely fast, and as a result it can be easy to not care
about algorithm runtime when working on small problems.
//
But once data gets a bit bigger&mdash;and the world is full of big
data&mdash;the difference between algorithms starts to matter.
//
A lot.

The second part of the lab provides you with an opportunity to get up close and
personal with the implementation and performance of several classic sorting
algorithms.


=== Forking the Lab11 Eclipse Project

Just as in previous labs we've set up an Eclipse project for Lab 11 on
//
https://github.com/cs125-illinois/Lab11[GitHub].
//
https://help.github.com/articles/fork-a-repo/[Fork]
//
and clone a copy of our repository as you have
//
link:/lab/3/#forking[previously].

=== Your Goal

We provide skeletons of three classic sorting algorithms for you to implement:
//
https://en.wikipedia.org/wiki/Bubble_sort[bubble sort],
//
https://en.wikipedia.org/wiki/Selection_sort[selection sort],
//
and
//
https://en.wikipedia.org/wiki/Merge_sort[merge sort].
//
Implement one, two, or all three of these algorithms.

Then use the provided plotting tool to explore their performance.
//
Remember from the written component that algorithm performance can be affected
by both the size _and_ the structure of the inputs.
//
We've given you inputs both of different size and structure, so this should be
an ideal starting point for an exploration of their impact on the algorithms you
have completed.

Work with other groups nearby to complete a characterization of all three
sorting algorithms.
//
You should be able to answers questions about how their performance varies with
input size, but also about how well they perform on different sized inputs.
//
You are free to split up the problem so that each group implements one sorting
algorithm and then you all compare results.

[[mp6]]
== Help with MP5 [.text-muted]#(20 Minutes)#

Use any remaining time in your lab section footnote:[Hopefully not much!] to get
help with link:/MP/6/[MP6].

// vim: ts=2:sw=2:et
