---
title: Final Project UI
description:
  Today you'll get started on your final project. Specifically, you'll find a
  partner, begin planning your project, and sketch out a user interface design
  for your app. You'll work on the final part of the lab using a technique
  called pair programming.
secret: 39DGju33yc
spelling_exceptions:
  - DIY
  - OpenWeatherMap
---
:sectnums:
:linkattrs:

[.lead]
//
Today's lab marks the beginning of the end of your journey into computer
science.
//
You'll begin working on your final project, and specifically gain insights into
how to design a _user interface_.

Note that like link:/lab/11/[Lab 11] there is no written part of this lab.
//
Instead, we'll expect you to seek out any required information yourself or
consulting your lab members for help.
//
*Remember that the link:/MP/7/[final project] has extra credit points for labs
that produce impressive projects*, so now is a good time to start working
together and helping each other out.

[[pairs]]
== Pair Programming

[.lead]
//
You'll work in pairs on today's activity.
//
You should work with your partner for MP7.
//
And you'll also have a chance to practice a programming approach called _pair
programming_.

[[partnering]]
=== Picking a Project Partner

Repeating our guidance about finding a partner from link:/lab/11/[last week's
lab]:

[quote]
____
//
Obviously you want to find someone to work with that you enjoy working with and
think that you can do an awesome project with&mdash;since we will be giving
extra credit for some of the best projects.
//
Another consideration is ensuring that at least one of you has a laptop that can
smoothly run Android Studio and the emulator, or an Android phone for demoing
your new application.
//
____

If you don't have a partner yet, find one before proceeding.

[[pairprogramming]]
=== Pair Programming

By now you've probably realized that programming is a mentally taxing full-brain
activity.
//
So, frequently when programming, two heads are _literally_ better than one.
//
That's where the idea of
//
https://en.wikipedia.org/wiki/Pair_programming[_pair programming_]
//
comes from.

What is pair programming?
//
Simply put, it describes any programming approach where two programmers work
together simultaneously using a single machine.
//
No&mdash;you don't type with all four hands footnote:[Although if you can do
that, there's probably some YouTube fame in it for you...].
//
Instead, pair programming divides the work into two roles:

. *Driver*: this programmer touches the keyboard and does all code editing
tasks.
//
. *Observer*: the second programmer _does not touch the keyboard_ but rather
observes what the driver is doing, reviewing each line of code, asking
questions, and generally serving as a guide and check on what the driver is
doing.

As a metaphor, think about the process of navigating a vehicle before voice
navigation footnote:[Can you remember those days?].
//
One person, the driver, keeps their hands on the wheel and their eyes on the
road.
//
The second person, the navigator, is able to observe the surroundings, look at
the map, and generally help keep the trip on track.

Pair programmers should switch roles often, and you should multiple times as you
complete the lab tasks below.
//
Pair programming is widely used in industry, partly because it is sometimes
considered to produce better code, but mainly because it's more fun than working
alone.

*Why are we doing this today?*
//
Simple: we want to help make sure that you and your partner can communicate and
work together effectively.
//
Pair programming forces you to communicate with your partner.
//
If you are driving and not communicating, your observer has no idea what you are
trying to do.
//
If you are observing and not communicating, your driver has no way to
incorporate your guidance.

So please complete the following tasks _using pair programming_.
//
Each group should only have one laptop active and the other put away.

[[diyui]]
== DIY UI [.text-muted]#(60 Minutes)#

[.lead]
//
Your first pair challenge for today's lab is to add a user interface (UI) to a
simple Android weather app.

We've set up the app to fetch the weather for Champaign from the
//
https://openweathermap.org/[OpenWeatherMap API],
//
You will need to sign up for an API key and add it to your project in the same
way as you did for
//
link:/MP/6#apikey[MP6].
//
But the main problem with this app is that it's missing a UI!
//
So that's your challenge.

*Note that this is far from easy.*
//
If you have never done UI design before, you will soon gain an appreciation for
how hard it is footnote:[Many a night I have spent trying to get a particular
website to just look a _bit_ different...].
//
And you'll quickly develop an appreciation for all of the beautiful and
well-designed apps that you use on a regular basis.
//
Design is hard!

Another reason that we are doing this MP now is that we want you to come up with
realistic UI goals for your final project.
//
That's what we'll work on during the <<mockup, second part of today's lab>>.

=== Forking and Cloning the Lab12 Android Studio Project

We've set up an
//
https://github.com/cs125-illinois/Lab12[Lab 12 GitHub repository]
//
containing an Android Studio Project that's correctly configured for Lab 12.
//
Getting access to it is similar to how you
//
link:/MP/setup/git/#importing[imported MP0].
//
But you have to fork our repository first.
//
If it's not obvious how to do that, try following
//
https://help.github.com/articles/fork-a-repo/[these instructions].

*Note that you should use Android Studio for this lab.*
//
We're done with IntelliJ at this point.

=== Examining the Existing Layout

We haven't really provided much for you to start with for Lab 12.
//
But go ahead and open up `res/layout/activity_main.xml` and examine the
skeleton that we've provided.

==== Design view v. text view

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/vmlK8pQpCGc" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

When working with Android UIs, it's important to understand that Android uses
it's own kind of markup language to design user interfaces.
//
Just like HTML determines the structure of a web page, Android uses XML to
define and position layout elements.

Android Studio always provides two ways to examine the layout: one is the
_design view_ that shows a graphical representation of how the UI will look.
//
The second is the _text view_ that shows the XML markup used to generate the
layout.

As you get started with UI design, we suggest using the design view as much as
possible&mdash;it will make things easier.
//
But if you want to continue Android development you'll want to get comfortable
with the XML view as well, and may want to learn how to design UIs by writing
the XML directly.

==== `LinearLayout`

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/x0W0UU-KUsU" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

Your app's `MainActivity` currently uses a single UI layout called a
//
https://developer.android.com/guide/topics/ui/layout/linear.html[`LinearLayout`].
//
It arranges all elements inside it into a single row, either horizontally or
vertically.
//
A `LinearLayout` is not suitable for more complex UI designs, but it can be a
decent starting point for simple applications.

=== Android Design Principles

Roughly speaking we can break the available Android UI components into three
categories:

* *Layouts*: these determine how the elements inside them are positioned.
Examples include the `LinearLayout`, the new `ConstraintLayout`, as well as
`FrameLayout` and `TableLayout`. Layouts are largely invisible to the user.
//
* *Containers*: these determine how a larger amount of content is displayed, for
example by scrolling (`ScrollView`, `HorizontalScrollView`), in a drop-down menu
(`Spinner`), or by using tabs (`TabLayout`). Containers may have navigation
elements that are visible, like a scroll bar, but mainly exist to organize the
things that they contain.
//
* *Components*: these are everything that is actually visible to the user,
including images (`ImageView`), buttons (`Button`, `ImageButton`), progress
bars, text input fields, etc.

One way to approach Android design is to start by answering the question: what
will the user see or interact with?
//
Then pick which component to use.
//
Next, figure out how to use the containers or layouts to adjust where the
component appears on the screen.
//
More often than not, that's the really tricky part.

=== Part 1: Button

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/kMAimyVNeVk" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

To begin, add a button to the UI.
//
Have that button trigger a refresh of the weather data.
//
Feel free to look at previous labs and MPs for help.

Note that each UI element that you want to access in your code must have a
unique ID.
//
You can can elements whatever you want, but a good name for this button might be
`refresh_weather` or something like that.
//
It's good to pick a meaningful name so that you remember what the button is for
what you are adding code to your `MainActivity.java` class.

Here are the steps required to add the button:

. Add the button to the UI. You can do this easily using the UI designer.
//
. Make sure that the button has useful text and a useful ID.
//
. Register a click handle for the button in your `onCreate` method, similar to
what was done for link:/MP/6/[MP6] and link:/lab/11/[Lab 11].
//
. Have that click handler run the function that actually updates the current
weather.

==== Viewing the XML

When you're done with adding your button using the UI designer, flip over to the
text view and take a look at what's there now.
//
Try to get a general understanding of how the various components fit together.
//
Try changing a few of the XML properties and see if you can alter how things
look on the display, and gain an understanding of what each property is for.

=== Part 2: Weather Display

Next, find a way to display something about the weather on the user interface.

There are multiple ways to do this, and you may want to explore the library of
design elements that are available to you.
//
For example, you could simply print a single adjective describing the current
weather to the display footnote:[I might actually use your calm weather app...].
//
If you want to get fancier, see if you can actually use an icon to display the
weather, rather than a text box.
//
And fancier still, see if you can add a progress bar that is shown when the API
call is taking place.
//
Where you stop is up to you!
//
And of course, you'll need to do a bit of JSON parsing just like for
link:/MP/6/[MP6].

=== Part 3: Help Others

Are you done early?
//
Great!
//
There's probably someone else in your lab that needs help.
//
Please try and provide them with some guidance.

[[mockup]]
== Final Project Planning and UI Mockup [.text-muted]#(50 Minutes)#

You and your partner should use the remaining lab time to begin work on two
important final project objectives.

First, you should decide what you are going to try and accomplish.
//
Keep in mind how much time and energy you have left, your relative ability
levels, and how much you want (or need) 1% extra credit.
//
*We also highly suggest working on a project that you enjoy.*
//
Excitement about the final product is extremely important to get you through the
inevitable moments of frustration.

Once you have decided on a final project idea, you should begin sketching a user
interface for your app.
//
Please use this lab to inform your UI design.
//
If you have some experience in this area, or just really like what you did for
the first hour, then by all means consider something a bit complicated.
//
If you struggled, stick with something simple.
//
Note that Android provides some built-in activities that come with basic layouts
designed for certain types of apps.
//
You can explore those by right-clicking on your project, choosing new and then
either activity or Google, which also contains some starter activities.

[[next]]
== Next Week

During next week's lab we'll ask each group for a brief overview of their
project and to demonstrate a working UI.
//
This means that all UI elements should be in place and should be attached as
needed to some kind of handler in each activity.
//
Those handlers don't have to do anything, yet: they can just log a message so
that we know that they are working.
//
Although you may want to keep going if you get to this point quickly.

// vim: ts=2:sw=2:et
