---
title: Command Line
description:
  "The command line is an important power tool for every computer programmer. It
  allows you to accomplish more tasks than you can do using a graphical
  interface, and faster and more accurately. However, like anything else it
  takes time and practice to master. We'll provide an introduction in this lab
  using a safe virtualized sandbox."
priority: 0.5
changefreq: monthly
layout: single.hbt
spelling_exceptions:
  - Lubuntu
  - VirtualBox
  - workspaces
sidebar: lab
draft: true
---
:sectnums:
:linkattrs:

[.lead]
//
The command line is an important power tool for every computer programmer and
technologist.
//
Once you master it it allows you to accomplish more than you can using graphical
interfaces, and accomplish those things faster and more accurately.
//
Essentially the command line allows you to interact with your computer
_programmatically_, writing what are essentially small programs one line at a
time.

This lab will introduce you to the command line environment.
//
To make this as safe and fun as possible, we'll encourage you to install and use
a virtualized Linux machine to learn and practice your command line skills.
//
This will both provide you with the complete power available to a system
administrator, while also ensuring that you can't do anything too terrible to
your computer.

== Lab Structure

Note that this lab is a bit different than previous labs.
//
There is no written component, and no programming component either.
//
Instead, you'll install some software, and then complete a few tasks using your
new command line skills.
//
We've also left things underspecified and open-ended.
//
This is intentional.
//
The best resources for learning the command line is the internet, and you should
feel free to search online for help, tutorials, and even solutions.

_If you are skilled at the command line_, please feel free to help those around
you.
//
This environment is new to many, and your experience will be appreciated by
those that are experiencing the terminal for the first time.

[[environment]]
== Getting a Command Line

[.lead]
//
Our first task in this lab is to provide you with a command line environment
that you can experiment with.
//
To accomplish this, we're going to use a powerful and important computer
technology called _virtualization_.

Our goal is to provide you with an environment that is both powerful and safe.
//
If you follow our instructions, you will be left with a new virtual computer
that you both have complete control over (power) and is also completely isolated
from the rest of your computer system (safety).


[[virtualbox]]
=== Install VirtualBox [.text-muted]#(10 Minutes)#

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/5GgoKbqcAVQ" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

[.lead]
//
The first step is to download and install the free
https://www.virtualbox.org/[VirtualBox] virtualization software.

What is virtualization?
//
In a nutshell, virtualization allows you to create a _virtual machine_: a
separate computer that runs inside your existing computer.
//
The virtual machine is completely isolated from the computer it runs
on&mdash;called the host&mdash;and from any other virtual machines you create.
//
It has its own memory, file system, and networking configuration.
//
Programs running _inside_ the virtual machine cannot affect or even seen
anything outside the virtual machine.

As a result, you can experiment inside your virtual machine without endangering
anything outside.
//
For example, if you accidentally remove every file in your virtual machine
footnote:[Oops], all of the files on the host are unaffected.
//
It is also extremely easy to restore your virtual machine to its starting point,
making it an ideal environment for experimentation.

[[linux]]
=== Install Linux [.text-muted]#(10 Minutes)#

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/N9yg5uNFiCU" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

With VirtualBox installed, you can now create a virtual machine.
//
Because the virtual machine is, in fact, a completely separate computer, we can
install an entirely new operating system on it.
//
And that's what we're going to to do.

Go ahead and install Ubuntu Linux in your virtual machine.
//
We'll let you figure out how to do this by searching around online&mdash;there
are many, many tutorials on this.
//
The specific version of Ubuntu is up to you, but we suggest that you install
//
http://lubuntu.me/downloads/[Lubuntu 16.04.3]
//
which is a lightweight long-term support release.
//
*Do not install Lubuntu 17.10&mdash;this is known not to work on VirtualBox.*
//
These release will continue to be supported for long periods of time, unlike the
latest and greatest which changes about once per year.

You can download and install pre-built Ubuntu images for VirtualBox.
//
But it's a bit more fun the first time to actually install using the install CD
image from the Ubuntu website, since it gives you a visceral sense that this is
a separate computer.
//
The process is exactly the same as if you were installing on so-called
//
https://en.wikipedia.org/wiki/Bare-metal_server[_bare metal_].

[[other]]
=== Other Ways to Get a Command Line

Depending on your what kind of machine you use you have other options for
getting a command prompt.
//
These other options don't all provide the same combination of power and safety
of our approach.
//
But if you can accept the trade-offs, or run into trouble with the approach
above, feel free to give them a try:

. Mac OS has a built-in Linux-like command line environment, which is one of the
reasons that Apples tend to be popular with hackers.
//
Run the Terminal app and you'll be presented with a `bash` prompt.
//
*Keep in mind, however, that mistakes made at the command line can do serious and
potentially irreparable damage to your machine.*
//
. All versions of Windows have their own terminal program, but it's extremely
unpleasant to use.
//
We don't recommend taking the time to learn it.
//
However, as of Windows 10 Windows users can now install a variety of Linux
utilities including standard shells that provide a more powerful command line
environment.
//
Start learning more
//
https://msdn.microsoft.com/en-us/commandline/wsl/about[here].
//
_We definitely recommend that Windows users explore this option_.
//
*Keep in mind, however, that mistakes made at the command line can do serious and
potentially irreparable damage to your machine.*
//
. Illinois provides a variety of remote access Linux and UNIX servers that you
can access over SSH.
//
Instructions for accessing the EWS servers via SSH are available
//
https://it.engineering.illinois.edu/user-guides/remote-access/accessing-linux-terminals-remotely-ssh[here].
//
However, unlike your own virtual machine, you will not have full administrator
access to these shared machines.
//
That's a good thing&mdash;if you did, you could wreak all kinds of havoc.
//
But if you're learning and want to do things like install software, configure
servers, and other fun machine administration tasks, not having administrator
access can be limiting.

[[navigating]]
== Getting Started [.text-muted]#(20 Minutes)#

Most of this information is easily available online, but here's just a primer to
get you started.

=== Anatomy of a Command Line Command

Consider this command line command:

[source,bash]
----
$ ls -l Documents
----

Like many, it consists of several parts:

* `ls`: this is the command itself&mdash;a computer program that runs and
serves some purpose.
//
* `Documents`: this is an _argument_ to the `ls` command.
//
Arguments many be required or optional, and their meaning depends on the command
that we are running.
//
In this case, `Documents` tells `ls` to list files in the `Documents` subdirectory of
the current directory.
//
* `-l`: this is a command _option_.
//
Options are normally optional, but can sometimes be required.
//
They typically alter the commands behavior in some way.
//
In this case, the `-l` option to `ls` tells it to use a long listing format,
which displays more information about each file and directory it encounters.

=== Navigating the File System

Many of the most widely-used command line operations involve navigating your
computer's file system.
//
You may have only semi-realized this, but your computer organizes all of its
files into a tree with a single root.
//
Directories&mdash;which you may know as folders&mdash;can contain files, but
also may contain other directories.
//
Some of this organization is up to you.

Inside your new terminal, try the following commands and determine what the do:

* `pwd`
//
* `ls`
//
* `cd`
//
* `find`
//
* `mkdir`
//
* `rmdir`
//
* `rm`... but be careful with this one!
//
There is no undo or recycling bin for `rm`!

[[exercises]]
== Command Line Exercises [.text-muted]#(40 Minutes)#

With your brand new command line environment set up, let's get down to some
exercises.
//
See how many of the following tasks you can accomplish during the lab period.

=== Clone and Build the Lab12 GitHub Project

Just as in previous labs we've set up an Eclipse project for Lab 12 on
//
https://github.com/cs125-illinois/Lab12[GitHub].
//
https://help.github.com/articles/fork-a-repo/[Fork]
//
and clone a copy of our repository as you have
//
link:/lab/3/#forking[previously].
//
However, this time *do not start Eclipse*.
//
Instead, figure out how to clone and build the project from the command line.
//
(You will need to fork the project using GitHub's web interface.)
//
If you get stuck, refer to the screencast above.

=== Practice Using SVN and Git

. *Checkout and build one of your MPs.*
//
Using only the command line, use Subversion to checkout one of your programming
assignments and then Gradle to build it.
//
Note that you may need to install some software: including the
//
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04[Oracle
JDK]
//
and
//
https://askubuntu.com/questions/55546/how-do-i-install-svn[Subversion].
//
. *Create a new Git repository and push it to GitHub.*
//
Starting with `git init`, create a new Git repository, add some files, and then
push it to GitHub.
//
(Feel free to remove it when you're done.)
//
. *Edit a file using a command line editor.*
//
There are
//
https://en.wikipedia.org/wiki/List_of_text_editors[many choices]
//
of editors that can run entirely at the command line.
//
99% of the time it's better to fire up a GUI-based source code editor&mdash;but
there are times that you don't have that option.
//
For example, you may have to log in to a remote machine and editor some
configuration files without a monitor attached.
//
So it's important to have _some_ familiarity with commonly-available command
line text editors such as
//
http://www.vim.org/[`vim`]
//
or
//
https://www.gnu.org/software/emacs/[`emacs`].

=== Other Fun

. *Track some system statistics.*
//
Try to figure out what processes are running on your virtual machine.
//
Pick a few and try to figure out what they are and why they are running.
//
. *Explore the internet.*
//
Install and use a few internet inspection tools.
//
For example, try to trace the path of a network packet from your machine to a
server on the west coast.
//
. *Try `tmux`.*
//
Experiment with the `tmux` terminal multiplexing utility.
//
It's quite helpful for creating and saving terminal workspaces so that you can
return to your work later, and particularly helpful when logging on to remote
machines.

[[mp7]]
== MP7 [.text-muted]#(30 Minutes)#

link:/MP/7/[MP7] is out and requires you to work in pairs with someone from your
lab section.
//
It is due _two weeks_ from now in lab.
//
Use the remainder of the lab period to find a partner and begin brainstorming
ideas for your link:/MP/7/[MP7] submission.

// vim: ts=2:sw=2:et
