---
title: Final Project Checkpoint
description:
  Today we'll review your progress on your final project.
---
:sectnums:
:linkattrs:

[.lead]
//
Today's lab is a final project checkpoint.
//
At this point we expect you to be done with your UI and moving on to the
functionality for your app.
//
The course staff will review your progress to confirm this.
//
*Remember that the link:/MP/5[final project] has extra credit points for labs
that produce impressive projects*.

[[checkpoint]]
== Checkpoint

At some point either today or tomorrow you need to briefly demo your progress on
your final project to a member of the course staff.
//
The best way to do this is to use the
//
https://cs125-help.cs.illinois.edu/[CS 125 Help System].
//
However, this will mean that only one project partner should demo the project.
//
Any course staff member can complete your final checkpoint form.
//
But they will need to know both your NetID and your partner's to make sure that
you both receive credit.

If you cannot use the
//
https://cs125-help.cs.illinois.edu/[help site],
//
you will need to make other arrangements with your TA.
//
You can find their contact information
//
https://cs125.cs.illinois.edu/info/people/#tas[here].

**Either way, you _must_ demo your final project before the end of the day on
Wednesday April 29th.**

[[next]]
== Next Week

During next week's lab we'll present the final videos from each group and
complete project grading.
//
At that point your app should be fully functional.

// vim: ts=2:sw=2:et
