---
title: Final Project Checkpoint
description:
  Today we'll review your progress on your final project and you'll present your
  idea to the rest of your lab and get some feedback.
---
:sectnums:
:linkattrs:

[.lead]
//
Today's lab is a final project checkpoint.
//
At this point we expect you to be done with your UI and moving on to the
functionality for your app.
//
The course staff will review your progress to confirm this, and you'll have a
chance to present your idea to the rest of your lab and get feedback.

*Remember that the link:/MP/7/[final project] has extra credit points for labs
that produce impressive projects*.
//
So now is a good time to start working together and helping each other out.

[[checkpoint]]
== Checkpoint [.text-muted]#(45 Minutes)#

For the first half of today's lab the course staff will circulate to check in on
you project status.
//
20 points are handed out today for having a working UI, with 10 points for
having made some progress and 0 points for not having made any.
//
Your lab course staff will also use this as an opportunity to ask about your
road map for completing the project by next week, and answer questions you might
have.

[[pitches]]
== Project Pitches [.text-muted]#(45 Minutes)#

[.lead]
//
In the second half of this lab, each project group should _very briefly_ present
their project idea to the rest of their lab section.

Being able to provide a short summary of a project to another person is
extremely important.
//
So important that it has a name&mdash;an
//
https://en.wikipedia.org/wiki/Elevator_pitch[elevator pitch]
//
footnote:[the idea being that if you were stuck in an elevator with Elon
Musk and had only 30 seconds to pitch him on your exciting idea...].
//
One characteristic of good pitches is that they are short, so try to keep yours
to under 60 seconds.
//
After you're done you'll have time to take a few questions from other students
in your lab section.

[[next]]
== Next Week

During next week's lab we'll present the final videos from each group and
complete project grading.
//
At that point your app should be fully functional.
//
Remember that the final project fair is Thursday 5/3/2018, and that there are
multiple ways to earn extra credit at the fair.

[[ices]]
== ICES Forms [.text-muted]#(20 Minutes)#

Use the remaining lab time to complete the ICES forms evaluating your TA.
//
Thanks for the feedback&mdash;we really appreciate it.

// vim: ts=2:sw=2:et
