---
title: Final Project Checkpoint
description:
  Today we'll review your progress on your final project and you'll complete the
  ICES forms.
---
:sectnums:
:linkattrs:

[.lead]
//
Today's lab is a final project checkpoint.
//
At this point we expect you to be done with your UI and moving on to the
functionality for your app.
//
The course staff will review your progress to confirm this.

*Remember that the link:/MP/6/[final project] has extra credit points for labs
that produce impressive projects*.
//
So now is a good time to continue working together and helping each other out.

[[checkpoint]]
== Checkpoint [.text-muted]#(80 Minutes)#

For the first portion of today's lab the course staff will circulate to check in on
you project status.
//
20 points are handed out today for having a working UI, with 10 points for
having made some progress and 0 points for not having made any.
//
Your lab course staff will also use this as an opportunity to ask about your
road map for completing the project by next week, and answer questions you might
have.

While the course staff is reviewing other groups continue working with your
project partner.

[[next]]
== Next Week

During next week's lab we'll present the final videos from each group and
complete project grading.
//
At that point your app should be fully functional.
//
Remember that the final project fair is Thursday 12/13/2018 from 5&ndash;9PM and
that there are multiple ways to earn extra credit at the fair.

[[ices]]
== ICES Forms [.text-muted]#(30 Minutes)#

Use the remaining lab time to complete the ICES forms evaluating your TA.
//
Thanks for the feedback&mdash;we really appreciate it.

// vim: ts=2:sw=2:et
