---
title: Trace Points
description:
  Work on simple code reading, algorithm development, variable assignment, and
  word counting exercises.
spelling_exceptions:
  - urlScanner
draft: true
---
:sectnums:
:linkattrs:

[.lead]
//
In this lab we begin focusing our attention on the art and craft&mdash;the
https://en.wikipedia.org/wiki/Techne[_techne_]&mdash;of programming.
//
We'll do some code reading and talk style; continue developing our algorithmic
chops; and get practice with variable assignment, loops, and counters.
//
We've also set aside some time to talk link:/MP/1/[MP1].

[[exercises]]
== Written Exercises [.text-muted]#(50 Minutes)#

[.lead]
//
We begin with a set of code reading and writing exercises.

Complete this part of the lab in pairs using Google Docs.
//
Create a copy of https://goo.gl/qXiTtc[our document template], and then edit it
to record you and your partner's answers.
//
**Note that you must open this document using your @illinois.edu Google Apps
account.**
//
We will not grant access to non-Illinois users footnote:[One of these weeks
we're going to say this and _not_ get a bunch of requests to share the document
to Gmail addresses. Maybe this week?].

Have a course staff member check your answers as you go.
//
When you are done, move on to the next section.

'''

[[scraping]]
== Simple Web Scraping [.text-muted]#(30 Minutes)#

[.lead]
//
For the second part of this lab we're going to do a quick code writing exercise.
//
Our goal is to show how easy it is to fetch and process content from the
web&mdash;the most impressive library that the world has ever created.

[[forking]]
=== Forking the Lab3 Eclipse Project

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/w7_6nBOUnjE" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

Just as in link:/lab/1/[Lab 1] and link:/lab/2/[Lab 2], we've set up an Eclipse
project for Lab 3.
//
And, just like link:/lab/1/[Lab 2] and link:/lab/2/[Lab 2], it's on
//
https://github.com/cs125-illinois/Lab3[GitHub].

However, this time we're going to use a more common GitHub development model
when you want to make your own changes to a project.
//
First, we'll https://help.github.com/articles/fork-a-repo/[_fork_] the
repository.
//
Then, we'll clone our own copy of it.
//
Once we're done, we'll be able to save our changes at the end of the lab, since
we have our own private copy of the project.

Here's what to do.
//
*Note that you will need a valid GitHub username for this part of the lab.*
//
If you don't have one, https://github.com/join[go ahead and create
one]&mdash;the process is quick,free, and painless.
//
Once you have your GitHub account set up:

. Go to
//
https://github.com/cs125-illinois/Lab3[https://github.com/cs125-illinois/Lab3,role="spelling_exception"].
//
In the upper right hand corner of the page, there is a button that says "Fork".
Click it.
//
. It may give you a choice of where to fork the repository.
//
Choose your personal GitHub account.
//
. Once that's done, you'll have your own copy of our Lab3 project at
//
link:https://github.com/yourgithubusername/Lab3[https://github.com/yourgithubusername/Lab3, role="noclick link_exception"]

Now, using the link to _your copy_ of the Lab3 project, follow the
//
link:/lab/1/#cloning[cloning the repository instructions from Lab 1].

==== Wait: where's the content?

You may have noticed that, unlike previous lab, there is no starter code in the
Lab3 project.
//
Why not?
//
Because we want you to get the hang of starting from scratch.
//
Why did we have you clone our largely-empty project then?
//
Mainly because Eclipse does a terrible job of setting good defaults for various
settings, and because we want you to keep using checkstyle.

=== Getting to the `main` Point

Working with our Lab3 project, create a new class in `src/main/java`.
//
You can call it anything you like.
//
Make sure that it has a main method&mdash;we'll be using it throughout the lab.
//
We've gone through this a few times in class, so hopefully you have the hang of
it by now.
//
Ask a neighbor or a staff member for help if you need it.

=== A Bit of Help

Our goal is to give you the chance to process web content as strings.
//
You could very easily find out how to do this online, probably discovering the
//
https://stackoverflow.com/questions/4328711/read-url-to-string-in-few-lines-of-java-code[same advice that our approach is based on].

But, to speed the plow a bit, we're going to provide you with a helper function.
//
Cut and paste the following function into the class you created above.
//
Don't put it _inside_ the main method&mdash;make it a separate function.
//
*Also note that the `import` statements have to go at the top of your file, not
at the same level as the new function.*

++++
<script
src="https://gist.github.com/gchallen/9dbbd5eb426f34b03cf507985d5fc722.js"></script>
++++

==== Nothing is magic

*You don't need to understand this code&mdash;just be able to use it.*
//
But here's an explanation for the curious footnote:[And this is just about as
easy as anything gets in Java...]:

* *Lines 1&ndash;3*: import the parts of the Java standard library that we need.
//
* *Lines 12&ndash;17*: we allocate a new
//
https://docs.oracle.com/javase/7/docs/api/java/util/Scanner.html[Scanner]
//
object (Line 12) and then initialize it (Line 14).
//
* *Line 14*:
//
https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openStream()[URL.openStream]
//
can throw several kinds of exceptions.
//
Normally we'd let the caller handle them, but in this case we'll suppress them
and return an empty string on error (Line 16).
//
* *Line 18*: now we have to convert the contents to a string.
//
https://community.oracle.com/blogs/pat/2004/10/23/stupid-scanner-tricks[This
post] explains a bit of the "\\A" part, which I don't fully understand but it
seems to work.
//
* *19&ndash;20*: Then we close our urlScanner to avoid a resource leak and return the string
contents.

=== Word Counting

Once you have our `urlToString` function integrated into your code, test it out
using `System.out.println`.
//
Here are some URLs that may be interesting to try.
//
Note that they all return raw text, rather than the
https://en.wikipedia.org/wiki/HTML[HTML] that you are using to seeing online.
//
But you should also experiment with some HTML pages, like
https://cs.illinois.edu/[this one].

[.spelling_exception]
--
* http://erdani.com/tdpl/hamlet.txt[http://erdani.com/tdpl/hamlet.txt]
//
* https://www.bls.gov/tus/charts/chart9.txt[https://www.bls.gov/tus/charts/chart9.txt]
//
* http://tgftp.nws.noaa.gov/data/raw/fz/fzus53.klot.srf.lot.txt[http://tgftp.nws.noaa.gov/data/raw/fz/fzus53.klot.srf.lot.txt]
--

Now, for each of the pages above, compute a _word count_.
//
Your class should compute the total number of words on the page.

*We are intentionally not giving you a lot of help with this part of the lab.*
//
But don't get discouraged!
//
Look around for help online, ask your neighbor, and be sure to ask your TA and
doyen for help as well.

==== Counting One Word

Now modify your code above so that it looks for and counts occurrences of a
specific word, which you can define as a constant in your code.
//
For example, how many times does the word "Prince" appear in
http://erdani.com/tdpl/hamlet.txt[Hamlet]?
//
Can you make your new function case-insensitive, so that "Prince" and "prince"
are counted as the same word?

==== Challenge: Unique Word Counting

If you get your word counting done with time to spare, try changing it so it
counts the number of _unique_ words in each file.
//
For example, the number of words in "this is a string is a string" is 7, but the
number of _unique_ words is 4.

Completing this part of the lab will probably require you explore advanced Java
data structures that you will not see for a while in this course.
//
But give it a shot if you get here with time to spare.

[[push]]
=== Saving Your Work

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/xT-tjHkQtx4" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

For Lab 3 we _really do_ want you to commit and push your changes to the new
GitHub repository that you created above.
//
Once you have some changes to your project, the process is similar *but not
identical* to the process of link:/MP/subversion/#commit[committing changes with
Subversion].

. Right click on the project and choose "Team &rarr; Commit".
//
. This will bring up a window where you can view what changes you have made to
the project.
//
Unlike Subversion, Git does not force you to commit every change
you have made at once.
//
This is useful in many cases&mdash;for example, when you were working on two new
features at once and want separate commits containing the changes for each.
//
. In our case, simply move all of the appropriate unstaged files into the
staging area.
//
. Then, write a commit message.
//
. At this point you have two options: "Commit", and "Commit and Push".
//
For the sake of this exercise, choose just "Commit".
//
. Now browse to your GitHub copy of Lab 3.
//
*You should not see your new changes.*
//
This is an important difference between Git and Subversion.
//
Git maintains a local copy of the _entire repository_, and commits go to that
repository first.
//
To get them to your remote repository on GitHub requires a separate step known
as a _push_.
//
. Go ahead and do the push now: "Team &rarr; Push to Upstream".
//
. Once that completes refresh your GitHub page.
//
You should see the last commit message you added as well as your changes.
//
That's all there is to it!

[[mp1]]
== Help with MP1 [.text-muted]#(20 Minutes)#

Use any remaining time in your lab section to get help with link:/MP/1/[MP1].
//
If you are done or making good progress, please help others&mdash;but help them
_learn_, don't just give them the answers.
//
And if you are behind, please reach out the course staff for help.

// vim: ts=2:sw=2:et
