---
title: Trace Points
description:
  Work on simple code reading, algorithm development, variable assignment, and
  word counting exercises.
spelling_exceptions:
  - urlScanner
secret: 0lP31uc3
---
:sectnums:
:linkattrs:

[.lead]
//
In this lab we focus our attention on the art and craft&mdash;the
https://en.wikipedia.org/wiki/Techne[_techne_]&mdash;of programming.
//
We'll do some code reading and talk style; continue developing our algorithmic
chops; and get practice with variable assignment, loops, and counters.
//
We've also set aside some time to talk link:/MP/2/[MP2].

[[exercises]]
== Written Exercises [.text-muted]#(40 Minutes)#

[.lead]
//
We begin with a set of code reading and writing exercises.

Complete this part of the lab in pairs using Google Docs.
//
Create a copy of
//
https://goo.gl/PxsFZP[our document template]
//
and then edit it to record you and your partner's answers.
//
**Note that you must open this document using your @illinois.edu Google Apps
account.**
//
We will not grant access to non-Illinois users footnote:[One of these weeks
we're going to say this and _not_ get a bunch of requests to share the document
to Gmail addresses. Maybe this week?].

Have a course staff member check your answers as you go.
//
When you are done, move on to the next section.

'''

[[scraping]]
== Simple Web Scraping [.text-muted]#(40 Minutes)#

[.lead]
//
For the second part of this lab we're going to do a quick code writing exercise.
//
Our goal is to show how easy it is to fetch and process content from the
web&mdash;the most impressive library of text the world has ever created.

[[starting]]
=== Creating a New IntelliJ Project

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/tlx5VZfaz5M" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

In this lab we're going to show you how to create a _new_ IntelliJ project,
rather than using one that we've already set up for you.
//
Follow the screencast above to learn how to do that&mdash;or just look it up
online.
//
There are plenty of good instructions out there.

[.alert.alert-warning]
//
--
//
**Note that this screencast has you configured Java 9.**
//
This semester you should use and configure Java 10.
//
--

=== Getting to the `main` Point

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/tHt1A_5lvXQ" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

Working with our Lab3 project, create a new class.
//
You can call it anything you like.
//
Make sure that it has a main method&mdash;we'll be using it throughout the lab.
//
IntelliJ has a way to create a command line app that will add this function for
you, or you can add it later.
//
Refer to the screencast above for guidance about how to create a new class in
IntelliJ.
//
*And make sure to add version control to your project as well, also as shown in
the screencast above.*
//
Ask a neighbor or a staff member for help if you need it.

=== A Bit of Help

Our goal is to give you the chance to process web content as strings.
//
You could very easily find out how to do this online, probably discovering the
//
https://stackoverflow.com/questions/4328711/read-url-to-string-in-few-lines-of-java-code[same advice that our approach is based on].

But, to speed the plow a bit, we're going to provide you with a helper function.
//
Cut and paste the following function into the class you created above.
//
Don't put it _inside_ the main method&mdash;make it a separate function.
//
*Also note that the `import` statements have to go at the top of your file, not
at the same level as the new function.*

++++
<script
src="https://gist.github.com/gchallen/9dbbd5eb426f34b03cf507985d5fc722.js"></script>
++++

==== Nothing is magic

*You don't need to understand this code&mdash;just be able to use it.*
//
But here's an explanation for the curious footnote:[And this is just about as
easy as anything gets in Java...]:

* *Lines 1&ndash;3*: import the parts of the Java standard library that we need.
//
* *Lines 12&ndash;17*: we allocate a new
//
https://docs.oracle.com/javase/7/docs/api/java/util/Scanner.html[Scanner]
//
object (Line 12) and then initialize it (Line 14).
//
* *Line 14*:
//
https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openStream()[URL.openStream]
//
can throw several kinds of exceptions.
//
Normally we'd let the caller handle them, but in this case we'll suppress them
and return an empty string on error (Line 16).
//
* *Line 18*: now we have to convert the contents to a string.
//
https://community.oracle.com/blogs/pat/2004/10/23/stupid-scanner-tricks[This
post] explains a bit of the "\\A" part, which I don't fully understand but it
seems to work.
//
* *19&ndash;20*: Then we close our urlScanner to avoid a resource leak and return the string
contents.

=== Word Counting

Once you have our `urlToString` function integrated into your code, test it out
using `System.out.println`.
//
Here are some URLs that may be interesting to try.
//
Note that they all return raw text, rather than the
https://en.wikipedia.org/wiki/HTML[HTML] that you are using to seeing online.
//
But you should also experiment with some HTML pages, like
https://cs.illinois.edu/[this one].

[.spelling_exception]
--
* http://erdani.com/tdpl/hamlet.txt[http://erdani.com/tdpl/hamlet.txt]
//
* https://www.bls.gov/tus/charts/chart9.txt[https://www.bls.gov/tus/charts/chart9.txt]
//
* http://tgftp.nws.noaa.gov/data/raw/fz/fzus53.klot.srf.lot.txt[http://tgftp.nws.noaa.gov/data/raw/fz/fzus53.klot.srf.lot.txt]
--

Now, for each of the pages above, compute a _word count_.
//
Your class should compute the total number of words on the page.

*We are intentionally not giving you a lot of help with this part of the lab.*
//
But don't get discouraged!
//
Look around for help online, ask your neighbor, and be sure to ask your TA and
doyen for help as well.

==== Counting One Word

Now modify your code above so that it looks for and counts occurrences of a
specific word, which you can define as a constant in your code.
//
For example, how many times does the word "Prince" appear in
http://erdani.com/tdpl/hamlet.txt[Hamlet]?
//
Can you make your new function case-insensitive, so that "Prince" and "prince"
are counted as the same word?

==== Challenge: Unique Word Counting

If you get your word counting done with time to spare, try changing it so it
counts the number of _unique_ words in each file.
//
For example, the number of words in "this is a string is a string" is 7, but the
number of _unique_ words is 4.

Completing this part of the lab will probably require you explore advanced Java
data structures that you will not see for a while in this course.
//
But give it a shot if you get here with time to spare.

[[push]]
=== Saving Your Work

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/QWu66Qxn06E" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

To complete Lab 3, you'll learn how to create a new empty GitHub repository, add
it to your project, and push your code to it.
//
Note that, unlike your MPs, this repository can be public.
//
Follow the screencast above to learn how to do this.

[[mp2]]
== Help with MP2 [.text-muted]#(20 Minutes)#

Use any remaining time in your lab section to get help with link:/MP/2/[MP2].
//
If you are done or making good progress, please help others&mdash;but help them
_learn_, don't just give them the answers.
//
And if you are behind, please reach out the course staff for help.

[[done]]
== Before You Leave

**Don't leave lab until**:

. You've completed the entire https://goo.gl/XJ1Aur[handout]
//
. You've finished the <<scraping, web scraping exercise>>
//
. You've pushed your work to GitHub and showed a TA or CA
//
. You've considered sticking around for a few minutes to help
others&mdash;either with the lab or with link:/MP/2/[MP2]
//
. And you've link:/m/grades/labs/[confirmed your participation in today's lab]

// vim: ts=2:sw=2:et
