---
title: Algorithms and Variables
description:
  Work on variable role identification, truth tables, simple finite-state
  machines, quiz preparation, and code cleanup exercises.
draft: true
---
:sectnums:
:linkattrs:

[.lead]
//
In this lab we'll continue to hone our programming skills.
//
We'll look at how variables are used within and around loops, provide a method
for understanding complex conditionals, and do a significant code reclamation
project.
//
We've also set aside some time to discuss link:/MP/2/[MP2].

[[exercises]]
== Written Exercises [.text-muted]#(50 Minutes)#

[.lead]
//
We begin with a set of code reading and writing exercises.

Complete this part of the lab in pairs using Google Docs.
//
Create a copy of https://goo.gl/KTxDWg[our document template], and then edit it
to record you and your partner's answers.
//
**Note that you must open this document using your @illinois.edu Google Apps
account.**
//
We will not grant access to non-Illinois users footnote:[One of these weeks
we're going to say this and _not_ get a bunch of requests to share the document
to Gmail addresses. Maybe this week? Actually, Gmail has been putting these in
my Spam folder, which is both a good and bad thing...].

Have a course staff member check your answers as you go.
//
When you are done, move on to the next section.

'''

[[cleanup]]
== Code Cleanup [.text-muted]#(30 Minutes)#

[.lead]
//
The next part of the lab focuses on style, both in terms of formatting and
code clarity.
//
We'll try to show you how _hard_ it is to read poorly-formatted code.
//
And then we give you a chance to get our terrible example to really shine.

=== Forking the Lab4 Eclipse Project

Just as in link:/lab/1/[Lab 1], link:/lab/2/[Lab 2], and link:/lab/3/[Lab 3],
we've set up an Eclipse project for Lab 4.
//
It's on
//
https://github.com/cs125-illinois/Lab4[GitHub].

We're going to use the more common GitHub development model when you want to
make your own changes to a project.
//
First, we'll https://help.github.com/articles/fork-a-repo/[_fork_] the
repository.
//
Then, we'll clone our own copy of it.
//
Once we're done, we'll be able to save our changes at the end of the lab, since
we have our own private copy of the project.

Follow the link:/lab/3/#forking[instructions from Lab 3].

=== Reclamation Project

Our Lab4 project has only one Java file&mdash;and it's a huge mess.
//
Your job is to clean it up.

Working with your partner, follow the instructions in the source code to get it back to a readable state.
//
Once you are done, compare your work with another group.
//
Offer a gentle critique of their choices, and let them do the same for you.

=== Saving Your Work

Just like link:/lab/3/[Lab 3], we do want you to save your work this time.
//
Follow the link:/lab/3/#push[Lab 3 pushing instructions].

[[mp2]]
== Help with MP2 [.text-muted]#(20 Minutes)#

Use any remaining time in your lab section to get help with link:/MP/2/[MP2].
//
If you are done or making good progress, please help others&mdash;but help them
_learn_, don't just give them the answers.
//
And if you are behind, please reach out the course staff for help.

=== `java.lang.String`

A good starting point is to review the
//
https://docs.oracle.com/javase/7/docs/api/java/lang/String.html[Java String
documentation].

Fortunately footnote:[or unfortunately&mdash;Javadoc formatting is pretty ugly]
you'll be reading a lot of documentation like this if you keep writing Java
code.
//
So it's worth getting used to how Javadoc documentation is laid out.
//
Get some initial practice navigating the String documentation.
//
Then, if you're feeling adventurous, try finding and exploring another piece of
Java documentation.

// vim: ts=2:sw=2:et
