---
title: Introduction to Android
description:
  Prepare your development environment for work on the Android MPs and begin
  MP4.
---

:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu[forum,role='noexternal']]

[.lead]
//
The goal of this lab is to prepare you to begin work on the Android set of MPs
(MP4 and MP5) and your Android final project.
//
You'll prepare your development environment by installing
//
link:/MP/setup/android-studio/[Android Studio],
//
build and run a simple Android app using the Android emulator,
//
and familiarize yourself with the
//
https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/[Microsoft
Computer Vision Application Programming Interface (API)].

[[android]]
== Android Environment Preparation [.text-muted]#(80 Minutes)#

[.lead]
//
In this section we'll have you set up Android to prepare your computer to build
Android apps and complete the next several MPs.

=== Install Android

Follow link:/MP/setup/android-studio[this tutorial] to download and install
Android Studio.
//
Make sure to follow the instructions carefully, and ask the course staff for
help if you need it.

=== Using the Android Emulator

Make sure that you complete the
//
link:/MP/setup/android-studio#emulator[this portion]
//
of the tutorial.
//
To work on MP4 and MP5, you will need either an Android device or a working
emulator&mdash;even if it runs a bit slowly.
//
Again, work with the course staff to try and complete this portion of the lab.

Once you have the "Hello, world!" application running, try to make the following
modifications to this simple app:

* Change the text that is shown to "Hello, CS 125!"
//
* Change the size of the text
//
* Change the position of the text
//
* Add some other element to the user interface

=== Using the Emulated Camera [.text-muted]#(Optional)#

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/B4JVqKHsYzk" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

As the final challenge for the Android portion of the lab, try to get the
camera working on your emulated device.
//
Feel free to skip this section if setting up Android took a while.

Consult the screencast above for instructions on how to do this.
//
You can test whether your emulated camera is working by using the built-in
Android Camera app.
//
If possible, set up your emulated camera to use your computer's built-in webcam,
assuming it has one.

[[mp4]]
== Getting Started on MP4 [.text-muted]#(30 Minutes)#

Use the remainder of your lab time to get started on
//
link:/MP/4[MP4].
//
There is a fair amount of information in the write up to review, and because this
is your first time working in Android the environment will feel a bit
unfamiliar.

Here's our suggestions about how to get started:

. First use the
//
https://cs125-illinois.github.io/MP4-Starter/[MP4 online documentation]
//
to finish enough of `Transform.java` so that your MP starts compiling.
//
We suggest just returning the pixel array unmodified.
//
This will mean that your app doesn't work, but also won't crash the way it will
if you return `null`.
//
. Next make sure that you can build and run the Android app: either on your own
phone, or on the emulator.
//
. Now pick one of the image transformations and get started!
//
The easiest set is probably the image shifts, but the one that will earn you the
most points the most rapidly is probably the green screen function
//
footnote:[Although you'll find it's hard to get green screen to work properly.].

[[done]]
== Before You Leave

**Don't leave lab until**:

. You have link:/MP/setup/android-studio[installed Android Studio]
//
. You have been able to successfully run the
//
link:/MP/setup/android-studio/#helloworld[Android "Hello, world!" app]
//
using the Android emulator or on your own device
//
. You have started link:/MP/4/[MP4]
//
. And so has everyone else in your lab section!

If you need more help, please come to link:/info/syllabus/#calendar[office
hours], or post on the {forum}.
