---
title: Objects I
description:
  Objects are an important programming concept in Java as well as other
  programming languages. Today, we begin a multi-week introduction to objects.
priority: 0.5
changefreq: monthly
layout: single.hbt
spelling_exceptions:
  - Pokémon
sidebar: lab
draft: true
---
:sectnums:
:linkattrs:

[.lead]
//
Today we begin introducing you to _objects_.
//
Objects are an important concept in many programming languages, and particularly
in Java.
//
They provide an intuitive way of organizing _state_ and _behavior_, the two main
components of any computer program.

[[exercises]]
== Written Exercises [.text-muted]#(45 Minutes)#

[.lead]
//
As usual, we begin with a written lab component.
//
This one is particularly important, however, so please slow down and complete
the exercises carefully.
//
Your course staff will review and discuss your answers along with the rest of
your section.

Complete this part of the lab in pairs using Google Docs.
//
Create a copy of https://goo.gl/SD6iZF[our document template], and then edit it
to record you and your partner's answers.
//
**Note that you must open this document using your @illinois.edu Google Apps
account.**
//
We will not grant access to non-Illinois users.

Have a course staff member check your answers as you go.
//
When you are done, move on to the next section.

'''

[[coding]]
== Pokémon Objects [.text-muted]#(60 Minutes)#

[.lead]
//
Like any other programming concept, the way to get familiar with objects is to
_use_ them.
//
In the second half of the lab we'll provide you with some practice at
manipulating object state and using object methods.

And we'll try to make it as interesting as possible by having you work with a
special type of objects: https://www.pokemon.com/us/[Pokémon] objects!

=== Forking the Lab7 Eclipse Project

Just as in previous labs we've set up an Eclipse project for Lab 7.
//
It's on
//
https://github.com/cs125-illinois/Lab7[GitHub].
//
https://help.github.com/articles/fork-a-repo/[Fork]
//
and clone a copy of our repository as you have
//
link:/lab/3/#forking[previously].

[[objects]]
=== Your Goal

[.lead]
//
Your job is to complete the provided program so that you can take input from the
user and configure each battling Pokémon appropriately.

You'll need to use your newly-acquired knowledge about objects and object
syntax.
//
You'll also probably want to look into how to use the
//
https://docs.oracle.com/javase/7/docs/api/java/util/Scanner.html[Java Scanner
Class].
//
The course staff will circulate to help out and provide useful advice.

[[mp4]]
== Help with MP4 [.text-muted]#(20 Minutes)#

Use any remaining time in your lab section to get help with link:/MP/4/[MP4].

// vim: ts=2:sw=2:et
