---
title: Objects III
description:
  Objects are an important programming concept in Java as well as other
  programming languages. Today, we continue a multi-week introduction to objects
  by discussing inheritance, casting, and function overriding.
priority: 0.5
changefreq: monthly
layout: single.hbt
spelling_exceptions:
  - Pokémon
sidebar: lab
draft: true
---
:sectnums:
:linkattrs:

[.lead]
//
Today we continue introducing you to _objects_.
//
Objects are an important concept in many programming languages, and particularly
in Java.
//
Today's focus is on several new intermediate object-oriented programming
concepts: inheritance, typecasting, and function overriding.

We will also discuss the overall Java class system.
//
The programming component allows you to utilize the power of inheritance to
expand the functionality of the Pokémon program that you started in
link:/lab/7/[Lab 7].

[[exercises]]
== Written Exercises [.text-muted]#(45 Minutes)#

[.lead]
//
As usual, we begin with a written lab component.
//
Please complete these exercises carefully.
//
Your course staff will review and discuss your answers along with the rest of
your section.

Complete this part of the lab in pairs using Google Docs.
//
Create a copy of https://goo.gl/frhz2G[our document template], and then edit it
to record you and your partner's answers.
//
**Note that you must open this document using your @illinois.edu Google Apps
account.**
//
We will not grant access to non-Illinois users.

Have a course staff member check your answers as you go.
//
When you are done, move on to the programming component.

'''

[[coding]]
== More Pokémon Objects [.text-muted]#(60 Minutes)#

[.lead]
//
Like any other programming concept, the way to get familiar with objects is to
_use_ them.
//
In the second half of the lab we'll provide you with some practice at
utilizing the relationships between objects.

And we'll try to make it as interesting as possible by having you continue
working with the Pokémon objects that we introduced in link:/lab/7/[Lab 7].

=== Forking the Lab9 Eclipse Project

Just as in previous labs we've set up an Eclipse project for Lab 9 on
//
https://github.com/cs125-illinois/Lab9[GitHub].
//
https://help.github.com/articles/fork-a-repo/[Fork]
//
and clone a copy of our repository as you have
//
link:/lab/3/#forking[previously].

=== Your Goal

We'll continue where we left off last time.
//
Except this time you have the chance to implement several new types of Pokémon:
Electric, Fire, and Water Pokémon.

Start by examining the base Pokémon class in `Pokemon.java`.
//
This type of Pokémon will perform a normal attack.
//
However, when fighting the specialty Pokémon they will have a chance to do
their special attack under certain conditions: if they are not already defeated,
and if the roll of the dice goes their way.

You'll need to complete the implementation of the specialty attack methods for
the Electric, Fire, and Water Pokémon.
//
You'll also need to rewrite the `buildPokemon` method to build specialty Pokémon
correctly depending on the user input.
//
Once that's done, your specialty Pokémon will be ready to battle in the
Colosseum!

[[mp5]]
== Help with MP5 [.text-muted]#(20 Minutes)#

Use any remaining time in your lab section to get help with link:/MP/5/[MP5].

// vim: ts=2:sw=2:et
