---
title: "Android and APIs"
description:
  Prepare your development environment for work on Android apps, and explore the
  Microsoft Computer Vision Application Programmer Interface (API).
---

:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu[forum,role='noexternal']]

[.lead]
//
The goal of this lab is to prepare you to begin work on the Android set of MPs
(MP6 and MP7) and your final project.
//
You'll prepare your development environment by installing
//
link:/MP/setup/android-studio/[Android Studio],
//
build and run a simple Android app using the Android emulator,
//
and familiarize yourself with the
//
https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/[Microsoft
Computer Vision Application Programmer Interface (API)].

[[done]]
== Before You Leave

**Don't leave lab until**:

. You have link:/MP/setup/android-studio[installed Android Studio]
//
. You have been able to successfully run our Android "Hello, world!" application
using the Android emulator
//
. You have reviewed our introduction to APIs
//
. You have obtained your key for Microsoft's Cognitive Services API
//
. And so has everyone else in your lab section!

If you need more help, please come to link:/info/syllabus/#calendar[office
hours], or post on the {forum}.
