---
title: "Android and APIs"
description:
  Prepare your development environment for work on Android apps, and explore the
  Microsoft Computer Vision Application Programmer Interface (API).
---

:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu[forum,role='noexternal']]

[.lead]
//
The goal of this lab is to prepare you to begin work on the Android set of MPs
(MP6 and MP7) and your final project.
//
You'll prepare your development environment by installing
//
link:/MP/setup/android-studio/[Android Studio],
//
build and run a simple Android app using the Android emulator,
//
and familiarize yourself with the
//
https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/[Microsoft
Computer Vision Application Programmer Interface (API)].

[[android]]
== Android Environment Preparation [.text-muted]#(45 Minutes)#

[.lead]
//
In this section we'll have you set up Android to prepare your computer to build
Android apps and complete the next several MPs.

=== Install Android

Follow link:/MP/setup/android-studio[this tutorial] to download and install
Android Studio.
//
Make sure to follow the instructions carefully, and ask the course staff for
help if you need it.

=== Using the Android Emulator

Make sure that you complete the
//
link:/MP/setup/android-studio#emulator[this portion]
//
of the tutorial.
//
To work on MP6 and MP7, you will need a working emulator&mdash;even if it runs a
bit slowly.
//
Again, work with the course staff to try and complete this portion of the lab.

Once you have the "Hello, world!" application running, try to make the following
modifications to this simple app:

* Change the text that is shown to "Hello, CS 125!"
//
* Change the size of the text
//
* Change the position of the text
//
* Add some other element to the user interface

=== Using the Emulated Camera

As the final challenge for the Android portion of the lab, try to get the
camera working on your emulated device.
//
Consult the screencast above for instructions on how to do this.
//
You can test whether your emulated camera is working by using the built-in
Android Camera app.
//
If possible, set up your emulated camera to use your computer's built-in webcam,
assuming it has one.

== Introduction to APIs [.text-muted]#(45 Minutes)#

[[done]]
== Before You Leave

**Don't leave lab until**:

. You have link:/MP/setup/android-studio[installed Android Studio]
//
. You have been able to successfully run our Android "Hello, world!" application
using the Android emulator
//
. You have reviewed our introduction to APIs
//
. You have obtained your key for Microsoft's Cognitive Services API
//
. And so has everyone else in your lab section!

If you need more help, please come to link:/info/syllabus/#calendar[office
hours], or post on the {forum}.
