---
title: "Android Studio Setup"
description:
  Prepare your computer to complete the Android-based machine problems (MPs).
---
:sectnums:
:linkattrs:

[.lead]
//
To complete the Android CS 125 machine problems (MPs) you'll write your
//
https://www.java.com/en/[Java]
//
code using the
//
https://developer.android.com/studio/index.html[Android Studio]
//
Integrated Development Environment (IDE) and test your apps using the
//
https://developer.android.com/studio/run/emulator.html[Android Emulator].
//
This guide will help you install and configure these important and powerful
development tool.

[.alert.alert-warning]
--
**Note that if have not
//
link:/MP/setup/java/[installed Java]
//
you should do that first.**
//
Return here when you're done.
//
Also note that you only need Android Studio for the Android-based MPs&mdash;this
semester starting with
//
link:/MP/4/[MP4].
--

[[intellij]]
== Android Studio

[.lead]
//
https://developer.android.com/studio/index.html[Android Studio]
//
is _the_ integrated development environment (IDE) for Android development.
//
Happily, Android Studio is based on
//
link:/MP/setup/intellij/[IntelliJ], which you are have already been using for
previous MPs.

Follow the instructions below that are appropriate for your machine.
//
But keep in mind that installing new software can be challenging, so don't be
discouraged if you get stuck.
//
We're here to help!
//
Come to office hours or
//
https://cs125-forum.cs.illinois.edu/c/mps/android-studio[post on the forum in
the Android Studio category].

[[version]]
=== Version

For Fall 2018 we are using Android Studio version 3.2, which is the latest
available as of October 2018.
//
Please install this version of Android Studio and continue using it throughout
the semester.
//
Minor upgrades are probably safe to install.
//
If a major upgrade is released, the course staff will let you if it is safe to
use.

[[install]]
=== Installation

Begin by downloading the version of Android Studio appropriate for your machine
using
//
https://developer.android.com/studio/index.html[this link].
//
Next, follow
//
https://developer.android.com/studio/install.html[these excellent installation
instructions].
//
**Please follow them carefully**.

[[checkstyle]]
== `checkstyle` Plugin

Once you have <<install, installed Android Studio>>, continue by installing the
//
https://plugins.jetbrains.com/plugin/1065-checkstyle-idea[Checkstyle-IDEA
IntelliJ plugin].
//
It's the same one that you used for your Java assignments using IntelliJ, but
should also work on Android Studio, and you can follow
//
link:/MP/setup/intellij/#plugins[the same instructions].

*Note that our CS 125 plugin is not yet compatible with Android Studio.*
//
We hope to fix that soon.

[[emulator]]
== Android Emulator

An important part of Android development is to be able to test your work.
//
If you have an Android device, you can configure Android Studio to install your
test app onto it.
//
However, if you don't have an Android device, or want to test on devices other
than ones that you own, you'll need to utilize the
//
https://developer.android.com/studio/run/emulator.html[Android Emulator].

The easiest way to get a virtual device set up is to start a project, build it,
and then try to run it.
//
That will launch a dialog allowing you to configure a virtual device.
//
// Follow the screencast above for a complete description.

[[devices]]
== Running on Real Devices

If you have an Android phone you can also install and run your apps on your own
device, which will be faster and more fun that using the emulator.
//
Follow
//
https://developer.android.com/training/basics/firstapp/running-app[this
tutorial]
//
for instructions on how to configure your device properly to run your apps
during development.
