---
title: "Working On EWS"
description:
  A discussion of how to complete the CS 125 labs and MPs on the Engineering Workstations
  (EWS) machines.
---
:sectnums:
:linkattrs:

[.lead]
//
We think that you'll have the best success in CS 125 working on your own
personal computer&mdash;preferably a laptop.
//
However, if you need to use the engineering workstations in the basement of
Siebel and other engineering buildings, instructions follow.

== Android Studio

Android Studio is available on the _Windows_ workstations located throughout the
basement of Siebel and in other EWS labs.
//
Notably, all of the workstations in our CS 125 office hours room (Siebel 0403)
are Windows machines where you can use Android Studio.

Android Studio should already be installed on these machines, but requires a few
additional steps to finish the setup process.
//
Please follow
//
https://answers.uillinois.edu/page.php?id=88845[these instructions].
//
When you have finished those steps please continue
//
link:/MP/setup/android-studio/#plugins[at this point in our Android Studio
instructions]
//
by installing the plugins you need for CS 125.
