---
title: "IntelliJ Setup"
description:
  Prepare your computer to complete the Java-based machine problems (MPs).
spelling_exceptions:
  - Ninite
  - x64
  - /Chromebooks?/
  - buildship
  - checkstyle
  - CheckStyle
  - Combinator
  - Swieskowski
  - Buildship
  - testng
  - PPA
  - Upd8
---
:sectnums:
:linkattrs:

[.lead]
//
To complete the CS 125 machine problems (MPs) you'll write your
//
https://www.java.com/en/[Java]
//
code using the
//
https://www.jetbrains.com/idea/[IDEA IntelliJ]
//
Integrated Development Environment (IDE) augmented with the
//
https://plugins.jetbrains.com/plugin/1065-checkstyle-idea[Checkstyle-IDEA
plugin].
//
This guide will help you install and configure this important and powerful
development tool.

[.alert.alert-warning]
--
**Note that if have not
//
link:/MP/setup/java/[installed Java]
//
you should do that first.**
//
Return here when you're done.
--

[[intellij]]
== IntelliJ

[.lead]
//
https://www.jetbrains.com/idea/[IntelliJ]
//
is a powerful and popular open-source integrated development environment
(IDE).
//
Many programmers utilize IDEs to simplify the process of writing, building,
testing, and debugging both large and small applications.

If you have a laptop or desktop that you plan to use for CS 125, you should
install IntelliJ on it.
//
Follow the instructions below that are appropriate for your machine.
//
But keep in mind that installing new software can be challenging, so don't be
discouraged if you get stuck.
//
We're here to help!
//
Come to office hours or
//
https://cs125-forum.cs.illinois.edu/c/mps/intellij[post on the forum in the IntelliJ category].

[[version]]
=== Version

For Fall 2018 we are using IntelliJ Community version 2018.2.2, which is the
latest free version available as of August 2018.
//
Please install this version of IntelliJ and continue using it throughout the
semester.
//
Minor upgrades are probably safe to install.
//
If a major upgrade is released, the course staff will let you if it is safe to
use.

[[install]]
=== Installation

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/sr8vIn-A3Uw" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

IntelliJ maintains an
//
https://www.jetbrains.com/help/idea/install-and-set-up-product.html[excellent
set of installation instructions].
//
**Please follow them carefully**, and make sure that you don't miss any
instructions specific to whether you are running Windows, Mac, or Linux.
//
You should not need to modify any of the default settings or plugins.

*Note that the screencast above is for an older version of IntelliJ IDEA, but
the process is the same for version 2018.2.2.*

== IntelliJ Plugins

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/c-lpQJ6e40g" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

Once you have <<install, installed IntelliJ>>, continue by installing two
plugins:

. The https://plugins.jetbrains.com/plugin/1065-checkstyle-idea[Checkstyle-IDEA
IntelliJ plugin] and
//
. Our CS 125 IntelliJ plugin.

[[checkstyle]]
=== `checkstyle`

We use
//
http://checkstyle.sourceforge.net/[`checkstyle`]
//
to help you learn how to write beautiful and maintainable code by requiring you
adhere to a coding standard.
//
**There are points on each MP for `checkstyle`, so you want to get the plugin
installed so that you can check your style in IntelliJ.**

Installing this plugin is straightforward:

. Start IntelliJ. If you have a project open, close it.
//
. Choose "Configure" and then "Plugins" on the main screen.
//
. Click "Browse repositories".
//
. Search for "checkstyle".
//
. Download and install the latest version of the plugin.
//
. Restart IntelliJ when you are done to finish the installation process.

[[cs125]]
=== CS 125 Plugin

Next install the
//
link:/tech/intellijplugin[CS 125 IntelliJ Plugin].
//
This plugin will simplify your MP development while also providing us with
valuable information about your progress on the MP.
//
You can read more about it
//
link:/tech/intellijplugin[here].

The process is almost identical to the one that you followed above to install
<<checkstyle, `checkstyle`>>:

. Start IntelliJ. If you have a project open, close it.
//
. Choose "Configure" and then "Plugins" on the main screen.
//
. Click "Browse repositories".
//
. Search for "CS 125"
//
. Download and install the latest version of the plugin.
//
. Restart IntelliJ when you are done to finish the installation process.

