---
title: "Java Installation"
description:
  Prepare your computer to complete the Java-based machine problems (MPs).
priority: 0.5
changefreq: monthly
layout: single.hbt
sidebar: MP
---
:sectnums:
:linkattrs:

[.lead]
//
CS 125 teaches the
//
https://www.java.com/en/[Java]
//
programming language.
//
This guide will help you install the software that you need to develop Java
applications.

[[java]]
== Java

[.lead]
//
https://www.java.com/en/[Java].
//
is a powerful and versatile programming language.
//
You can build all kinds of things with it, from web servers to command line
utilities to Android apps.

If you have a laptop or desktop that you plan to use for CS 125, you should
install Java on it.
//
Follow the instructions below that are appropriate for your machine.
//
But keep in mind that installing new software can be challenging, so don't be
discouraged if you get stuck.
//
We're here to help!
//
Come to office hours or
//
https://cs125-forum.cs.illinois.edu/c/mps/java[post on the forum in the Java category].

[[version]]
=== Version

For Spring 2018 we are using Java 9.0.1, the latest available as of available as
of January 2018.
//
Please install this version of IntelliJ and continue using it throughout the
semester.
//
Minor upgrades will probably not be a problem, and we do not anticipate another
major release of Java before the end of the semester.

[[install]]
=== Install on Mac and Windows

Download the appropriate software package for your machine
//
http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html[from
this web page].
//
Run the installer and it will guide you through the rest of the process.

[[linux]]
=== Install on Linux

If you are installing on Ubuntu Linux you may have more luck by using a
packaged Java installer.
//
https://medium.com/@shaaslam/how-to-install-oracle-java-9-in-ubuntu-16-04-671e598f0116[These
instructions]
//
document that process.
