---
title: "Java Installation"
description:
  Prepare your computer to complete the Java-based machine problems (MPs).
---
:sectnums:
:linkattrs:

[.lead]
//
CS 125 teaches the
//
https://www.java.com/en/[Java]
//
programming language.
//
This guide will help you install the software that you need to develop Java
applications.

[[java]]
== Java

[.lead]
//
https://www.java.com/en/[Java].
//
is a powerful and versatile programming language.
//
You can build all kinds of things with it, from web servers to command line
utilities to Android apps.

If you have a laptop or desktop that you plan to use for CS 125, you should
install Java on it.
//
Follow the instructions below that are appropriate for your machine.
//
But keep in mind that installing new software can be challenging, so don't be
discouraged if you get stuck.
//
We're here to help!
//
Come to office hours or
//
https://cs125-forum.cs.illinois.edu/c/mps/installing-java[post on the forum in the
Installing Java category].

[[version]]
=== Version

For Fall 2018 we are using
//
http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html[Java
10.0.2],
//
the latest available as of available as of August 2018.
//
Java 9 and 10 have some
//
https://dzone.com/articles/features-in-java-10[cool new features]
//
that we may discuss in class compared with Java 8 which you might be more
familiar with if you have used Java before.
//
Please install this version of Java and continue using it throughout the
semester.
//
Minor upgrades will probably not be a problem, and we do not anticipate another
major release of Java before the end of the semester.

[[install]]
=== Install on Mac and Windows

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/WSdJIyeRo_g" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

Download the appropriate software package for your machine
//
http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html[from
this web page].
//
Run the installer and it will guide you through the rest of the process.

[[linux]]
=== Install on Linux

If you are installing on Ubuntu Linux you may have more luck by using a packaged
Java installer.
//
https://www.linuxuprising.com/2018/04/install-oracle-java-10-in-ubuntu-or.html[This
article]
//
documents that process.

[[home]]
=== Setting JAVA_HOME

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/uiAASO-n3U0" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

You may need to set an environment variable to ensure that Gradle can find the
correct version of Java.
//
Try this if your local autograder refuses to run.
//
https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html[Here
are some instructions for Windows], and
//
https://www.mkyong.com/java/how-to-set-java_home-environment-variable-on-mac-os-x/[here
is a tutorial for Mac].
//
The screencast above shows how to complete the process on Windows machines.
//
*Note that the screencast shows how to do this for Java 9*, so you will need to
set the path correctly to point to the Java 10 version that you installed above.
