---
title: "Ready to Start"
description:
  Start exploring computer science concepts&mdash;including parallelism,
  debugging and testing. And get your environment set up to start programming.
outdated:
  name: lab
  current: /lab/
---

:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu[forum,role='noexternal']]

[.lead]
//
Let's get started!
//
The goal of our first lab is to prepare you to begin work on link:/MP/2018/spring/0/[MP0].
//
You'll prepare your development environment by installing
link:/MP/2018/spring/setup/java/[Java] and link:/MP/setup/intellij[IntelliJ], and walk
through the process of committing and submitting your work using
link:/MP/2018/spring/setup/git[Git].

== Introductions [.text-muted]#(15 Minutes)#

[.lead]
//
But first let's spend a few minutes getting to know each other.

Make sure that you introduce yourself to your
//
link:/info/people/#tas[teaching assistant],
//
and to the link:/info/people/#cas[volunteer course assistants]
//
that are helping with your section.
//
This is also a great opportunity to meet other students!
//
At some point during this lab section, try to find:

* a person from your dorm
//
* a person from the same major
//
* a person with programming experience...
//
* ...and one without programming experience
//
* somebody very different from you

Make it a goal today to learn _and remember_ the names of five other students.
//
The course staff will be working hard this semester to learn your
names&mdash;but please be patient with us.

=== Working Together

You'll frequently be working together in groups in our lab sections... and for
the rest of your life as a technologist.
//
So it's something worth getting good at.

When working with a new group of people, it's best to try to get out of your
comfort zone a bit&mdash;especially at first.
//
If you're used to doing a lot of talking, try to listen and make room for
other voices.
//
And if you're a bit on the quiet side, try to speak up and actively
participate.
//
Things get easier once everyone gets comfortable with each other.

'''

== Environment Preparation [.text-muted]#(45 Minutes)#

[.lead]
//
Next we're going to get you set up with the tools that you need to write
computer code for this course.

=== Enable Google Integration

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/iJV5iB6pdFE" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

In order to log on to the {forum}, and use our
//
link:/m/grades/MPs[online grade interface],
//
you need to enable Google integration for your @illinois.edu
account.
//
Follow
//
https://answers.uillinois.edu/illinois/47880[this link]
//
and walk through the instructions for undergraduate (probably) or graduate
(unlikely) students.
//
The screencast above demonstrates the process.

=== Setup Tutorials

There are three setup tutorials to complete;

. link:/MP/2018/spring/setup/java/[Install Java]
//
. link:/MP/2018/spring/setup/intellij/[Install IntelliJ]
//
. link:/MP/2018/spring/setup/git/[Get Started with Git]

Once you complete the tutorials above, continue with the rest of the lab
as described below.
//
**Don't go on until you've installed everything properly and gone through the
introduction to Git.**

== Practice With MP0 [.text-muted]#(50 Minutes)#

[.lead]
//
Now let's walk through the process of obtaining, developing, and submitting
link:/MP/2018/spring/0[MP0].
//
It's due in less than two weeks, so we want you to get comfortable with this
process right away.

To complete this part of lab, read through and follow the
//
link:/MP/2018/spring/0/[MP0 instructions].
//
**Don't leave your lab section until you have successfully submitted
MP0&mdash;even if your submission doesn't earn any points yet.**
//
If you finish early, find someone who hasn't finished and help them out.
//
Future labs will have points for collective achievement, so this is a
good chance to practice working together with your entire section.

[[done]]
== Before You Leave

**Don't leave lab until**:

. You have enabled Google Apps integration and logged on successfully to the
{forum}
//
. You have installed link:/MP/2018/spring/setup/java[Java] and
link:/MP/2018/spring/setup/intellij[IntelliJ]
//
. You have gone through our link:/MP/2018/spring/setup/git[Git and GitHub tutorial]
//
. You have obtained a copy of link:/MP/2018/spring/0/[MP0]...
//
. ...and made your first submission
//
. And so has everyone else in your lab section!

If you need more help, please come to link:/info/syllabus/#calendar[office
hours], or post on the {forum}.
