---
title: Introduction to Algorithms
date: 2018-10-22
description:
  Completion of a discussion of interfaces and introduction to algorithms.
spelling_exceptions:
  - GCD
youtube: https://youtu.be/NFKC7VWY_uM
---

[[ZrRhHAiZmjGVCqKzTkVDkwpNGYoRBTci]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Introduction to Algorithms</div>
++++
....
public final class Math {
  public static int gcd(int first, int second) {
    return 0;
  }
}
public class Example {
  public static void main(String[] unused) {
    System.out.println(Math.gcd(10, 20));
  }
}
....
--

[[GiCzhJdPpYadnzDkfjbZTUeTxnSlAizj]]
== Q6 Review: References

[source,java,role='smallest']
----
public class Car {
  // Constructor and private variable not shown
  public int increaseMileage() {
    return odometer++;
  }
  public boolean equals(Car other) {
    return odometer == other.odometer;
  }
}
public class Example {
  public static void main(String[] unused) {
    Car[] cars = new Car[10];
    Car car = new Car(10);
    for (int i = 0; i < cars.length; i++) {
      cars[i] = car;
    }
    for (int i = 0; i < cars.length; i++) {
      cars[i].increaseMileage();
    }
    System.out.println(cars[0].odometer);
  }
}
----

When the `main` method runs, what will be printed?

[[TlxtZufSIFpVrmkEUjnsFrOfjdmLbRIi]]
== ! Q6 Review: References

[.janini.compiler.smallest]
....
public class Car {
  public int odometer;
  public Car(int initialOdometer) {
    odometer = initialOdometer;
  }
  public int increaseMileage() {
    return odometer++;
  }
  public boolean equals(Car other) {
    return odometer == other.odometer;
  }
}
public class Example {
  public static void main(String[] unused) {
    Car[] cars = new Car[10];
    Car car = new Car(10);
    for (int i = 0; i < cars.length; i++) {
      cars[i] = car;
    }
    for (int i = 0; i < cars.length; i++) {
      cars[i].increaseMileage();
    }
    System.out.println(cars[0].odometer);
  }
}
....

[[fKdqglfiDveLkkifxciudAwnptKhAkxa]]
== Q6 Review: All or Nothing

Define a class called `All`.
//
It should provide a single class method named `orNothing` which takes two
parameters: an `int` (first) and a `boolean` (second).
//
`orNothing` should return an array of `All` references with the size provided as
the first parameter.
//
(If the first parameter is negative, return an empty array.)
//
If its second parameter is `false` `orNothing` should return the array containing
all references to _different_ `All` instances.
//
If its second parameter is `true` `orNothing` should return the array containing
all references to _the same_ `All` instance.

[[jxfLgutimlDceXmuAsVeBlFyFJnfhIuo]]
== ! Q6 Review: All or Nothing

[.janini.compiler.smallest]
....
public class Example {
  public static void main(String[] unused) {
    All[] alls = All.orNothing(10, true);
    for (int i = 0; i < 10; i++) {
      System.out.println(alls[i]);
    }
  }
}
....

[[tyQwTSdRMgfbyiaungJhUtqzJdkdhISM]]
== Review: Interface as Contract

[source,java,role='smallest']
----
/**
 * Compares this object with the specified object for order.
 *
 * Returns a negative integer, zero, or a positive integer as this object is
 * less than, equal to, or greater than the specified object.
 */
public interface Comparable {
  int compareTo(Object other);
}
----

[.lead]
//
Interfaces represent a _contract_ between the interface _provider_ and the
interface _user_.

The interface represents all that the two components on either side need to
agree on for things to work correctly.

[[hAIYbXvZIbCeHuFcdefAdTFdKMeLZzcV]]
== ! Another Comparable Example

[.janini.smallest.compiler]
....
public class Example {
  public static void main(String[] unused) {
    String[] strings = new String[] { new String("one"), new String("two"), new String("three") };
    System.out.println(maximum(values));
  }
  public static Object maximum(Comparable[] values) {
    return null;
  }
}
....

[[OCSfWmHAFFffpjpyenAaeFwujtpLCAHw]]
[.oneword]
//
== Questions?

About references, interfaces, or other object-oriented concepts?

[[WuPdwRslQMMvcKkRVzmobPMOSUWdrfeD]]
== Reminder: Midterm 1 is Next Week

[.s]
//
* This week: a quiz, primarily on interfaces and inheritance
//
* Next week: Midterm 1 covering object-oriented programming

[[aUxsyjhTqYgprQGAtYgCJCpFInIbEnMP]]
== Algorithms

[quote]
//
____
https://en.wikipedia.org/wiki/Algorithm[Algorithm]:
//
a process or set of rules to be followed in calculations or other
problem-solving operations, especially by a computer.
//
____

As computer scientists, we implement algorithms by having computers:

[.s]
//
* Perform simple calculations
//
* Store the results
//
* Make simple decisions
//
* Do things over and over again as fast as possible

[[JGTmnbkHwboAihJynfxUiXyvQBMcEFus]]
== Data Structures

[quote]
//
____
https://en.wikipedia.org/wiki/Data_structure[Data structure]:
//
a collection of data values, the relationships among them, and the functions or
operations that can be applied to the data.
//
____

As Java programmers we implement more complicated data structures using a mix
of:

[.s]
//
* Primitive types and objects to _store_ and organize data values
//
* Existing data structures like arrays
//
* References to reflect relationships among objects

[[YumtfuKBaLhokozilRqGVVRzrwypGfOd]]
== Algorithms and Data Structures

[.lead]
//
Algorithms and data structures are _highly complementary_:

[.s]
//
* We will implement algorithms that utilize specific features of data structures
//
* We will implement data structures to support specific algorithms
//
* We will use our existing imperative and object-oriented ideas along the way
//
* And we'll introduce a few more important ideas along the way

[[BzRRFIMstyqbRXhqEywqvIoQJUgYebbD]]
== Example: Greatest Common Denominator

[quote]
//
____
//
In mathematics, the
//
https://en.wikipedia.org/wiki/Greatest_common_divisor[greatest common divisor
(GCD)]
//
of two or more integers, which are not all zero, is the largest positive integer
that divides each of the integers.
//
____

[[pjDljAIzRjELOcfeobkDQFRinIBUMrhD]]
== ! GCD Algorithms

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://en.wikipedia.org/wiki/Greatest_common_divisor#Calculation"></iframe>
</div>
++++

[[tDXMsVMWQaICoZpNjRwvYQvYvpkBVCKA]]
[.oneword]
== But If We're In A Hurry...
What's a simpler approach?

[[JssrqejyvIyvwsXyrCkspJKxdKDMQLRk]]
== Brute Force Solution

[quote]
//
____
//
https://en.wikipedia.org/wiki/Brute-force_search[Brute force solution]:
//
a very general problem-solving technique that consists of systematically
enumerating all possible candidates for the solution and checking whether each
candidate satisfies the problem's statement.
//
____

[.s]
//
* Computers today are very, _very_ fast
//
* So try the simple thing first
//
* If it's too slow, try something a bit more sophisticated

[[qMuYttxuubacRODFMWhjihipuaPhWYqH]]
== ! GCD Implementation

[.janini.smallest.compiler]
....
public class SimpleMath {
}
public class Example {
  public static void main(String[] unused) {
    System.out.println(SimpleMath.GCD(10, 8));
    System.out.println(SimpleMath.GCD(100, 50));
    System.out.println(SimpleMath.GCD(94677, 65270));
  }
}
....

[[qdXwzQeEINKOPgbceNliwLWeLNyqnSVo]]
== ! Bring the Brute

image::https://cdn.vox-cdn.com/thumbor/wgMcgj6LStdjW-qlLkaHUBsdQzY=/0x0:2048x858/1200x800/filters:focal(834x251:1160x577)/cdn.vox-cdn.com/uploads/chorus_image/image/57442421/hulk_agnarok.0.jpg[role='mx-auto meme',width=640]

[[SAkZunVquojxGluWfhHFkLljmuDEmoNB]]
[.oneword]
== You Don't Need the Fastest Algorithm to Change the World

That's a good thing!

[[KTGrHQJiStmgrdjVjvLJBvdHTokGvbGK]]
== But Speed Eventually Matters

[.lead]
//
Even if you don't at the beginning, you will eventually start to care about how
fast your code runs.
//
For any number of the following reasons:

[.s]
//
* You're embarrassed that your algorithm makes your incredibly fast computer
seem slow
//
* You have to start paying for machines
//
* Your customer tells you that your program is too slow
//
* You're in a job interview

[[XIAanwdDVyALfCEgZLNQljuMKfylgtld]]
== So How Long Will It Take?

[.lead]
//
How long will our brute force GCD algorithm take?

[.s]
//
* To compute the GCD of 4 and 6
//
* To compute the GCD of 185 and 2045
//
* To compute the GCD of M and N

[[UgJrBAbxmpaEtUFaigwcjbLnlTfcIOoF]]
== Algorithm Analysis

[quote]
//
____
//
https://en.wikipedia.org/wiki/Analysis_of_algorithms[Algorithm analysis]:
//
the determination of the computational complexity of algorithms, that is the
amount of time, storage and/or other resources necessary to execute them.
//
____

[[nGsigkJsZbIIiuBueedkjOHenoatcePu]]
== Announcements

* The MP4 early deadline is _today_ at 5PM.
//
Get your 50 points!
//
* I now have office hours MWF from 10AM&ndash;12PM in Siebel 2227.
//
Please stop by!
//
* Remember to provide feedback on the course using the
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form].
//
* I've started to respond to existing feedback
//
https://cs125-forum.cs.illinois.edu/c/feedback[on the forum].


// vim: ts=2:sw=2:et
