---
title: Arrays and Algorithms
date: 2018-01-26
description:
  Continuation of arrays and introduction and practice with simple algorithms.
echo: https://goo.gl/kkigCQ
---
:imagesdir: /slides/images
:!sectids:

[[xwFAetEkwPYLqsDgwxkMoByfLxrCpBoS]]
== !

[.janini]
--
++++
<div class="message">Arrays and Algorithms<br/>Press Control-Return to run the code above</div>
++++
....
int[] numbers = {1, 2, 5};
for (int number : numbers) {
  System.out.println(number);
}
....
--

[[sZSgKWqBudTJujJbOdxqeQdqvWigxelT]]
== Review: Arrays

[.lead]
//
A Java array represents a series of zero or more values of the _same type_.

[.s]
//
* Arrays are our first example of a *data structure*.
//
* Arrays put values in order, one after another.
//
* Values in an array also have an _index_, their position in the array.

[[LmwXyHhUNCVzlkFXeZUaUAoxLFWChLjo]]
== Review: Declaring Arrays

[.lead]
//
Just like other variables, arrays have a _name_ and _type_.

But when we declare them we use brackets to declare an array instead of a single
value.

[source,java]
----
// A single integer named single
int integer;
// An array of integers named multiple
int[] multiple;

// A single character named one
char one;
// An array of characters named all
char[] all;
----

[[CabqmfPgmeNhrQvbvZrjxGSbovqlKpFV]]
== Review: Initializing Arrays

When it is declared an array is empty.
//
To use it we have to tell Java how many _elements_ it has.

*The size cannot be changed once the array is initialized.*
//
All arrays have a `.length` property that we can use to get their size.

[source,java]
----
// An array of 8 integers named multiple
int[] multiple = new int[8];
System.out.println(multiple.length); // Prints 8

// An array of characters named all
char[] all;
// Initialize all to hold 4 characters
all = new char[4];
----

[[aBQHizhlfNBFcQwZgzMEghiXNQbMBRjP]]
== Review: Initializing Arrays With Values

[.lead]
//
We can also assign values to an array when it is initialized:

[source,java]
----
// An array of the 4 integers 1, 2, 5, 10
int[] multiple = { 1, 2, 5, 10 };

// An array of the characters c, s, !
char[] awesome = { 'c', 's', '!' };
----

[[IPHnZDcTAbUPeAKGukqRQUbFNcSMTsTk]]
== 0 Indexing

[.lead]
//
You're computer scientist now. You start counting at zero.

[.s]
//
* An array's _first_ value is `a[0]`
//
* An array's _last_ value is `a[a.length - 1]`

[[gwzZCUcRRQULWoxfcMRaGZTABFwBguwo]]
== ! Bracket Syntax
[.janini]
....
int[] twos = { 1, 2, 4 };
System.out.println(twos[0]);
twos[0] = 2;
System.out.println(twos[0]);
System.out.println(twos[2]);
System.out.println(twos[twos.length - 1])
....

[[bJSoBAsMHJzBxvoiSmZyZnlXhOtEXTvf]]
== Out Of Bounds

[.janini]
....
int[] values = { 1, 2, 4, 8 };
System.out.println(values[4]);
....

[[YagQaxbUBvgniQPDXlnsIVNMgucOudgv]]
== Array Limitations

[.lead]
//
Java arrays are _fixed size_, meaning that we need to know how large they are
during initialization.

[.s]
//
* This can complicate our programs.
//
* (If your NetID is `janedoe2`, now you know why.)
//
* Java has other array-like data structures that are more flexible&mdash;we'll
discuss them later.

[[OSijtUjhvcktoiTwoYydEuPJEHfjwgBc]]
== Made For Each Other

[.lead]
//
Loops and arrays are frequently used together.

This is probably _the_ most common for loop. It iterates over all members of the
array: from 0 to `primes.length - 1`.

[source,java]
----
int[] primes = { 2, 3, 5, 7, 11, 13 };

for (int i = 0; i < primes.length; i++) {
  System.out.println(primes[i]);
}
----

[[aVGgRghxygAxuchrRiBgyQDSaTPgpOCB]]
== Enhanced `for` Loop

[source,java]
----
int[] primes = { 2, 3, 5, 7, 11, 13 };
for (int i = 0; i < primes.length; i++) {
  System.out.println(primes[i]);
}
----

This is so common that Java recently introduced a shortcut for it, the so-called
"enhanced" for loop syntax:

[source,java]
----
int[] primes = { 2, 3, 5, 7, 11, 13 };
for (int prime : primes) {
  System.out.println(prime);
}
----
If you don't care about the index, only the value, this is a useful loop.

[[znWIKWOBOGvxYwKMyEXJWdLFDzarxqHU]]
== ! Practice With Arrays

[.janini]
....
// Print every member of toPrint
char[] toPrint = { 'a', 'b', 'c', 'd' };
....

[[zbHZzdvrISmKiNawIhLBwiFdTZGdaIpC]]
== ! Practice With Arrays

[.janini]
....
// Print every member of toPrint on the same line
char[] toPrint = { 'a', 'b', 'c', 'd' };
....

[[hWXhNNJNFoqysBqjrPZSdBIloVLSecQE]]
== ! Practice With Arrays

[.janini]
....
// Print every member of toPrint backwards
char[] toPrint = { 'a', 'b', 'c', 'd' };
....

[[EvnylzsonIhzCXzjafCcjfRAdHXeKRJF]]
== ! Practice With Arrays

[.janini]
....
// Print only members of toPrint with even indices
char[] toPrint = { 'a', 'b', 'c', 'd', 'e', 'f' };
....

[[gKULlucOdlqQNRPGypVmBjvIFCGJgWdL]]
== ! Practice With Arrays
[.janini]
....
// Sum all members of the array
int[] toSum = { 10, 20, 30, 40, 50 }
....

[[byxqJUFxOoEPqQsBWQiEvdcjAIMyZbKG]]
== What Are Computers Good At?

. [.line-through]#Basic math#
//
. [.line-through]#Simple decision making#
//
. [.line-through]#Doing things over and over again very, very fast#
//
. [.line-through]#And storing data#

Now we understand how to harness our computers innate abilities.
//
But how do we get it to do what we want?

[[pLsAYxUijeDaSSOvrgXIDlcYkerLyrfy]]
== Algorithms

[quote]
____
https://en.wikipedia.org/wiki/Algorithm[Algorithm]:
//
a process or set of rules to be followed in calculations or other
problem-solving operations, especially by a computer.
____

As computer scientists, we implement algorithms by having computers:

[.s]
//
* Perform simple calculations
//
* Store the results
//
* Make simple decisions
//
* Do things over and over again as fast as possible

[[eDPSwXCanmERzKTKIsXTFfRvDUCpxAYp]]
== Algorithm Word Usage

[.lead]
//
Algorithms are not a new idea&mdash;but are heavily associated with a new
technology.

++++
<iframe name="ngram_chart" src="https://books.google.com/ngrams/interactive_chart?year_start=1800&year_end=2008&corpus=15&smoothing=7&case_insensitive=on&content=algorithm&direct_url=t4%3B%2Calgorithm%3B%2Cc0%3B%2Cs0%3B%3Balgorithm%3B%2Cc0%3B%3BAlgorithm%3B%2Cc0%3B%3BALGORITHM%3B%2Cc0" width=600 height=480 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0 scrolling=no></iframe>
++++

[[swWjFcJOdhdrOhilGvMgJZPKmRPUttqw]]
== All Algorithms All the Time

[.lead]
//
For the next few weeks we will focus on implementing simple algorithms.

This will allow us to practice our problem-solving abilities while we learn new
strategies for structuring our programs.

[[CzPWhJlvsKvQOZCTZQJqDrzXnEIQUFnF]]
== Maximum Over An Array

[.lead]
//
Given an array of integers, find the maximum value.

*First, what is our algorithm?*

[.s]
//
. Declare a maximum value&mdash;but what do we initialize it to?
//
. Examine each value in the array
//
. Compare it with the maximum we've seen so far&mdash;but then do what?

[[vpcybztlgRfiltilLJTYmPFMtfqbwlsX]]
== ! Maximum Over An Array
[.janini]
....
// Find the maximum value
int[] toSearch = { 1, 10, 6, 7, 3, 15, 4 };
....

[[DeBkVXtGAHkAKJinIoqPFkMcDhiJATxo]]
== ! Average Of An Array
[.janini]
....
// Compute the average
float[] toAverage = { 0.1, 6.7, 8.9, 10.4, 11.2, 0.9 };
....

[[icoJyaqDTsjCkVXNYOlHmREZfZutimGi]]
== Consecutive Identical Values

[.lead]
//
Given an array of chars, find all cases where consecutive elements are the same.

*First, what is our algorithm?*

[.s]
//
. Examine each value in the array
//
. Compare it with the next value&mdash;but how do we get at that?
//
. Print it out if they are the same

[[dkTKDbXZawhJBpCJFbkSOLpFzHmlSCFB]]
[.oneword]
== Next Time: Functions

[[vlEtbFmkVACgCiKhytEjVITurymLpzCi]]
== !MP0 Progress

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="embed-responsive-item" src="https://cs125.cs.illinois.edu/grades"></iframe>
</div>
++++

[[LizCJIzqnCfpILsSbWQUMPNYGXNwUpQv]]
== Announcements

* Quiz 1 start today in the CBTF. It covers variables, conditionals, and loops.
//
* The third set of Turing's Craft exercises (TC 2) are due *Sunday* by midnight.
//
* link:/MP/0/[MP0] is due today!
//
https://cs125.cs.illinois.edu/info/resources/#hours[Office hours]
//
until 5PM today. See announcement for rooms after 1PM.
//
* Consider signing up for
//
http://cs196.cs.illinois.edu/[CS 196]
//
if you want to learn Python and have a lot of fun!
//
They have a great and large group of staff this semester.

// vim: ts=2:sw=2:et
