---
title: Arrays and Algorithms
date: 2020-01-31
description:
  Continuation of arrays and introduction and practice with simple algorithms.
youtube: https://youtu.be/yuusSpTfUuY
---
:imagesdir: /slides/images
:!sectids:

[[xwFAetEkwPYLqsDgwxkMoByfLxrCpBoS]]
== !

[.janini]
--
++++
<div class="message">Arrays and Algorithms</div>
++++
....
int[] numbers = {1, 2, 5};
for (int number : numbers) {
  System.out.println(number);
}
....
--

[[sZSgKWqBudTJujJbOdxqeQdqvWigxelT]]
== Review: Arrays

[.lead]
//
A Java array represents a series of zero or more values of the _same type_.

[.s]
//
* Arrays are our first example of a *data structure*.
//
* Arrays put values in order, one after another.
//
* Values in an array also have an _index_, their position in the array.

[[LmwXyHhUNCVzlkFXeZUaUAoxLFWChLjo]]
== Review: Declaring Arrays

[.lead]
//
Just like other variables, arrays have a _name_ and _type_.

But when we declare them we use brackets to declare an array instead of a single
value.

[source,java]
----
// A single integer named single
int integer;
// An array of integers named multiple
int[] multiple;

// A single character named one
char one;
// An array of characters named all
char[] all;
----

[[CabqmfPgmeNhrQvbvZrjxGSbovqlKpFV]]
== Review: Initializing Arrays

When it is declared an array is empty.
//
To use it we have to tell Java how many _elements_ it has.

*The size cannot be changed once the array is initialized.*
//
All arrays have a `.length` property that we can use to get their size.

[source,java]
----
// An array of 8 integers named multiple
int[] multiple = new int[8];
System.out.println(multiple.length); // Prints 8

// An array of characters named all
char[] all;
// Initialize all to hold 4 characters
all = new char[4];
----

[[aBQHizhlfNBFcQwZgzMEghiXNQbMBRjP]]
== Review: Initializing Arrays With Values

[.lead]
//
We can also assign values to an array when it is initialized:

[source,java]
----
// An array of the 4 integers 1, 2, 5, 10
int[] multiple = {1, 2, 5, 10};

// An array of the characters c, s, !
char[] awesome = {'c', 's', '!'};
----

[[IPHnZDcTAbUPeAKGukqRQUbFNcSMTsTk]]
== 0 Indexing

[.lead]
//
You're computer scientist now. You start counting at zero.

[.s]
//
* An array's _first_ value is `a[0]`
//
* An array's _last_ value is `a[a.length - 1]`

[[gwzZCUcRRQULWoxfcMRaGZTABFwBguwo]]
== ! Bracket Syntax

[.janini]
....
int[] twos = {1, 2, 4};
System.out.println(twos[0]);
twos[0] = 2;
System.out.println(twos[0]);
System.out.println(twos[2]);
System.out.println(twos[twos.length - 1]);
....

[[bJSoBAsMHJzBxvoiSmZyZnlXhOtEXTvf]]
== ! Out Of Bounds

[.janini]
....
int[] values = {1, 2, 4, 8};
System.out.println(values[4]);
....

[[YagQaxbUBvgniQPDXlnsIVNMgucOudgv]]
== Array Limitations

[.lead]
//
Java arrays are _fixed size_, meaning that we need to know how large they are
during initialization.

[.s]
//
* This can complicate our programs.
//
* (If your NetID is `janedoe2`, now you know why.)
//
* Java has other array-like data structures that are more flexible&mdash;we'll
discuss them later.

[[OSijtUjhvcktoiTwoYydEuPJEHfjwgBc]]
== Made For Each Other

[.lead]
//
Loops and arrays are frequently used together.

This is probably _the_ most common for loop. It iterates over all members of the
array: from 0 to `primes.length - 1`.

[source,java]
----
int[] primes = {2, 3, 5, 7, 11, 13};

for (int i = 0; i < primes.length; i++) {
  System.out.println(primes[i]);
}
----

[[ybLhqjistDkCNAkTrdsqlOrkmzRlQpOp]]
== Controlling Loop Execution

[.lead]
//
There are two important _control statements_ that we can use with loops:

* `break`: immediately exit the loop. Maybe I found data I was looking for?
//
* `continue`: return to the top of the loop, perform the update, and continue if
the condition is still true. Maybe this piece of data isn't interesting?

[[HKgDlCjYPlNepNOrEnTNoEsbVhhFnUKx]]
== ! `break` Example

[.janini]
....
int search = 8;
for (int i = 0; i < 64; i++) {
  if (i == search) {
    System.out.println("Found");
    break;
  }
  System.out.println("Not found...");
}
....

[[VEAvuqSKWDzdowmSNwpZTiuKbMuZXlUh]]
== `break`

[.lead]
//
`break` is commonly used when you are looking for something using a loop and
want to exit when you find it.

(We'll talk about arrays in a few slides and this will make more sense.)

[[yeJMpUzucBnvisKCBFeQuPFAKyJDDhxS]]
== ! `continue` Example

[.janini]
....
for (int i = 0; i < 4; i++) {
  System.out.println("Going... " + i);
  if (i >= 2) {
    continue;
  }
  System.out.println("Here");
}
....

[[avEsVhcoWVOBCcUOxOCEmUPdSBkghzNK]]
== `continue`

[.lead]
//
`continue` is commonly used when you only want to execute the loop for some
values.

What would be another way to accomplish this?

[[lYWJpDhDlaBAhRNoglwuiNEqjZnTvPfj]]
== ! `continue` As `if`

[.janini]
....
for (int i = 0; i < 4; i++) {
  System.out.println("Going... " + i);
  if (i < 2) {
    System.out.println("Here");
  }
}
....

[[aVGgRghxygAxuchrRiBgyQDSaTPgpOCB]]
== Enhanced `for` Loop

[source,java]
----
int[] primes = {2, 3, 5, 7, 11, 13};
for (int i = 0; i < primes.length; i++) {
  System.out.println(primes[i]);
}
----

[.s]
//
--
//
This is so common that Java has a shortcut for it, the
enhanced `for` loop:

[source,java]
----
int[] primes = {2, 3, 5, 7, 11, 13};
for (int prime : primes) {
  System.out.println(prime);
}
----
If you don't care about the index, only the value, this is a useful loop.
//
--

[[dLeZjsKeXwWFeLsTcrdiaQURrLLdtcfg]]
[.oneword]
//
== Questions About Arrays or Loops?

[[rUxiOMZokgZRttcmHGuJJdxNHJcmnaKN]]
== You Can Do This

[.s]
//
* Fall 2018 Q1: [.s]#94%#
//
* Spring 2019 Q1: [.s]#92%#
//
* Fall 2019 Q1: [.s]#92%#
//
* Spring 2020 Q1: [.s]#90%#

[[znWIKWOBOGvxYwKMyEXJWdLFDzarxqHU]]
== ! Practice With Arrays

[.janini]
....
// Print every member of toPrint
char[] toPrint = {'a', 'b', 'c', 'd'};
....

[[zbHZzdvrISmKiNawIhLBwiFdTZGdaIpC]]
== ! Practice With Arrays

[.janini]
....
// Print every member of toPrint on the same line
char[] toPrint = {'a', 'b', 'c', 'd'};
....

[[hWXhNNJNFoqysBqjrPZSdBIloVLSecQE]]
== ! Practice With Arrays

[.janini]
....
// Print every member of toPrint backwards
char[] toPrint = {'a', 'b', 'c', 'd'};
....

[[EvnylzsonIhzCXzjafCcjfRAdHXeKRJF]]
== ! Practice With Arrays

[.janini]
....
// Print only members of toPrint with even indices
char[] toPrint = {'a', 'b', 'c', 'd', 'e', 'f'};
....

[[gKULlucOdlqQNRPGypVmBjvIFCGJgWdL]]
== ! Practice With Arrays
[.janini]
....
// Sum all members of the array
int[] toSum = {10, 20, 30, 40, 50};
....

[[byxqJUFxOoEPqQsBWQiEvdcjAIMyZbKG]]
== What Are Computers Good At?

. [.line-through]#Basic math#
//
. [.line-through]#Simple decision making#
//
. [.line-through]#Doing things over and over again very, very fast#
//
. [.line-through]#And storing data#

Now we understand how to harness our computers innate abilities.
//
But how do we get it to do what we want?

[[pLsAYxUijeDaSSOvrgXIDlcYkerLyrfy]]
== Algorithms

[quote]
____
https://en.wikipedia.org/wiki/Algorithm[Algorithm]:
//
a process or set of rules to be followed in calculations or other
problem-solving operations, especially by a computer.
____

As computer scientists, we implement algorithms by having computers:

[.s]
//
* Perform simple calculations
//
* Store the results
//
* Make simple decisions
//
* Do things over and over again as fast as possible

[[eDPSwXCanmERzKTKIsXTFfRvDUCpxAYp]]
== Algorithm Word Usage

[.lead]
//
Algorithms are not a new idea&mdash;but are heavily associated with a new
technology.

++++
<iframe name="ngram_chart" src="https://books.google.com/ngrams/interactive_chart?year_start=1800&year_end=2008&corpus=15&smoothing=7&case_insensitive=on&content=algorithm&direct_url=t4%3B%2Calgorithm%3B%2Cc0%3B%2Cs0%3B%3Balgorithm%3B%2Cc0%3B%3BAlgorithm%3B%2Cc0%3B%3BALGORITHM%3B%2Cc0" width=600 height=480 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0 scrolling=no></iframe>
++++

[[swWjFcJOdhdrOhilGvMgJZPKmRPUttqw]]
== All Algorithms All the Time

[.lead]
//
For the next few weeks we will focus on implementing simple algorithms.

This will allow us to practice our problem-solving abilities while we learn new
strategies for structuring our programs.

[[dRbFybuEWtffPzekwnZgEkeHaguzyyHn]]
== Maximum of Three Values

[.lead]
//
Given three integers, find the maximum value.

*First, what is our algorithm?*

[.s]
//
. Determine if `first` is the largest&mdash;if it is, we're done
//
. Otherwise we need to consider `second` and `third`...

[[LfiRLGCeqXsplYhiBeuSSAuXlVNfANSy]]
== !Largest of Three

[.janini]
....
int first = 10;
int second = 15;
int third = 4;
....

[[mPqAMdgKRROySzsLyOlfnRzklZclPkKy]]
== MP0

[.lead]
//
MP0 will be released Monday.
//
It's the first checkpoint of our semester-long Android machine _project_.

[.s.small]
//
* Some of you are going to sit down Monday with MP0 and _freak out_.
//
* Please try to stay calm! Our MPs can be intimating at first, but with time and
help from the course staff you'll get your head around it.
//
* You'll have a chance to get started on MP0 in lab next week, and we encourage
you to come to office hours as well.
//
* MP0 _does_ toss you into the deep end of Android app development.
//
*This is intentional.*
//
Working your way through large unfamiliar pieces of code is as much an important
computer science skill as solving small problems like our homework.

[[STnmdhpnnhtWYaWfYjXXvddAtUfLiigM]]
== Split Deadline Discussion

[.lead]
//
Half you have Sunday deadlines&mdash;the other half have Monday deadlines.
//
Let's talk about why.

[[dkTKDbXZawhJBpCJFbkSOLpFzHmlSCFB]]
[.oneword]
== Next Time: Functions

[[yTcqcbhuTVUyfvIeFljgLPwifqfgMdtK]]
== Announcements

[.small.spelling_exception]
//
* Homework continues today _and_ this weekend.
//
* We have link:/info/resources/#hours[office hours] today from 12&ndash;4PM.
//
* Everything is on link:/info/syllabus#calendar[the calendar].
//
* Please fill out the https://forms.gle/WDf8bniubhSeoKM77[initial student survey].
//
1% extra credit for anyone who does by *Sunday 2/2/2020.*

// vim: ts=2:sw=2:et
