---
title: Conditional Expressions
date: 2018-01-22
description:
  Introduction to comparisons and conditional expressions, the basis for
  programmatic decision making.
echo: https://goo.gl/CrM9Ld
---
:imagesdir: /learn/images
:!sectids:

[[kHoCSCXzvsIAFbIrBWoBZmaPCNVOOCdM]]
== !

[role='janini']
--
++++
<div class="message">Comparisons and conditional expressions</div>
++++
....
boolean todayIsMonday = true;
int currentTime = 8;
if (todayIsMonday && currentTime < 12) {
  System.out.println("Let's discuss conditionals");
} else {
  System.out.println("Can we talk about something else");
}
....
--

[[VAzyFFoDxschWNuTZMMizdJSZDyolcwn]]
== CS 196

* https://goo.gl/DF349E[8 AM]
//
* https://goo.gl/QLFY7s[10 AM]

[[POtIiKbRQNuZuYwSwdCgAeuyZhpQbmsv]]
== What Are Computers Good At?

. [.line-through]#Basic math#
//
. *Simple decision making*
//
. Doing things over and over again very, very fast
//
. [.line-through]#And storing data#

[[bAuWhpDPmVGgDaepoowJukwlfVQsJPdR]]
== Comparisons

[.lead]
//
Java also allows me to compare different variables: either against literal
values, or against other variables.

This is basis for _simple decision making_.

[[EuddnTejTlEZaIAttmJUDwqxLAWdYNQd]]
== Simple Comparisons

[role='janini']
....
// Let's try out ==, !=, <, <=, >, and >=
int tester = 10;
// This is equality
System.out.println(tester == 10);
....

[[kfjlldprRQUOtUaTuYveJPZEbFCgHlCU]]
== A Common Mistake

[.lead]
//
* `a = 10` means *set a to 10*
//
* `a == 10` means *test if a is equal to 10*

[[uOanIxfYhyBAYDDSDumbwovkhBiwNNcg]]
== Don't Get Confused

[role='janini']
....
int tester = 10;
// This is equality
System.out.println(tester == 10);
// This is not
System.out.println(tester = 5);
System.out.println(tester);
....

[[NZRZqEBsBPejsjEIMEUExRtpUZwnPHvN]]
== Comparisons Against Variables

[role='janini']
....
// Let's try out ==, !=, <, <=, >, and >=
int first = 10;
int second = 20;
System.out.println(first > first);
....

[[JXtQIUEitmTgnNBVMLHYYnkyMeHylXzT]]
== More Complex Comparisons

[role='janini']
....
// Let's try out ==, !=, <, <=, >, and >=
int first = 10;
int second = 20;
System.out.println(first + second == 30);
System.out.println(first - second <= 10);
....

[[GieGtJaHsXZBBBMvZqGAdPacxybqOQxP]]
[.oneword]
== Questions About Simple Comparisons?

[[BueiLwuNKbnJPZVcrKBddwHYcdYQyvjx]]
== Compound Comparisons

[.lead]
//
We can combine multiple comparisons together using logical and (`&&`) and or
(`||`) operators.

[[vDROZOQyBuCsHvUlGCATsKriCrZxCmeK]]
== ! Combining Comparisons

[role='janini']
....
int first = 10;
System.out.println(first > 5 && first < 10);
System.out.println(first < 10 && first > 5);
System.out.println(first > 10 || first > 5);
System.out.println(first > 10 || false);
....

[[FBXXgCFgySnrwZHYfSoUHPKWaxwklwjZ]]
== Evaluation Order

[.lead]
//
Conditionals are always evaluated from left to right, and evaluation stops as
soon as the result is known.

[[kTKjdTjMotZBlcgraocBlOSIGadWncvF]]
== Comparisons Enable Decisions

[role='janini']
....
// Comparisons enable decisions
int first = 10;
if (first > 20) {
  System.out.println("First is greater than 20");
} else {
  System.out.println("First is not greater than 20");
}
....

[[ZVszIucHlwfpNThvCPzvAuGXDQoXGDJm]]
== `if-else`

[.lead]
//
`if-else` statements are the building block for programmatic decision making:

[.s]
//
* _if_ something is true, do one thing;
//
* _otherwise_, if something else is true, do some other thing;
//
* _otherwise_, if something else is true, do some other thing;
//
* etc.

[[mKZSZKIqiozOhiBMXfrUaxnAYmcEWiNU]]
== `if-elseif-elseif-else`

[.lead]
`if` statements can have multiple clauses:

[source,java]
----
if (firstThing) {
  // do one thing
} else if (secondThing) {
  // do another thing
} else if (thirdThing) {
  // another thing
} else {
  // run if firstThing, secondThing, and thirdThing are all false
}
----

`else` statements are run if no if statement matches.

[[CDpGeuKlxKgJwOfLsqWUIfCazJSauLSt]]
== ! Only One Statement Runs

[role='janini']
....
// Only the first matching branch of if is executed
int comparison = 10;
if (comparison > 5) {
  System.out.println("I'll be executed");
} else if (comparison > 3) {
  System.out.println("I won't be executed");
} else {
  System.out.println("I definitely won't be executed");
}
....

[[ulsvDseRWSMaJGiZXigRkKHBdYgQEGwm]]
== Remember: Only One Statement Runs

[.lead]
//
*In any if statement, only one statement is executed.**


[[sCTwbrbupLHdZwRvBbUQlfGFoutbJTfB]]
== Somewhat Useful Example

[role='janini']
....
// Create an int called numSuperBowls, and then add 1 to it
// if patriotsWinAgain is true
....

[[fcnIiRcbbDBZyWPgBSCPEDBMiSUCxLEy]]
== Nested Conditionals

[.lead]
`if` statements can be nested inside other `if` statements

[source,java]
----
if (testMe) {
  if (testMeAgain) {
    // I am well tested
  } else {
    // I'm only moderated well-tested
  }
} else {
  // You need to write better tests
}
----

[[ySgvSxVBLXrmJCUTffzlhLYXqdWCKBeX]]
== !Practice With Nested Conditionals
[role='janini']
....
// What should we decide today?
....

[[PgMLuXcxwdrkzLNqnpFFWLNAsIHpiYTB]]
== Variable Scope

[.lead]
//
`if` statements provide our first example of a _block_ of code.

[source,java]
----
if (...) {
  // I'm a block of code
}
----

[.s]
//
* Blocks are enclosed by braces and can have multiple statements
//
* Variables declared _inside_ a block are not visible _outside_ it...
//
* But variables declared outside (and prior to) a block _are_ visible _inside_ it

[[ECKCAOoavGvvNXrOtQqqIZMxNKnbmBAj]]
== !Practice With Scope
[role='janini']
....
int outside = 5;
if (true) {
  int inside = 10;
  System.out.println(outside);
}
System.out.println(inside);
....

[[uyjfRCHsbnKWGDOzAwWeAPodEDLQbWjP]]
== Indentation Hints

[.lead]
//
Assuming you are indenting your code properly, a general rule of thumb about
scope:

[.s]
//
* You *can* access variables "to the left"
//
* You *cannot* access variables "to the right"

(Where directions are defined relative to the start of the line of code you are
writing.)

[[eUWkVtCUwaoLWfYANZKlTLvlRthqeEIz]]
== !Practice With Scope
[role='janini']
....
int outside = 5;
if (true) {
  int inside = 10;
  // outside is to my left, so OK
  System.out.println(outside);
}
// inside is to my right, so bad
System.out.println(inside);
....

[[DlfIqTyTBFGgkmhAEFlvVSLDzjPmbVxt]]
[.oneword]
== Next Time: Algorithms and Loops

[[SJLEFfbtRDIeALFWHknlBYYTuSLYfTOo]]
== !MP0 Progress

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="embed-responsive-item" src="https://cs125.cs.illinois.edu/grades"></iframe>
</div>
++++

[[bAMIDJtTOruAKgjPWiRdBcIJIwClvpMV]]
== Announcements

* The first set of Turing's Craft exercises are due tomorrow by midnight.
//
* link:/info/resources#emp[CS 199 EMP] and link:/info/resources#cs196[CS 196]
(the honors section) open for registration today at noon.
//
* link:/MP/0/[MP0] is out and due Friday! At this point you should be able to
finish `Quizzer`.
//
https://cs125.cs.illinois.edu/info/resources/#hours[Office hours]
//
until 7PM today.
//
* Please fill out the
//
https://goo.gl/forms/7I6PEhK7C4t6iX1k1[intro survey]!
//
1% extra credit for anyone who does by *today at noon*.
