---
title: Constructors and Visibility
date: 2020-02-19
description:
  A continued discussion of Java objects, introducing constructors and
  visibility.
---

[[TzChbqJCgkFihBhsGKSsxQCgNgfcontb]]
== !

[.janini.compiler.small]
--
++++
<div class="message">Constructors and Visibility</div>
++++
....
public class Course {
  private String name;
  public Course(String setName) {
    name = setName;
  }
  public void printName() {
    System.out.println(name);
  }
}
public class Example {
  public static void main(String[] unused) {
    Course cs125 = new Course("CS 125");
    cs125.printName();
  }
}
....
--

[[eYLaJspbncqffWNCyGeLCjhTXzwfKnYy]]
== Review: Class Declaration

[source,java]
----
class Person {
  // Variable declarations
  String name;
  // Declarations can include initialization
  int age = 0;

  // Any code has to go inside functions
  void printName() {
    System.out.println(name);
  }
  void birthday() {
    age++;
  }
}
----

[[cBvAQSUjOeMftzBoERafEeauVrkncSqx]]
== Review: `this`

[source,java]
----
class Dimensions {
  int width;
  int height;

  int area() {
    return this.width * this.height;
  }
}
----

[.lead]
//
Instance methods _can_ refer to _their_ instance variables using the `this`
keyword.

`this` refers to the instance that is executing the method.

[[XfjzwCcMeEaGJnQMGVKBGWTeoiIMHnXi]]
== When to Use `this`

[source,java]
----
class Dimensions {
  int width;
  int height;

  int area() {
    return width * height;
  }
}
----

[.lead]
//
This also works, and you might consider it a bit cleaner.

[[GQkSDDzyEwCVgBrPzzUIFXVBlGQVXknp]]
== New Examples

[.janini.compiler.small]
....
// Just a warning that some examples now work differently
// When run the main method of the Example class below is executed
public class Example {
  public static void main(String[] unused) {
    System.out.println("Hello, world!");
  }
}
....

[[mdNrgDBgmSLlrcmSFhPisvzgfeddDOdg]]
== ! When to Use `this`

[.janini.compiler.small]
....
public class Dimensions {
  public int width;
  public int height;

  public int area() {
    return width * height;
  }
}
public class Example {
  public static void main(String[] unused) {
    Dimensions example = new Dimensions();
    example.width = 10;
    example.height = 20;
    System.out.println(example.area());
  }
}
....

[[ajeIIqKVvQLniMORsJidtAJimqtKNpee]]
== Constructors

[source,java,role='small']
----
class Course {
  String name;
  // This is a constructor.
  Course(String setName) {
    name = setName;
  }
}
----

[.lead]
//
When we create a `new` object, a special method called a _constructor_ is run.

[.s]
//
* Constructors are _only_ run when the class is created. They can't be called
again.

[[buNTLZGlGhEWCuYdcziosJgrosQvbMTz]]
== Constructors: Syntax

[source,java,role='small']
----
public class Course {
  String name;
  // The constructor must be named Course
  // It's not declared to return anything...
  Course(String setName) {
    name = setName;
    // And doesn't explicitly return anything, but always returns a new Course
  }
}
----

[.s.small]
//
* Constructors can and do perform class-specific initialization.
//
* Constructors always shared the same same name as the class they create:
`Course` in the example above.
//
* Constructors don't declare or explicitly return anything&mdash;but always
return a new instance of their class.

[[FTdOVkxrUPztoaVrEEgbYkZrQlZTFKrq]]
== Constructors: Overloading

[source,java,role='small']
----
public class Course {
  String name;
  // This constructor sets the name
  Course(String setName) {
    name = setName;
  }
  // This constructor initializes the name to a blank string
  Course() {
    name = "";
  }
}
----

[.lead]
//
Like other functions, constructors can be overloaded.

[[DnfEfnflyEWiTptmnquiRqcrXeiBXMon]]
== Constructors: `this`

[source,java,role='small']
----
public class Course {
  String name;
  // This constructor sets the name
  Course(String setName) {
    name = setName;
  }
  // This constructor initializes the name to a blank string
  // by calling the other constructor
  Course() {
    this("");
  }
}
----

[.lead]
//
Constructors can use `this()` to call other constructors.

[[dNRMfdwEtepowaaciBuymTvAxgvQLMHB]]
== The Default Constructor

[source,java,role='small']
----
class Course {
  String name;
}
// This is the same as
class Course {
  String name;
  Course() {
  }
}
----

[.lead]
//
If you don't define a constructor, it's equivalent of an empty constructor that
doesn't set any fields.

[[RjGBTtWoaOclLyIPbQKbwFJrRvndpSPP]]
== Constructors Can't Fail

[source,java,role='small']
----
class Course {
  String name;
  Course(String setName) {
    // What do I do if the name is invalid?
    name = setName;
  }
}
----

[.lead.small]
//
Constructors _must_ return a new instance of their class.

[.s]
//
* So we don't have a good way to reject invalid inputs in constructors&mdash;yet.
//
* We'll come back to this when we talk about static methods...
//
* and when we discuss exceptions.

[[xerFaeehMgBcfwprdjQAKZoTzUWVPATK]]
== ! Constructors: Example

[.janini.compiler.small]
....
public class Person {
}
public class Example {
  public static void main(String[] unused) {
    Person you = new Person();
  }
}
....

[[JlVmEinaPtCRqpZOnlTolvogFyPHVKXB]]
[.oneword]
== Questions about Constructors?

[[lgQfefprNzbjsIHmmBdDzxInRNdQMAlK]]
== Announcements

* Congrats to those that have taken the midterm! If you haven't yet, good luck.
//
* My office hours as usual today from 4&ndash;5PM in Siebel 2227.
//
* We have a
//
link:/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!

// vim: ts=2:sw=2:et
