---
title: More Practice with Recursion
date: 2018-03-26
description:
  More practice with recursion, including on non-tree structures.
---

[[jrRQIGHYmPhPUoMLkIWzHUsgoPNdbBOn]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">More Practice with Recursion</div>
++++
....
....
--

[[OzjXTgMoWVzPCuhDMmFiABSwulDOvcZT]]
== Exam Announcement

[.lead]
//
**We will no longer hold a three-hour seated exam in Foellinger Auditorium on
5/11/2018.**

Instead, we will hold a rolling exam in the CBTF from Sunday 5/6/2018&ndash;Wednesday
5/9/2018.

* The TAs footnote:[Who have to grade the exam...] and I have decided together
that a computerized exam is a better approach. It will be much fairer and both
faster and easier to grade.
//
* The exam will consist of a mixture of (autograded) programming questions,
(autograded) multiple-choice questions, and TA-graded free answer questions.
//
* If you changed your travel plans to stay for the Friday exam, I apologize.

[[udWeLekzKVnByaRnHrpSzgDrSKYkmeuT]]
== CBTF Programming Questions

[.lead]
//
The CBTF final exam _will include_ programming questions.

[.s]
//
* The editing interface will be familiar to you from the lecture examples.
//
* The grading interface will be familiar to you from the MPs.
//
* We will be rolling this out as soon as possible. At minimum you'll have a few
chances to practice on the last few quizzes leading up to the exam.

[[ozTEehqBqloFcjlwPAYzKAswtrxjuDlr]]
== Announcements

* The link:/MP/5/[MP5] deadline is today at 5PM.
//
* We've added an
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
