---
title: Exceptions and Errors
date: 2018-04-23
description:
  Discussion of Java errors and error handling.
---
:imagesdir: /learn/images

[[TtJisSLNUcaxKLyWZHfTUBNaEvfKPpGU]]
== !

[.janini.smaller]
--
++++
<div class="message">Exceptions and Errors</div>
++++
....
static void throwError() throws Exception {
  throw new Exception("Exceptions and Errors");
}

try {
  throwError();
} catch (Exception e) {
  System.out.println(e);
}
....
--

[[PuyiTWBrGWwPIAOMQXiVMNbgGWAukMvW]]
== !Warmup Problem

[.janini.compiler.smallest]
....
public class Item {
  public Object key;
  public Object value;
  public Item next;
  Item(Object setKey, Object setValue, Item setNext) {
    this.key = setKey;
    this.value = setValue;
    this.next = setNext;
  }
}
public class HashMap {
  private Item[] items = new Item[16];
  public int keyCount = 0;
  private int hash(Object key) {
    return key.hashCode() % 16;
  }
  public void put(Object key, Object value) {
    int bucket = hash(key);
    Item current = items[bucket];
    for (; current != null; current = current.next) {
      if (current.key.equals(key)) {
        current.value = value;
        return;
      }
    }
    Item newItem = new Item(key, value, items[bucket]);
    items[bucket] = newItem;
    keyCount++;
    return;
  }
  public Object get(Object key) {
    int bucket = hash(key);
    Item current = items[bucket];
    for (; current != null; current = current.next) {
      if (current.key.equals(key)) {
        return current.value;
      }
    }
    return null;
  }
  // Complete the allKeys function below
  public Object[] allKeys() {
    return null;
  }
}
public class Example {
  public static void main(String[] unused) {
    HashMap ourHashMap = new HashMap();
    ourHashMap.put("test", "me");
    ourHashMap.put("test", "another");
    System.out.println(ourHashMap.allKeys());
  }
}
....

[[cfNxpyuNplVjZOGkrvUuWTtPHBfHbdhI]]
[.oneword]
//
== Exceptions
//
Because things go wrong...

[[OzQfgiJWbHOderTtUClGAngECYmlpaNU]]
== Why Exceptions?

[.lead]
//
What do you do when you can't go on?

[source,java]
----
class StringStorage {
  /**
   * Create a new object to store strings.
   *
   * @param storageSize the size of the StringStorage,
   *        must be positive
   */
  public StringStorage(final int storageSize) {
    if (storageSize <= 0) {
      // what now?
    }
  }
}
----

[[wkaxBLzVUsfkoRJnKKGGsmhKRjfPqcfS]]
== Why Exceptions?

[.lead]
//
What do you do when you can't go on?

[source,java]
----
/**
 * Read an integer from a passed string
 * and then do something with it.
 */
static int readInteger(final String intAsString) {
  int value = Integer.parseInt(intAsString);
  // But what if intAsString was "foo"?
}
----

[[GnIneJYyrmknSwxawxFLrkfgLTkrkCvS]]
== `try-catch`

[.lead]
//
Java's exception handling control structure is called a `try-catch` block:

[source,java]
----
try {
  // Do something that could cause an exception
} catch (Exception e) {
  // Handle all exceptions that inherit from Exception
}
// Go on if things proceeded normally
----

[[FCwSppBUbsdntJPLYVWUmKhTjmwczUgt]]
== `try-catch` with Multiple `catch`

[.lead]
//
Sometimes you want to handle errors differently depending on what caused them:

[source,java]
----
try {
  // Do something that could cause an exception
} catch (NullPointerException e) {
  // Handle null pointer exceptions
} catch (ArrayIndexOutOfBoundsException e) {
  // Handle array out of bounds exceptions
}
// Go on if things proceeded normally
----

[[qBUvchHqwhTYgXirWtbHjrdzfSozLyed]]
== `try-catch` with Multiple `catch`

[.lead]
//
You can also merge multiple exception types together like this:

[source,java,role='smaller']
----
try {
  // Do something that could cause an exception
} catch (NullPointerException|IllegalArgumentException e) {
  // Handle null pointer and illegal argument exceptions
}
// Go on if things proceeded normally
----

[[kwZARxJnTlrBuFmKcUMufYbTUVEQzwNm]]
== ! `try-catch` Example

[.janini.smaller]
....
import java.util.Random;

static int throwRandomError() throws Exception {
  Random random = new Random();
  if (random.nextBoolean()) {
    Object it = null;
    return it.hashCode();
  } else {
    int[] array = new int[] {};
    return array[4];
  }
}

// Handle both errors thrown by the function above
throwRandomError();
....

[[jxVCByewgzqbjYjfWzfiuRCWBfuPrfYs]]
== Exceptional Control Flow

[.lead]
//
When an error is thrown control flow _immediately_ jumps to an
enclosing `catch` statement, if one exists.

The `catch` may be in the caller or multiple levels up.

[source,java,role='smallest']
----
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
----

[[YAUdXnxjOpdzBcNRJLgXVKzarNSWNagr]]
== ! `try-catch` with Functions Example


[.janini.smaller]
....
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
foo4();
....


[[YVOVNHgIXQcGbotRhnTLjlRxlloFSLng]]
== Types of Exceptions

[.lead]
//
Java exceptions are broken into three distinct categories:

[.s]
//
* *Checked exceptions*: these are for places where you _know_ something might go
wrong and it's out of your control
//
* *Unchecked exceptions* (or runtime errors): these are usually cased by
something dumb that you (the programmer) did wrong
//
* *Errors*: these are reserved for serious system problems that are probably not
recoverable

[[AglZaxPbaQdMAUyURkopiDaKCMrueDWb]]
== Checked Exceptions: Examples

[.lead]
//
Checked exceptions are for cases where an failure *external to your program* can
cause an exception to occur

[.s]
//
* https://docs.oracle.com/javase/7/docs/api/java/io/FileNotFoundException.html[`FileNotFoundException`]:
//
your program tried to open a file that you expected to exist but it did not
//
* https://docs.oracle.com/javase/7/docs/api/java/net/URISyntaxException.html[`URISyntaxException`]:
//
your program tried to parse a universal resource identifier (URI) but it was
invalid

[[WCoZXcWMWrPzctmXYbUERwsqWmxbhsGH]]
== ! Example Checked Exception

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/net/URISyntaxException.html"></iframe>
</div>
++++

[[JvELdFMCwSnXRmghdAhhglEfbojSOHJI]]
== Checked Exceptions: Handling

[.lead]
//
If you use a function that may generate a checked exception, you must either
wrap it in a `try-catch` block or declare that you may throw it.

[source,role='s smaller']
----
static URI createURI(final String input) {
  // Example where we handle URISyntaxExceptions
  try {
    return new URI(input);
  } catch (URISyntaxException e) {
    System.out.println(input + " is not a valid URI");
  }
}
----

[source,role='s smaller mt-2']
----
// Example where we throw URISyntaxExceptions
static URI createURI(final String input) throws URISyntaxException {
  return new URI(input);
}
----

[[lTSokCKduCxcHhdvMeDXSCDpGcryAMul]]
== ! Checked Exceptions: Handling Example

[.janini.smaller]
....
import java.net.URI;
static URI createURI(final String input) {
  return new URI(input);
}
System.out.println(createURI("https://cs125.cs.illinois.edu/"));
....

[[OfiMUvDfLqHrmsHHbwRRrxkkLLWCItZx]]
== Unchecked Exceptions: Examples

[.lead]
//
Unchecked examples are usually the result of _programmer error_.

You've probably made many of these mistakes by now...

[.s.small]
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/ArrayIndexOutOfBoundsException.html[`ArrayIndexOutOfBoundsException`]:
//
[.s]#you walked off the end of an array#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/NullPointerException.html[`NullPointerException`]:
//
[.s]#you dereferenced a `null` reference#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/ClassCastException.html[`ClassCastException`]:
//
[.s]#you tried to cast something to a subclass of which it is not an instance#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalArgumentException.html[`IllegalArgumentException`]:
//
[.s]#you passed incorrect arguments to a function or constructor#

[[NyzuaYxzzlhLTKVQoOsgHPbtfPQAbbDC]]
== ! Unchecked Exceptions: Examples

[.janini.smaller]
....
import java.util.Arrays;

static void faulter() {
}
try {
  faulter();
} catch (ArrayIndexOutOfBoundsException e) {
  System.out.println("Whoops!");
} catch (NullPointerException e) {
  System.out.println("Oh, no!");
} catch (ClassCastException e) {
  System.out.println("That's too bad...");
} catch (IllegalArgumentException e) {
  System.out.println("Don't do that!");
}
....

[[JeobqXuXzWOKfLNYVANnZhhpASBkdiJz]]
== ! Arrays Again

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html"></iframe>
</div>
++++

[[KXOYoGDTpyttOUMGgFJomhMqvznzGXoE]]
== Unchecked Exceptions: Handling

[.lead]
//
Unlike checked exceptions, you do not need to declare or handle unchecked
exceptions.

However, you _can_ handle them:

[source,java,role='s smaller']
----
try {
  String s = callMyPartnersDodgyCode();
  if (s.length() == 0) {
    return;
  }
} catch (NullPointerException e) {
  return;
}
----

[[kQbOfdZFwWMQsOQmhbBQogCUGHympVWJ]]
== Errors: Examples

[.lead]
//
Java errors indicate serious conditions that are usually not recoverable:

[.s]
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/OutOfMemoryError.html[`OutOfMemoryError`]:
//
Java ran out of memory and is going to crash
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/StackOverflowError.html[`StackOverflowError`]:
//
You recursed too deeply and Java is going to crash
//
* Note that sometimes _these are still your fault_: you used too much memory or
forgot your base case

[[ajpSqxeufhVlXQkgrigFcjuJqXwzCANS]]
== Exception Handling Strategies

[.lead]
//
Here are reasonable strategies for handling each kind of exception:

[.s]
//
* *Errors*: _don't_ try to handle these, just go bye-bye
//
* *Unchecked exceptions*: try to _avoid_ these by improving your code
//
* *Checked exceptions*: try to handle these and have your program
continue running, or exit gracefully...
//
* but don't go on unless you can.

[[RoxnUIFqZCBrBZnusOrpzbLuksmJMpdG]]
== Working with Exceptions

[.lead]
//
Java exceptions are just another kind of Java object&mdash;and they have some
useful features, particularly when debugging:

[.s]
//
* `toString`: like every other Java `Object`, exceptions can be printed
//
* `getMessage`: retrieves just the message associated with this exception
//
* `printStackTrace`: print a _stack trace_ for the error showing what caused it
and what other functions were involved

[[wIAiKctczCEQFknYPSiRbruXLqBIGBMy]]
== !Throwable Documentation

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html"></iframe>
</div>
++++

[[zzlPSnhuaDjSgoGIAkpIjUQZeiuerNQe]]
== !Working with Exceptions Examples

[.janini.smaller]
....
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
foo4();
....

== Rethrowing Exceptions

[.lead]
//
Sometimes you may want to just record what happened but not know what to do with
an error.

In that case you may want to rethrow it out of the catch block:

[source,role='smaller']
----
static URI createURI(final String input) {
  // Example where we handle URISyntaxExceptions
  try {
    return new URI(input);
  } catch (URISyntaxException e) {
    // Log that something went wrong
    Log.e(TAG, input + " is not a valid URI");
    // Rethrow the exception
    throw(e);
  }
}
----

== Throwing Your Own Exceptions

[.lead]
//
So how do we handle a case like this?

[source,java]
----
class StringStorage {
  /**
   * Create a new object to store strings.
   *
   * @param storageSize the size of the StringStorage,
   *        must be positive
   */
  public StringStorage(final int storageSize) {
    if (storageSize <= 0) {
      // what now?
    }
  }
}
----

== ! Throwing Your Own Exceptions

[.janini.smaller.compiler]
....
class StringStorage {
  /**
   * Create a new object to store strings.
   *
   * @param storageSize the size of the StringStorage,
   *        must be positive
   */
  public StringStorage(final int storageSize) {
    if (storageSize <= 0) {
      // what now?
    }
  }
}
class Example {
  public static void main(final String[] unused) {
    StringStorage stringStorage = new StringStorage(-1);
  }
}
....

[[cOoeHZUWDypFrxsatLfQZXqrMnvSBIWc]]
== Final Project Reminders

[[dzObIAUNjSBldZMkzRYoEOfeXeEoLEwG]]
== ICES Plan and Incentives

[[oViMXZJHRuOiNPZSUiHsapzzDrHNNTpN]]
== Announcements

* link:/MP/7/[MP7 (the final project)] is out.
//
Please get started!
//
* The
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
remains available on the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
