---
title: Functions and Algorithms
date: 2018-01-29
description:
  Continued introduction to functions and practice using algorithms to
  solve problems.
spelling_exceptions:
  - GCD
draft: true
---

[[HiatdhpaUkUnyCVrqTZFbPvmyUaqWSVN]]
== Consecutive Identical Values

[.lead]
//
Given an array of chars, find all cases where consecutive elements are the same.

*First, what is our algorithm?*

[.s]
//
. Examine each value in the array
//
. Compare it with the next value&mdash;but how do we get at that?
//
. Print it out if they are the same

[[nbSIYahKjyKuYqGenoNlETYtzzvVjQpO]]
== ! Consecutive Identical Values

[.janini.small]
....
// Print consecutive identical values
char[] toSearch = { 'a', 'b', 'b', 'c', 'e', 'f', 'f' };
....

[[BzRRFIMstyqbRXhqEywqvIoQJUgYebbD]]
== Greatest Common Denominator

[quote]
//
____
//
In mathematics, the
//
https://en.wikipedia.org/wiki/Greatest_common_divisor[greatest common divisor
(GCD)]
//
of two or more integers, which are not all zero, is the largest positive integer
that divides each of the integers.
//
____

[[pjDljAIzRjELOcfeobkDQFRinIBUMrhD]]
== ! GCD Algorithms

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://en.wikipedia.org/wiki/Greatest_common_divisor#Calculation"></iframe>
</div>
++++

[[tDXMsVMWQaICoZpNjRwvYQvYvpkBVCKA]]
[.oneword]
== But We Only Have a Few Minutes Left...

[[JssrqejyvIyvwsXyrCkspJKxdKDMQLRk]]
== Brute Force Solution

[quote]
____
https://en.wikipedia.org/wiki/Brute-force_search[Brute force solution]:
//
a very general problem-solving technique that consists of systematically
enumerating all possible candidates for the solution and checking whether each
candidate satisfies the problem's statement.
____

[.s]
//
* Computers today are very, _very_ fast
//
* So try the simple thing first
//
* If it's too slow, try something a bit more sophisticated

[[qMuYttxuubacRODFMWhjihipuaPhWYqH]]
== ! GDC Implementation

[.janini.small]
....
// Print the GCD
System.out.println(gcd(24, 18));
....

[[SAkZunVquojxGluWfhHFkLljmuDEmoNB]]
[.oneword]
== You Don't Need the Fastest Algorithm to Change the World

That's a good thing!
