---
title: Practice with Functions and Strings
date: 2018-02-02
description:
  More practice with functions and Java Strings.
spelling_exceptions:
  - GCD
draft: true
---
:imagesdir: /slides/images
:!sectids:

[[tEtREXcdwvLNenEEApUWWxYcIyInPqrh]]
== !

[.janini.small]
--
++++
<div class="message">Practice with Functions and Strings<br/>Press Control-Return to run the code above</div>
++++
....
String[] courses = { "CS 125", "CS 225", "CS 241" };
void bestCourse(String[] options) {
  for (String course: options) {
    System.out.print(course);
    if (course.contains("125")) {
      System.out.print(" is the best");
    } else {
      System.out.println();
    }
  }
}
....
--

[[nXJaqYifBIRupMOUvdurSxJJtMqOMjnO]]
== Consecutive Identical Values

[.lead]
//
Given a string, write a function to find all cases where consecutive characters
are the same.

*First, what is our algorithm?*

[.s]
//
. Examine each character in the array
//
. Compare it with the next character&mdash;but how do we get at that?
//
. Print it out if they are the same

[[myIIGowgWcgYdJyAHTrrOBJNehWuJjkr]]
== ! Consecutive Identical Characters

[.janini.small]
....
// Print consecutive identical characters
String toSearch = "abcdefeffh";
....

[[dgqLkvllIxGBVWNUgvWRaphpbprIUZmd]]
== Split Name

[.lead]
//
Imagine I have a person's full name in a string in either one of the following
two formats:

. "First Last", or
//
. "Last, First"

Write a function to split the name into two string values: one storing the first
name and the second storing the last name.

[[LusbpptlAvcVVksiUCrVcWRbBGsDtOkn]]
== ! Split Name

[.janini.small]
....
// Split into first and last name
String fullName = "Chuchu Challen";
....

[[gPucDaBMQDrRTTpzHGhYeKkUqKBFQzyR]]
== Search Text

[.lead]
//
Given a line of text, write a function that searches for all occurrences of a
given word.

[[CjUbIEwBODHnKAjrDdalyYWzIqZflMlk]]
== ! Search Text

[.janini.small]
....
// Search text for a specific word
String text = "Where do random thoughts come from?"
....

// vim: ts=2:sw=2:et
