---
title: Functions and Algorithms
date: 2018-01-29
description:
  Introduction to functions and using algorithms to solve simple problems.
draft: true
---
:imagesdir: /slides/images
:!sectids:

[[WMIXpAhbQaTskdstiILhxUgbcbLLsFyk]]
== ! Average Of An Array
[role='janini']
....
// Compute the average
float[] toAverage = { 0.1, 6.7, 8.9, 10.4, 11.2, 0.9 };
....

[[HiatdhpaUkUnyCVrqTZFbPvmyUaqWSVN]]
== Consecutive Identical Values

[.lead]
//
Given an array of chars, find all cases where consecutive elements are the same.

*First, what is our algorithm?*

[.s]
//
. Examine each value in the array
//
. Compare it with the next value&mdash;but how do we get at that?
//
. Print it out if they are the same

[[nbSIYahKjyKuYqGenoNlETYtzzvVjQpO]]
== ! Consecutive Identical Values
[role='janini']
....
// Print consecutive identical values
char[] toSearch = { 'a', 'b', 'b', 'c', 'e', 'f', 'f' };
....

[[JssrqejyvIyvwsXyrCkspJKxdKDMQLRk]]
== Brute Force Solution

[quote]
____
https://en.wikipedia.org/wiki/Brute-force_search[Brute force solution]:
//
a very general problem-solving technique that consists of systematically
enumerating all possible candidates for the solution and checking whether each
candidate satisfies the problem's statement.
____

[.s]
//
* Computers today are very, _very_ fast
//
* So try the simple thing first
//
* If it's too slow, try something a bit more sophisticated

[[SAkZunVquojxGluWfhHFkLljmuDEmoNB]]
[.oneword]
== You Don't Need the Fastest Algorithm to Change the World

That's a good thing!

[[OBLbAkJElAJAKOCSqyEIEFgKyaPMwouY]]
== Announcements
