---
title: Imperative Finale
date: 2018-02-09
description:
  More imperative constructs and practice.
spelling_exceptions:
  - GCD
---
:imagesdir: /slides/images
:!sectids:

[[MSYQNbhtaxlUcSzvjwiMRMJJAmyQZsnd]]
== !

[.janini.small]
--
++++
<div class="message">Imperative Finale<br/>Press Control-Return to run the code above</div>
++++
....
System.out.println("We're almost done with imperative programming...");
....
--

[[HltJmohVAiSOVkbDyMDvVSxVeYTnaQmt]]
== Casting

[.lead]
//
If you want to _force_ Java to convert a variable from one type to another you
can try applying a _cast_.

[source,java]
----
int i = 10;
double d = i; // This works since no information is lost
i = d; // This does not work since we'd have to throw out the fraction
i = (int) d; // But we can force Java to do it
----

[[bcsEuCBErjgIjQHaKvcOzsFASZdTIemI]]
== ! Casting

[.janini.small]
....
int i = 10;
double d = i; // This works since no information is lost
i = d; // This does not work...
i = (int) d; // ...but we can force Java to do it
....

[[dfZDbioIVRPdrUKNnAedFUWRYIlHwlEC]]
== Most Common Character

[.lead]
//
Imagine I have a string and want to determine which character appears most.

Write a function that returns the most common character.

[[uWCVIWQvecQoNrgNOqxXnNtOmCmoulca]]
[.oneword]
== What's Our Algorithm?

[[pRLEGNuhmEEyRNHwlewxDuXIzisgMUyc]]
== ! Here's Some Help

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html"></iframe>
</div>
++++

[[uvJzvrVwHpAMAfBsvuyPBxlKvTBfRAEo]]
[.oneword]
== Searching is OK
(Just don't search for or use "Solution to CS 125 MP2".)

[[VLnTwXzQJUKZxItXbvYRWiGOGLcURNsq]]
== ! Most Common Character

[.janini.small]
....
// Determine the most common character
static char mostCommon(String input) {
}
System.out.println(mostCommon("AAAbcd"));
....

[[OPSrkYUNTxrjfKcdKlMrOeaNTfwJaaCi]]
== Switch Statements

[.lead]
//
Remember the `if` statement?
[source,java]
----
if (conditionA) {
  // do something
} else if (conditionB) {
  // do something else
} else if (conditionC) {
  // ...
}
----

It too has a friend:

[.s]
--
[source,java]
----
switch (variable) {
  case A:
    // do something
  case B:
    // do something else...
}
----
--

[[nGiQLdRcHAuGxCdGVrExNKMGjQtwQPlJ]]
== Switch Statements

[.lead]
//
`switch` is more limited than `if-else`, but also more flexible:

[.s]
//
* It only works for testing primitive types and ``String``s
//
* But you can match multiple ``case``s in a single `switch` statement
//
* Execution _starts_ at a matching `case` statement and continues until a
`break` statement is reached

[[BNTWPZKfwWhfxfRAtLWKGjIEGdZoPTVZ]]
== ! Switch Statements

[.janini.small]
....
int test = 2;
switch (test) {
  case 0: System.out.print("A");
  case 1: System.out.print("B");
  case 2: System.out.print("C");
  case 3: System.out.print("D");
  default: System.out.print("E");
}
System.out.println();
....


[[BzRRFIMstyqbRXhqEywqvIoQJUgYebbD]]
== Greatest Common Denominator

[quote]
//
____
//
In mathematics, the
//
https://en.wikipedia.org/wiki/Greatest_common_divisor[greatest common divisor
(GCD)]
//
of two or more integers, which are not all zero, is the largest positive integer
that divides each of the integers.
//
____

[[pjDljAIzRjELOcfeobkDQFRinIBUMrhD]]
== ! GCD Algorithms

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://en.wikipedia.org/wiki/Greatest_common_divisor#Calculation"></iframe>
</div>
++++

[[tDXMsVMWQaICoZpNjRwvYQvYvpkBVCKA]]
[.oneword]
== But If We're In A Hurry...

[[JssrqejyvIyvwsXyrCkspJKxdKDMQLRk]]
== Brute Force Solution

[quote]
____
https://en.wikipedia.org/wiki/Brute-force_search[Brute force solution]:
//
a very general problem-solving technique that consists of systematically
enumerating all possible candidates for the solution and checking whether each
candidate satisfies the problem's statement.
____

[.s]
//
* Computers today are very, _very_ fast
//
* So try the simple thing first
//
* If it's too slow, try something a bit more sophisticated

[[qMuYttxuubacRODFMWhjihipuaPhWYqH]]
== ! GDC Implementation

[.janini.small]
....
// Print the GCD
System.out.println(gcd(24, 18));
....

[[qdXwzQeEINKOPgbceNliwLWeLNyqnSVo]]
== ! Bring the Brute

image::https://cdn.vox-cdn.com/thumbor/wgMcgj6LStdjW-qlLkaHUBsdQzY=/0x0:2048x858/1200x800/filters:focal(834x251:1160x577)/cdn.vox-cdn.com/uploads/chorus_image/image/57442421/hulk_agnarok.0.jpg[role='mx-auto meme',width=640]

[[SAkZunVquojxGluWfhHFkLljmuDEmoNB]]
[.oneword]
== You Don't Need the Fastest Algorithm to Change the World

That's a good thing!

[[XIAanwdDVyALfCEgZLNQljuMKfylgtld]]
== But How Long Will It Take?

[.lead]
//
How long will our brute force GCD algorithm take?

[.s]
//
* To compute the GCD of 4 and 6
//
* To compute the GCD of 185 and 2045
//
* To compute the GCD of M and N

[[gPucDaBMQDrRTTpzHGhYeKkUqKBFQzyR]]
== Search Text

[.lead]
//
Given a line of text, write a function that searches for all occurrences of a
given word.

[[eyqUvEBDookviajBvuXtPufaOcUyPAhM]]
[.oneword]
== What's Our Algorithm?

[[CjUbIEwBODHnKAjrDdalyYWzIqZflMlk]]
== ! Search Text

[.janini.small]
....
// Search text for a specific word
String text = "Where do random thoughts come from?"
....

[[kLZPLCwNTswvGzxkLeLVyLvzOzzBzbxG]]
== ! Read The Documentation

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/lang/String.html"></iframe>
</div>
++++

[[bXcdkAWxGuwdeFZyXiMBWFXvvRNmKLtZ]]
== Announcements

* Quiz 3 starts today in the CBTF. It covers multi-dimensional arrays and more
about functions.
//
* TC 7 will be out shortly and due *Sunday* by midnight.
//
* link:/MP/1/[MP2] is due today!
//
https://cs125.cs.illinois.edu/info/resources/#hours[Office hours]
//
until 5PM today.
//
* MP3 will be out today and due in _two weeks_.
//
It's your introduction to object-oriented programming, so don't expect to begin
it until next Monday when we start talking about objects.

// vim: ts=2:sw=2:et
