---
title: Imperative Finale
date: 2018-02-09
description:
  More imperative constructs and practice.
echo: https://goo.gl/N9X3rn
---
:imagesdir: /slides/images
:!sectids:

[[MSYQNbhtaxlUcSzvjwiMRMJJAmyQZsnd]]
== !

[.janini.small]
--
++++
<div class="message">Imperative Finale<br/>Press Control-Return to run the code above</div>
++++
....
System.out.println("We're almost done with imperative programming...");
....
--

[[HltJmohVAiSOVkbDyMDvVSxVeYTnaQmt]]
== Casting

[.lead]
//
If you want to _force_ Java to convert a variable from one type to another you
can try applying a _cast_.

[source,java]
----
int i = 10;
double d = i; // This works since no information is lost
i = d; // This does not work since we'd have to throw out the fraction
i = (int) d; // But we can force Java to do it
----

[[bcsEuCBErjgIjQHaKvcOzsFASZdTIemI]]
== ! Casting

[.janini.small]
....
int i = 10;
double d = i; // This works since no information is lost
i = d; // This does not work...
i = (int) d; // ...but we can force Java to do it
....

[[dfZDbioIVRPdrUKNnAedFUWRYIlHwlEC]]
== Most Common Character

[.lead]
//
Imagine I have a string and want to determine which character appears most.

Write a function that returns the most common character.

[[uWCVIWQvecQoNrgNOqxXnNtOmCmoulca]]
[.oneword]
== What's Our Algorithm?

[[pRLEGNuhmEEyRNHwlewxDuXIzisgMUyc]]
== ! Here's Some Help

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html"></iframe>
</div>
++++

[[uvJzvrVwHpAMAfBsvuyPBxlKvTBfRAEo]]
[.oneword]
== Searching is OK
(Just don't search for or use "Solution to CS 125 MP2".)

[[VLnTwXzQJUKZxItXbvYRWiGOGLcURNsq]]
== ! Most Common Character

[.janini.small]
....
// Determine the most common character
static char mostCommon(String input) {
}
System.out.println(mostCommon("AAAbcd"));
....

[[bXcdkAWxGuwdeFZyXiMBWFXvvRNmKLtZ]]
== Announcements

* Quiz 3 starts today in the CBTF. It covers multi-dimensional arrays and more
about functions.
//
* TC 7 will be out shortly and due *Sunday* by midnight.
//
* link:/MP/1/[MP2] is due today!
//
https://cs125.cs.illinois.edu/info/resources/#hours[Office hours]
//
until 5PM today.
//
* MP3 will be out today and due in _two weeks_.
//
It's your introduction to object-oriented programming, so don't expect to begin
it until next Monday when we start talking about objects.

// vim: ts=2:sw=2:et
