---
title: Linked Lists
date: 2019-10-28
description:
  Completion of a discussion of linked lists and midterm exam review.
spelling_exceptions:
  - 3n
  - lookups
---

[[ZrRhHAiZmjGVCqKzTkVDkwpNGYoRBTci]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Linked Lists</div>
++++
....
public interface SimpleList {
  public Object get(int index);
  public void set(int index, Object element);
  public void add(int index, Object element);
  public Object remove(int index);
  public int size();
}
public class Example {
  public static void main(String[] unused) {
    SimpleList simpleList = new SimpleArrayList(new Integer[] { 1, 2 });
    simpleList.add(2, (Integer) 5);
    for (int i = 0; i < simpleList.size(); i++) {
      System.out.println(simpleList.get(i));
    }
  }
}
....
--

[[FLrMUeaPPdghfXdVtAoFhyJeHBGeBJfV]]
== Review: Lists

[.lead]
//
What you have been building on the last few homework problems is a more general
data structure called a _list_.

Lists are an _ordered_ footnote:[We'll talk about unordered soon...] data structure that allow us to:

[.s]
//
* Get and set values at any index (like an array)
//
* Add or remove values at any index (this is new)
//
* Lists are one of the two data structures you meet in heaven&mdash;maps are the
other and we'll get to them in a few weeks

[[ZNOikwniBxwwdnfIrXpGZeDunUmkcdRQ]]
== Review: Data Structure Tradeoffs

[.lead]
//
Depending on how we structure data different implementations of the _same_
interface can have different performance characteristics.

[.s]
//
* We'll start by looking at this with _lists_
//
* Lists that store items using arrays have *fast* (O(1)) lookups but _slow_
(O(n)) modifications
//
* Lists that store items using linked lists have _slow_ lookups (O(n)) but some
insertions are *fast* (O(1))
//
* Both also present different memory usage tradeoffs

[[GgjDBubcXoMJtfILfeFlevdxnkSdDZFc]]
== Our List Interface

[source,java]
----
interface SimpleList {
  /** Get the object at this index. */
  Object get(int index);
  /** Set the object at this index to the passed element. */
  void set(int index, Object element);
  /** Add the object at the specified location in the list. */
  void add(int index, Object element);
  /** Remove and return the object at the specified location in the list. */
  Object remove(int index);
  /** Return the number of elements in the list. */
  int size();
}
----

(The official Java one contains a bunch of convenience methods that we don't
want.)

[[jjuOzugQvkSIeJBnLlfaTmqivAFVUVZa]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smallest']
----
public class Item {
  private Object value;
  private Item next;
  Item(Object setValue, Item setNext) {
    value = setValue;
    next = setNext;
  }
}
----

<<<

[[bvukTzGvgbKQdWJiVcbVkzvCLveVTLcR]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smallest']
----
public class Item {
  private Object value;
  private Item next;
  Item(Object setValue, Item setNext) {
    value = setValue;
    next = setNext;
  }
}
Item items = new Item((Integer) 0, null);
----

<<<

++++
<div class="digraph small TB">
  Item [ label = "Item|0" ]
  items -> Item
</div>
++++

[[LNBNtXZglNoDtVpnSUNLBXxXDxLZRmDE]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smallest']
----
public class Item {
  private Object value;
  private Item next;
  Item(Object setValue, Item setNext) {
    value = setValue;
    next = setNext;
  }
}
Item items = new Item((Integer) 0, null);
items = new Item((Integer) 8, items);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item [ label = "Item|0" ]
  Item8 [ label = "Item|8" ]
  items -> Item8
  Item8 -> Item
</div>
++++

[[WAdJPunuCYPRWbuZQvICJKkHNiUoiBsw]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smallest']
----
public class Item {
  private Object value;
  private Item next;
  Item(Object setValue, Item setNext) {
    value = setValue;
    next = setNext;
  }
}
Item items = new Item((Integer) 0, null);
items = new Item((Integer) 8, items);
items = new Item((Integer) 5, items);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item [ label = "Item|0" ]
  Item8 [ label = "Item|8" ]
  Item5 [ label = "Item|5" ]
  items -> Item5
  Item5 -> Item8
  Item8 -> Item
</div>
++++

[[uvyuFIghbYXbXzMNglHaMMhbqqXqKGYL]]
== Another Option: Linked Lists

[source,java,role='smallest']
----
interface SimpleList {
  public Object get(int index);
  public void set(int index, Object element);
  public void add(int index, Object element);
  public Object remove(int index);
  public int size();
}
public class SimpleLinkedList implements SimpleList {
  class Item {
    Object value;
    Item next;
    Item(Object setValue, Item setNext) {
      value = setValue;
      next = setNext;
    }
  }
  private Item start;
}
----

[[pFfMfaklggDxABUyHIoUOomlxdhJNmAX]]
== Review: `LinkedList` `addToFront`

[source,java]
----
public class SimpleLinkedList {
  private Item start;
  public void addToFront(Object value) {
    start = new Item(value, start);
  }
}
----

[.s]
//
* *What is n&mdash;or what feature drives performance?*
//
[.s]#The length of the list.#
//
* What is the performance of `addToFront`?
//
[.s]#O(1): constant time!#

[[eRuvOPCigAcMMwCpOUhtUcBMNSiRoBFb]]
[.oneword]
//
== Wow! What's the catch?
//
(There's always a catch.)

[[uxETPHKiReXjnLMwmpdVNZwTsvFshNbf]]
== `LinkedList`: `get`

[source,java]
----
public class SimpleLinkedList {
  private Item start;
  public void addToFront(Object value) {
    start = new Item(value, start);
  }
  public Object get(int index) {
    // This should be easy...
  }
}
----

[[HIFRUbegMElyTCRryTvdWMzsnTFvAaJp]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class SimpleLinkedList {
  public Object get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
SimpleLinkedList list = new SimpleLinkedList();
list.addToFront((Integer) 1);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  start -> Item1
</div>
++++

[[huaxLPNSoVSkxUbFnCUWqRwuDZQqgJMw]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class SimpleLinkedList {
  public Object get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
SimpleLinkedList list = new SimpleLinkedList();
list.addToFront((Integer) 1);
list.addToFront((Integer) 2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  Item2 [ label = "Item|2" ]
  start -> Item2
  Item2 -> Item1
</div>
++++

[[MtSJPhEljoKufnnBjwnMhJzpMuTmWMFr]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class SimpleLinkedList {
  public Object get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
SimpleLinkedList list = new SimpleLinkedList();
list.addToFront((Integer) 1);
list.addToFront((Integer) 2);
list.addToFront((Integer) 3);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[OQXWCIblWobBKVCXOmUNWFOkQhCKuFkj]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class SimpleLinkedList {
  public Object get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
SimpleLinkedList list = new SimpleLinkedList();
list.addToFront((Integer) 1);
list.addToFront((Integer) 2);
list.addToFront((Integer) 3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item0 [ label = "Item|1" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item0
</div>
++++

[[uTCRqFIioaWUbZXxmfyHvXYrSAEEPpnH]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class SimpleLinkedList {
  public Object get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
SimpleLinkedList list = new SimpleLinkedList();
list.addToFront((Integer) 1);
list.addToFront((Integer) 2);
list.addToFront((Integer) 3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3", fillcolor="lightblue", style="filled" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[IEKNGKZOSoQTcaAWJVuwbUBrlUaleLHp]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class SimpleLinkedList {
  public Object get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
SimpleLinkedList list = new SimpleLinkedList();
list.addToFront((Integer) 1);
list.addToFront((Integer) 2);
list.addToFront((Integer) 3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  Item2 [ label = "Item|2", fillcolor="lightblue", style="filled" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[bcglIwAIsYtwxwTorcPMDROVbXnqTSvu]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class SimpleLinkedList {
  public Object get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
SimpleLinkedList list = new SimpleLinkedList();
list.addToFront((Integer) 1);
list.addToFront((Integer) 2);
list.addToFront((Integer) 3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1", fillcolor="lightblue", style="filled" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[wOcKkEBJTHkkCcDKpEwCCNYvCSUinhUY]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class SimpleLinkedList {
  public Object get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
SimpleLinkedList list = new SimpleLinkedList();
list.addToFront((Integer) 1);
list.addToFront((Integer) 2);
list.addToFront((Integer) 3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1", fillcolor="green", style="filled" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[pxuXZdXDaFvnXeerjuOzfTjYXWOCvOan]]
== Linked Lists: Iteration

[source,java,role='smaller']
----
public class SimpleLinkedList {
  private Item start;
}
public class Item {
  public int value;
  public Item next;
}
----

[.lead]
//
We can iterate through our `LinkedList` using a `for` loop.

[[nlYljBaffrrPZfYjSwRRokqjNFrUqSkm]]
== ! `LinkedList` `for`

[.janini.smallest.compiler]
....
public class SimpleLinkedList {
  class Item {
    Object value;
    Item next;
    Item(Object setValue, Item setNext) {
      value = setValue;
      next = setNext;
    }
  }
  private Item start;
  public SimpleLinkedList(Object[] array) {
    for (int i = array.length - 1; i >= 0; i--) {
      this.addToFront(array[i]);
    }
  }
  public void addToFront(Object value) {
    start = new Item(value, start);
  }
  public void printList() {
    // Write a for loop iterating over this list
  }
}
public class Example {
  public static void main(String[] unused) {
    SimpleLinkedList myList = new SimpleLinkedList(new Integer[] { 1, 2, 3 });
    myList.printList();
  }
}
....

[[pEPepnOKrIPDRHLzgWbgWtoumQcPZCrp]]
[.oneword]
== But How Do We Insert?

[[nerIYzgfjYucqloclntPXXXuoxWPoXyu]]
== `LinkedList` Insertion Algorithm

[.s]
//
. Find the right spot.
//
. Set the reference on the preceding item to point to the new item.
//
. Set the reference on the new item to point to the former next item.

[[aJqVtwosxLpEzEELSiDrluCkDftdVFsM]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  start -> Item5
  Item5 -> Item8
  Item8 -> Item1
</div>
++++

[[zOwLRABNObeVBCMMXUXervMeZsDHHIaj]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5" ]
  Item8 [ label = "Item|8", fillcolor="green" style="filled" ]
  Item1 [ label = "Item|1" ]
  start -> Item5
  Item5 -> Item8
  Item8 -> Item1
</div>
++++

[.s]#But wait, now we can't change the _preceding_ reference.#

[[PjJcvbtgFhhtTivglyVutpdqdHgRlGee]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5", fillcolor="green" style="filled" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  start -> Item5
  Item5 -> Item8
  Item8 -> Item1
</div>
++++

[[XWkIZquMkCyhpMAfyVuKtmPLZpMmLTWC]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5", fillcolor="green" style="filled" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  Item7 [ label = "Item|7" ]
  start -> Item5
  Item5 -> Item8
  Item8 -> Item1
  Item1 -> Item7 [style=invis]
</div>
++++

[[axthZIrmKjSLSVsfRpziruJdWPWSsGeO]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5", fillcolor="green" style="filled" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  Item7 [ label = "Item|7" ]
  start -> Item5
  Item5 -> Item7
  Item7 -> Item8 [style=invis]
  Item8 -> Item1
</div>
++++

[[wDhvwOPZturUQaSVCGHRmtTqwKddqKyI]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  Item7 [ label = "Item|7" ]
  start -> Item5
  Item5 -> Item7
  Item7 -> Item8
  Item8 -> Item1
</div>
++++

[[JBKRvvXqROogVmYfdoYBgwwoiInUqLVw]]
== Singly Linked Lists

[source,java,role='smaller']
----
public class SimpleLinkedList {
  class Item {
    Object value;
    Item next;
    Item(Object setValue, Item setNext) {
      value = setValue;
      next = setNext;
    }
  }
  private Item start;
}
----

[.lead]
//
What we've been discussing is known as a _singly_ linked list.

[[ZzkrRixhzKByfLpVbXSoMvNCfoHruinc]]
== Doubly Linked Lists

[source,java,role='smaller']
----
public class SimpleDoublyLinkedList {
  class Item {
    Object value;
    Item next;
    Item previous;
    Item(Object setValue, Item setNext) {
      value = setValue;
      next = setNext;
    }
  }
  private Item start;
  private Item end;
}
----

[.lead]
//
You can also have both forward _and_ backward links. This is known an a
_doubly_ linked list.


[[IrhfppWiBrQzcMyldmluKPgiYlrjJtYj]]
[.ss]
== Doubly Linked Lists

[source,java,role='smallest']
----
public class SimpleDoublyLinkedList {
  class Item {
    Object value;
    Item next;
    Item previous;
    Item(Object setValue, Item setNext) {
      value = setValue;
      next = setNext;
    }
  }
  private Item start;
  private Item end;
}
----

<<<

++++
<div class="digraph small TB">
  Item0 [ label = "Item|0" ]
  Item2 [ label = "Item|2" ]
  Item4 [ label = "Item|4" ]
  start -> Item0
  Item0 -> Item2
  Item2 -> Item0
  Item2 -> Item4
  Item4 -> Item2
  end -> Item4
</div>
++++

[[CmKtLrByiQHzIHiRNpaTpHgpKrJvqQVZ]]
== Time v. Space

[source,java,role='smallest']
----
public class SimpleArrayList {
  private Object[] array;
}
public class SimpleDoublyLinkedList {
  class Item {
    Object value;
    Item next;
    Item previous;
  }
  private Item start;
  private Item end;
}
----

[.lead]`ArrayList` v. `LinkedList` also represents a _time_ v. _space_ tradeoff.

[.s.small]
//
* `LinkedList` is faster for certain operations...
//
* but consumes more space to store the same amount of information.

[[UZWfhblmpgARaijHSpMHsIAeuXwyWqor]]
== Time v. Space

[source,java,role='smallest']
----
public class SimpleArrayList {
  private Object[] array;
}
public class SimpleDoublyLinkedList {
  class Item {
    Object value;
    Item next;
    Item previous;
  }
  private Item start;
  private Item end;
}
----

[.lead]
//
To store n ``int``s:

[.s]
//
* `ArrayList`: [.s]#n ``value``s#
//
* `LinkedList`: [.s]#3n (1 `value`, 1 `next`, 1 `previous`)#

[[HukfpNfUOulnnDElwTJYZyNKTvhGgtDM]]
== `ArrayList` v. `LinkedList`

[.lead]
//
Both provide the _same_ functionality, but with different _performance_
characteristics.

[%autowidth.spread,cols="^,^,^",options='header']
|===

^| Operation
^| `ArrayList`
^| `LinkedList`

| `add` (at front)
| [.s]#O(n)#
| [.s]#*O(1)*#

| `get` and `set`
| [.s]#*O(1)*#
| [.s]#O(n)#

| `insert` (anywhere)
| [.s]#O(n)#
| [.s]#O(n)#

|===


[[XRenWLYUsfpGLdlyrLDHyMkeRTSGMukE]]
== ! SimpleArrayList

[.janini.smallest.compiler]
....
public interface SimpleList {
  public Object get(int index);
  public void set(int index, Object element);
  public void add(int index, Object element);
  public Object remove(int index);
  public int size();
}
public class SimpleLinkedList implements SimpleList {
  class Item {
    Object value;
    Item next;
    Item(Object setValue, Item setNext) {
      value = setValue;
      next = setNext;
    }
  }
  private Item start;

  public SimpleLinkedList(Object[] array) {
    for (int i = array.length - 1; i >= 0; i--) {
      this.add(0, array[i]);
    }
  }

  public void add(int index, Object toAdd) {
    if (index == 0) {
      start = new Item(toAdd, start);
    }
  }

  public int size() {
    int currentSize = 0;
    for (Item current = start; current != null; current = current.next) {
      currentSize++;
    }
    return currentSize;
  }
}
public class Example {
  public static void main(String[] unused) {
    SimpleList simpleList = new SimpleLinkedList(new Integer[] { 1, 2, 5 });
    System.out.println(simpleList.size());
  }
}
....

[[lJcCMyeWhddIzcdhiLSDPvylMQZYwVRV]]
[.oneword]
== Questions About Lists?

[[vQhgISVnpMnpYRuBdNGKGbVuwCTbdeeR]]
== Midterm Overview and Review

Midterm format:

* *40 points*: 10 4-point multiple-choice questions drawn from previous quizzes
//
* *60 points*: 3 20-point programming questions, all including partial
credit

[[LfURaMrvaiZqQnWfdznVZWMjBnOSveWE]]
== Midterm Topic Coverage

[.lead]
//
Everything up through _last week's quiz_.

* Lectures starting
//
https://cs125.cs.illinois.edu/learn/2019_09_23_introduction_to_objects[9/23/2019]
//
through
//
https://cs125.cs.illinois.edu/learn/2019_10_18_more_about_interfaces[10/18/2019].
//
* No coverage of algorithms, algorithm runtime, or lists.

[[MCMAQBboSAumferwaBRUuTdFlxHDnbnj]]
[.oneword]
//
== Midterm Questions?

[[OreWdRNvfsGvebeLexINvWzuEzAMBFLX]]
== Reminders

[.s.lead]
//
* You're all doing great!
//
* The point of the exams (and quizzes) is to get you to do the homework
problems.

[[nGsigkJsZbIIiuBueedkjOHenoatcePu]]
== Announcements

* Midterm 1 starts tomorrow in the CBTF.
//
It's worth the same amount as a quiz **but cannot be dropped.**

// vim: ts=2:sw=2:et
