---
title: Linked Lists
date: 2018-03-07
description:
  Continuation of a discussion of linked lists, including inserting elements and
  iteration.
spelling_exceptions:
  - 3n
---

[[pgYMuWIZOClhbnKQazmcPUWjaySoCIar]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Linked Lists</div>
++++
....
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
public class LinkedList {
  private Item start;
  public int get(int index) {
    Item current = start;
    for (int i = 0; i < index; i++) {
      current = current.next;
    }
    return current.value;
  }
}
public class Example {
  public static void main(String[] unused) {
  }
}
....
--

[[ZcSyAWnnkkSqpuXrEGLIRzspjCMTqMDZ]]
[.oneword]
== No Professor Of The Day Award For Me
(At least not today.)

[[rJOxXOGNaQrhuLzoqiKfoeSvEbCZcvww]]
== Lecture Participation Reminder

[.lead]
//
Lecture participation scores will be up later today.
//
*Some of you will be unhappy.*

Our participation tracking algorithm is _very_ generous. But, to earn
participation credit, you need:

[.s]
//
* *To be in the right place.* No points for attending the wrong lecture.
//
* *To be following along with the slides.* No points for just being logged in.
//
* Questions?

[[mtewUULnaMvHglEMtJNEctwLkKXbHVqt]]
== Cheating

[.lead]
//
I take academic integrity extremely seriously.
//
Cheaters will be caught and punished.

We've begun checking submissions for plagiarism.

[.s]
//
* 99% of you are fine. *Thanks for being honest and working hard.*
//
* 1% of you are not fine. *You'll be hearing from us.*

[[eHRxJUhDLukJpzNYHmPYdwCshvuiEpya]]
[.oneword]
== Course Policies Questions?

We have good reasons for the choices we've made about how the course is set up.
But there are always tradeoffs. I'm happy to discuss.

[[yIksCGacXTpEUsZJulwkCHBpwsvWMNFp]]
== Q6 Review: Terminology

[source,java,role='smallest']
----
class Parent { }
class Child extends Parent { }
----

In Java, any method that will accept an instance of `Parent` will also accept an
instance of `Child`. This is due to...

[[gYbroZRyPeylyRcTrRpQrGjbrWCeOXEr]]
== Q6 Review: Object Casting

[source,java,role='smallest']
----
public class Top {
  public static void printOne(Top top) {
    Bottom bottom = (Bottom) top;
    bottom.print();
  }
  public void print() {
    System.out.println("Top");
  }
}
public class Bottom extends Top {
  public void print() {
    System.out.println("Bottom");
  }
}
public class Example {
  public static void main(String[] unused) {
    Top top = new Top();
    Top.printOne(top);
  }
}
----

When the `main` method runs, what will be printed?

[[HSVhcAvjRKzeCPcLEVVjOyYZngrXrGlM]]
== ! Q6 Review: Object Casting

[.janini.compiler.smallest]
....
public class Top {
  public static void printOne(Top top) {
    Bottom bottom = (Bottom) top;
    bottom.print();
  }
  public void print() {
    System.out.println("Top");
  }
}
public class Bottom extends Top {
  public void print() {
    System.out.println("Bottom");
  }
}
public class Example {
  public static void main(String[] unused) {
    Top top = new Top();
    Top.printOne(top);
  }
}
....

[[drGfkPQUuIWlQbKrBMzouxWqWQEOivkK]]
== Q6 Review: References

[source,java,role='smallest']
----
public class Car {
  public int odometer;
  public Car(int initialOdometer) {
    odometer = initialOdometer;
  }
  public int increaseMileage() {
    return odometer++;
  }
}
public class Example {
  public static void main(String[] unused) {
    Car[] cars = new Car[10];
    Car car = new Car(10);
    for (int i = 0; i < cars.length; i++) {
      cars[i] = car;
    }
    for (int i = 0; i < cars.length; i++) {
      cars[i].increaseMileage();
    }
    System.out.println(cars[0].odometer);
  }
}
----

When the `main` method runs, what will be printed?

[[aVHprWTYNpzLYYXgewmOZeORloIAGRRB]]
== ! Q6 Review: References

[.janini.compiler.smallest]
....
public class Car {
  public int odometer;
  public Car(int initialOdometer) {
    odometer = initialOdometer;
  }
  public int increaseMileage() {
    return odometer++;
  }
  public boolean equals(Car other) {
    return odometer == other.odometer;
  }
}
public class Example {
  public static void main(String[] unused) {
    Car[] cars = new Car[10];
    Car car = new Car(10);
    for (int i = 0; i < cars.length; i++) {
      cars[i] = car;
    }
    for (int i = 0; i < cars.length; i++) {
      cars[i].increaseMileage();
    }
    System.out.println(cars[0].odometer);
  }
}
....

[[LcyEAmVtUdcHjdXtILAeYWjLVFHCYoLE]]
== Q6 Review: Polymorphism

[source,java,role='smallest']
----
public class Shape {
  public String toString() {
    return "Shape";
  }
}
public class FourSides extends Shape {
  public String toString() {
    return "FourSides";
  }
}
public class Example {
  public static void main(String[] unused) {
    FourSides s = new Shape();
    System.out.println(s);
  }
}
----

When the `main` method above runs, what will be printed?

[[fNGgzyoKhumeyEtMqZgwOMgVXpiCilEK]]
== ! Q6 Review: Polymorphism

[.janini.compiler.smallest]
....
public class Shape {
  public String toString() {
    return "Shape";
  }
}
public class FourSides extends Shape {
  public String toString() {
    return "FourSides";
  }
}
public class Example {
  public static void main(String[] unused) {
    FourSides s = new Shape();
    System.out.println(s);
  }
}
....

[[vDfnzUuMOuMRHAAdncCKUaciSuZDBygs]]
== Q6 Review: Garbage Collection

[source,java]
----
public class Example {
  public static void main(String[] unused) {
    String[] strings = new String[10];
    for (int i = 0; ; i++) {
      strings[i % 10] = new String();
    }
  }
}
----

After the code above runs for a while, how many valid `String` objects will
exist in the system?

[[VgYgAHgZIcREUpqGNdxTklOAGrPTRLtU]]
[.ss]
== Linked Lists

[source,java,role='smaller']
----
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
----

<<<

[[bPzPQuXqzJCYzMTEVwglDCplYhvLWJnQ]]
[.ss]
== Linked Lists

[source,java,role='smaller']
----
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
Item items = new Item(0, null);
----

<<<

++++
<div class="digraph small TB">
  Item [ label = "Item|0" ]
  items -> Item
</div>
++++

[[QGCsOehngugYkACMiMSLsbHMSjAVOkho]]
[.ss]
== Linked Lists

[source,java,role='smaller']
----
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
Item items = new Item(0, null);
items = new Item(8, items);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item [ label = "Item|0" ]
  Item8 [ label = "Item|8" ]
  items -> Item8
  Item8 -> Item
</div>
++++

[[GtlmuxhzhfUyTAHMaqczUJfMltCOYeMn]]
[.ss]
== Linked Lists

[source,java,role='smaller']
----
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
Item items = new Item(0, null);
items = new Item(8, items);
items = new Item(5, items);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item [ label = "Item|0" ]
  Item8 [ label = "Item|8" ]
  Item5 [ label = "Item|5" ]
  items -> Item5
  Item5 -> Item8
  Item8 -> Item
</div>
++++

[[TqpqrwnmogqCyDjXoapZgGkybZhBPNVy]]
== Linked Lists: Iteration

[source,java,role='smaller']
----
public class LinkedList {
  private Item start;
}
public class Item {
  public int value;
  public Item next;
}
----

[.lead]
//
We can iterate through our `LinkedList` using a `for` loop.

[[nlYljBaffrrPZfYjSwRRokqjNFrUqSkm]]
== ! `LinkedList` `for`

[.janini.smallest.compiler]
....
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
public class LinkedList {
  private Item start;
  public LinkedList(int[] array) {
    for (int i = array.length - 1; i >= 0; i--) {
      this.addToFront(array[i]);
    }
  }
  public void addToFront(int value) {
    start = new Item(value, start);
  }
  public String toString() {
    String string = "";
    Item current = start;
    while (current != null) {
      string += current.value + " ";
      current = current.next;
    }
    return string.trim();
  }
}
public class Example {
  public static void main(String[] unused) {
    LinkedList myList = new LinkedList(new int[] { 1, 2, 3 });
    // Write a for loop using myList
  }
}
....

[[oxJSFsbGhmTbUMqDhtQJYRfwOTOKvJAp]]
== `LinkedList`: Push

[source,java,role='smaller']
----
public class LinkedList {
  private Item start;
}
public class Item {
  public int value;
  public Item next;
}
----

[.lead]
//
Now, we can add an item to the _end_ of our linked list.

[[AjGCgLvviLBoOygYpJkyuYCDXpVeDpSE]]
== ! `LinkedList` Push

[.janini.smallest.compiler]
....
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
public class LinkedList {
  private Item start;
  public LinkedList(int[] array) {
    for (int i = array.length - 1; i >= 0; i--) {
      this.addToFront(array[i]);
    }
  }
  public void addToFront(int value) {
    start = new Item(value, start);
  }
  // Write this function
  public void addToEnd(int value) {
  }
  public String toString() {
    String string = "";
    Item current = start;
    while (current != null) {
      string += current.value + " ";
      current = current.next;
    }
    return string.trim();
  }
}
public class Example {
  public static void main(String[] unused) {
    LinkedList myList = new LinkedList(new int[] { 1, 2, 3 });
    System.out.println(myList);
  }
}
....

[[pEPepnOKrIPDRHLzgWbgWtoumQcPZCrp]]
[.oneword]
== But How Do We Insert?

[[nerIYzgfjYucqloclntPXXXuoxWPoXyu]]
== `LinkedList` Insertion Algorithm

[.s]
//
. Find the right spot.
//
. Set the reference on the preceding item to point to the new item.
//
. Set the reference on the new item to point to the former next item.

[[aJqVtwosxLpEzEELSiDrluCkDftdVFsM]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  start -> Item5
  Item5 -> Item8
  Item8 -> Item1
</div>
++++

[[zOwLRABNObeVBCMMXUXervMeZsDHHIaj]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5" ]
  Item8 [ label = "Item|8", fillcolor="green" style="filled" ]
  Item1 [ label = "Item|1" ]
  start -> Item5
  Item5 -> Item8
  Item8 -> Item1
</div>
++++

[.s]#But wait, now we can't change the _preceding_ reference.#

[[PjJcvbtgFhhtTivglyVutpdqdHgRlGee]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5", fillcolor="green" style="filled" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  start -> Item5
  Item5 -> Item8
  Item8 -> Item1
</div>
++++

[[XWkIZquMkCyhpMAfyVuKtmPLZpMmLTWC]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5", fillcolor="green" style="filled" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  Item7 [ label = "Item|7" ]
  start -> Item5
  Item5 -> Item8
  Item8 -> Item1
  Item1 -> Item7 [style=invis]
</div>
++++

[[axthZIrmKjSLSVsfRpziruJdWPWSsGeO]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5", fillcolor="green" style="filled" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  Item7 [ label = "Item|7" ]
  start -> Item5
  Item5 -> Item7
  Item7 -> Item8 [style=invis]
  Item8 -> Item1
</div>
++++

[[wDhvwOPZturUQaSVCGHRmtTqwKddqKyI]]
== Insertion Example

Let's insert value 7 at index 1.

++++
<div class="digraph smaller">
  Item5 [ label = "Item|5" ]
  Item8 [ label = "Item|8" ]
  Item1 [ label = "Item|1" ]
  Item7 [ label = "Item|7" ]
  start -> Item5
  Item5 -> Item7
  Item7 -> Item8
  Item8 -> Item1
</div>
++++

[[JwrUmyTLWlUEqQiFsxuHuxGiEHAvDtGH]]
== ! `LinkedList` Insert

[.janini.smallest.compiler]
....
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
public class LinkedList {
  private Item start;
  public LinkedList(int[] array) {
    for (int i = array.length - 1; i >= 0; i--) {
      this.addToFront(array[i]);
    }
  }
  public void addToFront(int value) {
    start = new Item(value, start);
  }
  // Write this function
  public void insert(int index, int value) {
  }
  public String toString() {
    String string = "";
    Item current = start;
    while (current != null) {
      string += current.value + " ";
      current = current.next;
    }
    return string.trim();
  }
}
public class Example {
  public static void main(String[] unused) {
    LinkedList myList = new LinkedList(new int[] { 1, 2, 3 });
    System.out.println(myList);
  }
}
....

[[JBKRvvXqROogVmYfdoYBgwwoiInUqLVw]]
== Singly Linked Lists

[source,java,role='smaller']
----
public class Item {
  public int value;
  public Item next;
  Item(int setValue, Item setNext, setPrevious) {
    this.value = setValue;
    this.next = setNext;
  }
}
public class LinkedList {
  private Item start;
}
----

[.lead]
//
What we've been discussing is known as a _singly_ linked list.

[[ZzkrRixhzKByfLpVbXSoMvNCfoHruinc]]
== Doubly Linked Lists

[source,java,role='smaller']
----
public class Item {
  public int value;
  public Item next;
  public Item previous;
}
public class DoublyLinkedList {
  private Item start;
  private Item end;
}
----

[.lead]
//
You can also have both forward _and_ backward links. This is known an a
_doubly_ linked list.


[[IrhfppWiBrQzcMyldmluKPgiYlrjJtYj]]
[.ss]
== Doubly Linked Lists

[source,java,role='smaller']
----
public class Item {
  public int value;
  public Item next;
  public Item previous;
}
public class DoublyLinkedList {
  private Item start;
  private Item end;
}
----

<<<

++++
<div class="digraph small TB">
  Item0 [ label = "Item|0" ]
  Item2 [ label = "Item|2" ]
  Item4 [ label = "Item|4" ]
  start -> Item0
  Item0 -> Item2
  Item2 -> Item0
  Item2 -> Item4
  Item4 -> Item2
  end -> Item4
</div>
++++

[[HTGNaXGWKsqdPcILLRuwBiFmpamPVvpQ]]
== Singly v. Doubly-Linked List

[width="100%",cols="^,^,^",options='header']
|===

^| Operation
^| Singly Linked List
^| Doubly Linked List

| `add` (at front)
| [.s]#O(1)#
| [.s]#O(1)#

| `add` (at back)
| [.s]#O(n)#
| [.s]#*O(1)*#

| `get` and `set`
| [.s]#O(n)#
| [.s]#O(n)#

|===

[[CmKtLrByiQHzIHiRNpaTpHgpKrJvqQVZ]]
== Time v. Space

[source,java,role='smaller']
----
public class ArrayList {
  private int[] data;
}
public class Item {
  public int value;
  public Item next;
  public Item previous;
}
public class DoublyLinkedList {
  private Item start;
  private Item end;
}
----

[.lead]`ArrayList` v. `LinkedList` also represents a _time_ v. _space_ tradeoff.

[.s]
//
* `LinkedList` is faster for certain operations...
//
* but consumes more space to store the same amount of information.

[[UZWfhblmpgARaijHSpMHsIAeuXwyWqor]]
== Time v. Space

[source,java,role='smaller']
----
public class ArrayList {
  private int[] data;
}
public class Item {
  public int value;
  public Item next;
  public Item previous;
}
public class DoublyLinkedList {
  private Item start;
  private Item end;
}
----

[.lead]
//
To store n ``int``s:

[.s]
//
* `ArrayList`: [.s]#n ``value``s#
//
* `LinkedList`: [.s]#3n (1 `value`, 1 `next`, 1 `previous`)#

[[JtyGwCLnUwqkqAhWVlTcYzOsTAUtRBQG]]
== Announcements

* link:/MP/4/[MP4] is due Friday.
//
* We've added an
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!
//
* Continue to communicate with the course staff about the strike as needed.
We're trying to keep everything up and running.
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
