---
title: Lists
date: 2018-03-05
description:
  Discussion of lists implemented both using arrays and linked lists.
---

[[TQcbLBvzGXemZKfpSvbOuepsOUbmWwqq]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Lists</div>
++++
....
public class Item {
  private int value;
  private Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
  public void setNext(Item setNext) {
    this.next = setNext;
  }
  public Item getNext() {
    return this.next;
  }
  public int getValue() {
    return this.value;
  }
}
public class LinkedList {
  private Item start;
  public void addToFront(int value) {
    start = new Item(value, start);
  }
  public int get(int index) {
  }
}
public class Example {
  public static void main(String[] unused) {
  }
}
....
--

[[kiuuHhvtkeNBrxzvZlBCjAdYovjtAXem]]
== Algorithms and Data Structures

[.lead]
//
For the next two weeks we'll be discussing fundamental computer science
_algorithms_ and _data structures_.

[.s]
//
* *Algorithm*: a way of doing something
//
* *Data structure*: a way of storing data that enables certain algorithms

[[IRjECqRugdjLLGMBzUFyfYJUfZJxxoVG]]
== Arrays

[source,java]
----
int[] values = new int[10];
----

[.lead]
//
At this point the only data structure we've discussed is the _array_.

[.s]
//
* *Good*: looking up an element in an array is O(1) footnote:[or constant time].
//
* *Bad*: the size of a Java array cannot be changed once it is created.

[[oFjnHJFHAMiBIIvaytaNNxjnVTrFFItX]]
[.oneword]
//
== So How Do We Add Items?

Hint: it's possible.

[[BLSbLyVhijVQLPaDmJdcviQvVrmehnQu]]
== ! Array Append Implementation

[.janini.smaller]
....
import java.utils.Arrays;
/*
 * Append an item to an array.
 */
static int[] append(int[] inputArray, int newValue) {
}
....

[[rXjhyqeJLXTgQCIwqqZfEQVOiUsCCgGK]]
== Array Append Performance

[source,java]
----
int[] append(int[] inputArray, int newValue) {
  // Create a new array one larger than the existing array
  // Copy all values over
  // Add the new value at the end
  // Return the new array
}
----

[.s]
//
* *What is n&mdash;or what feature drives performance?*
//
[.s]#The length of `inputArray`.#
//
* *Best case runtime*: [.s]#O(n)#
//
* *Worst case runtime*: [.s]#O(n)#
//
* *Average case runtime*: [.s]#O(n)#

[[LEyzqbhelTdWuMTbEHBBOHNTqHFfVtZh]]
== ! Array Insert Implementation

[.janini.smaller]
....
import java.utils.Arrays;
/*
 * Insert an item into the array at the given position.
 */
static int[] insert(int[] inputArray, int newValue, int position) {
}
....

[[wzaspGePmHbJRDzWxaugNPUBEgRFPjpN]]
== Array Insert Performance

[source,java]
----
int[] append(int[] inputArray, int newValue, int position) {
  // Create a new array one larger than the existing array
  // Copy all values over, adding the new value at the right spot
  // Return the new array
}
----

[.s]
//
* *What is n&mdash;or what feature drives performance?*
//
[.s]#The length of `inputArray`.#
//
* *Best case runtime*: [.s]#O(n)#
//
* *Worst case runtime*: [.s]#O(n)#
//
* *Average case runtime*: [.s]#O(n)#

[[YyibonHxVplBBKQDhstAZFKmtuJKHDYW]]
== Lists

[.lead]
//
Lists are a _tremendously_ useful data structure. Every modern language has them
footnote:[even Java!].

[.s]
//
* The size of a list can change at runtime.
//
* Items can be added and removed from the front or back:
//
** Add to front (`prepend`, `unshift`) or back (`append`, `push`)
//
** Remove from front (`shift`) or back (`pop`)
//
* Items can be added or removed from anywhere in the list (`insert` or `remove`)
//
* Items can be retrieved and set by index (`get` and `set`)

[[VkTMutAWADQhqNsbPGslndDjULyqqNUD]]
== ! Java `ArrayList`
++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html"></iframe>
</div>
++++

[[AqUbuIpzQiCSRhpnOEUmvyxvKlxDrvjJ]]
[.oneword]
//
== Why `ArrayList`?

[[GSDbRtMRolMiBVKgnSmdcGQrgBWTgTzU]]
== `ArrayList`: `get` and `set`

[source,java,role='smaller']
----
public class ArrayList {
  private int[] data;
  ArrayList() {
    this.data = new int[0];
  }
  public int get(int index) {
    return this.data[index];
  }
  public void set(int index, int value) {
    this.data[index] = value;
  }
}
----

[.s]
//
* *What is n&mdash;or what feature drives performance?*
//
[.s]#The length of the list.#
//
* What is the performance of `get`?
//
[.s]#O(1): constant time!#
//
* What is the performance of `set`?
//
[.s]#O(1): constant time!#

[[dWOUXmDXbjaatvVBSjkkqTDqOMiqRDlm]]
== `ArrayList`: `insert` and `remove`

[source,java,role='smaller']
----
public class ArrayList {
  private int[] data;
  ArrayList() {
    this.data = new int[0];
  }
  public void insert(int index, int value) {
    ...
  }
  public int remove(int index) {
    ...
  }
}
----

[.s]
//
* What is the performance of `insert`?
//
[.s]#O(n): have to copy the entire list.#
//
* What is the performance of `remove`?
//
[.s]#O(n): have to copy the entire list.#

[[jjuOzugQvkSIeJBnLlfaTmqivAFVUVZa]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smaller']
----
public class Item {
  private int value;
  private Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
----

<<<

[[bvukTzGvgbKQdWJiVcbVkzvCLveVTLcR]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smaller']
----
public class Item {
  private int value;
  private Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
Item items = new Item(0, null);
----

<<<

++++
<div class="digraph small TB">
  Item [ label = "Item|0" ]
  items -> Item
</div>
++++

[[LNBNtXZglNoDtVpnSUNLBXxXDxLZRmDE]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smaller']
----
public class Item {
  private int value;
  private Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
Item items = new Item(0, null);
items = new Item(8, items);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item [ label = "Item|0" ]
  Item8 [ label = "Item|8" ]
  items -> Item8
  Item8 -> Item
</div>
++++

[[WAdJPunuCYPRWbuZQvICJKkHNiUoiBsw]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smaller']
----
public class Item {
  private int value;
  private Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
}
Item items = new Item(0, null);
items = new Item(8, items);
items = new Item(5, items);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item [ label = "Item|0" ]
  Item8 [ label = "Item|8" ]
  Item5 [ label = "Item|5" ]
  items -> Item5
  Item5 -> Item8
  Item8 -> Item
</div>
++++

[[uvyuFIghbYXbXzMNglHaMMhbqqXqKGYL]]
[.ss]
== Another Option: Linked Lists

[source,java,role='smallest']
----
public class LinkedList {
  private Item start;
  public addToFront(int value) {
    start = new Item(value, start);
  }
}
----

<<<

[source,java,role='smallest']
----
public class Item {
  private int value;
  private Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
  public void setNext(Item setNext) {
    this.next = setNext;
  }
  public Item getNext() {
    return this.next;
  }
  public int getValue() {
    return this.value;
  }
}
----

[[xsaqFUCXGdWBcvgSrwKjsLHWsYrNDLlh]]
== ! `LinkedList` Example

[.janini.smallest.compiler]
....
public class Item {
  private int value;
  private Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
  public void setNext(Item setNext) {
    this.next = setNext;
  }
  public Item getNext() {
    return this.next;
  }
  public int getValue() {
    return this.value;
  }
}
public class LinkedList {
  private Item start;
  public void addToFront(int value) {
    start = new Item(value, start);
  }
  public String toString() {
    String string = "";
    Item current = start;
    while (current != null) {
      string += current.getValue() + " ";
      current = current.getNext();
    }
    return string.trim();
  }
}
public class Example {
  public static void main(String[] unused) {
  }
}
....

[[pFfMfaklggDxABUyHIoUOomlxdhJNmAX]]
== `LinkedList`: `addToFront`

[source,java]
----
public class LinkedList {
  private Item start;
  public void addToFront(int value) {
    start = new Item(value, start);
  }
}
----

[.s]
//
* *What is n&mdash;or what feature drives performance?*
//
[.s]#The length of the list.#
//
* What is the performance of `addToFront`?
//
[.s]#O(1): constant time!#

[[eRuvOPCigAcMMwCpOUhtUcBMNSiRoBFb]]
[.oneword]
//
== Wow! What's the catch?
//
(There's always a catch.)

[[uxETPHKiReXjnLMwmpdVNZwTsvFshNbf]]
== `LinkedList`: `get`

[source,java]
----
public class LinkedList {
  private Item start;
  public void addToFront(int value) {
    start = new Item(value, start);
  }
  public int get(int index) {
    // This should be easy...
  }
}
----

[[ToJOhcQvwLPGrKzyjTctnXGUlpaNgABO]]
== ! `LinkedList` Example

[.janini.smallest.compiler]
....
public class Item {
  private int value;
  private Item next;
  Item(int setValue, Item setNext) {
    this.value = setValue;
    this.next = setNext;
  }
  public void setNext(Item setNext) {
    this.next = setNext;
  }
  public Item getNext() {
    return this.next;
  }
  public int getValue() {
    return this.value;
  }
}
public class LinkedList {
  private Item start;
  public void addToFront(int value) {
    start = new Item(value, start);
  }
  public int get(int index) {
  }
}
public class Example {
  public static void main(String[] unused) {
  }
}
....

[[HIFRUbegMElyTCRryTvdWMzsnTFvAaJp]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class LinkedList {
  public int get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
LinkedList list = new LinkedList();
list.addToFront(1);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  start -> Item1
</div>
++++

[[huaxLPNSoVSkxUbFnCUWqRwuDZQqgJMw]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class LinkedList {
  public int get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
LinkedList list = new LinkedList();
list.addToFront(1);
list.addToFront(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  Item2 [ label = "Item|2" ]
  start -> Item2
  Item2 -> Item1
</div>
++++

[[MtSJPhEljoKufnnBjwnMhJzpMuTmWMFr]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class LinkedList {
  public int get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
LinkedList list = new LinkedList();
list.addToFront(1);
list.addToFront(2);
list.addToFront(3);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[OQXWCIblWobBKVCXOmUNWFOkQhCKuFkj]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class LinkedList {
  public int get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
LinkedList list = new LinkedList();
list.addToFront(1);
list.addToFront(2);
list.addToFront(3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item0 [ label = "Item|1" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item0
</div>
++++

[[uTCRqFIioaWUbZXxmfyHvXYrSAEEPpnH]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class LinkedList {
  public int get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
LinkedList list = new LinkedList();
list.addToFront(1);
list.addToFront(2);
list.addToFront(3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3", fillcolor="lightblue", style="filled" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[IEKNGKZOSoQTcaAWJVuwbUBrlUaleLHp]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class LinkedList {
  public int get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
LinkedList list = new LinkedList();
list.addToFront(1);
list.addToFront(2);
list.addToFront(3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1" ]
  Item2 [ label = "Item|2", fillcolor="lightblue", style="filled" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[bcglIwAIsYtwxwTorcPMDROVbXnqTSvu]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class LinkedList {
  public int get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
LinkedList list = new LinkedList();
list.addToFront(1);
list.addToFront(2);
list.addToFront(3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1", fillcolor="lightblue", style="filled" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[wOcKkEBJTHkkCcDKpEwCCNYvCSUinhUY]]
[.ss]
== `LinkedList`: `get`

[source,java,role='smaller']
----
public class LinkedList {
  public int get(int index) {
    // until I get to the index
    // follow each Item to the next
  }
}
LinkedList list = new LinkedList();
list.addToFront(1);
list.addToFront(2);
list.addToFront(3);
list.get(2);
----

<<<

++++
<div class="digraph small TB mx-auto">
  Item1 [ label = "Item|1", fillcolor="green", style="filled" ]
  Item2 [ label = "Item|2" ]
  Item3 [ label = "Item|3" ]
  start -> Item3
  Item3 -> Item2
  Item2 -> Item1
</div>
++++

[[HukfpNfUOulnnDElwTJYZyNKTvhGgtDM]]
== `ArrayList` v. `LinkedList`

[.lead]
//
Both provide the _same_ functionality, but with different _performance_
characteristics.

[width="100%",cols="^,^,^",options='header']
|===

^| Operation
^| `ArrayList`
^| `LinkedList`

| `add` (at front)
| [.s]#O(n)#
| [.s]#*O(1)*#

| `get` and `set`
| [.s]#*O(1)*#
| [.s]#O(n)#

| `insert` (anywhere)
| [.s]#O(n)#
| [.s]#O(n)#

|===

[[pxmMRUovvighafzysajDTLzYWtXOPhQH]]
== Announcements

* link:/MP/4/[MP4] is due Friday. The early deadline is *today*.
//
* We've added an
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!
//
* Continue to communicate with the course staff about the strike as needed.
We're trying to keep everything up and running.
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
