---
title: More Constructs
date: 2018-02-07
description:
  More imperative programming constructs and practice with algorithms.
spelling_exceptions:
  - GCD
echo: https://goo.gl/2cZ9hi
---
:imagesdir: /slides/images
:!sectids:

[[GfHTlawcMZRgXqXNhwcWsVHYtFCxBOvF]]
== !

[.janini.smaller]
--
++++
<div class="message">More Constructs<br/>Press Control-Return to run the code above</div>
++++
....
char[][] currentBoard =
  {{'X', 'O', '.'}, {'O', 'X', 'X'}, {'O', 'O', 'O'}};
static char checkBoard(char[][] board) {
  for (int i = 0; i < board.length; i++) {
    if (board[i][0] != '.' &&
        board[i][0] == board[i][1] &&
        board[i][1] == board[i][2]) {
      return board[i][0];
    }
  }
  return '.';
}
System.out.println(checkBoard(currentBoard));
....
--

[[FvnOrONtOGvRaMNKSpkqprbJULYznddV]]
== Q2 Review: Empty Arrays

[source,java]
----
boolean g(char[] x, char[] y) {
  if (x.length != y.length) {
    return false;
  }
  for (int i = 0; i < x.length; i++) {
    if (x[i] != y[i]) {
      return false;
    }
  }
  return true;
}
----

What happens if the function above is called with two empty arrays?

[[OQextsmyguYvUttCdRdyfPDnmqIyfHEv]]
== ! Q2 Review: Empty Arrays

[.janini.smaller]
....
static boolean g(char[] x, char[] y) {
  if (x.length != y.length) {
    return false;
  }
  for (int i = 0; i < x.length; i++) {
    if (x[i] != y[i]) {
      return false;
    }
  }
  return true;
}
System.out.println(g(new char[0], new char[0]));
....

[[yowTfLIYTfvavaanoBreRJauXiHjoPbW]]
== Q2 Review: Javadoc

[.lead]
//
If you don't write good Javadoc comments, which of the following will not
happen?

[[QgZlrXBjAYxDfwzBoJvdtwsBeKeoezTQ]]
== Q2 Review: Problems

[source,java]
----
boolean t(String f, String g) {
  for (int i = 0; i < f.length(); i++) {
    if (f.charAt(i) != g.charAt(g.length() - i)) {
      return false;
    }
  }
  return true;
}
----

What are problems with the code above?

[[MFVdvwNSHySuUhXPxpkIQGLYKRhxsWrQ]]
== ! Q2 Review: Problems

[.janini.small]
....
// Let's clean up this mess
static boolean t(String f, String g) {
  for (int i = 0; i < f.length(); i++) {
    if (f.charAt(i) != g.charAt(g.length() - i)) {
      return false;
    }
  }
  return true;
}
....

[[NKfHfMNXFWmCUHYZENuiqMTIjhQkFfRu]]
== Q2 Review: Functions

[.lead]
//
What is _not_ a reason to break your code into functions?

[[aqdhiuUidCXSagiBqzZHGcOwuDTjEYTf]]
== Q2 Review: Quickly

[quote]
____
https://www.merriam-webster.com/dictionary/iterate[iterate]:
//
to say or do again or again and again
____

(Like in a `for` loop.)

[source,java]
----
void printStuff() {
  System.out.println("Stuff");
}
----

[[zqkWJGCYXfgOIAVqIEaVDzqdRRbYKglb]]
== The do-while Loop

[.lead]
//
Remember the `while` loop?

[source,java]
----
while (condition) {
  // do something
}
----

It also has a friend:

[.s]
--
[source,java]
----
do {
  // do something
} while (condition);
----

What's the difference?
--


[[WmfAYAcjhSGdGmaAuCEzbIuCSkaGdSPs]]
== Split Name

[.lead]
//
Imagine I have a person's full name in a string in either one of the following
two formats:

. "First Last", or
//
. "Last, First"

Write a function to split the name into two string values: one storing the first
name and the second storing the last name.

[[iJAoMgezojhJraOapZjwJeDJayWJGcqe]]
[.oneword]
== What's Our Algorithm?

[[cfvgLyEhXtEsVVRaohUePFhFjwpUVfyP]]
== ! Split Name

[.janini.small]
....
// Split into first and last name
String fullName = "Chuchu Challen";
....

[[JCtcfRHYmACtmdBvICfodQLzJaIZgNgn]]
== ! Here's Some Help

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/lang/String.html"></iframe>
</div>
++++

[[ljWwNiTNUZTcMwVnwMCthxpYtdaHFbqP]]
== Announcements

* link:/MP/2/[MP2] is out and due _on Friday_. Please get started!

* The _next_ set of Turing's Craft exercises (TC6) are due _tomorrow_ at midnight.

* My office hours start today after class and continue MWF at 11AM in the lounge
outside 0226.
//
Please stop by to say hi, chat about the class and computer science in general,
or if you have any questions.
//
I look forward to meeting you!

// vim: ts=2:sw=2:et
