---
title: Practice with Recursion
date: 2018-03-14
description:
  Continuation of recursive practice on binary trees.
draft: true
---

[[voXqzPFbehmlKvzPJindiCNjYHooPgth]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Practice with Recursion</div>
++++
....
import java.util.Random;

public class Tree {
  Random random = new Random();
  public int value;
  public Tree right;
  public Tree left;

  Tree(int setValue) {
    value = setValue;
  }
  Tree(int[] array) {
    value = array[0];
    for (int i = 1; i < array.length; i++) {
      add(array[i]);
    }
  }

  public void add(int value) {
    if (right == null) {
      right = new Tree(value);
    } else if (left == null) {
      left = new Tree(value);
    } else if (random.nextBoolean()) {
      right.add(value);
    } else {
      left.add(value);
    }
  }

  public String toString() {
    String returnString = "" + value;
    if (left != null) {
      returnString += " " + left.toString();
    }
    if (right != null) {
      returnString += " " + right.toString();
    }
    return returnString;
  }
}

public class Example {
  public static void main(String[] unused) {
    Tree tree = new Tree(new int[] { 1, 2, 3, 4 });
    System.out.println(tree);
  }
}
....
--

[[cqVgjZbBhDimdNKBlxRPJOBMHZzAYZob]]
== Recursive Implementation

[source,java]
----
int factorial(int n) {
  if (n == 1) {
    return 1;
  } else {
    return n * factorial(n - 1); // I called myself!
  }
}
----

[.lead]
//
We refer to a function that calls itself as a _recursive function_.

[[IdXQXruptJpAnhOJVkFnLBgrlzoQCoHp]]
== ! Recursive Factorial

[.janini.smaller]
....
static int factorial(int n) {
  if (n == 1) {
    return 1;
  } else {
    return n * factorial(n - 1);
  }
}
System.out.println(factorial(4));
....

[[rbbSGYKLgdxZlQMHziyxVIXYJEMfusDQ]]
== Recursive Strategies

[.lead]
//
Recursion can be _hard_ to wrap your mind around at first.
//
But these three strategies will help.

[.s]
//
. *Know when to stop.* When you identify the smallest subproblem, you must
return. Otherwise your program will not terminate. This is also called the _base
case_.
//
. *Make the problem smaller in each step.* If the problem doesn't get smaller,
you will never reach the base case. This is also called the _recursive step_.
//
. *Combine results from your recursive calls properly.*

[[gRDqpIvNYsoaRJfrfHSXsebpZMSkrUuJ]]
== Recursive Tree Right Greater Than Left

[.lead]
//
Let's find the number of nodes in our tree where the value of the right child is
greater than or equal to value of the left child.

[[SYKjilNSxLlsdxRsuxYvvTgpGnSqBtXT]]
[.oneword]
//
== What's Our (Recursive) Algorithm?

[[zSswMAKnLOEUAmowsjltDxsmgyLuCSii]]
== Recursive Tree Right Greater Than Left

[.s]
//
* *Base case*: [.s]#We've reached a tree with one node. It does not have a right
child or left child, so we can return 0.#
//
* *Recursive step*: [.s]#Consider our right tree and left tree separately.#
//
* *Combine results*: [.s]#Determine whether our right child is greater than our
left child. If so, add 1 to the sum of results from our left and right child.#

[[LWTPSosRFqExmcZpSPYAxSifaSoFXjZU]]
== !Recursive Right Greater Than Left Example

[.janini.compiler.smallest]
....
import java.util.Random;

public class Tree {
  Random random = new Random();
  public int value;
  public Tree right;
  public Tree left;

  Tree(int setValue) {
    value = setValue;
  }
  Tree(int[] array) {
    value = array[0];
    for (int i = 1; i < array.length; i++) {
      add(array[i]);
    }
  }

  public void add(int value) {
    if (right == null) {
      right = new Tree(value);
    } else if (left == null) {
      left = new Tree(value);
    } else if (random.nextBoolean()) {
      right.add(value);
    } else {
      left.add(value);
    }
  }

  public int rightGreaterThanLeft() {
  }
}

public class Example {
  public static void main(String[] unused) {
    Tree tree = new Tree(new int[] { 1, 2, 3, 4 });
    System.out.println(tree.rightGreaterThanLeft());
  }
}
....

[[WAyrLFXUzCWZNywsuBwGVRNlfQyIsaxV]]
== Recursive Tree Print Leaves

[.lead]
//
Let's print _only_ leaf nodes: those that have neither a left nor a right child.

[[wFkePtuoPHtjiQgMUaRMxqrXubVNPQoY]]
[.oneword]
//
== What's Our (Recursive) Algorithm?

[[nBBvXLuotvVfrtrnfEEjpVKYJqQqZZYK]]
== Recursive Tree Print Leaves

[.s]
//
* *Base case*: [.s]#We've reached a tree with no left or right node. It's also a
a leaf node, so print our value.#
//
* *Recursive step*: [.s]#Consider our right tree and left tree separately.#
//
* *Combine results*: [.s]#Nothing to do here, just continue down the tree.#

[[ApTsFupsyGxTnQxQNOutQbJTYqctEttB]]
== !Recursive Tree Print Leaves

[.janini.compiler.smallest]
....
import java.util.Random;

public class Tree {
  Random random = new Random();
  public int value;
  public Tree right;
  public Tree left;

  Tree(int setValue) {
    value = setValue;
  }
  Tree(int[] array) {
    value = array[0];
    for (int i = 1; i < array.length; i++) {
      add(array[i]);
    }
  }

  public void add(int value) {
    if (right == null) {
      right = new Tree(value);
    } else if (left == null) {
      left = new Tree(value);
    } else if (random.nextBoolean()) {
      right.add(value);
    } else {
      left.add(value);
    }
  }

  public void printLeaves() {
  }
}

public class Example {
  public static void main(String[] unused) {
    Tree tree = new Tree(new int[] { 1, 2, 3, 4 });
    tree.printLeaves();
  }
}
....

[[MKTKEwmTmxMuIDInwIpRNxHlUZshIsmb]]
== Recursive Tree Search

[.lead]
//
Let's determine whether a tree contains a certain value.

[[ngirvffoqoVGBWAiUDJsvyNkZwEiGOey]]
[.oneword]
//
== What's Our (Recursive) Algorithm?

[[ewLkRIFqyrsFlNUbTYbeQysFyvkpYWoD]]
== Recursive Tree Search

[.s]
//
* *Base case*: [.s]#We've reached a node with no descendants. Return true if
it's value matches, zero otherwise.#
//
* *Recursive step*: [.s]#Consider our right tree and left tree separately.#
//
* *Combine results*: [.s]#Return true if either we or our right or left subtree
contain the search value.#

[[LByULNOsTbXEXKjWCAKWIPaJmRtpKfIm]]
== !Recursive Tree Search

[.janini.compiler.smallest]
....
import java.util.Random;

public class Tree {
  Random random = new Random();
  public int value;
  public Tree right;
  public Tree left;

  Tree(int setValue) {
    value = setValue;
  }
  Tree(int[] array) {
    value = array[0];
    for (int i = 1; i < array.length; i++) {
      add(array[i]);
    }
  }

  public void add(int value) {
    if (right == null) {
      right = new Tree(value);
    } else if (left == null) {
      left = new Tree(value);
    } else if (random.nextBoolean()) {
      right.add(value);
    } else {
      left.add(value);
    }
  }

  public static boolean search(Tree tree, int value) {
  }
}

public class Example {
  public static void main(String[] unused) {
    Tree tree = new Tree(new int[] { 1, 2, 3, 4 });
    System.out.println(Tree.search(tree, 4));
  }
}
....

[[IOOCxXrcOvEnrMjoNsixcoECGwxRdHzd]]
== Announcements

* link:/MP/4/[MP4] is due _today_ at 5PM.
//
* MP5 will be released today at 5PM.
//
* We've added an
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.
I'll need to leave at 11:30AM.

// vim: ts=2:sw=2:et
