---
title: Practice with Functions and Strings
date: 2018-02-02
description:
  More practice with functions and Java Strings.
spelling_exceptions:
  - GCD
echo: https://goo.gl/p5zyXq
---
:imagesdir: /slides/images
:!sectids:

[[tEtREXcdwvLNenEEApUWWxYcIyInPqrh]]
== !

[.janini.small]
--
++++
<div class="message">Practice with Functions and Strings</div>
++++
....
String[] courses = { "CS 125", "CS 225", "CS 241" };
static void bestCourse(String[] options) {
  for (String course: options) {
    System.out.print(course);
    if (course.contains("125")) {
      System.out.print(" is the best");
    }
    System.out.println();
  }
}
bestCourse(courses);
....
--

[[QXeDdtoIJghFLWgVVxlLDTyJGYnfkMyM]]
[.oneword]
== Algorithmic Thinking and Problem Solving

[[BujyetipnNDrtCDwOkrBiiTJbXjxHwVu]]
[.oneword]
== But First: More About Functions

[[WYGKDMJrYLPMExMvDrlPcHvhJXJULrdT]]
== Java Method Overloading

[.lead]
//
I told you that functions couldn't have the same name.

[.s]
--
*I lied.*
--

[[iJVMrRgNoMDSQndAuhyBGsxwipXUxmyY]]
== ! Bad Professor

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://www.usnews.com/education/blogs/professors-guide/2010/01/06/10-warning-signs-of-a-bad-professor"></iframe>
</div>
++++

[[wswjWrauPrlUigRkLcyzcewZsvsCXVAL]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  return first + second;
}
static double sum(double first, double second) {
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
System.out.println("WTF?!");
....

[[hMOkqKTcxmOlCMscnAhDrISCCrbmuKSA]]
== Java Method Overloading

[.lead]
//
Java uses _both_ the function name _and_ the the list of arguments and types to
determine which function to call.

Together they are called the _function signature_.

[.s]
//
. *Does the function have the right name?*
//
. *Does the function take the right arguments in the right order?*
//
. Java will also try to convert types to find a match as long as no loss of
precision occurs

[[gSVpdvguUsItuviFdwvmyPOhnMVwlErX]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  System.out.println("Summing ints");
  return first + second;
}
static double sum(double first, double second) {
  System.out.println("Summing doubles");
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
....

[[uHxLfZRUUSeKHKZXVkQEndWETbAOgXOj]]
== Function Input Validation

[.lead]
//
A common function design pattern is to _check your inputs at the top_.

Think about all the bad inputs you could possibly get from the caller.

[source,java]
----
int sum(int[] numbers) {
  // check numbers to make sure it's sane
}
----

[[IvXkDdLRgNBLsSBPsbafXVMWXMQbkIQF]]
== ! Function Input Validation

[.janini.small]
....
static int sum(int[] numbers) {
  // check numbers to make sure it's sane
}
....

[[yBXWpiIYZpCTIiwedPUiflmeXRDXXbyM]]
== `null` Arrays

[.lead]
//
What is the value of array declared below?

[source,java]
----
int[] output = null;
System.out.println(output);
----

[.s]
//
* Java has a special value that can be used to indicate that an object has not
been initialized: `null`.
//
* `null` is not a valid object: it has no properties or methods that you can
use.
//
* Attempts to use `null` will result in an error

[[EaGRLETbzDaduqdILxVMZGtholIVxhZu]]
== ! `null` Arrays

[.janini]
....
int[] output = null;
System.out.println(output);
System.out.println(output.length);
....

[[MtRsCbMHmLhOLCCaHMlzRjbUaAvypYeW]]
[.oneword]
== Defensive Programming 101

[.lead]
//
*Always check objects for `null`.*

[[bFVBvhmjufzGfxvxxruaPuBSduFKcJlu]]
[.oneword]
== Let's Solve Some Problems!

[[nXJaqYifBIRupMOUvdurSxJJtMqOMjnO]]
== Consecutive Identical Values

[.lead]
//
Given a string, write a function to find all cases where consecutive characters
are the same.

*First, what is our algorithm?*

[.s]
//
. Examine each character in the array
//
. Compare it with the next character&mdash;but how do we get at that?
//
. Print it out if they are the same

[[myIIGowgWcgYdJyAHTrrOBJNehWuJjkr]]
== ! Consecutive Identical Characters

[.janini.small]
....
// Print consecutive identical characters
String toSearch = "abcdefeffh";
....

[[OEzuTpurwrhHSauViYyTwSIyybNxVVVz]]
== ! Read The Documentation

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/lang/String.html"></iframe>
</div>
++++

[[agRjmuPXNFgsskQjpuMryxBeLimsaExA]]
== Testing

[.lead]
//
Test cases are an indispensable part of modern software development.

[.s]
//
* To perform a simple test, pick a input that you know the answer to and check
that your function returns the expected value.
//
* Try to pick cases that are hard and where you might not get the right
answer&mdash;we call these _corner cases_.

[[DiVVcOhkSBTwKHQcrnPQCRTjBuzasxRF]]
== Announcements

* Quiz 2 starts today in the CBTF. It covers arrays, functions, and strings.
//
* The fifth set of Turing's Craft exercises (TC 5) will be out shortly and due
*Sunday* by midnight.
//
* link:/MP/1/[MP1] is due today!
//
https://cs125.cs.illinois.edu/info/resources/#hours[Office hours]
//
until 5PM today.
//
* MP2 will be out today and due next week&mdash;it's another new challenge.

// vim: ts=2:sw=2:et
