---
title: Practice with Functions and Strings
date: 2018-02-02
description:
  More practice with functions and Java Strings.
spelling_exceptions:
  - GCD
---
:imagesdir: /slides/images
:!sectids:

[[tEtREXcdwvLNenEEApUWWxYcIyInPqrh]]
== !

[.janini.small]
--
++++
<div class="message">Practice with Functions and Strings<br/>Press Control-Return to run the code above</div>
++++
....
String[] courses = { "CS 125", "CS 225", "CS 241" };
static void bestCourse(String[] options) {
  for (String course: options) {
    System.out.print(course);
    if (course.contains("125")) {
      System.out.print(" is the best");
    }
    System.out.println();
  }
}
bestCourse(courses);
....
--

[[QXeDdtoIJghFLWgVVxlLDTyJGYnfkMyM]]
[.oneword]
== Algorithmic Thinking and Problem Solving

[[BujyetipnNDrtCDwOkrBiiTJbXjxHwVu]]
[.oneword]
== But First: More About Functions

[[WYGKDMJrYLPMExMvDrlPcHvhJXJULrdT]]
== Java Method Overloading

[.lead]
//
I told you that functions couldn't have the same name.

[.s]
--
*I lied.*
--

[[iJVMrRgNoMDSQndAuhyBGsxwipXUxmyY]]
== ! Bad Professor

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://www.usnews.com/education/blogs/professors-guide/2010/01/06/10-warning-signs-of-a-bad-professor"></iframe>
</div>
++++

[[wswjWrauPrlUigRkLcyzcewZsvsCXVAL]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  return first + second;
}
static double sum(double first, double second) {
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
System.out.println("WTF?!");
....

[[hMOkqKTcxmOlCMscnAhDrISCCrbmuKSA]]
== Java Method Overloading

[.lead]
//
Java uses _both_ the function name _and_ the argument signature to determine
which function to call.

[.s]
//
. *Does the function have the right name?*
//
. *Does the function take the right arguments in the right order?*
//
. Java will also try to convert types to find a match as long as no loss of
precision occurs

[[gSVpdvguUsItuviFdwvmyPOhnMVwlErX]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  System.out.println("Summing ints");
  return first + second;
}
static double sum(double first, double second) {
  System.out.println("Summing doubles");
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
....

[[uHxLfZRUUSeKHKZXVkQEndWETbAOgXOj]]
== Function Input Validation

[.lead]
//
A common function design pattern is to _check your inputs at the top_.

Think about all the bad inputs you could possibly get from the caller.

[source,java]
----
int sum(int[] numbers) {
  // check numbers to make sure it's sane
}
----

[[IvXkDdLRgNBLsSBPsbafXVMWXMQbkIQF]]
== ! Function Input Validation

[.janini.small]
....
static int sum(int[] numbers) {
  // check numbers to make sure it's sane
}
....

[[yBXWpiIYZpCTIiwedPUiflmeXRDXXbyM]]
== `null` Arrays

[.lead]
//
What is the value of array declared below?

[source,java]
----
int[] output = null;
System.out.println(output);
----

[.s]
//
* Java has a special value that can be used to indicate that an object has not
been initialized: `null`.
//
* `null` is not a valid object: it has no properties or methods that you can
use.
//
* Attempts to use `null` will result in an error

[[EaGRLETbzDaduqdILxVMZGtholIVxhZu]]
== ! `null` Arrays

[.janini]
....
int[] output = null;
System.out.println(output);
System.out.println(output.length);
....

[[MtRsCbMHmLhOLCCaHMlzRjbUaAvypYeW]]
[.oneword]
== Defensive Programming 101

[.lead]
//
*Always check objects for `null`.*

[[bFVBvhmjufzGfxvxxruaPuBSduFKcJlu]]
[.oneword]
== Let's Solve Some Problems!

[[nXJaqYifBIRupMOUvdurSxJJtMqOMjnO]]
== Consecutive Identical Values

[.lead]
//
Given a string, write a function to find all cases where consecutive characters
are the same.

*First, what is our algorithm?*

[.s]
//
. Examine each character in the array
//
. Compare it with the next character&mdash;but how do we get at that?
//
. Print it out if they are the same

[[myIIGowgWcgYdJyAHTrrOBJNehWuJjkr]]
== ! Consecutive Identical Characters

[.janini.small]
....
// Print consecutive identical characters
String toSearch = "abcdefeffh";
....

[[dgqLkvllIxGBVWNUgvWRaphpbprIUZmd]]
== Split Name

[.lead]
//
Imagine I have a person's full name in a string in either one of the following
two formats:

. "First Last", or
//
. "Last, First"

Write a function to split the name into two string values: one storing the first
name and the second storing the last name.

[[uLcwjkMviNxXzPUGSvzKOnXZejIuVdiV]]
[.oneword]
== What's Our Algorithm?

[[OEzuTpurwrhHSauViYyTwSIyybNxVVVz]]
== ! Read The Documentation
++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/lang/String.html"></iframe>
</div>
++++

[[LusbpptlAvcVVksiUCrVcWRbBGsDtOkn]]
== ! Split Name

[.janini.small]
....
// Split into first and last name
String fullName = "Chuchu Challen";
....

[[gPucDaBMQDrRTTpzHGhYeKkUqKBFQzyR]]
== Search Text

[.lead]
//
Given a line of text, write a function that searches for all occurrences of a
given word.

[[eyqUvEBDookviajBvuXtPufaOcUyPAhM]]
[.oneword]
== What's Our Algorithm?

[[CjUbIEwBODHnKAjrDdalyYWzIqZflMlk]]
== ! Search Text

[.janini.small]
....
// Search text for a specific word
String text = "Where do random thoughts come from?"
....

[[okKIJujIjYYDDEdlozylLUFAAHzzvtyo]]
== Most Common Character

[.lead]
//
Given a string, determine which character appears most often.

[[rRjIZhZaJLkxOjhsHvbgusjuJxhsbqAg]]
[.oneword]
== What's Our Algorithm?

[[JCtcfRHYmACtmdBvICfodQLzJaIZgNgn]]
== ! Here's Some Help

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html"></iframe>
</div>
++++

[[dfZDbioIVRPdrUKNnAedFUWRYIlHwlEC]]
== Most Common Character

[.janini.small]
....
// Determine the most common character
static char mostCommon(String input) {
}
System.out.println(mostCommon("AAAbcd"));
....

[[agRjmuPXNFgsskQjpuMryxBeLimsaExA]]
== Testing

[.lead]
//
Test cases are an indispensable part of modern software development.

[.s]
//
* To perform a simple test, pick a input that you know the answer to and check
that your function returns the expected value.
//
* Try to pick cases that are hard and where you might not get the right
answer&mdash;we call these _corner cases_.

[[BzRRFIMstyqbRXhqEywqvIoQJUgYebbD]]
== Greatest Common Denominator

[quote]
//
____
//
In mathematics, the
//
https://en.wikipedia.org/wiki/Greatest_common_divisor[greatest common divisor
(GCD)]
//
of two or more integers, which are not all zero, is the largest positive integer
that divides each of the integers.
//
____

[[pjDljAIzRjELOcfeobkDQFRinIBUMrhD]]
== ! GCD Algorithms

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://en.wikipedia.org/wiki/Greatest_common_divisor#Calculation"></iframe>
</div>
++++

[[tDXMsVMWQaICoZpNjRwvYQvYvpkBVCKA]]
[.oneword]
== But If We're In A Hurry...

[[JssrqejyvIyvwsXyrCkspJKxdKDMQLRk]]
== Brute Force Solution

[quote]
____
https://en.wikipedia.org/wiki/Brute-force_search[Brute force solution]:
//
a very general problem-solving technique that consists of systematically
enumerating all possible candidates for the solution and checking whether each
candidate satisfies the problem's statement.
____

[.s]
//
* Computers today are very, _very_ fast
//
* So try the simple thing first
//
* If it's too slow, try something a bit more sophisticated

[[qMuYttxuubacRODFMWhjihipuaPhWYqH]]
== ! GDC Implementation

[.janini.small]
....
// Print the GCD
System.out.println(gcd(24, 18));
....

[[qdXwzQeEINKOPgbceNliwLWeLNyqnSVo]]
== ! Bring the Brute

image::https://cdn.vox-cdn.com/thumbor/wgMcgj6LStdjW-qlLkaHUBsdQzY=/0x0:2048x858/1200x800/filters:focal(834x251:1160x577)/cdn.vox-cdn.com/uploads/chorus_image/image/57442421/hulk_agnarok.0.jpg[role='mx-auto meme',width=640]

[[SAkZunVquojxGluWfhHFkLljmuDEmoNB]]
[.oneword]
== You Don't Need the Fastest Algorithm to Change the World

That's a good thing!

[[XIAanwdDVyALfCEgZLNQljuMKfylgtld]]
== But How Long Will It Take?

[.lead]
//
How long will our brute force GCD algorithm take?

[.s]
//
* To compute the GCD of 4 and 6
//
* To compute the GCD of 185 and 2045
//
* To compute the GCD of M and N


// vim: ts=2:sw=2:et
