---
title: Object Review
date: 2020-03-02
description:
  A chance to slow down and review Java objects, including instances,
  constructors, class design, inheritance, and polymorphism.
spelling_exceptions:
  - Liskov
---

[[yvPGyAzjIWxppDwhCkgPugvxiKuRyxUi]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Object Review</div>
++++
....
public class Pet {
  public void printMe() {
    System.out.println("I'm a pet");
  }
}
public class Dog extends Pet {
  public void printMe() {
    System.out.println("I'm a dog");
  }
}
public class Example {
  public static void main(String[] unused) {
    Pet chuchu = new Dog();
    Pet xyz = new Pet();
    chuchu.printMe();
    xyz.printMe();
  }
}
....
--

[[euFmCPofTEKYzhHanuwnTAvSmxizieuF]]
[.oneword]
//
== Who's Frustrated?

Probably everyone.
//
[.s]#What do you do when you're frustrated?#


[[tJAEhRBaxOdrIAfHFqeluBfFBFVZEkZI]]
== Review: Polymorphism

[quote]
____
https://en.wikipedia.org/wiki/Polymorphism_(computer_science)[Polymorphism]:
//
the provision of a single interface to entities of different types.
____

[[xejQOFdnYNedKmENRxJOESdlitSRXvBw]]
== Subtype Polymorphism

[source,java,role='small']
----
public class Pet {
  public void printMe() {
    System.out.println("I'm a pet");
  }
}
public class Dog extends Pet {
  public void printMe() {
    System.out.println("I'm a dog");
  }
}
----

[.lead]
//
In Java, _every_ object is really an instance of at least _two_ types:

[.s]
//
* Each `Pet` is also an `Object`
//
* Each `Dog` is also a `Pet` and also an `Object`

[[zAfgNaUvOdTRoYcImWOGArtsyjxiCuXW]]
== Object Upcasting

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
----

[.lead]
//
Java will _upcast_ object types automatically.

[[CibxAzCMpvrFpjbBUcHRBnCoPdroMZDc]]
== ! Object Conversion: Upcasting

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
....

[[YHYXBIyexgSczCgXpNsrgcVZtiCWeifQ]]
== But Instances Retain Their Types

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Object chuchuAsObject = chuchu;
    System.out.println(chuchuAsObject);
    Pet chuchuAsPet = chuchu;
    System.out.println(chuchuAsPet);
  }
}
----

[[faLGlVEpJnzuilavUdSpPJnjoRNXqcsn]]
== ! But Instances Retain Their Types

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Object chuchuAsObject = chuchu;
    System.out.println(chuchuAsObject);
    Pet chuchuAsPet = chuchu;
    System.out.println(chuchuAsPet);
  }
}
....

[[sdlBDsmJxGzipqJCuKbCXcwbxKBRbrno]]
== Object Downcasting

[source,java,role='smallest']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Object chuchu = new Dog();
    Example.printAnything(chuchu);
    Pet chuchuAsPet = (Pet) chuchu; // chuchu is a Pet, so this works
    Example.printAnything(chuchuAsPet);
  }
}
----

[.lead]
//
We can also cast instances _down_ but only if the instance is
actually the appropriate subtype.

Java checks the cast at runtime to make sure that it is appropriate.

[[GJrYLdzWnTewfJWDGEyNqVxQyxjMmJCk]]
== ! Object Conversion: Downcasting

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Object chuchu = new Dog();
    System.out.println(chuchu);
    Pet chuchuAsPet = (Pet) chuchu; // chuchu is a Pet, so this works
    System.out.println(chuchuAsPet);
    Dog chuchuAsDog = (Dog) chuchu; // chuchu is also a Dog, so this works
    System.out.println(chuchuAsDog);
  }
}
....

[[CpZeQftzcOFsQCDCxiBqCcyBJtoOHNvI]]
== Type Testing: `instanceof`

[source,java,role='smallest']
----
public class Pet { }
public class Dog extends Pet { }
public class Cat extends Pet { }
public class Example {
  public static void main(String[] unused) {
    Pet chuchu = new Dog();
    Pet xyz = new Cat();
    System.out.println(chuchu instanceof Dog); // Prints true
    System.out.println(chuchu instanceof Pet); // Prints true
    System.out.println(chuchu instanceof Cat); // Prints false
  }
}
----

The Java `instanceof` operator allows you to test whether an object is an
instance of _or_ a descendant of a particular class.

[[OefedXVUqXZifDYrxutlCilKEnwfvnij]]
== ! Type Testing: `instanceof`

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet { }
public class Cat extends Pet { }
public class Example {
  public static void main(String[] unused) {
    Pet chuchu = new Dog();
    Pet xyz = new Cat();
    System.out.println(chuchu instanceof Dog); // Prints true
    System.out.println(chuchu instanceof Pet); // Prints true
    System.out.println(chuchu instanceof Cat); // Prints false
  }
}
....


[[AtydbVpehoLTEsgqUCgcTyIHlnazMXPZ]]
== Liskov Substitution Principle

[quote,role='spelling_exception']
____
https://en.wikipedia.org/wiki/Liskov_substitution_principle[Substitutability]
//
is a principle in object-oriented programming stating that, in a computer
program, if S is a subtype of T, then objects of type T may be replaced with
objects of type S (i.e. an object of type T may be substituted with any object
of a subtype S) without altering any of the desirable properties of T
(correctness, task performed, etc.).
____

[[nUWyBwYOCDtTXFYmxzjQBKdtSVcLLhjZ]]
== Substitutability in Practice

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
----

Since everything is an `Object`, any Java object inherits all of the desirable
properties of `Object`: like `toString`.

[[VhyrHDhYiwsScmHUunmuvwgwbiWRJPqJ]]
[.oneword]
== Subtype Polymorphism

[.lead]
//
We can always use `toString`, but every class can implement it
differently.

[[yvYtRfULCbIvhMMdEOcGHIreUrBynaXT]]
[.oneword]
== Same Names, Different Behavior

[.lead]
//
Where else have we seen this before?

[[vGwilOBrBAWUfzutpyvFACGGhIYzMNyQ]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  return first + second;
}
static double sum(double first, double second) {
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
....

[[CaeAiZMIixRpAkCxQeiqMdVeitvqdxFV]]
== Polymorphism

[quote]
____
https://en.wikipedia.org/wiki/Polymorphism_(computer_science)[Polymorphism]:
//
the provision of a single interface to entities of different types.
____

[.s]
//
* *Subtype polymorphism*: a single method can act on all descendants of a given
class
//
* *Method overloading*: a method can behave differently depending on its arguments
//
* Generics (discussed later)

[[jiSCXBdAuOnhpItuaduAEfKpwsGqyKYz]]
== Worked Examples

Please refer to
//
https://youtu.be/XgDbzmHQh_w?t=1998[last semester's video]
//
for a walkthrough of how to complete one of the recent homework problems.

[[aeVJuVbnHSUwndHSELusYguefZbWovbn]]
[.oneword]
//
== Questions About Objects?

[[HiLlpvxKziOlYYkRfdKZIjluYKLMNtQj]]
== Announcements

* Congrats to the Blue Team for finishing up MP1!
//
Good luck to the Orange Team who have their deadline day today.
//
* link:/MP/2/[MP2] will be released at 8PM tonight.
//
* We have a
//
link:/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!

// vim: ts=2:sw=2:et
