---
title: Object Review
date: 2019-02-22
description:
  A chance to slow down and review Java objects, including instances,
  constructors, class design, inheritance, and polymorphism.
spelling_exceptions:
  - Liskov
---

[[yvPGyAzjIWxppDwhCkgPugvxiKuRyxUi]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Object Review</div>
++++
....
public class Pet {
  public void printMe() {
    System.out.println("I'm a pet");
  }
}
public class Dog extends Pet {
  public void printMe() {
    System.out.println("I'm a dog");
  }
}
public class Example {
  public static void main(String[] unused) {
    Pet chuchu = new Dog();
    Pet xyz = new Pet();
    chuchu.printMe();
    xyz.printMe();
  }
}
....
--

[[tJAEhRBaxOdrIAfHFqeluBfFBFVZEkZI]]
== Review: Polymorphism

[quote]
____
https://en.wikipedia.org/wiki/Polymorphism_(computer_science)[Polymorphism]:
//
the provision of a single interface to entities of different types.
____

[[xejQOFdnYNedKmENRxJOESdlitSRXvBw]]
== Subtype Polymorphism

[source,java,role='small']
----
public class Pet {
  public void printMe() {
    System.out.println("I'm a pet");
  }
}
public class Dog extends Pet {
  public void printMe() {
    System.out.println("I'm a dog");
  }
}
----

[.lead]
//
In Java, _every_ object is really an instance of at least _two_ types:

[.s]
//
* Each `Pet` is also an `Object`
//
* Each `Dog` is also a `Pet` and also an `Object`

[[zAfgNaUvOdTRoYcImWOGArtsyjxiCuXW]]
== Review: Object Upcasting

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
----

[.lead]
//
Java will _upcast_ object types automatically.

[[CibxAzCMpvrFpjbBUcHRBnCoPdroMZDc]]
== ! Object Conversion: Upcasting

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
....

[[YHYXBIyexgSczCgXpNsrgcVZtiCWeifQ]]
== But Instances Retain Their Types

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Object chuchuAsObject = chuchu;
    System.out.println(chuchuAsObject);
    Pet chuchuAsPet = chuchu;
    System.out.println(chuchuAsPet);
  }
}
----

[[faLGlVEpJnzuilavUdSpPJnjoRNXqcsn]]
== ! But Instances Retain Their Types

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Object chuchuAsObject = chuchu;
    System.out.println(chuchuAsObject);
    Pet chuchuAsPet = chuchu;
    System.out.println(chuchuAsPet);
  }
}
....

[[sdlBDsmJxGzipqJCuKbCXcwbxKBRbrno]]
== Review: Object Downcasting

[source,java,role='smallest']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Object chuchu = new Dog();
    Example.printAnything(chuchu);
    Pet chuchuAsPet = (Pet) chuchu; // chuchu is a Pet, so this works
    Example.printAnything(chuchuAsPet);
  }
}
----

[.lead]
//
We can also cast instances _down_ but only if the instance is
actually the appropriate subtype.

Java checks the cast at runtime to make sure that it is appropriate.

[[GJrYLdzWnTewfJWDGEyNqVxQyxjMmJCk]]
== ! Object Conversion: Downcasting

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Object chuchu = new Dog();
    System.out.println(chuchu);
    Pet chuchuAsPet = (Pet) chuchu; // chuchu is a Pet, so this works
    System.out.println(chuchuAsPet);
    Dog chuchuAsDog = (Dog) chuchu; // chuchu is also a Dog, so this works
    System.out.println(chuchuAsDog);
  }
}
....

[[AtydbVpehoLTEsgqUCgcTyIHlnazMXPZ]]
== Liskov Substitution Principle

[quote,role='spelling_exception']
____
https://en.wikipedia.org/wiki/Liskov_substitution_principle[Substitutability]
//
is a principle in object-oriented programming stating that, in a computer
program, if S is a subtype of T, then objects of type T may be replaced with
objects of type S (i.e. an object of type T may be substituted with any object
of a subtype S) without altering any of the desirable properties of T
(correctness, task performed, etc.).
____

[[nUWyBwYOCDtTXFYmxzjQBKdtSVcLLhjZ]]
== Substitutability in Practice

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
----

Since everything is an `Object`, any Java object inherits all of the desirable
properties of `Object`: like `toString`.

[[VhyrHDhYiwsScmHUunmuvwgwbiWRJPqJ]]
[.oneword]
== Subtype Polymorphism

[.lead]
//
We can always use `toString`, but every class can implement it
differently.

[[yvYtRfULCbIvhMMdEOcGHIreUrBynaXT]]
[.oneword]
== Same Names, Different Behavior

[.lead]
//
Where else have we seen this before?

[[vGwilOBrBAWUfzutpyvFACGGhIYzMNyQ]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  return first + second;
}
static double sum(double first, double second) {
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
....

[[CaeAiZMIixRpAkCxQeiqMdVeitvqdxFV]]
== Polymorphism

[quote]
____
https://en.wikipedia.org/wiki/Polymorphism_(computer_science)[Polymorphism]:
//
the provision of a single interface to entities of different types.
____

[.s]
//
* *Subtype polymorphism*: a single method can act on all descendants of a given
class
//
* *Method overloading*: a method can behave differently depending on its arguments
//
* Generics (discussed later)

[[nqWbDnGJqKLMIaHvSuYCGMtSXNjuiFnu]]
== Review: `Flip`

Define a public `class` named `Flip` with a single public instance method
called `flop` that takes no parameters and returns a `boolean`.
//
It should also provide a single constructor that takes a `boolean` argument that
sets the initial state of the `Flip` instance.

[[RSDJtKTdunEmcqILifrbnnxfEkmlrjgR]]
== Review: `FlipFlop`

Similar to our previous `Counter` example `Flip` maintains one piece of state,
the `boolean` value initialized in the constructor.
//
Calling `flop` changes the state from `false` to `true` or `true` to `false` and
returns the _new_ (not the old) state.
//
So, for example:

[source,java,role='smaller']
----
Flip flip = new Flip(true);
System.out.println(flip.flop()); // prints false
System.out.println(flip.flop()); // prints true
System.out.println(flip.flop()); // prints false

Flip flop = new Flip(false);
System.out.println(flop.flop()); // prints true
System.out.println(flop.flop()); // prints false
System.out.println(flop.flop()); // prints true
----

However, the internal state of your `Flip` class should be _private_.
//
Our test suite will check for this.

[[fqBIvbLbXdHTnliQyQwTDkOVwUPVBJhG]]
== ! Review: `Flip`

[.janini.small.compiler]
....
public class Example {
  public static void main(String[] unused) {
    Flip flip = new Flip(true);
    LastTen lastTen = new LastTen();
    for (int i = 0; i < 8; i++) {
      System.out.println(flip.flop());
    }
  }
}
....

[[orYebYemmWfwiIkouECEpHwzgUmvHngq]]
== Review: `LastTen`

Complete the implementation of a class called `LastTen`.
//
Your class should implement two public methods as described below:

. `void add(int newValue)`: add a new integer to the values that we are
remembering
//
. `int[] getLastTen()`: return the last ten values that were added using add, in
any order.
//
If fewer than ten values were added, you should return zeros in their place.

Your class should also provide a constructor that takes no arguments.
//
It should not expose any of its state publicly.

[[PuCamSKgLSZBtxPcnrGgUvIqvsJQfhtr]]
== ! `LastTen` Attempt 1

[.janini.small.compiler]
....
import java.util.Arrays;

public class Example {
  public static void main(String[] unused) {
    LastTen lastTen = new LastTen();
    for (int i = 0; i < 32; i++) {
      lastTen.add(i);
    }
    System.out.println(Arrays.toString(lastTen.getLastTen()));
  }
}
....

[[gGQSTGJEsdIRfuiEeTMNdLglNFSDhBZV]]
== ! `LastTen` Attempt 2

[.janini.small.compiler]
....
import java.util.Arrays;

public class Example {
  public static void main(String[] unused) {
    LastTen lastTen = new LastTen();
    for (int i = 0; i < 32; i++) {
      lastTen.add(i);
    }
    System.out.println(Arrays.toString(lastTen.getLastTen()));
  }
}
....

[[DUBdpEaAvnXiNefdsOofrRFDZTBMnApM]]
== ! `LastTen` Attempt 3

[.janini.small.compiler]
....
import java.util.Arrays;

public class Example {
  public static void main(String[] unused) {
    LastTen lastTen = new LastTen();
    for (int i = 0; i < 32; i++) {
      lastTen.add(i);
    }
    System.out.println(Arrays.toString(lastTen.getLastTen()));
  }
}
....

[[efNgsNVacYNjhRepXrMbcCbfGDJiEdBK]]
== Object Modeling

[.lead]
//
We frequently use Java objects to model real objects or entities.

Objects allow us to _design_ software that deals with things in realistic and
natural ways.

[[QKbwvSUPNbeavWhkTsZyRZEGHEAuicDP]]
== Let's Model Something

[.janini.compiler.small]
....
public class Example {
  public static void main(String[] unused) {
  }
}
....

[[aeVJuVbnHSUwndHSELusYguefZbWovbn]]
[.oneword]
//
== Questions About Objects?

[[vBnPLekwLKSwctchhYVDzwDYAcHnLwtF]]
== Java Packages

[.lead]
//
A Java _package_ is a bundle of resources&mdash;mainly classes&mdash;that
provide related functionality.

[.s.small]
//
* The Java SDK provides a set of packages starting with `java` or
`javax`: like `java.util`.
//
* These _standard libraries_ are always available for
you to use when you write Java code.
//
* Other companies and organizations can create and distribute their own software
packages: like `com.google.common.math` or `org.apache.commons.text`.
//
* Unlike the standard libraries, you have to do some extra work to make these
libraries available for each project you are working on.

[[OxCNCEdjJZZhBNvuwRZYlAXXjEEarnYS]]
== Package Naming

[.lead]
//
Java establishes _naming conventions_ to ensure that multiple developers can
work on similar projects without collisions.

[.s]
//
* Standard libraries start with `java` or `javax`
//
* External libraries use a reversed domain name: `com.google...`,
`edu.illinois.cs.cs125....`, or `com.github.cs125-illinois...`.
//
* If you publish to GitHub, `com.github.<username>...` is a good choice.

[[dvUyavhbysBlokxBLJZlQUVNFNfTHNJM]]
[.oneword]
== Don't Do It Yourself

You _have_ to learn to use software libraries.

[[LMhibrQYIFqYfnFusRNzCWzgqggvdDfk]]
== Course v. Real Programming

[.table.small,cols="3*^.^",options='header']
|===

|&nbsp;
{set:cellbgcolor!}
|Course
|Real

| *You start with...*
| A small amount of great code
| A large amount of complex and confusing code

| *Most of your time is spent...*
| Programming
| Understanding the system

| *You solve problems...*
| Yourself!
| *By finding existing solutions*

| *You end up building...*
| Something small
| Something really cool

| *We call this...*
| Doing the MP
| Hacking

|===

[[YwpAOrPEaokQVLVClBDbPxGMbzzaxiaX]]
[.nologo]
== ! The Java Standard Library

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/8/docs/api/overview-summary.html"></iframe>
</div>
++++

[[mSdYyLaxMJsosGasHkNxcWBMMBrZIWZJ]]
[.nologo]
== ! Standard Library Example

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html"></iframe>
</div>
++++

[[wpYzILHVHcoqixovDBWbQwmQeuQkoADR]]
== Importing Standard Libraries

[source,java,role='small']
----
// If I use the fully-qualified name I don't need an import...
System.out.println(java.util.Arrays.toString(new int[] { 1, 2, 3 }));
----

[source,java,role='s mt-3']
----
// ...but it's common to use one.
// This makes Arrays available in this class
import java.util.Arrays;
// Now I can use its methods
System.out.println(Arrays.toString(new int[] { 1, 2, 3 }));
----

[source,java,role='s mt-3']
----
// I can also import all classes from java.util, although
// checkstyle will complain
import java.util.*;
// Now I can use its methods
System.out.println(Arrays.toString(new int[] { 1, 2, 3 }));
----

[[rzbCoCaoKnyUenfrONuOeInBDrCZJdFW]]
[.nologo]
== ! Java External Libraries

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://mvnrepository.com/"></iframe>
</div>
++++

[[oSeXSCuViZSEmEXAvyOuDYeuzHCWoGkr]]
[.nologo]
== ! External Library Example

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://google.github.io/guava/releases/19.0/api/docs/com/google/common/math/BigIntegerMath.html"></iframe>
</div>
++++

[[tWOJqoHXhtlVOfPgGblCjbhAXjdTmfCM]]
== Importing Non-Standard Libraries

[source,java]
----
// Unfortunately, it's not quite this easy...
import com.google.common.math.BigIntegerMath;
----

[[illRZGGRjlgKrBSTfbAqhaioSnpwLFqO]]
[.oneword]
== Gradle to the Rescue

[.lead]
//
There are multiple ways to make external libraries available as part of your
project. We're going to show you how to do this using
//
https://gradle.org/[_Gradle_].

[[cYGaEIKPtCRIvfHaPklwBzMbsVaErrBz]]
== What is Gradle footnote:[not "the Gradle"]?

[.lead]
//
https://gradle.org/[Gradle] is a _build tool_. It helps with things like:

[.s]
//
* building your Java program or Android app
//
* running test suites and code quality tools like `checkstyle`
//
* packaging your Java code into a _package_, if appropriate
//
* build Javadoc documentation
//
* _fetching any dependencies that your project needs_

[[DHZgxVaSgEKWRvqlfCajAZtBWZNVrVSv]]
== Example `build.gradle`

[source,groovy]
----
// We're building a Java application
apply plugin: 'java'

// Look for dependencies on jcenter
repositories {
    jcenter()
}

// We don't have any dependencies yet
dependencies {
}
----

[[nrdlFHtMGnMzOjAxtuHvcDnABgmhFzut]]
== `build.gradle` With Dependency

[source,groovy]
----
// We're building a Java application
apply plugin: 'java'

// Look for dependencies on jcenter
repositories {
    jcenter()
}

// Use the Google Guava library version 24.1-jre
dependencies {
    // When I compile the project I need this library
    compile 'com.google.guava:guava:24.1-jre'
}
----

[[UtfvqbakmGiuQxhhWGwqUmKFTMxwSCjZ]]
== Gradle Dependency Format

[source,groovy]
----
dependencies {
    compile 'com.google.guava:guava:24.1-jre'
    // example: compile 'GROUP:ARTIFACT:VERSION'
}
----

[.lead]
//
Gradle's dependency block breaks each dependency into three parts:

[.s]
//
* `GROUP`: usually indicates an organization that provides this dependency,
like `com.google` or `com.github.cs125-illinois`.
//
* `ARTIFACT`: a string identifying the dependency to add to the project.
//
* `VERSION`: a version string identifying which version of the library to use.

[[vBbwgXiXNfHOtRkJiNElbzHnMInRkSLQ]]
== Maven Format

[.lead]
//
Sometimes you see the dependency in this format, which is used by another build
tool called Maven:

[source,xml]
----
<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-text</artifactId>
  <version>1.3</version>
</dependency>
----

[.s]
--
This is equivalent to `org.apache.commons:commons-text:1.3` in Gradle.
--

[[uMDkZjyFXZhwZhZfqXoWnfoHVpMvmMaF]]
== `GROUP` and `ARTIFACT`

[.lead]
//
Just be aware that these are _not necessarily_ related to the package name.

[.s]
//
* `com.google.guava:guava` provides `com.google.common.math`, etc.
//
* `com.github.cs125-illinois:sortlib` provides
`edu.illinois.cs.cs125.sortlib`

[[TOBMAZXTnIlkYxXmasplpfPNxSLWHZAs]]
== `VERSION`

[.lead]
//
Package versioning is _incredibly important_.

[.s]
//
* If you develop your app to work with `1.10.1`, it may not work with `2.0.0`.
//
* So you pin your app at a particular version of a library.
//
* However, it _is_ important to periodically update your libraries to the latest
version, but not that that may take some time and energy.

[[goAVHEprLupuCbtxiqjucUiGaOhLvtxT]]
== `.jar` Files

[.lead]
//
A single Java library usually consists of many different class files and other
resources. They are packaged into a single _Java archive_, or `.jar` file.

[source,bash,role='smallest']
----
$ jar tvf sortlib.jar
     0 Sun Apr 15 16:00:08 CDT 2018 META-INF/
    25 Sun Apr 15 16:00:08 CDT 2018 META-INF/MANIFEST.MF
     0 Sun Apr 15 16:00:08 CDT 2018 edu/
     0 Sun Apr 15 16:00:08 CDT 2018 edu/illinois/
     0 Sun Apr 15 16:00:08 CDT 2018 edu/illinois/cs/
     0 Sun Apr 15 16:00:08 CDT 2018 edu/illinois/cs/cs125/
     0 Sun Apr 15 16:00:08 CDT 2018 edu/illinois/cs/cs125/sortlib/
   595 Sun Apr 15 16:00:08 CDT 2018 edu/illinois/cs/cs125/sortlib/Sorting.class
----

[[fCYndsidCgNfuObeeJHoIbgkcuKqulRi]]
[.oneword]
//
== Questions About Packaging?

I know that this is dull and a bit confusing. Post on the forum if you have
questions!

[[HiLlpvxKziOlYYkRfdKZIjluYKLMNtQj]]
== Announcements

* link:/MP/2/[MP2] is out and due in less than two weeks. **Get started!**
//
* This week's lab exercise is open and available over the weekend. Have fun!
//
* I have office hours from 1&ndash;3PM today in Siebel 2227. Please stop by!
//
* **We will _not_ have a lecture next Wednesday.**
//
* We have a
//
link:/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!

// vim: ts=2:sw=2:et
