---
title: Object References
date: 2018-02-26
description:
  An introduction to object references, their implications for Java programming,
  and a bit about Java memory management.
---

[[XvVPGwaRhahvjdxCblIifRgJogEUVwFu]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Object References</div>
++++
....
public class Person {
  public String name;
  Person(String name) {
    this.name = name;
  }
  public boolean equals(Person other) {
    return this.name == other.name;
  }
}
public class Example {
  public static void main(String[] unused) {
    Person geoffrey = new Person("Geoffrey");
    Person alsoGeoffrey = geoffrey;
    Person anotherGeoffrey = new Person("Geoffrey");
    System.out.println(alsoGeoffrey == geoffrey);
    System.out.println(alsoGeoffrey.equals(geoffrey));
    System.out.println(anotherGeoffrey == geoffrey);
    System.out.println(anotherGeoffrey.equals(geoffrey));
  }
}
....
--

[[qWcdunxsQUZvWXluIpetvUNFVUAmCjVP]]
[.oneword]
== This is _Not_ a Class on Java Internals

[.lead]
//
You should learn to think _in Java_, not worry (yet) about what is going on
below.

[[drSMdGFVAAqrAxUkxYuOVntLZQwbJhIt]]
== But We'll Do A _Bit_ of Java Internals

Either because it's

[.s]
//
* *important*
//
* interesting
//
* fun
//
* or some combination of the above.

[[XxGahOwmXfZrBFQuELVZOxrslVpDJEnC]]
== References

[quote]
//
____
//
https://en.wikipedia.org/wiki/Reference_(computer_science)[Reference:]
//
a value that enables a program to _indirectly_ access a particular datum, such
as a variable's value or a record, in the computer's memory or in some other
storage device.
//
The reference is said to refer to the datum, and accessing the datum is called
dereferencing the reference.
____

[[jhiIsrkMqrXqNBPNwaMQPVIGXpdHPnge]]
== Java Reference Variables

[source,java,role='smallest']
----
class Person { }
/*
 * me is declared to hold a reference to an object of type Person,
 * but currently refers to nothing.
 */
Person me;

/*
 * Initializing an instance to null is another way of indicating
 * that it currently refers to nothing.
 */
Person you = null;

me = new Person(); // Now me points to a new Person object
you = me; // Now me and you point to the same Person object
System.out.println(you == me);
you = new Person(); // Now you points to a new Person object
System.out.println(you == me);
----

[.lead]
//
We can refer to a Java variable that refers to an object as a _reference
variable_.

[[ePzrrhanajpSQIFiEmThxkYyCQtBUDrR]]
== ! Java Reference Variables

[.janini.smaller]
....
class Person { }
/*
 * me is declared to hold a reference to an object of type Person,
 * but currently refers to nothing.
 */
Person me;

/*
 * Initializing an instance to null is another way of indicating
 * that it currently refers to nothing.
 */
Person you = null;

me = new Person(); // Now me points to a new Person object
you = me; // Now me and you point to the same Person object
System.out.println(you == me);
you = new Person(); // Now you points to a new Person object
System.out.println(you == me);
....

[[dKbotvmzkEPDwFtKDtWfbWLWtsQvtzUv]]
== References Are Not Objects

[.lead]
//
References _are not_ the thing the refer to.

What are some real-world examples of references?

[.s]
//
* *A phone number*: which refers to a phone
//
* *A street address*: which refers to a physical location
//
* *A social security number*: which refers to a person

[[itfuafekfLjAzwwbVrkStPQVIGyxObCF]]
== Copying References

[.lead]
//
Copying a reference _does not_ copy the object it refers to.

[.s]
//
* *Copying a phone number doesn't copy the phone.*
//
Anyone with the number can call the same person.
//
* *Copying a street address doesn't copy the location.*
//
Anyone with the address can navigate to the same spot.
//
* *Copying a social security number doesn't copy the person* footnote:[Is that
even possible?].
//
Anyone with social security number may be able to impersonate that person.

[[mgDxtWzOVhgiyiPrSUQKCwwUKOAeHLuC]]
== ! Copying References

[.janini]
....
class Person {
  public int age;
}
Person me;
me = new Person();
Person you = me;
me.age = 10;
System.out.println(you.age);
....

[[mIzaMkJisKMhTtGuDJdBQQQLzmaeZvUp]]
[.ss]
== Copying References

[source,java]
----
class Person {
  public int age;
}
Person me;
----

<<<

++++
<div class="digraph default">
  me
</div>
++++

[[oTxeeptDAAbhPoFfhrUmlbRqOGBifBCI]]
[.ss]
== Copying References

[source,java]
----
class Person {
  public int age;
}
Person me = new Person();
----

<<<

++++
<div class="digraph default">
  Person [ label = "Person|age = 0" ]
  me -> Person [ label = "refers to" ]
</div>
++++

[[HRLZQYDutqYyuRJLAfRTUKWsHAAnIsXh]]
[.ss]
== Copying References

[source,java]
----
class Person {
  public int age;
}
Person me = new Person();
Person you = me;
----

<<<

++++
<div class="digraph default">
  Person [ label = "Person|age = 0" ]
  me -> Person [ label = "refers to" ]
  you -> Person [ label = "refers to" ]
</div>
++++

[[BNDFZUWJXXyorFCxmkBrigvGUpbPKsEb]]
[.ss]
== Copying References

[source,java]
----
class Person {
  public int age;
}
Person me = new Person();
Person you = me;
me.age = 10;
----

<<<

++++
<div class="digraph default">
  Person [ label = "Person|age = 10" ]
  me -> Person [ label = "set age" ]
  you -> Person
</div>
++++

[[EbMSAXuEuSUQYYKcghZAlJXEgDAazCWh]]
[.ss]
== Copying References

[source,java]
----
class Person {
  public int age;
}
Person me = new Person();
Person you = me;
me.age = 10;
System.out.println(you.age);
----

<<<

++++
<div class="digraph default">
  Person [ label = "Person|age = 10" ]
  me -> Person
  you -> Person [ label = "get age" ]
</div>
++++

[[OmTSjTmYpHwjYoPLKPiqfxoTUMMjNKUl]]
== ! Copying References

[.janini]
....
class Person {
  public int age;
}
Person me;
me = new Person();
Person you = me;
me.age = 10;
System.out.println(you.age);
....

[[eQpiyhXFcqMSmIAgOndHFzSGcIJfkOSR]]
[.ss]
== Swapping References

[source,java,role='smaller']
----
class Person {
  public int age;
  Person(int setAge) {
    this.age = setAge;
  }
}
Person me = new Person(38);
Person you = new Person(18);
----

<<<

++++
<div class="digraph default">
  P2 [ label = "Person|age = 18" ]
  P1 [ label = "Person|age = 38" ]
  me -> P1
  you -> P2
</div>
++++

[[lkfWvkqKjRjIjJZWJvPzqfFkFyphDUFO]]
[.ss]
== Swapping References

[source,java,role='smaller']
----
class Person {
  public int age;
  Person(int setAge) {
    this.age = setAge;
  }
}
Person me = new Person(38);
Person you = new Person(18);
Person tmp = me;
----

<<<

++++
<div class="digraph default">
  P1 [ label = "Person|age = 38" ]
  P2 [ label = "Person|age = 18" ]
  me -> P1
  you -> P2
  tmp -> P1
  me -> you [style=invis]
  you -> tmp [style=invis]
  {rank=same; me you tmp}
</div>
++++

[[pWMfaKXkBZCrwPFnsQKKsUWcnCsVJBzf]]
[.ss]
== Swapping References

[source,java,role='smaller']
----
class Person {
  public int age;
  Person(int setAge) {
    this.age = setAge;
  }
}
Person me = new Person(38);
Person you = new Person(18);
Person tmp = me;
me = you;
----

<<<

++++
<div class="digraph default">
  P1 [ label = "Person|age = 38" ]
  P2 [ label = "Person|age = 18" ]
  me -> P2
  me -> P1 [style=invis]
  you -> P2
  you -> P1 [style=invis]
  tmp -> P1
  tmp -> P2 [style=invis]
  me -> you [style=invis]
  you -> tmp [style=invis]
  {rank=same; me you tmp}
</div>
++++

[[UywGpTsMtxFOHkCUrvxZmOYaZYzFqZMv]]
[.ss]
== Swapping References

[source,java,role='smaller']
----
class Person {
  public int age;
  Person(int setAge) {
    this.age = setAge;
  }
}
Person me = new Person(38);
Person you = new Person(18);
Person tmp = me;
me = you;
you = tmp;
----

<<<

++++
<div class="digraph default">
  P1 [ label = "Person|age = 38" ]
  P2 [ label = "Person|age = 18" ]
  me -> P2
  me -> P1 [style=invis]
  you -> P1
  you -> P2 [style=invis]
  tmp -> P1
  tmp -> P2 [style=invis]
  me -> you [style=invis]
  you -> tmp [style=invis]
  {rank=same; me you tmp}
</div>
++++

[[ZlSlVntakQfPDbkrVfimWKcshUXdksDO]]
[.ss]
== Swapping References

[source,java,role='smaller']
----
class Person {
  public int age;
  Person(int setAge) {
    this.age = setAge;
  }
}
Person me = new Person(38);
Person you = new Person(18);
Person tmp = me;
me = you;
you = me;
// Now we can discard tmp
----

<<<

++++
<div class="digraph default">
  P1 [ label = "Person|age = 38" ]
  P2 [ label = "Person|age = 18" ]
  me -> P2
  you -> P1
  me -> P1 [style=invis]
  you -> P2 [style=invis]
</div>
++++

// vim: ts=2:sw=2:et
