---
title: Static and Modeling
date: 2018-10-01
description:
  Midterm review followed by more about Java objects, including static methods
  and variables.
youtube: https://youtu.be/2S8oyTZrRQA
spelling_exceptions:
  - GCD
  - Xyz
---

[[wGEQuJkAUhyxysXZUnzyNGFHNKOzeXJi]]
== !

[.janini.compiler.small]
--
++++
<div class="message">Static and Modeling</div>
++++
....
public class Course {
  public static void printName() {
    System.out.println("CS 125");
  }
}
public class Example {
  public static void main(String[] unused) {
    Course.printName();
  }
}
....
--

[[KcQRXpFXdmuAnxnLEHQTdJNVVXdUdWnY]]
== Midterm Review: String Processing

A common task when working with is extracting data from structured text.
//
For example, consider that you are provided employee records in the following
format:

```text
Name:Position:Salary
```

Here are some examples:

```text
Chuchu Challen:Senior Challen Family Dog:10000
Xyz Challen:Junior Challen Family Cat: 8000
Little Helper:Challen Family Roomba
```

[[sensjjnpmjGanDOqouJAcJgQyYSeRclX]]
== Midterm Review: String Processing

**Note that not every record has all possible fields.**
//
(Little Helper works in exchange for free electricity.)
//
In addition, some records may have whitespace around the values, as in the data
for "Xyz Challen" above.

[[LGoieNVuJpiZFIdQNNyKZczeRRAliCCq]]
== Midterm Review: String Processing

Your job is to write a function called `getSalary` that, given a record in the
format above passed as a `String`, returns that person's salary as an `int`.
//
If the record does not contain a salary or if the record is `null` you should
return `-1`.

As a reminder we provided a copy of the Java `String` documentation on the quiz
cover page.
//
You may want to refer to that, and in particular to the `split` and `trim`
functions.
//
Note that you can pass a `String` to `split` rather than a regular expression,
and it will split the string at each occurrence of the passed `String`.

[[nuKMZnDsVysyNvedTiPlndMSnxfatCoA]]
== Midterm Review: String Processing

We have also provided a copy of the Java `Integer` documentation on the quiz
cover page.
//
You should examine the `Integer.parseInt` function to convert a
`String` into an `int`:

```java
int i = Integer.parseInt("10");
```

However, note that this function _will not work_ if there is whitespace
surrounding the integer.
//
So you'll need to remove it.
//
See the `String` hints above.

[[cgeZFZddFMuCmnKobNegrigntnmFyunf]]
== ! Midterm Review: String Processing

[.janini.small]
....
System.out.println(getSalary("Chuchu:Senior Challen Family Dog:10000"));
....

[[YOWktApdylegwNvLtEfZmnDhvrNfilST]]
== Midterm Review: GCD

Define and implement a function below called `gcd` that returns the greatest
common denominator (GCD) as an `int` of an array of passed positive `int` values.
//
The greatest common divisor (GCD) of two or more integers, which are not all
zero, is the largest positive integer that divides each of the integers.
//
The passed array may be `null`, empty, or contain only 0s&mdash;in these cases return `-1`.

[[qlBiCcBerzeaQluXldiNDWLzEQZPLjQb]]
== Midterm Review: GCD

**You do not need to implement a sophisticated GCD algorithm.**
//
A simple iterative solution will work fine.
//
Once you have dealt with the bad inputs (`null`, empty) you may want to try to
implement the following algorithm:

[.small.s]
//
. First, find the maximum value over the passed array.
//
This is also the place to see if you have been given all zeroes.
//
. Now, start at that value and work downward.
//
. For each potential GCD, find the remainder when you divide every element in
the input array by the potential GCD.
//
If they are all zero, you have found the GCD.
//
If any is non-zero, move on to the next potential value.

[[aCDuMymnEfOuZxePefWeeSXdTrmsDZSV]]
== ! Midterm Review: GCD

[.janini.small]
....
System.out.println(gcd(20, 10, 5));
....

[[mBTUbPeFkfcconeufXXvCCNCiKViJepV]]
[.oneword]
//
== Midterm Questions?

[[fufaLBxVODEUnkLfFIwehGffqBnydFYV]]
[.oneword]
//
== Reminder: Quiz 4


[[eTgfLgcMsxPQEsxdUuCOfSKOCVKugAYZ]]
== The `static` Keyword

[source,java,role='small']
----
public class Course {
  public static int count = 0;
  public static void printName() {
    System.out.println("Name");
  }
}
public class Example {
  public static void main(String[] unused) {
    // We can call printName without creating an instance
    Course.printName();
    // We can increment count without creating an instance
    Course.count++;
  }
}
----

[.lead]
//
`static` methods and variables belong to the _class_, not to a specific
instance.

[[JcfeftoggWYEqmVcqHqWFWLVDrBYSrKv]]
== `static` Methods

[source,java,role='smaller']
----
public class Course {
  public static void printName() {
    System.out.println("Name");
  }
}
public class Example {
  public static void main(String[] unused) {
    // This works
    Course.printName();
    // This also works
    Course CS125 = new Course();
    CS125.printName();
  }
}
----

[.s]
//
* `static` methods are called directly on the class, rather than on an instance
//
* ...but they _can_ be called on the instance as well.

[[GogDSWyLriatEwvWVbqNnpNScdTGsZnm]]
== `static` Methods and `this`

[source,java]
----
public class Course {
  public String name;
  public static void printName() {
    // This doesn't work
    System.out.println(this.name);
  }
}
----

[.lead]
//
`static` methods can be called without an instance, and so can't use `this`

[[AGXzadhOVsBxnfSsSKGKsHhYNePpixZD]]
== `static` Variables

[source,java,role='small']
----
public class Course {
  public static int count = 0;
  public void printCount() {
    System.out.println(count);
  }
}
public class Example {
  public static void main(String[] unused) {
    Course CS125 = new Course();
    Course CS225 = new Course();
    Course.count++;
    CS125.printCount();
    CS225.printCount();
  }
}
----

[.lead]
//
`static` variables are shared by all instances of a given `class`


[[aJrAPQCvltPcxpPVAvGrGqdLWEhKRlRK]]
== ! `static` Variables

[.janini.smallest.compiler]
....
public class Course {
  private String name;
  public static int count = 0;
  public void printCount() {
    System.out.println(this.name + " " + this.count);
  }
  Course(String setName) {
    this.name = setName;
  }
}
public class Example {
  public static void main(String[] unused) {
    Course CS125 = new Course("125");
    Course CS225 = new Course("225");
    Course.count++;
    CS125.printCount();
    CS225.printCount();
  }
}
....

[[XHfGpqVIAFIKzUxynzGVJLgDpLnzNwON]]
== `static`, `public`, and `private`

[.lead]
//
`public` and `private` also work on static variables and methods

[.s]
//
* `public`: the (static) variable can be read or written by anyone
//
* `private`: the (static) variable can only read or written by methods defined _on that
class_
//
* `public`: the (static) method can be called by anyone
//
* `private`: the (static) method can only be called by other methods _on that class_

[[edyTnfheyncuqOGTqDCiVblPbDhDspnE]]
== `static` Object Creation Method

[.lead]
//
We can also use a class method to be able to return `null` when creating a new
object if invalid parameters are supplied.

[[vYdcSSHUfxavYQtnRnYMNLTmZdeandOy]]
== ! `static` for Object Creation

[.janini.smallest.compiler]
....
public class Storage {
  private int[] storage;
}
public class Example {
  public static void main(String[] unused) {
  }
}
....

[[PzievfvBAnLYMbjqVoPmzSAhYzhqmAFt]]
== Announcements

* link:/MP/3/[MP3] is out and due _two weeks_ from _today_.
//
* I'm holding office hours today from 10AM&ndash;12PM.
//
* Regular Monday office hours today from 10AM&ndash;5PM.
//
*Today is great day to come and get started on link:/MP/3/[MP3]*.

// vim: ts=2:sw=2:et
