---
draft: true
---

[[dgqLkvllIxGBVWNUgvWRaphpbprIUZmd]]
== Split Name

[.lead]
//
Imagine I have a person's full name in a string in either one of the following
two formats:

. "First Last", or
//
. "Last, First"

Write a function to split the name into two string values: one storing the first
name and the second storing the last name.

[[uLcwjkMviNxXzPUGSvzKOnXZejIuVdiV]]
[.oneword]
== What's Our Algorithm?

[[LusbpptlAvcVVksiUCrVcWRbBGsDtOkn]]
== ! Split Name

[.janini.small]
....
// Split into first and last name
String fullName = "Chuchu Challen";
....

[[gPucDaBMQDrRTTpzHGhYeKkUqKBFQzyR]]
== Search Text

[.lead]
//
Given a line of text, write a function that searches for all occurrences of a
given word.

[[eyqUvEBDookviajBvuXtPufaOcUyPAhM]]
[.oneword]
== What's Our Algorithm?

[[CjUbIEwBODHnKAjrDdalyYWzIqZflMlk]]
== ! Search Text

[.janini.small]
....
// Search text for a specific word
String text = "Where do random thoughts come from?"
....

[[okKIJujIjYYDDEdlozylLUFAAHzzvtyo]]
== Most Common Character

[.lead]
//
Given a string, determine which character appears most often.

[[rRjIZhZaJLkxOjhsHvbgusjuJxhsbqAg]]
[.oneword]
== What's Our Algorithm?

[[JCtcfRHYmACtmdBvICfodQLzJaIZgNgn]]
== ! Here's Some Help

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html"></iframe>
</div>
++++

[[dfZDbioIVRPdrUKNnAedFUWRYIlHwlEC]]
== Most Common Character

[.janini.small]
....
// Determine the most common character
static char mostCommon(String input) {
}
System.out.println(mostCommon("AAAbcd"));
....

[[agRjmuPXNFgsskQjpuMryxBeLimsaExA]]
== Testing

[.lead]
//
Test cases are an indispensable part of modern software development.

[.s]
//
* To perform a simple test, pick a input that you know the answer to and check
that your function returns the expected value.
//
* Try to pick cases that are hard and where you might not get the right
answer&mdash;we call these _corner cases_.

[[BzRRFIMstyqbRXhqEywqvIoQJUgYebbD]]
== Greatest Common Denominator

[quote]
//
____
//
In mathematics, the
//
https://en.wikipedia.org/wiki/Greatest_common_divisor[greatest common divisor
(GCD)]
//
of two or more integers, which are not all zero, is the largest positive integer
that divides each of the integers.
//
____

[[pjDljAIzRjELOcfeobkDQFRinIBUMrhD]]
== ! GCD Algorithms

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://en.wikipedia.org/wiki/Greatest_common_divisor#Calculation"></iframe>
</div>
++++

[[tDXMsVMWQaICoZpNjRwvYQvYvpkBVCKA]]
[.oneword]
== But If We're In A Hurry...

[[JssrqejyvIyvwsXyrCkspJKxdKDMQLRk]]
== Brute Force Solution

[quote]
____
https://en.wikipedia.org/wiki/Brute-force_search[Brute force solution]:
//
a very general problem-solving technique that consists of systematically
enumerating all possible candidates for the solution and checking whether each
candidate satisfies the problem's statement.
____

[.s]
//
* Computers today are very, _very_ fast
//
* So try the simple thing first
//
* If it's too slow, try something a bit more sophisticated

[[qMuYttxuubacRODFMWhjihipuaPhWYqH]]
== ! GDC Implementation

[.janini.small]
....
// Print the GCD
System.out.println(gcd(24, 18));
....

[[qdXwzQeEINKOPgbceNliwLWeLNyqnSVo]]
== ! Bring the Brute

image::https://cdn.vox-cdn.com/thumbor/wgMcgj6LStdjW-qlLkaHUBsdQzY=/0x0:2048x858/1200x800/filters:focal(834x251:1160x577)/cdn.vox-cdn.com/uploads/chorus_image/image/57442421/hulk_agnarok.0.jpg[role='mx-auto meme',width=640]

[[SAkZunVquojxGluWfhHFkLljmuDEmoNB]]
[.oneword]
== You Don't Need the Fastest Algorithm to Change the World

That's a good thing!

[[XIAanwdDVyALfCEgZLNQljuMKfylgtld]]
== But How Long Will It Take?

[.lead]
//
How long will our brute force GCD algorithm take?

[.s]
//
* To compute the GCD of 4 and 6
//
* To compute the GCD of 185 and 2045
//
* To compute the GCD of M and N
