---
draft: true
---

[[OPSrkYUNTxrjfKcdKlMrOeaNTfwJaaCi]]
== Switch Statements

[.lead]
//
Remember the `if` statement?
[source,java]
----
if (conditionA) {
  // do something
} else if (conditionB) {
  // do something else
} else if (conditionC) {
  // ...
}
----

It too has a friend:

[.s]
--
[source,java]
----
switch (variable) {
  case A:
    // do something
  case B:
    // do something else...
}
----
--

[[nGiQLdRcHAuGxCdGVrExNKMGjQtwQPlJ]]
== Switch Statements

[.lead]
//
`switch` is more limited than `if-else`, but also more flexible:

[.s]
//
* It only works for testing primitive types and ``String``s
//
* But you can match multiple ``case``s in a single `switch` statement
//
* Execution _starts_ at a matching `case` statement and continues until a
`break` statement is reached

[[BNTWPZKfwWhfxfRAtLWKGjIEGdZoPTVZ]]
== ! Switch Statements

[.janini.small]
....
int test = 2;
switch (test) {
  case 0: System.out.print("A");
  case 1: System.out.print("B");
  case 2: System.out.print("C");
  case 3: System.out.print("D");
  default: System.out.println("E");
}
System.out.println();
....

[[gPucDaBMQDrRTTpzHGhYeKkUqKBFQzyR]]
== Search Text

[.lead]
//
Given a line of text, write a function that searches for all occurrences of a
given word.

[[eyqUvEBDookviajBvuXtPufaOcUyPAhM]]
[.oneword]
== What's Our Algorithm?

[[CjUbIEwBODHnKAjrDdalyYWzIqZflMlk]]
== ! Search Text

[.janini.small]
....
// Search text for a specific word
String text = "Where do random thoughts come from?"
....

[[kLZPLCwNTswvGzxkLeLVyLvzOzzBzbxG]]
== ! Read The Documentation

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/lang/String.html"></iframe>
</div>
++++

[[eElRbazMJbGpaHfrEAGOxqdhlEUjKpHJ]]
== Other Access Modifiers

[.lead]
//
(Java also provides `protected` and package private modifiers&mdash;but they
don't make sense until we discuss packages.)

[[uLPZroAsMblwalogMaPDbzszkcQeVlEo]]
== Getters and Setters

[source,java,role='small']
----
public class Person {
  private int age;
  public void setAge(int setAge) {
    this.age = setAge;
  }
  public int getAge() {
    return this.age;
  }
}
----

[.lead]
//
In Java it's common to have _private_ instance variables with public methods
that set or get their values: called _setters_ and _getters_.

[[oDKbLeOnKjNLLDaUpPxiFXRuDeUiVtUC]]
== Getters and Setters: Why?

[source,java,role='smallest']
----
public class Person {
  private int name;
  private int firstName;
  private int lastName;
  public void setName(int setName) {
    String[] nameParts = setName.split(" ");
    this.name = setName;
    this.firstName = nameParts[0];
    this.lastName = nameParts[1];
  }
  public int getName() {
    return this.name;
  }
  public int getFirstName() {
    return this.firstName;
  }
  public int getLastName() {
    return this.lastName;
  }
}
----

[.lead]
//
Getters and setters allow an object to react to changes to its variables.

[[wonpBdFJRHThXEZuFNtsAJXwhHalvCdU]]
== Object Modeling

[.lead]
//
We frequently use Java objects to model real objects or entities.

Objects allow us to _design_ software that deals with things in realistic and
natural ways.

[[QKbwvSUPNbeavWhkTsZyRZEGHEAuicDP]]
== Let's Model Something

[.janini.smaller]
....
....


