---
title: Web APIs
date: 2018-04-11
description:
  Web protocol examples and web APIs.
spelling_exceptions:
  - DNS
  - IPv4
  - IPv6
  - SMTP
  - YNP
  - Gmail
  - MetaWeather
  - Bob Kahn
  - Vint Cerf
---

[[HVnGZbaPCPKUZAUCdxLIwtJkHkEeYqwl]]
[.oneword]
== Web APIs

Some examples for today are available here:
//
https://github.com/cs125-illinois/lecture-webapis-examples[`https://github.com/cs125-illinois/lecture-webapis-examples`]
//
Feel free to fork!

[[pTHCdYuCyqqRzhfrZBmPVlxaMMqlQqxq]]
== What is the World Wide Web?

[.s]
//
* *A protocol*: the Hypertext Transfer Protocol
//
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol[(HTTP)]
//
* *A markup language*: the Hypertext Markup Language
//
https://en.wikipedia.org/wiki/HTML[(HTML)]
//
* *A styling language*: Cascading Style Sheets
//
https://en.wikipedia.org/wiki/Cascading_Style_Sheets[(CSS)]
//
* *A programming language*:
//
https://en.wikipedia.org/wiki/JavaScript[JavaScript]

[[feLPwPHMQSsPpUmshWroUcSKcWKeCxbd]]
== HTTP: `GET` Request

[.lead]
//
HTTP defines how web browsers request (`GET`) content:

When you type
//
http://cs125-illinois.github.io/lecture-webapis-examples/simple.html[`http://cs125-illinois.github.io/lecture-webapis-examples/simple.html`]
//
into your browser, it sends a message to `cs125-illinois.github.io` that looks
like this:

[source]
----
GET /lecture-webapis-examples/simple.html HTTP/1.1
Host: cs125-illinois.github.io
----

[[jqBzouDGtPyaHKmOwnbpCvRASaKvBFfC]]
== `GET` Parameters

[.lead]
//
You can send some data to the server in a `GET` request using _query
parameters_.

[.s.small]
//
* These follow the path and an `?` sign in the URL
//
* Each takes the form `key=value`
//
* Key-value pairs are separated by `&` delimiters
//
* Here's an example: `search?safe=off&source=hp?q=cs125`:
** `safe=off`
** `source=hp`
** `q=cs125`

[[ZYZfArcqHGbcpMGDWpUxTEAYpHhSMMOP]]
== HTTP: `GET` Response

[.lead]
//
If the request succeeds, the server responds with something that looks like
this:

[source]
----
HTTP/1.1 200 OK
Date: Sun, 08 Apr 2018 08:56:53 GMT
Last-Modified: Sat, 20 Nov 2014 07:16:26 GMT
Content-Length: 44
Content-Type: text/html

<html>
  <body>
    ...
----

[[BszNyUYxaqPnTlZclvOYZTyRJdgHHnmX]]
== HTTP: `POST` Request

[.lead]
//
HTTP also defines how web browsers submit information (`POST`):

When you submit the form on
//
http://cs125-illinois.github.io/lecture-webapis-examples/form.html[`http://cs125-illinois.github.io/lecture-webapis-examples/form.html`],
//
it sends a message to `cs125-illinois.github.io` that looks like this:

[source]
----
POST /lecture-webapis-examples/simple.html HTTP/1.1
Host: cs125-illinois.github.io

text=word
----

Note that this fails on `github.io` because it only serves _static_ pages and
doesn't deal with data provided by users.

[[uEuXCurrnJzwJygQyftDiaVpiXQzPHbU]]
== HTTP: `GET` and `POST`

[.lead]
//
HTTP defines many other types of requests, but `GET` and `POST` are by far the
most common.

[.s]
//
* *Every time you load a web page* it starts with a `GET`, and usually that's
followed by many other `GET` requests to fetch others parts of the page: style
sheets, images, JavaScript code.
//
* *Every time you submit a form* it uses a `POST` to send data to the server, at
which point your Facebook comment is recorded, or your credit card is charged
and an package starts its way toward your house

[[QKSooQlYPRANKRYoWgElNxbqrvVrScFm]]
== HTTP: `GET` v `POST`

[.lead]
//
The HTTP protocol specifies different semantics for `GET` and `POST`:

[.s]
//
* `GET` _should not_ change anything about the world, just return a document
//
* `POST` _should_ change something about the world&mdash;create a new account,
pay your bill, purchase something, send a message, etc.
//
* As a result it is _safe_ to repeat a `GET` but potentially _problematic_ to
repeat a `POST`: hence the "Do not click back" and "Do not submit this form
twice" kind of warnings.


[[ENeAbNYgDNrbwqRpHZJduekhgMOdxOow]]
== Web Page Contents: HTML

[.lead]
//
HTML defines how each page is _structured_:

[source,html,role='small']
----
<h1>This is a Simple Web Page</h1>

<p>
  HTML includes both content and instructions to the browser determining
  how the content should look. For example, the following items should be
  in a numbered list:
</p>

<ol>
  <li>First</li>
  <li>Second</li>
  <li>Third</li>
</ol>

<p>
  <strong>Here is some bold text.</strong> <i>And this in italics.</i>
</p>
----

[[hKVjQbpzQALswjASEhlGXSTyHHgkGWvD]]
[.nologo]
== ! Web Page Contents: HTML

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="embed-responsive-item" src="https://cs125-illinois.github.io/lecture-webapis-examples/simple.html"></iframe>
</div>
++++

[[jusdaKZZdKzMfBIQchXrTXKenbeDgzBl]]
== Web Evolution

[.lead]
//
The web has gone through many design changes over the years.

[.s.small]
//
* *Static Sites*: the web server returns a _file_ from the disk that contains a
complete web document
** Example: most of `cs125.cs.illinois.edu` is a static website
//
* *Dynamic Sites*: the web server _runs code_ to produce an HTML document and
respond to `POST` requests created by forms
** Example: sites like `my.cs.illinois.edu` are dynamic sites
//
* *Web Apps*: most of the site is _generated by JavaScript_ that runs in the
user's browser, with the server providing data as needed
** Examples: `cs125.cs.illinois.edu/m/grades`, Discourse, Gmail, Google Docs

[[kVGxyCnuUrtKMDbQUEwsrVEZuOyXqgyo]]
== Web Page Contents: CSS

[.lead]
//
CSS defines how each page _looks_:

[source,css,role='small']
----
body {
  font-family: sans-serif;
}
h1 {
  font-size: 48px;
  font-weight: bold;
}
----

[[QCnklVenUskadiskeZRvQQIlwAPyKXZl]]
[.nologo]
== ! Web Page Contents: CSS

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="embed-responsive-item" src="https://cs125-illinois.github.io/lecture-webapis-examples/css.html"></iframe>
</div>
++++

[[bqpQtLWMeCreTUItFEeLrXrmwetlXSJR]]
== Web Page Contents: JavaScript

[.lead]
//
JavaScript defines what each page _does_:

[source,javascript,role='small']
----
setInterval(function () {
  var x = document.getElementById("title")
  if (x.style.visibility === "visible") {
    x.style.visibility = "hidden"
  } else {
    x.style.visibility = "visible"
  }
}, 1000)
----

[[hvUpMeTGNRDIIgBOLjgIAGAeTuZUDHdv]]
[.nologo]
== ! Web Page Contents: JavaScript

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="embed-responsive-item" src="https://cs125-illinois.github.io/lecture-webapis-examples/javascript.html"></iframe>
</div>
++++

[[BzSmObkOJqwnQrxPqQbeeiOgXXpbiFDy]]
[.oneword]
//
== So What's a Web _API_?

[[yyuJpkncwjTgIiTBmtNZIUHdZFQnXSGU]]
== What's An API?

[quote]
____
//
https://en.wikipedia.org/wiki/Application_programming_interface[In computer
programming, an application programming interface (API)]
//
is a set of subroutine definitions, protocols, and tools for building
application software.
____

In English, an _API_ is a set of functions that perform a set of related and
useful tasks.

[[VhKcyDdXgMnfeOXUFUtqYTEIXFRxBmua]]
== Example API

[.lead]
//
Let's say we wanted to find out the weather at a particular location:

[source,java]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)

// Get the current weather a particular location and a particular time
static WeatherInfo getAtLocation(WeatherLocation location, Date date)

// Get a list of possible WeatherInfo objects for a given location string
static WeatherInfo[] searchLocations(String query)
----

[[JLNFoBPiCoEGSAeKEmLVCEayqKYizNUm]]
== Web APIs

[.lead]
//
A _web API_ is just an API that you access over the web. Consider that:

[.s]
//
* We can send data to a web server using `POST` and also using URL parameters in
a `GET` request
//
* The web server can run code in response
//
* And return a response, _which does not have to be a HTML document_

[[sQoshKdkerQbElGQyoWmkEymnLkzrZKF]]
== Web APIs: Sending Arguments

[source,java,role="small"]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)
----

To send the `location` argument to the `getAtLocation` function over the web we
have several options:

[.s.small]
//
* Stick it the URL: `/api/getAtLocation/(location)/`
//
* Add it as a query parameter: `/api/getAtLocation?location=(location)`
//
* Use a `POST` request and put it in the body, possibly as JSON:

[source,role="small s"]
----
POST /api/getAtLocation/

{
  "location": (location)
}
----

[[ijoYpJSPQQLblMzMSckYOpVMqASJepju]]
== Web APIs: Returning Results

[source,java,role="small"]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)
----

In many cases web APIs return results using _JSON_ (JavaScript Object Notation):

[source,json,role='small']
----
{
  "consolidated_weather": [
  {
    "id": 6511056423747584,
      "weather_state_name": "Thunder",
      "weather_state_abbr": "t",
      "wind_direction_compass": "E",
      "created": "2018-04-09T02:37:19.655990Z",
      "applicable_date": "2018-04-08",
      "min_temp": -2.6099999999999999,
      "max_temp": 2.2149999999999999,
      "the_temp": 2.4950000000000001,
      "wind_speed": 2.8707529204565336,
      ...
----

[[ovMOptnsNzzKKfODatpgqmCEDEelFDYN]]
== Let's Do An Example

[.lead]
//
We'll continue our weather example using the
//
https://www.metaweather.com/api/[free MetaWeather API]
//
and
//
https://www.getpostman.com/[PostMan]

[[ZsOQNCeyFRLfYMLCfmRDxwhgFYiBXBXm]]
[.oneword]
== What's Awesome...

Is that there are
//
https://github.com/toddmotto/public-apis[a gazillion]
//
public APIs out there.
//
So go have fun!

[[JuTQULKcDJyYbpOvzZuoVHSBBAMPJKQI]]
[.oneword]
//
== Questions About Web APIs?

[[ReefhsOZCrSqsNCRBofFMqYMOjJZtIBz]]
== Announcements

* We've posted some
//
link:/MP/6/#errata[MP6 errata].
//
Please follow these screencasts if you are having a hard time getting your
environment set up.
//
* The
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
remains available on the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
