---
title: Web APIs
date: 2018-04-13
description:
  Web APIs.
spelling_exceptions:
  - DNS
  - IPv4
  - IPv6
  - SMTP
  - YNP
  - Gmail
  - MetaWeather
  - Bob Kahn
  - Vint Cerf
---

[[akBdVGIbdUuOBCWPJUJACrtqtiiiMWsS]]
[.oneword]
== Web APIs

Some examples for today are available here:
//
https://github.com/cs125-illinois/lecture-webapis-examples[`https://github.com/cs125-illinois/lecture-webapis-examples`]
//
Feel free to fork!

[[wfdQvQZAipVkTZPRnQrNavedMEtHXFyO]]
[.oneword]
//
== So What's a Web _API_?

[[yyuJpkncwjTgIiTBmtNZIUHdZFQnXSGU]]
== What's An API?

[quote]
____
//
https://en.wikipedia.org/wiki/Application_programming_interface[In computer
programming, an application programming interface (API)]
//
is a set of subroutine definitions, protocols, and tools for building
application software.
____

In English, an _API_ is a set of functions that perform a set of related and
useful tasks.

[[VhKcyDdXgMnfeOXUFUtqYTEIXFRxBmua]]
== Example API

[.lead]
//
Let's say we wanted to find out the weather at a particular location:

[source,java]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)

// Get the current weather a particular location and a particular time
static WeatherInfo getAtLocation(WeatherLocation location, Date date)

// Get a list of possible WeatherInfo objects for a given location string
static WeatherInfo[] searchLocations(String query)
----

[[JLNFoBPiCoEGSAeKEmLVCEayqKYizNUm]]
== Web APIs

[.lead]
//
A _web API_ is just an API that you access over the web. Consider that:

[.s]
//
* We can send data to a web server using `POST` and also using URL parameters in
a `GET` request
//
* The web server can run code in response
//
* And return a response, _which does not have to be an HTML document_

[[sQoshKdkerQbElGQyoWmkEymnLkzrZKF]]
== Web APIs: Sending Arguments

[source,java,role="small"]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)
----

To send the `location` argument to the `getAtLocation` function over the web we
have several options:

[.s.small]
//
* Stick it the URL: `/api/getAtLocation/(location)/`
//
* Add it as a query parameter: `/api/getAtLocation?location=(location)`
//
* Use a `POST` request and put it in the body, possibly as JSON:

[source,role="small s"]
----
POST /api/getAtLocation/

{
  "location": (location)
}
----

[[ijoYpJSPQQLblMzMSckYOpVMqASJepju]]
== Web APIs: Returning Results

[source,java,role="small"]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)
----

In many cases web APIs return results using _JSON_ (JavaScript Object Notation):

[source,json,role='small']
----
{
  "consolidated_weather": [
  {
    "id": 6511056423747584,
      "weather_state_name": "Thunder",
      "weather_state_abbr": "t",
      "wind_direction_compass": "E",
      "created": "2018-04-09T02:37:19.655990Z",
      "applicable_date": "2018-04-08",
      "min_temp": -2.6099999999999999,
      "max_temp": 2.2149999999999999,
      "the_temp": 2.4950000000000001,
      "wind_speed": 2.8707529204565336,
      ...
----

[[ovMOptnsNzzKKfODatpgqmCEDEelFDYN]]
== Let's Do An Example

[.lead]
//
We'll continue our weather example using the
//
https://www.metaweather.com/api/[free MetaWeather API]
//
and
//
https://www.getpostman.com/[PostMan]

[[ZsOQNCeyFRLfYMLCfmRDxwhgFYiBXBXm]]
[.oneword]
== What's Awesome...

Is that there are
//
https://github.com/toddmotto/public-apis[a gazillion]
//
public APIs out there.
//
So go have fun!

[[JuTQULKcDJyYbpOvzZuoVHSBBAMPJKQI]]
[.oneword]
//
== Questions About Web APIs?

[[SqGkgcTkdQVjvOobbhObNLIevzXsYvdI]]
== Announcements

* We've posted some
//
link:/MP/6/#errata[MP6 errata].
//
Please follow these screencasts if you are having a hard time getting your
environment set up.
//
* The
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
remains available on the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
