---
title: Web APIs
date: 2018-04-13
description:
  Web APIs.
spelling_exceptions:
  - DNS
  - IPv4
  - IPv6
  - SMTP
  - YNP
  - Gmail
  - MetaWeather
  - Bob Kahn
  - Vint Cerf
  - frisbees
  - transformative
  - mockup
echo: https://goo.gl/byGAAN
---

[[akBdVGIbdUuOBCWPJUJACrtqtiiiMWsS]]
[.oneword]
== Web APIs

[[QKeUzlHTSNNsJbgNcbqjGUeTHlTFsjFq]]
== Object Modeling

[.lead]
//
We frequently use Java objects to model real objects or entities.

Objects allow us to _design_ software that deals with things in realistic and
natural ways.

[[kHQpiaadgbluVBAnvMmcBasKpkzNVIdg]]
== ! Class Example

[.janini.smallest.compiler]
....
public class Example {
  public static void main(String[] unused) {
  }
}
....

[[etVihciFCCPNmctHHSVytxymXTZQgwbc]]
[.oneword]
== What Did You Model?

Note that one of the free response questions on the exam might be an object
modeling question.

[[ektVXgCnvbMbQYRWmoUJmAGlqQMqPAFC]]
== HTTP: `GET` and `POST`

[.lead]
//
HTTP defines many other types of requests, but `GET` and `POST` are by far the
most common.

[.s]
//
* *Every time you load a web page* it starts with a `GET`, and usually that's
followed by many other `GET` requests to fetch others parts of the page: style
sheets, images, JavaScript code.
//
* *Every time you submit a form* it uses a `POST` to send data to the server, at
which point your Facebook comment is recorded, or your credit card is charged
and an package starts its way toward your house

[[WgscvlWONzCiyMGTuqghXquyomqPzcUg]]
== Web Evolution

[.lead]
//
The web has gone through many design changes over the years.

[.s.small]
//
* *Static Sites*: the web server returns a _file_ from the disk that contains a
complete web document
** Example: most of `cs125.cs.illinois.edu` is a static website
//
* *Dynamic Sites*: the web server _runs code_ to produce an HTML document and
respond to `POST` requests created by forms
** Example: sites like `my.cs.illinois.edu` are dynamic sites
//
* *Web Apps*: most of the site is _generated by JavaScript_ that runs in the
user's browser, with the server providing data as needed
** Examples: `cs125.cs.illinois.edu/m/grades`, Discourse, Gmail, Google Docs

[[zcwjOHKsxMVbvuMTokNgtNLaHJdOTkBP]]
== What is the World Wide Web?

[.s]
//
* *A protocol*: the Hypertext Transfer Protocol
//
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol[(HTTP)]
//
* *A markup language*: the Hypertext Markup Language
//
https://en.wikipedia.org/wiki/HTML[(HTML)]
//
* *A styling language*: Cascading Style Sheets
//
https://en.wikipedia.org/wiki/Cascading_Style_Sheets[(CSS)]
//
* *A programming language*:
//
https://en.wikipedia.org/wiki/JavaScript[JavaScript]

[[wfdQvQZAipVkTZPRnQrNavedMEtHXFyO]]
[.oneword]
//
== So What's a Web _API_?

[[yyuJpkncwjTgIiTBmtNZIUHdZFQnXSGU]]
== What's An API?

[quote]
____
//
https://en.wikipedia.org/wiki/Application_programming_interface[In computer
programming, an application programming interface (API)]
//
is a set of subroutine definitions, protocols, and tools for building
application software.
____

In English, an _API_ is a set of functions that perform a set of related and
useful tasks.

[[VhKcyDdXgMnfeOXUFUtqYTEIXFRxBmua]]
== Example API

[.lead]
//
Let's say we wanted to find out the weather at a particular location:

[source,java]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)

// Get the current weather a particular location and a particular time
static WeatherInfo getAtLocation(WeatherLocation location, Date date)

// Get a list of possible WeatherInfo objects for a given location string
static WeatherLocation[] searchLocations(String query)
----

[[JLNFoBPiCoEGSAeKEmLVCEayqKYizNUm]]
== Web APIs

[.lead]
//
A _web API_ is just an API that you access over the web. Consider that:

[.s]
//
* We can send data to a web server using `POST` and also using URL parameters in
a `GET` request
//
* The web server can run code in response
//
* And return a response, [.s]#_which does not have to be an HTML document_#
//
* And in many cases custom internet protocols are blocked by firewalls, making
it attractive to run APIs over HTTP

[[sQoshKdkerQbElGQyoWmkEymnLkzrZKF]]
== Web APIs: Sending Arguments

[source,java,role="small"]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)
----

To send the `location` argument to the `getAtLocation` function over the web we
have several options:

[.s.small]
//
* Stick it the URL: `/api/getAtLocation/(location)/`, which can be mapped to a
function call
//
* Add it as a query parameter: `/api/getAtLocation?location=(location)`
//
* Use a `POST` request and put it in the body, possibly as JSON:

[source,role="small s"]
----
POST /api/getAtLocation/

{
  "location": (location)
}
----

[[ijoYpJSPQQLblMzMSckYOpVMqASJepju]]
== Web APIs: Returning Results

[source,java,role="small"]
----
// Get the current weather a particular location
static WeatherInfo getAtLocation(WeatherLocation location)
----

In many cases web APIs return results using _JSON_ (JavaScript Object Notation):

[source,json,role='small']
----
{
  "consolidated_weather": [
  {
    "id": 6511056423747584,
      "weather_state_name": "Thunder",
      "weather_state_abbr": "t",
      "wind_direction_compass": "E",
      "created": "2018-04-09T02:37:19.655990Z",
      "applicable_date": "2018-04-08",
      "min_temp": -2.6099999999999999,
      "max_temp": 2.2149999999999999,
      "the_temp": 2.4950000000000001,
      "wind_speed": 2.8707529204565336,
      ...
----

[[ovMOptnsNzzKKfODatpgqmCEDEelFDYN]]
== Let's Do An Example

[.lead]
//
We'll continue our weather example using the
//
https://www.metaweather.com/api/[free MetaWeather API]
//
and
//
https://www.getpostman.com/[PostMan]

[[ZsOQNCeyFRLfYMLCfmRDxwhgFYiBXBXm]]
[.oneword]
== What's Awesome...

Is that there are
//
https://github.com/toddmotto/public-apis[a gazillion]
//
public APIs out there.
//
So go have fun!

[[ehlqzEhyBDazbIHaqTjpObNLXLubhqWa]]
== What is REST?

[.lead]
//
You'll often hear of REST or RESTful web APIs.

[.s.small]
//
* REST is a _design pattern_ for creating web APIs.
//
* URLs map to resources: so `GET` `/products` returns a list of all products,
while `GET` `/products/10` get information about product with ID 10
//
* HTTP verbs are meaningful: `GET` gets something, `POST` creates a new entity,
`DELETE` removes one, etc.
//
* HTTP response codes are meaningful: 200 is `OK`, 405 is not authorized, etc.
//
* The bodies of requests and responses are in `JSON`

[[SpcgsfLVgvldZzAVoUJHsBiUOxSPvLEE]]
== REST Examples

[.table.small,cols="3*^.^",options='header']
|===

|Request
|Meaning
|Java-Like Function

|[.s]#`GET /items`#
|[.s]#Retrieve a list of all items#
|[.s]#`public static Item[] getItems()`#

|[.s]#`GET /items/81`#
|[.s]#Retrieve information about item 81#
|[.s]#`public static Item[] getItems(int id)`#

|[.s]#`GET /items?type=frisbee`#
|[.s]#Retrieve a list of all items that are frisbees#
|[.s]#`public static Item[] getItems(String type)`#

|[.s]#`POST /items`#
|[.s]#Create a new item#
|[.s]#`public static boolean createItem(Item newItem)`#

|===

[[FKPZGlamLRDVEJHjjxFnDjkqMxooAsMH]]
== More REST Examples

With two additional useful HTTP verbs: `PUT` and `DELETE`

[.table.small,cols="3*^.^",options='header']
|===

|Request
|Meaning
|Java-Like Function

|[.s]#`PUT /items/81`#
|[.s]#Update information about item 81#
|[.s]#`public static boolean updateItem(Item updateTime, int id)`#

|[.s]#`DELETE /items/81`#
|[.s]#Delete item 81#
|[.s]#`public static boolean deleteItem(int id)`#

|===

[[JuTQULKcDJyYbpOvzZuoVHSBBAMPJKQI]]
[.oneword]
//
== Questions About Internet, Web, or Web APIs?

[[HtKEWqTEwzEPzDSjqfIvDwiIWZWSzXqQ]]
== Internet Design Principles

[.lead]
//
The internet established many powerful and important _design principles_.
//
One of the most important is the _end-to-end principle_:


[quote]
____
In networks designed according to the
//
https://en.wikipedia.org/wiki/End-to-end_principle[end-to-end principle],
//
application-specific features reside in the communicating end nodes of the
network, rather than in intermediary nodes, such as gateways and routers, that
exist to establish the network.
____

[[lTVxOqKIJeqpxtlWpxSuzjPINWGWZOwK]]
== End-to-End Example: Reliable Delivery

[.lead]
//
Reliable delivery is _not guaranteed_ by the core Internet Protocol.

[.s]
//
* Not every application needs it!
//
* Moved to the _endpoints_: that is, implemented on your device and whatever
computer you want to communicate with reliably.

[[GiuISzhloTQxbzcjHBBhFhJAzWSOnGUx]]
== End-to-End Principle: Consequences

[.lead]
//
The end-to-end principles has had powerful implications for internet design and
evolution.

[.s]
//
* The core network stays simple
//
* The core network _doesn't choose winners and losers_

[[WsnIIRchesWsJjxchaCCShmRJuhiaGML]]
== Net Neutrality

[.lead]
//
Net neutrality is essentially enshrining the end-to-end principle in law.

[.s]
//
* Internet service providers should not discriminate against traffic based on
where it comes from, where it is going, or other features
//
* *This keeps the internet available for the kinds of transformative innovation
it has supported since its creation.*

[[PCmWKojKEZEbGdSLJwQxcCBCHMeHVXBk]]
[.oneword]
//
== This Will Be Your Problem Soon

Please do the right thing.

[[SqGkgcTkdQVjvOobbhObNLIevzXsYvdI]]
== Announcements

* We've posted some
//
link:/MP/6/#errata[MP6 errata].
//
Please follow these screencasts if you are having a hard time getting your
environment set up.
//
* The
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
remains available on the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
