---
title: Final Project Demos
description:
  Today you'll demo your final project by showing your video, and your lab
  section will choose two projects to promote at the Final Project Fair.
outdated:
  name: lab
  current: /lab/
---
:sectnums:
:linkattrs:

[.lead]
//
Today is our last lab for this semester, and your chance to demo your final
project.
//
The course staff will review your project according to our
//
link:/MP/2019/spring/5#grading[MP5 grading criteria].
//
In addition, your lab should choose two projects to promote at the final project
fair: one by a group of beginners, and a second by any group without
restrictions.

[[demos]]
== Demos [.text-muted]#(110 Minutes)#

The entirety of today's lab will be spent demoing your final project.
//
If you haven't yet, please use
//
https://forms.gle/LwPeeZnK68tqJXPo8[this form]
//
to submit information about your project: a link to your YouTube
video, a link to your GitHub repository, and a team name for the final project
fair (if you are participating).

=== Most Impressive Projects

Your TA and course staff will help your lab choose two most impressive projects:
one done by a team of beginners, and a second done by anyone.
//
These will be invited to a special area at the project fair.
//
Remember that if one of your lab's projects wins at the project fair, your
entire lab earns 1% extra credit!

// vim: ts=2:sw=2:et
