---
title: "MP7: Final Project"
description:
  MP7 gives you a chance to show what you've learned this semester by planning
  and executing a project of your own choosing.
outdated:
  name: MP
  current: /mp/
---
:sectnums:
:linkattrs:

:forum: pass:normal[https://cs125-forum.cs.illinois.edu/c/mps/spring2018-mp7[forum,role='noexternal']]

[.lead]
//
You've learned a lot this semester.
//
Now it's time to try out your newly-acquired super powers.
//
MP7 is not about us giving you something to do&mdash;it's about you
accomplishing something _you want_ to do using computer programming.

MP7 is different than previous MPs.
//
It is done in pairs with a partner from your lab section.
//
And it due in your lab section during the last week of class: so during lab on
either *Tuesday 5/1/2018* or *Wednesday 5/2/2018*.

We're also giving you a chance to earn <<extra, extra credit>> by doing a great
project _and_ participating in our first ever Final Project Fair, from
4&ndash;6PM on 5/3/2018 in Siebel.

[[objectives]]
== Learning Objectives

If the previous MPs have had you execute carefully-planned routes from point A
to point B, MP7 takes you on a journey off the map.
//
You'll learn how to plan and execute a small Android project of your own design.
//
You'll also learn how to work with a partner.
//
We'll also continue to reinforce the learning objectives from previous MPs
(link:/MP/2018/spring/1/[1], link:/MP/2018/spring/2/[2], link:/MP/2018/spring/3/[3], link:/MP/2018/spring/4/[4], link:/MP/2018/spring/5/[5],
and link:/MP/2018/spring/6/[6]).
//
MP7 brings everything together and starts you out on a career as an independent
software developer.

[[rules]]
== Rules

Our goal in MP7 is to give you as much flexibility as possible, so there are few
rules about what you can and can't do.
//
But those that we do have are important:

You _must_ do something new for MP7.
//
Do not submit something from another class, or something you've done previously.
//
You may want to work on something that you've started on previously, but given
that you'll be working with a partner that's not fair to them.
//
So you should pick something new to do for MP7.
//
It doesn't have to be a huge project&mdash;you only have two weeks.
//
But it should be original work.

Here are the rest of the rules:

* You need to build an Android app.
//
* You need to design a simple UI. We'll provide help with that in lab.
//
* You'll need to finish your UI mockup in a week and demo it in lab.
//
* You need to use a new web API, software library, or Android feature.
//
* You need to commit your work to GitHub&mdash;to either a public or private
GitHub repository.
//
* You need to work with someone in your lab section.
//
* *Other than that, what to do is up to you.*

You turn in MP7 by presenting it in lab during the last week of class, and you
and your partner should plan that together.
//
* You _do_ have to publish your work on GitHub&mdash;privately if you want.*
//
So you should set up your project using Git and be able to show that you have
committed and pushed your code to GitHub as part of your turn-in presentation.

[[help]]
== Getting Help

While MP7 is self-driven, please feel free to approach the course staff for
help.
//
Post on the {forum}, or come to office hours and discuss your project idea and
implementation with the course staff.

[[grading]]
== Grading

Grading for MP7 will be generous.
//
It is worth 100 points total, broken down as follows:

. *20 points* for building an original _and_ working Android app
//
. *20 points* for the first UI checkpoint
//
. *20 points* for using a new web API, software library, or Android feature

. *10 points* for ensuring that all team members have roles in the project
//
. *20 points* for presenting your work during your final lab section
//
. *10 points* for properly publishing your work on GitHub

There is (obviously) no autograding or online testing for MP7.
//
Grades are entirely at the discretion of the course staff.

*Also note that, unlike MPs 0&ndash;6, MP7 cannot be dropped.*
//
It's too important&mdash;this is your chance to do something cool, creative, and
to show us everything you've learned this semester.

[[extra]]
=== Final Project Fair and Extra Credit

MP7 also provides an opportunity to earn extra credit by participating in our CS
125 Final Project Fair.
//
We are providing extra credit as follows:

[.s]
//
* *1%* increase in your final CS 125 grade for participating in the final
project fair, from 4&ndash;6PM on Thursday 5/3/2018.
//
* *1%* increase in your final CS 125 grade if your project is judged to be one of the
most impressive.
//
Note that _we will take into account your level of
ability when you started CS 125_ when determining how impressive your project
is.
//
So this is open to students of all ability levels.
//
* *1%* increase in your final CS 125 grade if one of the projects from _your
lab_ is judged to be most impressive.

Note that the maximum extra credit is 2%: if you participate in the fair and
either have one of the most impressive projects or are in a lab that has one.
//
Put another way, if you have one of the most impressive projects you don't get
an extra 1% from the lab incentive.
//
However, this extra credit is independent from any previous extra credit that
you might have earned earlier this semester.

[[submitting]]
== Submitting Your Work

You and your partner should prepare a 5 minute presentation for the last lab
section during the final week of class.
//
Your presentation should cover what you did, why you did it, who did what, and
any other interesting details: interesting technical problems you encountered,
how you collaborated, or ideas for future work.
//
You should also confirm that this was an original project and that it was
published to GitHub under one or both of the project partner's accounts.

[[cheating]]
=== Academic Integrity

Please review the link:/MP/2018/spring/0#cheating[MP0 academic integrity guidelines].
//
In addition, for MP7 any attempt to turn in non-original work will be treated as
an academic integrity violation.
//
Consider yourself warned.
