---
title: "Working On EWS"
description:
  A discussion of how to complete the CS 125 MPs on the Engineering Workstations
  (EWS) machines.
spelling_exceptions:
  - OpenJDK
outdated:
  name: MP
  current: /mp/
---
:sectnums:
:linkattrs:

[.lead]
//
We think that you'll have the best success in CS 125 working on your own
personal computer&mdash;preferably a laptop.
//
However, if you need to use the engineering workstations in the basement of
Siebel and other engineering buildings, instructions follow.

== Git and Java

Happily both Git and Java are already installed on the EWS machines.
//
At present Java is still on version 1.8, and it is the
//
http://openjdk.java.net/[open source OpenJDK]
//
rather than the proprietary Oracle JDK.
//
We don't think that this is going to matter, but if you are worried that it
might you can install Oracle Java by following the
//
http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html[instructions
on their web site].

== IntelliJ

++++
<div class="row justify-content-center mt-3 mb-3">
  <div class="col-12 col-lg-8">
    <div class="embed-responsive embed-responsive-4by3">
      <iframe class="embed-responsive-item" width="560" height="315" src="//www.youtube.com/embed/hdx2HbY7HhU" allowfullscreen></iframe>
    </div>
  </div>
</div>
++++

IntelliJ is available using the
//
https://it.engineering.illinois.edu/user-guides/software/linux-software-modules[EWS
Linux software modules system].
//
The screencast above walks you through the process of activating and using the
module.
//
At that point you can continue with the instructions about
//
link:/MP/2018/fall/setup/intellij#checkstyle[installing the `checkstyle` IntelliJ plugin]
//
and establishing your
//
link:/MP/2018/fall/setup/git#workflow[CS 125 MP workflow].
