---
title: Practice with Functions and Strings
date: 2019-02-01
description:
  A discussion of method overloading and type casting, followed by more practice
  with Java functions and Strings.
spelling_exceptions:
  - GCD
youtube: https://youtu.be/Ax8hcZIx6Po
---
:imagesdir: /slides/images
:!sectids:

[[tEtREXcdwvLNenEEApUWWxYcIyInPqrh]]
== !

[.janini.small]
--
++++
<div class="message">Practice with Functions and Strings</div>
++++
....
String[] courses = { "CS 125", "CS 225", "CS 241", "STAT 107" };
static void bestCourse(String[] options) {
  for (String course: options) {
    System.out.print(course);
    if (course.contains("125")) {
      System.out.print(" is the best");
    }
    System.out.println();
  }
}
bestCourse(courses);
....
--

[[QXeDdtoIJghFLWgVVxlLDTyJGYnfkMyM]]
[.oneword]
== Algorithmic Thinking and Problem Solving

[[BujyetipnNDrtCDwOkrBiiTJbXjxHwVu]]
[.oneword]
== But First: More About Functions

[[JCBOUZUKUWSRGZEDXOKZVEPQBNWADGRD]]
[.oneword]
== But First: How _Are_ You?

[[WYGKDMJrYLPMExMvDrlPcHvhJXJULrdT]]
== Java Method Overloading

[.lead]
//
I told you that functions couldn't have the same name.

[.s]
--
*I lied.*
--

[[iJVMrRgNoMDSQndAuhyBGsxwipXUxmyY]]
== ! Bad Professor

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://www.usnews.com/education/blogs/professors-guide/2010/01/06/10-warning-signs-of-a-bad-professor"></iframe>
</div>
++++

[[wswjWrauPrlUigRkLcyzcewZsvsCXVAL]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  return first + second;
}
static double sum(double first, double second) {
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
System.out.println("WTF?!");
....

[[hMOkqKTcxmOlCMscnAhDrISCCrbmuKSA]]
== Java Method Overloading

[.lead]
//
Java uses _both_ the function name _and_ the the list of arguments and types to
determine which function to call.

Together they are called the _function signature_.

[.s]
//
. *Does the function have the right name?*
//
. *Does the function take the right arguments in the right order?*
//
. Java will also try to convert types to find a match as long as no loss of
precision occurs

[[gSVpdvguUsItuviFdwvmyPOhnMVwlErX]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  System.out.println("Summing ints");
  return first + second;
}
static double sum(double first, double second) {
  System.out.println("Summing doubles");
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
....

[[uHxLfZRUUSeKHKZXVkQEndWETbAOgXOj]]
== Function Input Validation

[.lead]
//
A common function design pattern is to _check your inputs at the top_.

Think about all the bad inputs you could possibly get from the caller.

[source,java]
----
int sum(int[] numbers) {
  // check numbers to make sure it's sane
}
----

[[IvXkDdLRgNBLsSBPsbafXVMWXMQbkIQF]]
== ! Function Input Validation

[.janini.small]
....
static int sum(int[] numbers) {
  // check numbers to make sure it's sane
}
....

[[yBXWpiIYZpCTIiwedPUiflmeXRDXXbyM]]
== `null` Arrays

[.lead]
//
What is the value of array declared below?

[source,java]
----
int[] output = null;
System.out.println(output);
----

[.s]
//
* Java has a special value that can be used to indicate that an object has not
been initialized: `null`.
//
* `null` is not a valid object: it has no properties or methods that you can
use.
//
* Attempts to use `null` will result in an error

[[EaGRLETbzDaduqdILxVMZGtholIVxhZu]]
== ! `null` Arrays

[.janini]
....
int[] output = null;
System.out.println(output);
System.out.println(output.length);
....

[[MtRsCbMHmLhOLCCaHMlzRjbUaAvypYeW]]
[.oneword]
== Defensive Programming 101

[.lead]
//
*Always check objects for `null`.*

Java and other Java-like languages now also have better primitives for dealing
with `null` and avoiding
//
https://kotlinlang.org/docs/reference/null-safety.html[the Billion Dollar
Mistake].

[[HltJmohVAiSOVkbDyMDvVSxVeYTnaQmt]]
== Casting

[.lead]
//
If you want to _force_ Java to convert a variable from one type to another you
can try applying a _cast_.

[source,java]
----
int i = 10;
double d = i; // This works since no information is lost
i = d; // This does not work since we'd have to throw out the fraction
i = (int) d; // But we can force Java to do it
----

[[bcsEuCBErjgIjQHaKvcOzsFASZdTIemI]]
== ! Casting

[.janini.small]
....
int i = 10;
double d = i; // This works since no information is lost
i = d; // This does not work...
i = (int) d; // ...but we can force Java to do it
....

[[bFVBvhmjufzGfxvxxruaPuBSduFKcJlu]]
[.oneword]
== Let's Solve Some Problems!

[[EDTZMRFNRRZFQZYYRWOPMGMNQFDXONJQ]]
== String Reverse

[.lead]
//
Given a `String`, return it in reverse order.

*First, what is our algorithm?*
//
I can think of at least three ways to do this...

[.s]
//
. Examine each character in the input `String`
//
. Put it in the right place in the output `String`

[[CTLBHVPUNNQVONERMCWGDEIBZODITFTE]]
== ! String Reverse

[.janini.small]
....
static String reverse(String input) {
}
....

[[OEzuTpurwrhHSauViYyTwSIyybNxVVVz]]
== ! Read The Documentation

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/10/docs/api/java/lang/String.html"></iframe>
</div>
++++


[[IiSngNdYzdEnzLMjikxwjrNwXThqAOAO]]
== Dropped Grade Policy

[.lead]
//
CS 125 has a generous dropped grade policy.
//
However, these are _not_ "get out of class free" cards.

[.s.small]
//
* Dropped lectures and labs are pre-excused absences intended to accommodate
_all_ the reasons you might miss class or not complete a homework problem:
sickness, family emergencies, travel, religious obligations, extracurricular
activities, etc.
//
* *As a result we don't excuse absences.*
//
Please don't email us about this.
//
* *We expect you to try to attend and complete everything.*
//
But the dropped grades are for times when circumstances intervene.
//
* If you use them up skipping class just because you don't feel like coming, and
then your fish dies and you are bereft, you don't get more.

[[xQXgbdRgVarmQwliOIBZtdzszqeKYBPZ]]
== Announcements

[.small]
//
* link:/MP/2019/spring/0/[MP0] is out and due _next Monday_.
//
The early deadline is _today_ at 5PM.
//
Please get started!
//
Office hours start immediately after class in Siebel 0403.
//
* My office hours today will be in *Siebel 0403* from 1&ndash;3PM.
//
* Please fill out the https://goo.gl/forms/FWkjiW2jp9HoU82U2[initial student
survey].
//
1% extra credit for anyone who does by *Sunday 02/03/2019*.

// vim: ts=2:sw=2:et
