---
title: Object Review
date: 2019-02-22
description:
  A chance to slow down and review Java objects, including instances,
  constructors, class design, inheritance, and polymorphism.
spelling_exceptions:
  - Liskov
youtube: https://youtu.be/7TsEAl42nig
---

[[yvPGyAzjIWxppDwhCkgPugvxiKuRyxUi]]
== !

[.janini.smallest.compiler]
--
++++
<div class="message">Object Review</div>
++++
....
public class Pet {
  public void printMe() {
    System.out.println("I'm a pet");
  }
}
public class Dog extends Pet {
  public void printMe() {
    System.out.println("I'm a dog");
  }
}
public class Example {
  public static void main(String[] unused) {
    Pet chuchu = new Dog();
    Pet xyz = new Pet();
    chuchu.printMe();
    xyz.printMe();
  }
}
....
--

[[tJAEhRBaxOdrIAfHFqeluBfFBFVZEkZI]]
== Review: Polymorphism

[quote]
____
https://en.wikipedia.org/wiki/Polymorphism_(computer_science)[Polymorphism]:
//
the provision of a single interface to entities of different types.
____

[[xejQOFdnYNedKmENRxJOESdlitSRXvBw]]
== Subtype Polymorphism

[source,java,role='small']
----
public class Pet {
  public void printMe() {
    System.out.println("I'm a pet");
  }
}
public class Dog extends Pet {
  public void printMe() {
    System.out.println("I'm a dog");
  }
}
----

[.lead]
//
In Java, _every_ object is really an instance of at least _two_ types:

[.s]
//
* Each `Pet` is also an `Object`
//
* Each `Dog` is also a `Pet` and also an `Object`

[[zAfgNaUvOdTRoYcImWOGArtsyjxiCuXW]]
== Review: Object Upcasting

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
----

[.lead]
//
Java will _upcast_ object types automatically.

[[CibxAzCMpvrFpjbBUcHRBnCoPdroMZDc]]
== ! Object Conversion: Upcasting

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
....

[[YHYXBIyexgSczCgXpNsrgcVZtiCWeifQ]]
== But Instances Retain Their Types

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Object chuchuAsObject = chuchu;
    System.out.println(chuchuAsObject);
    Pet chuchuAsPet = chuchu;
    System.out.println(chuchuAsPet);
  }
}
----

[[faLGlVEpJnzuilavUdSpPJnjoRNXqcsn]]
== ! But Instances Retain Their Types

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Object chuchuAsObject = chuchu;
    System.out.println(chuchuAsObject);
    Pet chuchuAsPet = chuchu;
    System.out.println(chuchuAsPet);
  }
}
....

[[sdlBDsmJxGzipqJCuKbCXcwbxKBRbrno]]
== Review: Object Downcasting

[source,java,role='smallest']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Object chuchu = new Dog();
    Example.printAnything(chuchu);
    Pet chuchuAsPet = (Pet) chuchu; // chuchu is a Pet, so this works
    Example.printAnything(chuchuAsPet);
  }
}
----

[.lead]
//
We can also cast instances _down_ but only if the instance is
actually the appropriate subtype.

Java checks the cast at runtime to make sure that it is appropriate.

[[GJrYLdzWnTewfJWDGEyNqVxQyxjMmJCk]]
== ! Object Conversion: Downcasting

[.janini.smaller.compiler]
....
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Still a Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Object chuchu = new Dog();
    System.out.println(chuchu);
    Pet chuchuAsPet = (Pet) chuchu; // chuchu is a Pet, so this works
    System.out.println(chuchuAsPet);
    Dog chuchuAsDog = (Dog) chuchu; // chuchu is also a Dog, so this works
    System.out.println(chuchuAsDog);
  }
}
....

[[AtydbVpehoLTEsgqUCgcTyIHlnazMXPZ]]
== Liskov Substitution Principle

[quote,role='spelling_exception']
____
https://en.wikipedia.org/wiki/Liskov_substitution_principle[Substitutability]
//
is a principle in object-oriented programming stating that, in a computer
program, if S is a subtype of T, then objects of type T may be replaced with
objects of type S (i.e. an object of type T may be substituted with any object
of a subtype S) without altering any of the desirable properties of T
(correctness, task performed, etc.).
____

[[nUWyBwYOCDtTXFYmxzjQBKdtSVcLLhjZ]]
== Substitutability in Practice

[source,java,role='smaller']
----
public class Pet { }
public class Dog extends Pet {
  public String toString() {
    return "Dog";
  }
}
public class Example {
  public static void main(String[] unused) {
    Dog chuchu = new Dog();
    Pet xyz = new Pet();
    Example.printAnything(chuchu);
    Example.printAnything(xyz);
  }
  public static void printAnything(Object toPrint) {
    System.out.println(toPrint.toString());
  }
}
----

Since everything is an `Object`, any Java object inherits all of the desirable
properties of `Object`: like `toString`.

[[VhyrHDhYiwsScmHUunmuvwgwbiWRJPqJ]]
[.oneword]
== Subtype Polymorphism

[.lead]
//
We can always use `toString`, but every class can implement it
differently.

[[yvYtRfULCbIvhMMdEOcGHIreUrBynaXT]]
[.oneword]
== Same Names, Different Behavior

[.lead]
//
Where else have we seen this before?

[[vGwilOBrBAWUfzutpyvFACGGhIYzMNyQ]]
== ! Java Method Overloading

[.janini.small]
....
static int sum(int first, int second) {
  return first + second;
}
static double sum(double first, double second) {
  return first + second;
}
System.out.println(sum(10, 20));
System.out.println(sum(10.0, 20.0));
....

[[CaeAiZMIixRpAkCxQeiqMdVeitvqdxFV]]
== Polymorphism

[quote]
____
https://en.wikipedia.org/wiki/Polymorphism_(computer_science)[Polymorphism]:
//
the provision of a single interface to entities of different types.
____

[.s]
//
* *Subtype polymorphism*: a single method can act on all descendants of a given
class
//
* *Method overloading*: a method can behave differently depending on its arguments
//
* Generics (discussed later)

[[nqWbDnGJqKLMIaHvSuYCGMtSXNjuiFnu]]
== Review: `Flip`

Define a public `class` named `Flip` with a single public instance method
called `flop` that takes no parameters and returns a `boolean`.
//
It should also provide a single constructor that takes a `boolean` argument that
sets the initial state of the `Flip` instance.

[[orYebYemmWfwiIkouECEpHwzgUmvHngq]]
== Review: `LastTen`

Complete the implementation of a class called `LastTen`.
//
Your class should implement two public methods as described below:

. `void add(int newValue)`: add a new integer to the values that we are
remembering
//
. `int[] getLastTen()`: return the last ten values that were added using add, in
any order.
//
If fewer than ten values were added, you should return zeros in their place.

Your class should also provide a constructor that takes no arguments.
//
It should not expose any of its state publicly.

[[PuCamSKgLSZBtxPcnrGgUvIqvsJQfhtr]]
== ! `LastTen` Attempt 1

[.janini.small.compiler]
....
import java.util.Arrays;

public class Example {
  public static void main(String[] unused) {
    LastTen lastTen = new LastTen();
    for (int i = 0; i < 32; i++) {
      lastTen.add(i);
    }
    System.out.println(Arrays.toString(lastTen.getLastTen()));
  }
}
....

[[gGQSTGJEsdIRfuiEeTMNdLglNFSDhBZV]]
== ! `LastTen` Attempt 2

[.janini.small.compiler]
....
import java.util.Arrays;

public class Example {
  public static void main(String[] unused) {
    LastTen lastTen = new LastTen();
    for (int i = 0; i < 32; i++) {
      lastTen.add(i);
    }
    System.out.println(Arrays.toString(lastTen.getLastTen()));
  }
}
....

[[DUBdpEaAvnXiNefdsOofrRFDZTBMnApM]]
== ! `LastTen` Attempt 3

[.janini.small.compiler]
....
import java.util.Arrays;

public class Example {
  public static void main(String[] unused) {
    LastTen lastTen = new LastTen();
    for (int i = 0; i < 32; i++) {
      lastTen.add(i);
    }
    System.out.println(Arrays.toString(lastTen.getLastTen()));
  }
}
....

[[aeVJuVbnHSUwndHSELusYguefZbWovbn]]
[.oneword]
//
== Questions About Objects?

[[HiLlpvxKziOlYYkRfdKZIjluYKLMNtQj]]
== Announcements

* link:/MP/2019/spring/2/[MP2] is out and due in less than two weeks. **Get started!**
//
* This week's lab exercise is open and available over the weekend. Have fun!
//
* I have office hours from 1&ndash;3PM today in Siebel 2227. Please stop by!
//
* **We will _not_ have a lecture next Wednesday.**
//
* We have a
//
link:/info/feedback/[anonymous feedback form]
//
to the course website. Use it to give us feedback!

// vim: ts=2:sw=2:et
